INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$bernardo$$, $$São Bernardo de Claraval$$, $$Doutor Melífluo$$, $$20 de Agosto$$, 8, 20, $$1090, Fontaine$$, $$1153, Claraval$$, '{"Apicultores"}'::text[], $$Abade cisterciense, grande devoto de Nossa Senhora e pregador das Cruzadas. Reformou a vida monástica.$$, $$Abade cisterciense, grande devoto de Nossa Senhora e pregador das Cruzadas. Reformou a vida monástica.$$, $$[]$$::jsonb, '{"\"De Maria numquam satis — De Maria nunca se diz o bastante.\""}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Bernhard_von_Clairvaux_%28Initiale-B%29.jpg/440px-Bernhard_von_Clairvaux_%28Initiale-B%29.jpg$$, NULL, '{"Devoção mariana","Eloquência"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$bartolomeu$$, $$São Bartolomeu$$, $$Apóstolo$$, $$24 de Agosto$$, 8, 24, $$Séc. I, Caná$$, $$Séc. I, Armênia$$, '{"Curtidores","Encadernadores"}'::text[], $$Identificado com Natanael, "israelita sem falsidade". Pregou na Índia e Armênia, onde foi esfolado vivo.$$, $$Identificado com Natanael, "israelita sem falsidade". Pregou na Índia e Armênia, onde foi esfolado vivo.$$, $$[]$$::jsonb, '{"\"De Nazaré pode sair algo bom?\""}'::text[], $$apostle$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Jusepe_de_Ribera_-_Martyrdom_of_Saint_Bartholomew_-_Google_Art_Project.jpg/440px-Jusepe_de_Ribera_-_Martyrdom_of_Saint_Bartholomew_-_Google_Art_Project.jpg$$, NULL, '{"Sinceridade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$natividade-maria$$, $$Natividade de Nossa Senhora$$, $$O Nascimento de Maria$$, $$8 de Setembro$$, 9, 8, NULL, NULL, '{"Nascituros"}'::text[], $$Festa que celebra o nascimento da Virgem Maria, filha de São Joaquim e Santa Ana.$$, $$Festa que celebra o nascimento da Virgem Maria, filha de São Joaquim e Santa Ana.$$, $$[]$$::jsonb, '{"\"Bendita és tu entre as mulheres.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Albrecht_Altdorfer_-_Nativity_of_the_Virgin_-_Google_Art_Project.jpg/440px-Albrecht_Altdorfer_-_Nativity_of_the_Virgin_-_Google_Art_Project.jpg$$, NULL, '{"Pureza","Eleição"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$nome-maria$$, $$Santíssimo Nome de Maria$$, $$Doce Nome de Maria$$, $$12 de Setembro$$, 9, 12, NULL, NULL, '{"Humanidade"}'::text[], $$Festa que celebra o santo nome de Maria, que significa "senhora" ou "estrela do mar".$$, $$Festa que celebra o santo nome de Maria, que significa "senhora" ou "estrela do mar".$$, $$[]$$::jsonb, '{"\"Ao ouvir o nome de Maria, o Céu se alegra e o inferno treme.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{"Devoção"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$exaltacao-cruz$$, $$Exaltação da Santa Cruz$$, $$A Cruz Gloriosa$$, $$14 de Setembro$$, 9, 14, NULL, NULL, '{"Penitentes"}'::text[], $$Festa que celebra a descoberta da verdadeira Cruz por Santa Helena e a vitória da Cruz de Cristo.$$, $$Festa que celebra a descoberta da verdadeira Cruz por Santa Helena e a vitória da Cruz de Cristo.$$, $$[]$$::jsonb, '{"\"Nós, porém, pregamos Cristo crucificado.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Agnolo_Gaddi_True_Cross.jpg/440px-Agnolo_Gaddi_True_Cross.jpg$$, NULL, '{"Redenção"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$nossa-senhora-dores$$, $$Nossa Senhora das Dores$$, $$Mater Dolorosa$$, $$15 de Setembro$$, 9, 15, NULL, NULL, '{"Aflitos"}'::text[], $$Memória das sete dores de Maria: a profecia de Simeão, a fuga ao Egito, a perda de Jesus no Templo, o encontro na Via Crucis, a crucificação, a deposição e a sepultura.$$, $$Memória das sete dores de Maria: a profecia de Simeão, a fuga ao Egito, a perda de Jesus no Templo, o encontro na Via Crucis, a crucificação, a deposição e a sepultura.$$, $$[]$$::jsonb, '{"\"Uma espada traspassará a tua alma.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Mater_Dolorosa_by_Carlo_Dolci.jpg/440px-Mater_Dolorosa_by_Carlo_Dolci.jpg$$, NULL, '{"Compaixão","Sofrimento"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$mateus$$, $$São Mateus$$, $$Apóstolo e Evangelista$$, $$21 de Setembro$$, 9, 21, $$Séc. I, Cafarnaum$$, $$Séc. I, Etiópia$$, '{"Contadores","Banqueiros"}'::text[], $$Publicano chamado por Jesus, autor do primeiro Evangelho. Pregou na Etiópia.$$, $$Publicano chamado por Jesus, autor do primeiro Evangelho. Pregou na Etiópia.$$, $$[]$$::jsonb, '{"\"Segue-me! E ele se levantou e o seguiu.\""}'::text[], $$apostle$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Caravaggio_-_The_Calling_of_Saint_Matthew.jpg/440px-Caravaggio_-_The_Calling_of_Saint_Matthew.jpg$$, NULL, '{"Conversão","Obediência"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$arcanjos$$, $$Santos Arcanjos Miguel, Gabriel e Rafael$$, $$Os Três Arcanjos$$, $$29 de Setembro$$, 9, 29, NULL, NULL, '{"Soldados","Polícia","Médicos"}'::text[], $$Os três arcanjos mencionados na Escritura: Miguel o defensor, Gabriel o mensageiro, Rafael o curador.$$, $$Os três arcanjos mencionados na Escritura: Miguel o defensor, Gabriel o mensageiro, Rafael o curador.$$, $$[]$$::jsonb, '{"\"Quem é como Deus?\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Guido_Reni_031.jpg/440px-Guido_Reni_031.jpg$$, NULL, '{"Proteção","Mensagem","Cura"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$anjos-guarda$$, $$Santos Anjos da Guarda$$, $$Protetores Celestes$$, $$2 de Outubro$$, 10, 2, NULL, NULL, '{"Crianças","Vigilantes"}'::text[], $$Festa que celebra os anjos designados por Deus para guardar e proteger cada pessoa.$$, $$Festa que celebra os anjos designados por Deus para guardar e proteger cada pessoa.$$, $$[]$$::jsonb, '{"\"Ele enviará seus anjos para te guardar em todos os teus caminhos.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Bernardo_Strozzi_-_Guardian_Angel.jpg/440px-Bernardo_Strozzi_-_Guardian_Angel.jpg$$, NULL, '{"Proteção"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$nossa-senhora-rosario$$, $$Nossa Senhora do Rosário$$, $$Rainha do Santo Rosário$$, $$7 de Outubro$$, 10, 7, NULL, NULL, '{"Rosário"}'::text[], $$Festa instituída após a victory de Lepanto em 1571, atribuída à intercessão de Nossa Senhora do Rosário.$$, $$Festa instituída após a victory de Lepanto em 1571, atribuída à intercessão de Nossa Senhora do Rosário.$$, $$[]$$::jsonb, '{"\"Rezai o Rosário todos os dias.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Bartolom%C3%A9_Esteban_Murillo_-_Our_Lady_of_the_Rosary_-_Google_Art_Project.jpg/440px-Bartolom%C3%A9_Esteban_Murillo_-_Our_Lady_of_the_Rosary_-_Google_Art_Project.jpg$$, NULL, '{"Oração","Meditação"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$nossa-senhora-aparecida$$, $$Nossa Senhora Aparecida$$, $$Padroeira do Brasil$$, $$12 de Outubro$$, 10, 12, NULL, NULL, '{"Brasil"}'::text[], $$Em 1717, três pescadores encontraram a imagem da Imaculada Conceição no Rio Paraíba do Sul. Foi proclamada Rainha e Padroeira do Brasil em 1930.$$, $$Em 1717, três pescadores encontraram a imagem da Imaculada Conceição no Rio Paraíba do Sul. Foi proclamada Rainha e Padroeira do Brasil em 1930.$$, $$[]$$::jsonb, '{"\"Sou a serva do Senhor.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Nossa_Senhora_Aparecida.jpg/440px-Nossa_Senhora_Aparecida.jpg$$, NULL, '{"Maternidade","Humildade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$lucas$$, $$São Lucas Evangelista$$, $$O Evangelista Médico$$, $$18 de Outubro$$, 10, 18, $$Séc. I, Antioquia$$, $$Séc. I, Beócia$$, '{"Médicos","Pintores","Artistas"}'::text[], $$Médico grego, companheiro de São Paulo, autor do terceiro Evangelho e dos Atos dos Apóstolos.$$, $$Médico grego, companheiro de São Paulo, autor do terceiro Evangelho e dos Atos dos Apóstolos.$$, $$[]$$::jsonb, '{"\"Pareceu-me bem, depois de tudo ter investigado, escrever-te uma narração ordenada.\""}'::text[], $$apostle$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Simone_Martini_and_Lippo_Memmi_-_The_Annunciation_and_Two_Saints_-_WGA15010.jpg/440px-Simone_Martini_and_Lippo_Memmi_-_The_Annunciation_and_Two_Saints_-_WGA15010.jpg$$, NULL, '{"Investigação","Compaixão"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$frei-galvao$$, $$São Frei Galvão$$, $$O Santo das Pílulas$$, $$25 de Outubro$$, 10, 25, $$1739, Guaratinguetá, Brasil$$, $$1822, São Paulo$$, '{"Grávidas","Arquitetos"}'::text[], $$Primeiro santo nascido no Brasil, famoso por sua caridade e pelas "Pílulas de Frei Galvão".$$, $$Primeiro santo nascido no Brasil, famoso por sua caridade e pelas "Pílulas de Frei Galvão".$$, $$[]$$::jsonb, '{"\"Depois do parto, a Virgem permaneceu intacta.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{"Caridade","Pureza"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$todos-santos$$, $$Todos os Santos$$, $$Solenidade de Todos os Santos$$, $$1 de Novembro$$, 11, 1, NULL, NULL, '{"Igreja Triunfante"}'::text[], $$Solenidade que celebra todos os santos, conhecidos e desconhecidos, que já contemplam a face de Deus no Céu.$$, $$Solenidade que celebra todos os santos, conhecidos e desconhecidos, que já contemplam a face de Deus no Céu.$$, $$[]$$::jsonb, '{"\"Bem-aventurados os puros de coração, pois verão a Deus.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Albrecht_D%C3%BCrer_-_Adoration_of_the_Trinity_%28Landauer_Altar%29_-_Google_Art_Project.jpg/440px-Albrecht_D%C3%BCrer_-_Adoration_of_the_Trinity_%28Landauer_Altar%29_-_Google_Art_Project.jpg$$, NULL, '{"Santidade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$fieis-defuntos$$, $$Fiéis Defuntos$$, $$Comemoração dos Fiéis Defuntos$$, $$2 de Novembro$$, 11, 2, NULL, NULL, '{"Almas do Purgatório"}'::text[], $$Dia dedicado à oração pelas almas do Purgatório, para que alcancem a visão beatífica de Deus.$$, $$Dia dedicado à oração pelas almas do Purgatório, para que alcancem a visão beatífica de Deus.$$, $$[]$$::jsonb, '{"\"Dai-lhes, Senhor, o repouso eterno.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Bouguereau-The_Day_of_the_Dead.jpg/440px-Bouguereau-The_Day_of_the_Dead.jpg$$, NULL, '{"Oração pelos mortos"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$carlos-borromeu$$, $$São Carlos Borromeu$$, $$Reformador de Milão$$, $$4 de Novembro$$, 11, 4, $$1538, Arona$$, $$1584, Milão$$, '{"Seminários","Bispos"}'::text[], $$Arcebispo de Milão, grande reformador pós-Trento, dedicou sua vida e fortuna aos pobres e à educação do clero.$$, $$Arcebispo de Milão, grande reformador pós-Trento, dedicou sua vida e fortuna aos pobres e à educação do clero.$$, $$[]$$::jsonb, '{"\"As almas se conquistam de joelhos.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/San_Carlo_Borromeo.jpg/440px-San_Carlo_Borromeo.jpg$$, NULL, '{"Reforma","Caridade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$martinho-tours$$, $$São Martinho de Tours$$, $$O Soldado de Cristo$$, $$11 de Novembro$$, 11, 11, $$316, Panônia$$, $$397, Candes$$, '{"Soldados","Alfaiates","Mendigos"}'::text[], $$Soldado romano que partilhou seu manto com um mendigo e depois viu Cristo vestido com ele. Tornou-se bispo de Tours.$$, $$Soldado romano que partilhou seu manto com um mendigo e depois viu Cristo vestido com ele. Tornou-se bispo de Tours.$$, $$[]$$::jsonb, '{"\"Não posso desertar. Sou soldado de Cristo.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/El_Greco_-_Saint_Martin_and_the_Beggar_-_WGA10554.jpg/440px-El_Greco_-_Saint_Martin_and_the_Beggar_-_WGA10554.jpg$$, NULL, '{"Caridade","Humildade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$apresentacao-maria$$, $$Apresentação de Nossa Senhora$$, $$Maria no Templo$$, $$21 de Novembro$$, 11, 21, NULL, NULL, '{"Vida consagrada"}'::text[], $$Festa que celebra a tradição da apresentação da Virgem Maria no Templo de Jerusalém pelos seus pais.$$, $$Festa que celebra a tradição da apresentação da Virgem Maria no Templo de Jerusalém pelos seus pais.$$, $$[]$$::jsonb, '{"\"Desde a infância, Maria se consagrou totalmente a Deus.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Titian_-_Presentation_of_the_Virgin_at_the_Temple_%28detail%29_-_WGA22782.jpg/440px-Titian_-_Presentation_of_the_Virgin_at_the_Temple_%28detail%29_-_WGA22782.jpg$$, NULL, '{"Consagração"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$cecilia$$, $$Santa Cecília$$, $$Padroeira da Música$$, $$22 de Novembro$$, 11, 22, $$Séc. II, Roma$$, $$230, Roma$$, '{"Músicos","Poetas"}'::text[], $$Virgem e mártir romana, padroeira dos músicos por ter cantado a Deus em seu coração durante seu casamento forçado.$$, $$Virgem e mártir romana, padroeira dos músicos por ter cantado a Deus em seu coração durante seu casamento forçado.$$, $$[]$$::jsonb, '{"\"Cantai ao Senhor um cântico novo.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Guido_Reni_-_Saint_Cecilia_-_Google_Art_Project.jpg/440px-Guido_Reni_-_Saint_Cecilia_-_Google_Art_Project.jpg$$, NULL, '{"Música","Pureza"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$andre$$, $$Santo André$$, $$O Primeiro Chamado$$, $$30 de Novembro$$, 11, 30, $$Séc. I, Betsaida$$, $$Séc. I, Patras$$, '{"Pescadores","Escócia","Grécia"}'::text[], $$Irmão de São Pedro e primeiro apóstolo chamado por Jesus. Crucificado em cruz em forma de X em Patras.$$, $$Irmão de São Pedro e primeiro apóstolo chamado por Jesus. Crucificado em cruz em forma de X em Patras.$$, $$[]$$::jsonb, '{"\"Encontrámos o Messias!\""}'::text[], $$apostle$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Artus_Wolffort_-_Saint_Andrew.jpg/440px-Artus_Wolffort_-_Saint_Andrew.jpg$$, NULL, '{"Vocação","Martírio"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$francisco-xavier$$, $$São Francisco Xavier$$, $$Apóstolo do Oriente$$, $$3 de Dezembro$$, 12, 3, $$1506, Navarra$$, $$1552, Ilha de Sanchoão$$, '{"Missionários","Turismo"}'::text[], $$Jesuíta co-fundador, missionário nas Índias, Malásia e Japão. Batizou mais de 30 mil pessoas.$$, $$Jesuíta co-fundador, missionário nas Índias, Malásia e Japão. Batizou mais de 30 mil pessoas.$$, $$[]$$::jsonb, '{"\"Quantas almas deixam de ir ao Céu por falta de quem as ensine!\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Fran%C3%A7ois-Xavier.jpg/440px-Fran%C3%A7ois-Xavier.jpg$$, NULL, '{"Missão","Zelo"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$barbara$$, $$Santa Bárbara$$, $$Protetora contra Raios$$, $$4 de Dezembro$$, 12, 4, $$Séc. III, Nicomédia$$, $$306, Nicomédia$$, '{"Artilheiros","Mineradores","Bombeiros"}'::text[], $$Virgem e mártir presa numa torre por seu pai pagão. Converteu-se ao cristianismo e foi decapitada pelo próprio pai.$$, $$Virgem e mártir presa numa torre por seu pai pagão. Converteu-se ao cristianismo e foi decapitada pelo próprio pai.$$, $$[]$$::jsonb, '{"\"Cristo é minha fortaleza e minha torre.\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Robert_Campin_-_Saint_Barbara_-_Google_Art_Project.jpg/440px-Robert_Campin_-_Saint_Barbara_-_Google_Art_Project.jpg$$, NULL, '{"Fortaleza","Fé"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$nicolau$$, $$São Nicolau$$, $$Bispo de Mira$$, $$6 de Dezembro$$, 12, 6, $$270, Patara$$, $$343, Mira$$, '{"Crianças","Marinheiros","Comerciantes"}'::text[], $$Bispo generoso que secretamente dava presentes aos pobres. Inspiração para a figura do Papai Noel.$$, $$Bispo generoso que secretamente dava presentes aos pobres. Inspiração para a figura do Papai Noel.$$, $$[]$$::jsonb, '{"\"A generosidade é a melhor forma de pregar o Evangelho.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Jan_Matejko_-_Saint_Nicholas.PNG/440px-Jan_Matejko_-_Saint_Nicholas.PNG$$, NULL, '{"Generosidade","Proteção"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$ambrosio$$, $$Santo Ambrósio$$, $$Doutor da Igreja$$, $$7 de Dezembro$$, 12, 7, $$340, Tréveris$$, $$397, Milão$$, '{"Apicultores","Milão"}'::text[], $$Bispo de Milão que batizou Santo Agostinho. Grande pregador e defensor da Igreja contra o arianismo.$$, $$Bispo de Milão que batizou Santo Agostinho. Grande pregador e defensor da Igreja contra o arianismo.$$, $$[]$$::jsonb, '{"\"Onde está Pedro, aí está a Igreja.\""}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Ambrosius_of_Milan.jpg/440px-Ambrosius_of_Milan.jpg$$, NULL, '{"Eloquência","Coragem"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$imaculada-conceicao$$, $$Imaculada Conceição$$, $$Concebida sem Pecado$$, $$8 de Dezembro$$, 12, 8, NULL, NULL, '{"Portugal","Brasil","Estados Unidos"}'::text[], $$Solenidade que celebra o dogma de que Maria foi concebida sem pecado original, definido por Pio IX em 1854.$$, $$Solenidade que celebra o dogma de que Maria foi concebida sem pecado original, definido por Pio IX em 1854.$$, $$[]$$::jsonb, '{"\"Eu sou a Imaculada Conceição.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Bartolom%C3%A9_Esteban_Murillo_-_The_Immaculate_Conception_of_the_Venerable_Ones_-_Google_Art_Project.jpg/440px-Bartolom%C3%A9_Esteban_Murillo_-_The_Immaculate_Conception_of_the_Venerable_Ones_-_Google_Art_Project.jpg$$, NULL, '{"Pureza","Graça"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$nossa-senhora-guadalupe$$, $$Nossa Senhora de Guadalupe$$, $$Padroeira das Américas$$, $$12 de Dezembro$$, 12, 12, NULL, NULL, '{"Américas","México"}'::text[], $$Em 1531, a Virgem Maria apareceu ao indígena Juan Diego no México, deixando sua imagem milagrosamente impressa em sua tilma.$$, $$Em 1531, a Virgem Maria apareceu ao indígena Juan Diego no México, deixando sua imagem milagrosamente impressa em sua tilma.$$, $$[]$$::jsonb, '{"\"Não estou eu aqui, que sou tua Mãe?\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Virgen_de_guadalupe1.jpg/440px-Virgen_de_guadalupe1.jpg$$, NULL, '{"Maternidade","Evangelização"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$joao-cruz$$, $$São João da Cruz$$, $$Doutor Místico$$, $$14 de Dezembro$$, 12, 14, $$1542, Fontiveros$$, $$1591, Úbeda$$, '{"Contemplativos","Poetas"}'::text[], $$Carmelita e místico espanhol, reformador da Ordem com Santa Teresa. Autor de Noite Escura e Cântico Espiritual.$$, $$Carmelita e místico espanhol, reformador da Ordem com Santa Teresa. Autor de Noite Escura e Cântico Espiritual.$$, $$[]$$::jsonb, '{"\"Onde não há amor, ponha amor e recolherás amor.\""}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/John_of_the_Cross_drawing.png/440px-John_of_the_Cross_drawing.png$$, NULL, '{"Contemplação","Purificação"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$natal$$, $$Natividade do Senhor$$, $$O Natal de Jesus Cristo$$, $$25 de Dezembro$$, 12, 25, NULL, NULL, '{"Humanidade"}'::text[], $$Solenidade máxima que celebra o nascimento de Jesus Cristo em Belém, a Encarnação do Verbo de Deus.$$, $$Solenidade máxima que celebra o nascimento de Jesus Cristo em Belém, a Encarnação do Verbo de Deus.$$, $$[]$$::jsonb, '{"\"Glória a Deus nas alturas e paz na terra aos homens de boa vontade.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Gerard_van_Honthorst_001.jpg/440px-Gerard_van_Honthorst_001.jpg$$, NULL, '{"Encarnação","Humildade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$estevao$$, $$Santo Estêvão$$, $$Protomártir$$, $$26 de Dezembro$$, 12, 26, $$Séc. I, Jerusalém$$, $$34, Jerusalém$$, '{"Diáconos"}'::text[], $$Primeiro mártir cristão, apedrejado em Jerusalém. Diácono cheio do Espírito Santo, viu o Céu aberto antes de morrer.$$, $$Primeiro mártir cristão, apedrejado em Jerusalém. Diácono cheio do Espírito Santo, viu o Céu aberto antes de morrer.$$, $$[]$$::jsonb, '{"\"Senhor, não lhes imputes este pecado.\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Giacinto_Gimignani_-_The_Stoning_of_St_Stephen.jpg/440px-Giacinto_Gimignani_-_The_Stoning_of_St_Stephen.jpg$$, NULL, '{"Perdão","Coragem"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$joao-evangelista$$, $$São João Evangelista$$, $$O Discípulo Amado$$, $$27 de Dezembro$$, 12, 27, $$Séc. I, Betsaida$$, $$100, Éfeso$$, '{"Escritores","Teólogos"}'::text[], $$O mais jovem apóstolo, único que permaneceu aos pés da Cruz. Autor do quarto Evangelho e do Apocalipse.$$, $$O mais jovem apóstolo, único que permaneceu aos pés da Cruz. Autor do quarto Evangelho e do Apocalipse.$$, $$[]$$::jsonb, '{"\"Deus é amor.\""}'::text[], $$apostle$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Guido_Reni_-_St_John_the_Evangelist_-_WGA19218.jpg/440px-Guido_Reni_-_St_John_the_Evangelist_-_WGA19218.jpg$$, NULL, '{"Amor","Contemplação"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$santos-inocentes$$, $$Santos Inocentes$$, $$Os Primeiros Mártires$$, $$28 de Dezembro$$, 12, 28, NULL, $$Séc. I, Belém$$, '{"Crianças"}'::text[], $$Os meninos de Belém mortos por ordem de Herodes na tentativa de matar o Menino Jesus. Primeiros mártires do cristianismo.$$, $$Os meninos de Belém mortos por ordem de Herodes na tentativa de matar o Menino Jesus. Primeiros mártires do cristianismo.$$, $$[]$$::jsonb, '{"\"Uma voz se ouviu em Ramá, choro e grande lamento.\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Guido_Reni_-_Massacre_of_the_Innocents.jpg/440px-Guido_Reni_-_Massacre_of_the_Innocents.jpg$$, NULL, '{"Inocência"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sagrada-familia$$, $$Sagrada Família$$, $$Jesus, Maria e José$$, $$30 de Dezembro$$, 12, 30, NULL, NULL, '{"Famílias"}'::text[], $$Festa que celebra a família de Nazaré como modelo de fé, amor e santidade para todas as famílias cristãs.$$, $$Festa que celebra a família de Nazaré como modelo de fé, amor e santidade para todas as famílias cristãs.$$, $$[]$$::jsonb, '{"\"E Jesus crescia em sabedoria, estatura e graça diante de Deus e dos homens.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Murillo_sagrada_familia_del_pajarito.jpg/440px-Murillo_sagrada_familia_del_pajarito.jpg$$, NULL, '{"Família","Amor"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-severino$$, $$São Severino de Nórica$$, $$Apóstolo dos Bávaros$$, $$8 de Janeiro$$, 1, 8, NULL, NULL, '{}'::text[], $$Monge que evangelizou os povos germânicos durante as invasões bárbaras.$$, $$Monge que evangelizou os povos germânicos durante as invasões bárbaras.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-adriao$$, $$São Adrião de Canterbury$$, $$Abade e Mestre$$, $$9 de Janeiro$$, 1, 9, NULL, NULL, '{}'::text[], $$Abade africano que se tornou grande educador na Inglaterra anglo-saxã.$$, $$Abade africano que se tornou grande educador na Inglaterra anglo-saxã.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-gregorio-nissa$$, $$São Gregório de Nissa$$, $$Padre Capadócio$$, $$10 de Janeiro$$, 1, 10, $$335, Capadócia$$, $$395, Capadócia$$, '{"Teólogos","Místicos"}'::text[], $$Irmão de São Basílio, grande teólogo da doutrina trinitária e um dos pais da mística cristã.$$, $$Irmão de São Basílio, grande teólogo da doutrina trinitária e um dos pais da mística cristã.$$, $$[]$$::jsonb, '{"\"O conceito que temos de Deus não é Deus.\""}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, NULL, '{"Contemplação","Sabedoria"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-teodosio$$, $$São Teodósio Cenobiarca$$, $$Pai dos Cenobitas$$, $$11 de Janeiro$$, 1, 11, $$423, Capadócia$$, $$529, Palestina$$, '{"Monges"}'::text[], $$Monge palestino que fundou numerosas comunidades monásticas (cenóbios) na Terra Santa e defendeu a ortodoxia contra o monofisismo.$$, $$Monge palestino que fundou numerosas comunidades monásticas (cenóbios) na Terra Santa e defendeu a ortodoxia contra o monofisismo.$$, $$[]$$::jsonb, '{"\"A vida em comum é a escola da caridade.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{"Comunidade","Fé"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-bento-biscop$$, $$São Bento Biscop$$, $$Abade e Erudito$$, $$12 de Janeiro$$, 1, 12, $$628, Northumbria$$, $$689, Wearmouth$$, '{"Músicos","Pintores"}'::text[], $$Monge inglês que fundou os mosteiros de Wearmouth e Jarrow, trazendo da Itália livros e arte que permitiram o florescimento da cultura cristã na Inglaterra.$$, $$Monge inglês que fundou os mosteiros de Wearmouth e Jarrow, trazendo da Itália livros e arte que permitiram o florescimento da cultura cristã na Inglaterra.$$, $$[]$$::jsonb, '{"\"Os livros são tesouros da alma.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{"Cultura","Zelo"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-felix-nola$$, $$São Félix de Nola$$, $$Confessor e Mártir$$, $$14 de Janeiro$$, 1, 14, NULL, NULL, '{}'::text[], $$Sacerdote italiano que suportou prisões e torturas pela fé.$$, $$Sacerdote italiano que suportou prisões e torturas pela fé.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-paulo-tebas$$, $$São Paulo de Tebas$$, $$Primeiro Eremita$$, $$15 de Janeiro$$, 1, 15, NULL, NULL, '{}'::text[], $$Considerado o primeiro eremita cristão, viveu sozinho no deserto egípcio por 90 anos.$$, $$Considerado o primeiro eremita cristão, viveu sozinho no deserto egípcio por 90 anos.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-marcelo-papa$$, $$São Marcelo I$$, $$Papa Confessor$$, $$16 de Janeiro$$, 1, 16, $$Séc. III, Roma$$, $$309, Roma$$, '{"Roma"}'::text[], $$Papa que reorganizou a Igreja após a perseguição de Diocleciano, exigindo penitência dos que renegaram a fé ("lapsi") antes de reintegrá-los.$$, $$Papa que reorganizou a Igreja após a perseguição de Diocleciano, exigindo penitência dos que renegaram a fé ("lapsi") antes de reintegrá-los.$$, $$[]$$::jsonb, '{"\"A ordem na Igreja exige fidelidade e penitência.\""}'::text[], $$pope$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Cathedra_Petri_adjusted.JPG/440px-Cathedra_Petri_adjusted.JPG$$, NULL, '{"Justiça","Misericórdia"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;
