INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$santa-prisca$$, $$Santa Prisca$$, $$Virgem e Mártir$$, $$18 de Janeiro$$, 1, 18, NULL, NULL, '{}'::text[], $$Jovem romana martirizada por se recusar a sacrificar aos ídolos pagãos.$$, $$Jovem romana martirizada por se recusar a sacrificar aos ídolos pagãos.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-mario-marta$$, $$Santos Mário e Marta$$, $$Mártires de Roma$$, $$19 de Janeiro$$, 1, 19, NULL, NULL, '{}'::text[], $$Família persa martirizada em Roma durante a perseguição de Cláudio.$$, $$Família persa martirizada em Roma durante a perseguição de Cláudio.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-vicente$$, $$São Vicente Mártir$$, $$Diácono de Saragoça$$, $$22 de Janeiro$$, 1, 22, $$Séc. III, Huesca$$, $$304, Valência$$, '{"Lisboa","Viticultores","Diáconos"}'::text[], $$Diácono espanhol torturado cruelmente mas que manteve firmeza inabalável na fé durante a perseguição de Diocleciano.$$, $$Diácono espanhol torturado cruelmente mas que manteve firmeza inabalável na fé durante a perseguição de Diocleciano.$$, $$[]$$::jsonb, '{"\"O corpo está nas vossas mãos, mas a alma pertence a Deus.\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{"Fortaleza","Fidelidade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-ildefonso$$, $$Santo Ildefonso de Toledo$$, $$Defensor de Maria$$, $$23 de Janeiro$$, 1, 23, $$607, Toledo$$, $$667, Toledo$$, '{"Toledo"}'::text[], $$Arcebispo de Toledo, grande defensor da virgindade perpétua de Maria e autor de obras marianas célebres.$$, $$Arcebispo de Toledo, grande defensor da virgindade perpétua de Maria e autor de obras marianas célebres.$$, $$[]$$::jsonb, '{"\"Minha Senhora, meu domínio, Tu governas a mim e a tudo o que é meu.\""}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, NULL, '{"Devoção mariana"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-francisco-sales$$, $$São Francisco de Sales$$, $$Doutor do Amor$$, $$24 de Janeiro$$, 1, 24, $$1567, Saboia$$, $$1622, Lyon$$, '{"Jornalistas","Escritores","Surdos"}'::text[], $$Bispo de Genebra, mestre espiritual e padroeiro dos jornalistas. Autor da Introdução à Vida Devota.$$, $$Bispo de Genebra, mestre espiritual e padroeiro dos jornalistas. Autor da Introdução à Vida Devota.$$, $$[]$$::jsonb, '{"\"Uma gota de mel atrai mais moscas que um barril de vinagre.\""}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, NULL, '{"Mansidão","Caridade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$santos-timoteo-tito$$, $$Santos Timóteo e Tito$$, $$Bispos e Discípulos de Paulo$$, $$26 de Janeiro$$, 1, 26, NULL, NULL, '{}'::text[], $$Colaboradores íntimos de São Paulo, destinatários de epístolas pastorais.$$, $$Colaboradores íntimos de São Paulo, destinatários de epístolas pastorais.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-angela-merici$$, $$Santa Ângela Merici$$, $$Fundadora das Ursulinas$$, $$27 de Janeiro$$, 1, 27, NULL, NULL, '{}'::text[], $$Fundou a Companhia de Santa Úrsula, dedicada à educação feminina.$$, $$Fundou a Companhia de Santa Úrsula, dedicada à educação feminina.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-gildas$$, $$São Gildas$$, $$O Sábio$$, $$29 de Janeiro$$, 1, 29, NULL, NULL, '{}'::text[], $$Monge e historiador britânico do século VI.$$, $$Monge e historiador britânico do século VI.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-batilde$$, $$Santa Batilde$$, $$Rainha dos Francos$$, $$30 de Janeiro$$, 1, 30, NULL, NULL, '{}'::text[], $$Escrava anglo-saxã que se tornou rainha da França e promoveu obras de caridade.$$, $$Escrava anglo-saxã que se tornou rainha da França e promoveu obras de caridade.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-joao-bosco$$, $$São João Bosco$$, $$Pai dos Jovens$$, $$31 de Janeiro$$, 1, 31, $$1815, Castelnuovo d'Asti$$, $$1888, Turim$$, '{"Jovens","Estudantes","Editores"}'::text[], $$Sacerdote italiano, fundador dos Salesianos, dedicou a vida à educação da juventude através do Sistema Preventivo.$$, $$Sacerdote italiano, fundador dos Salesianos, dedicou a vida à educação da juventude através do Sistema Preventivo.$$, $$[]$$::jsonb, '{"\"Basta que sejais jovens para que eu vos ame muito.\""}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{"Alegria","Pedagogia","Caridade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-joao-britto$$, $$São João de Brito$$, $$O "Pandaru-Swami"$$, $$4 de Fevereiro$$, 2, 4, $$1647, Lisboa$$, $$1693, Oriyur, Índia$$, '{"Portugal","Índia"}'::text[], $$Jesuíta português missionário na Índia, martirizado por defender a fé cristã e adaptar-se aos costumes indianos para evangelizar.$$, $$Jesuíta português missionário na Índia, martirizado por defender a fé cristã e adaptar-se aos costumes indianos para evangelizar.$$, $$[]$$::jsonb, '{"\"O que recebi de Deus devo levar aos outros.\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{"Inculturação","Martírio"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-columbano-fev$$, $$São Columbano$$, $$Monge Missionário$$, $$7 de Fevereiro$$, 2, 7, NULL, NULL, '{}'::text[], $$Monge irlandês que fundou mosteiros por toda a Europa continental.$$, $$Monge irlandês que fundou mosteiros por toda a Europa continental.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-josefina-bakhita$$, $$Santa Josefina Bakhita$$, $$A Flor do Sudão$$, $$8 de Fevereiro$$, 2, 8, $$1869, Darfur, Sudão$$, $$1947, Schio, Itália$$, '{"Vítimas de tráfico humano","Sudão"}'::text[], $$Sudanesa escravizada e torturada que encontrou a liberdade e a fé na Itália, tornando-se religiosa canossiana.$$, $$Sudanesa escravizada e torturada que encontrou a liberdade e a fé na Itália, tornando-se religiosa canossiana.$$, $$[]$$::jsonb, '{"\"Se eu encontrasse os que me escravizaram, ajoelharia e lhes beijaria as mãos, pois se isso não tivesse acontecido eu não seria agora cristã e religiosa.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{"Perdão","Fé","Humildade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-apolonia$$, $$Santa Apolônia$$, $$Padroeira dos Dentistas$$, $$9 de Fevereiro$$, 2, 9, $$Séc. III, Alexandria$$, $$249, Alexandria$$, '{"Dentistas","Doenças de dentes"}'::text[], $$Mártir de Alexandria que teve todos os dentes arrancados antes de ser ameaçada de fogueira por sua fé.$$, $$Mártir de Alexandria que teve todos os dentes arrancados antes de ser ameaçada de fogueira por sua fé.$$, $$[]$$::jsonb, '{"\"Cristo é meu alimento e minha doçura.\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{"Fortaleza"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-bento-aniane$$, $$São Bento de Aniane$$, $$Reformador Beneditino$$, $$12 de Fevereiro$$, 2, 12, NULL, NULL, '{}'::text[], $$Monge que reformou a vida monástica no Império Carolíngio.$$, $$Monge que reformou a vida monástica no Império Carolíngio.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$santa-fusca-maura$$, $$Santas Fusca e Maura$$, $$Mártires de Ravena$$, $$13 de Fevereiro$$, 2, 13, NULL, NULL, '{}'::text[], $$Jovens mártires italianas durante a perseguição de Décio.$$, $$Jovens mártires italianas durante a perseguição de Décio.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-faustino-jovita$$, $$Santos Faustino e Jovita$$, $$Mártires de Bréscia$$, $$15 de Fevereiro$$, 2, 15, NULL, NULL, '{}'::text[], $$Irmãos cavaleiros martirizados na cidade de Bréscia.$$, $$Irmãos cavaleiros martirizados na cidade de Bréscia.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-juliana$$, $$Santa Juliana de Nicomédia$$, $$Virgem e Mártir$$, $$16 de Fevereiro$$, 2, 16, NULL, NULL, '{}'::text[], $$Jovem que resistiu ao casamento com um pagão e foi martirizada.$$, $$Jovem que resistiu ao casamento com um pagão e foi martirizada.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sete-fundadores-servitas$$, $$Sete Santos Fundadores dos Servitas$$, $$Servos de Maria$$, $$17 de Fevereiro$$, 2, 17, NULL, NULL, '{}'::text[], $$Sete nobres florentinos que fundaram a Ordem dos Servos de Maria.$$, $$Sete nobres florentinos que fundaram a Ordem dos Servos de Maria.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-simao-jerusalen$$, $$São Simeão de Jerusalém$$, $$Bispo e Mártir$$, $$18 de Fevereiro$$, 2, 18, NULL, NULL, '{}'::text[], $$Segundo bispo de Jerusalém, crucificado aos 120 anos de idade.$$, $$Segundo bispo de Jerusalém, crucificado aos 120 anos de idade.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-corrado$$, $$São Conrado de Piacenza$$, $$Eremita Penitente$$, $$19 de Fevereiro$$, 2, 19, NULL, NULL, '{}'::text[], $$Nobre que causou um incêndio acidental e dedicou o resto da vida à penitência.$$, $$Nobre que causou um incêndio acidental e dedicou o resto da vida à penitência.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-eucherio$$, $$Santo Eucário de Orléans$$, $$Bispo$$, $$20 de Fevereiro$$, 2, 20, NULL, NULL, '{}'::text[], $$Bispo de Orléans que defendeu a Igreja contra as intromissões reais.$$, $$Bispo de Orléans que defendeu a Igreja contra as intromissões reais.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-pedro-damiao$$, $$São Pedro Damião$$, $$Reformador Monástico$$, $$21 de Fevereiro$$, 2, 21, $$1007, Ravena$$, $$1072, Faenza$$, '{"Caminhantes"}'::text[], $$Monge e cardeal reformador, autor de importantes obras teológicas e espirituais, defensor da disciplina eclesiástica.$$, $$Monge e cardeal reformador, autor de importantes obras teológicas e espirituais, defensor da disciplina eclesiástica.$$, $$[]$$::jsonb, '{"\"Não temas; se Deus te enviou esta provação, Ele te dará as forças para suportá-la.\""}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, NULL, '{"Zelo","Ascese"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-policarpo$$, $$São Policarpo de Esmirna$$, $$O Último dos Padres Apostólicos$$, $$23 de Fevereiro$$, 2, 23, $$69 d.C., Esmirna$$, $$155 d.C., Esmirna$$, '{"Enfermos"}'::text[], $$Bispo de Esmirna, discípulo do apóstolo São João, queimado vivo aos 86 anos por se recusar a amaldiçoar Cristo.$$, $$Bispo de Esmirna, discípulo do apóstolo São João, queimado vivo aos 86 anos por se recusar a amaldiçoar Cristo.$$, $$[]$$::jsonb, '{"\"Sirvo-O há 86 anos e Ele nunca me fez mal; como posso blasfemar contra meu Rei que me salvou?\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{"Fidelidade","Martírio"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-modesto$$, $$São Modesto de Jerusalém$$, $$Patriarca$$, $$24 de Fevereiro$$, 2, 24, NULL, NULL, '{}'::text[], $$Patriarca de Jerusalém que restaurou os locais santos após a invasão persa.$$, $$Patriarca de Jerusalém que restaurou os locais santos após a invasão persa.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-cesario$$, $$São Cesário de Nazianzo$$, $$Médico$$, $$25 de Fevereiro$$, 2, 25, NULL, NULL, '{}'::text[], $$Irmão de São Gregório, médico na corte imperial que morreu servindo os pobres.$$, $$Irmão de São Gregório, médico na corte imperial que morreu servindo os pobres.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-porfirio$$, $$São Porfírio de Gaza$$, $$Destruidor de Ídolos$$, $$26 de Fevereiro$$, 2, 26, NULL, NULL, '{}'::text[], $$Bispo que eliminou os templos pagãos de Gaza com grande zelo missionário.$$, $$Bispo que eliminou os templos pagãos de Gaza com grande zelo missionário.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-gabriel-possenti$$, $$São Gabriel da Virgem Dolorosa$$, $$Jovem Santo$$, $$27 de Fevereiro$$, 2, 27, NULL, NULL, '{}'::text[], $$Jovem passionista italiano que alcançou grande santidade antes de morrer aos 24 anos.$$, $$Jovem passionista italiano que alcançou grande santidade antes de morrer aos 24 anos.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-romano$$, $$São Romano de Condat$$, $$Fundador de Mosteiros$$, $$28 de Fevereiro$$, 2, 28, NULL, NULL, '{}'::text[], $$Monge que fundou os mosteiros do Jura nos Alpes franceses.$$, $$Monge que fundou os mosteiros do Jura nos Alpes franceses.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-david-gales$$, $$São David de Gales$$, $$Padroeiro do País de Gales$$, $$1 de Março$$, 3, 1, NULL, NULL, '{}'::text[], $$Monge e bispo galês do século VI, padroeiro do País de Gales.$$, $$Monge e bispo galês do século VI, padroeiro do País de Gales.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$santa-ines-boemia$$, $$Santa Inês de Boêmia$$, $$Princesa Clarissa$$, $$2 de Março$$, 3, 2, NULL, NULL, '{}'::text[], $$Princesa tcheca que recusou casamentos reais para se tornar clarissa.$$, $$Princesa tcheca que recusou casamentos reais para se tornar clarissa.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-catarina-drexel$$, $$Santa Catarina Drexel$$, $$Apóstola dos Marginalizados$$, $$3 de Março$$, 3, 3, NULL, NULL, '{}'::text[], $$Herdeira americana que fundou uma ordem dedicada aos afro-americanos e indígenas.$$, $$Herdeira americana que fundou uma ordem dedicada aos afro-americanos e indígenas.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-joao-jose-cruz$$, $$São João José da Cruz$$, $$Franciscano$$, $$5 de Março$$, 3, 5, NULL, NULL, '{}'::text[], $$Frade franciscano napolitano famoso por seus milagres e vida de oração.$$, $$Frade franciscano napolitano famoso por seus milagres e vida de oração.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-coleta$$, $$Santa Coleta$$, $$Reformadora Clarissa$$, $$6 de Março$$, 3, 6, NULL, NULL, '{}'::text[], $$Virgem que reformou a Ordem de Santa Clara, restaurando a pobreza original.$$, $$Virgem que reformou a Ordem de Santa Clara, restaurando a pobreza original.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-francisca-romana$$, $$Santa Francisca Romana$$, $$Padroeira dos Motoristas$$, $$9 de Março$$, 3, 9, NULL, NULL, '{}'::text[], $$Nobre romana que viveu como esposa, mãe e fundadora, tendo visões de seu anjo da guarda.$$, $$Nobre romana que viveu como esposa, mãe e fundadora, tendo visões de seu anjo da guarda.$$, $$[]$$::jsonb, '{}'::text[], $$mystic$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Giovanni_Battista_Tiepolo_-_Saint_Catherine_of_Siena.jpg/440px-Giovanni_Battista_Tiepolo_-_Saint_Catherine_of_Siena.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$quarenta-martires$$, $$Os 40 Mártires de Sebaste$$, $$Soldados de Cristo$$, $$10 de Março$$, 3, 10, NULL, NULL, '{}'::text[], $$Quarenta soldados romanos que morreram congelados por se recusarem a renegar a fé.$$, $$Quarenta soldados romanos que morreram congelados por se recusarem a renegar a fé.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-sofronio$$, $$São Sofrônio de Jerusalém$$, $$Patriarca$$, $$11 de Março$$, 3, 11, NULL, NULL, '{}'::text[], $$Patriarca de Jerusalém que defendeu a fé ortodoxa contra o monotelismo.$$, $$Patriarca de Jerusalém que defendeu a fé ortodoxa contra o monotelismo.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-maximiliano-mar$$, $$São Maximiliano$$, $$Mártir Objetor$$, $$12 de Março$$, 3, 12, NULL, NULL, '{}'::text[], $$Jovem cristão que recusou o serviço militar romano e foi executado.$$, $$Jovem cristão que recusou o serviço militar romano e foi executado.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-rodrigo$$, $$São Rodrigo de Córdoba$$, $$Mártir da Espanha$$, $$13 de Março$$, 3, 13, NULL, NULL, '{}'::text[], $$Sacerdote espanhol martirizado pelos mouros em Córdoba.$$, $$Sacerdote espanhol martirizado pelos mouros em Córdoba.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-matilde$$, $$Santa Matilde$$, $$Rainha da Germânia$$, $$14 de Março$$, 3, 14, NULL, NULL, '{}'::text[], $$Rainha alemã conhecida por sua generosidade aos pobres e fundação de mosteiros.$$, $$Rainha alemã conhecida por sua generosidade aos pobres e fundação de mosteiros.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;
