INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$thomas-aquinas$$, $$São Tomás de Aquino$$, $$Doctor Angelicus$$, $$28 de Janeiro$$, 1, 28, $$1225, Roccasecca, Itália$$, $$1274, Abadia de Fossanova, Itália$$, '{"Estudantes","Universidades","Filósofos","Teólogos","Livreiros"}'::text[], $$Frade dominicano, teólogo e filósofo italiano. Considerado o maior teólogo da Igreja Católica, autor da Suma Teológica.$$, $$Nascido numa família nobre, Tomás entrou para a Ordem dos Pregadores (Dominicanos) contra a vontade da família, que o manteve preso durante um ano para dissuadi-lo. Estudou em Paris e Colônia sob a orientação de Santo Alberto Magno. Tornou-se professor em Paris e Roma, onde compôs a sua obra-prima, a Suma Teológica, uma síntese monumental de toda a teologia cristã à luz da filosofia aristotélica.

Conhecido como o "Boi Mudo da Sicília" pelos colegas por seu silêncio contemplativo, Alberto Magno profetizou que seus mugidos seriam ouvidos pelo mundo inteiro. Tomás demonstrou que fé e razão não se contradizem, mas se complementam — a razão natural pode alcançar verdades sobre Deus, e a Revelação eleva o conhecimento humano a verdades sobrenaturais.

Escreveu mais de 60 obras, incluindo comentários sobre quase toda a Escritura, sobre Aristóteles, e tratados teológicos. Perto do fim da vida, após uma experiência mística durante a Missa, declarou: "Tudo o que escrevi parece-me palha em comparação com o que me foi revelado." Foi canonizado em 1323 e declarado Doutor da Igreja em 1567. Leão XIII proclamou-o padroeiro das escolas católicas em 1880.$$, $$[{"title":"Suma Teológica","url":"https://sumateologica.files.wordpress.com/2017/04/suma-teolc3b3gica.pdf","year":"1265–1274"},{"title":"Suma Contra os Gentios","url":"https://www.corpusthomisticum.org/scg1001.html","year":"1259–1265"},{"title":"Questões Disputadas sobre a Verdade","url":"https://www.corpusthomisticum.org/qdv01.html","year":"1256–1259"},{"title":"Comentário ao Evangelho de João","url":"https://www.corpusthomisticum.org/cio01.html","year":"1270–1272"},{"title":"De Ente et Essentia","url":"https://www.corpusthomisticum.org/oee.html","year":"1252–1256"},{"title":"Compêndio de Teologia","url":"https://www.corpusthomisticum.org/oct01.html","year":"1265–1267"}]$$::jsonb, '{"\"O temor é o princípio da sabedoria.\"","\"A graça não destrói a natureza, mas a aperfeiçoa.\"","\"Para quem tem fé, nenhuma explicação é necessária. Para quem não tem fé, nenhuma explicação é possível.\"","\"Tudo o que escrevi parece-me palha em comparação com o que me foi revelado.\""}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, $$Concedei-me, Senhor, uma vontade que vos queira, uma mente que vos conheça, uma diligência que vos busque, uma sabedoria que vos encontre, uma vida que vos agrade, uma perseverança que vos espere e uma confiança que finalmente vos abrace.$$, '{"Sabedoria","Humildade","Pureza","Contemplação","Fé"}'::text[], $$[{"ref":"Jo 1,1","label":"No princípio era o Verbo"},{"ref":"Rm 1,20","label":"Conhecimento de Deus pela razão"}]$$::jsonb, '{36,156,159,2500}'::integer[], $$[{"title":"Aeterni Patris (Leão XIII)","url":"https://www.vatican.va/content/leo-xiii/pt/encyclicals/documents/hf_l-xiii_enc_04081879_aeterni-patris.html"},{"title":"Fides et Ratio (João Paulo II)","url":"https://www.vatican.va/content/john-paul-ii/pt/encyclicals/documents/hf_jp-ii_enc_14091998_fides-et-ratio.html"}]$$::jsonb),
($$agostinho$$, $$Santo Agostinho de Hipona$$, $$Doctor Gratiae$$, $$28 de Agosto$$, 8, 28, $$354, Tagaste, Numídia (atual Argélia)$$, $$430, Hipona, Numídia$$, '{"Teólogos","Cervejeiros","Impressores","Convertidos"}'::text[], $$Bispo de Hipona e um dos mais importantes Padres da Igreja. Sua conversão é um dos relatos mais célebres da literatura cristã.$$, $$Filho de Santa Mônica e de Patrício, um pagão, Agostinho viveu uma juventude dissoluta marcada pela busca intelectual. Passou pelo maniqueísmo, pelo ceticismo e pelo neoplatonismo antes de sua dramática conversão ao cristianismo em 386, narrada nas célebres Confissões.

A cena no jardim de Milão — ao ouvir uma voz infantil dizer "Tolle, lege" (Toma e lê) — levou-o a abrir a Carta aos Romanos, e nesse instante sua vida mudou para sempre. Foi batizado por Santo Ambrósio na Páscoa de 387.

Como bispo de Hipona durante 35 anos, Agostinho combateu vigorosamente as heresias do donatismo, do pelagianismo e do maniqueísmo. Sua obra A Cidade de Deus, escrita após o saque de Roma em 410, apresenta uma visão grandiosa da história humana como peregrinação entre duas "cidades" — a terrena e a celestial.

Agostinho é considerado o pai da teologia ocidental. Sua doutrina sobre a graça, o pecado original, a Trindade e a predestinação moldou profundamente o pensamento cristão. Morreu durante o cerco vândalo a Hipona, recitando os Salmos Penitenciais.$$, $$[{"title":"Confissões","url":"https://www.augustinus.it/portoghese/confessioni/index.htm","year":"397–400"},{"title":"A Cidade de Deus","url":"https://www.augustinus.it/portoghese/cdd/index.htm","year":"413–426"},{"title":"A Trindade (De Trinitate)","url":"https://www.augustinus.it/latino/trinita/index.htm","year":"400–416"},{"title":"Comentário aos Salmos","url":"https://www.augustinus.it/latino/esposizioni_salmi/index.htm","year":"392–418"},{"title":"Sobre a Doutrina Cristã","url":"https://www.augustinus.it/latino/dottrina_cristiana/index.htm","year":"396–426"},{"title":"Enquirídio (Manual da Fé, Esperança e Caridade)","url":"https://www.augustinus.it/latino/enchiridion/index.htm","year":"421"}]$$::jsonb, '{"\"Fizeste-nos para Ti, Senhor, e o nosso coração está inquieto enquanto não descansar em Ti.\"","\"Tarde te amei, ó Beleza tão antiga e tão nova, tarde te amei!\"","\"Ama e faze o que quiseres.\"","\"A medida do amor é amar sem medida.\""}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Saint_Augustine_by_Philippe_de_Champaigne.jpg/440px-Saint_Augustine_by_Philippe_de_Champaigne.jpg$$, $$Tarde te amei, ó Beleza tão antiga e tão nova! Estavas dentro de mim e eu procurava-Te fora. Chamaste, gritaste, e rompeste a minha surdez.$$, '{"Contrição","Busca pela Verdade","Caridade","Perseverança","Identidade"}'::text[], $$[{"ref":"Sl 42,2","label":"A minha alma tem sede de Deus"},{"ref":"Rm 13,13-14","label":"Revesti-vos do Senhor Jesus Cristo"}]$$::jsonb, '{27,30,1718,2560}'::integer[], $$[{"title":"Augustinum Hipponensem (João Paulo II)","url":"https://www.vatican.va/content/john-paul-ii/pt/apost_letters/1986/documents/hf_jp-ii_apl_26081986_augustinum-hipponensem.html"}]$$::jsonb),
($$francisco-assis$$, $$São Francisco de Assis$$, $$Il Poverello$$, $$4 de Outubro$$, 10, 4, $$1181/1182, Assis, Itália$$, $$1226, Porciúncula, Assis$$, '{"Animais","Ecologia","Mercadores","Itália"}'::text[], $$Fundador da Ordem dos Frades Menores. Renunciou à riqueza para viver em pobreza radical, seguindo Cristo literalmente.$$, $$Filho de um rico comerciante de tecidos, o jovem Francisco viveu uma juventude mundana e sonhava com a glória militar. Após ser preso na guerra contra Perugia e sofrer uma grave doença, iniciou uma profunda conversão.

O momento decisivo veio quando, na igreja de São Damião, ouviu o crucifixo dizer: "Francisco, vai e repara a minha Igreja que, como vês, está em ruínas." Inicialmente interpretou literalmente a mensagem, restaurando igrejas abandonadas, mas logo compreendeu que era chamado a renovar toda a Igreja.

Despojou-se de tudo diante do bispo de Assis, devolvendo ao pai até as roupas, e abraçou a pobreza radical como "Senhora Pobreza". Atraiu seguidores e fundou a Ordem dos Frades Menores (Franciscanos), aprovada pelo Papa Inocêncio III em 1209. Fundou também a Segunda Ordem (Claras) com Santa Clara, e a Terceira Ordem para leigos.

Em 1219, durante a Quinta Cruzada, atravessou as linhas inimigas para dialogar com o sultão al-Kamil do Egito — um gesto profético de diálogo inter-religioso. Em 1224, no Monte Alverna, recebeu os estigmas — as chagas de Cristo — tornando-se o primeiro estigmatizado da história.

Compôs o Cântico das Criaturas, considerado uma das primeiras obras-primas da literatura italiana. Morreu em 1226 cantando o Salmo 141, e foi canonizado apenas dois anos depois.$$, $$[{"title":"Cântico das Criaturas","url":"https://www.franciscanos.org.br/?p=cantico-das-criaturas","year":"1224"},{"title":"Regra Bulada (Regra definitiva)","url":"https://www.vatican.va/content/francesco/pt/encyclicals/documents/papa-francesco_20150524_enciclica-laudato-si.html","year":"1223"},{"title":"Testamento de São Francisco","url":"https://www.ofm.org/en/sources/test-en/","year":"1226"},{"title":"Admoestações","year":"1220–1226"},{"title":"Carta a toda a Ordem","year":"1225–1226"}]$$::jsonb, '{"\"Senhor, fazei-me instrumento da vossa paz.\"","\"Pregai o Evangelho em todo o tempo; quando necessário, usai palavras.\"","\"Comecemos, irmãos, a servir o Senhor, porque até agora pouco ou nada fizemos.\""}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Giotto_di_Bondone_-_Legend_of_St_Francis_-_15._Sermon_to_the_Birds_-_WGA09139.jpg/440px-Giotto_di_Bondone_-_Legend_of_St_Francis_-_15._Sermon_to_the_Birds_-_WGA09139.jpg$$, $$Senhor, fazei-me instrumento de vossa paz. Onde houver ódio, que eu leve o amor; onde houver ofensa, que eu leve o perdão.$$, '{"Pobreza","Fraternidade","Alegria","Humildade"}'::text[], $$[{"ref":"Mt 10,7-10","label":"A missão dos doze"},{"ref":"Mt 19,21","label":"Vende tudo o que tens"}]$$::jsonb, '{301,344,125,1438,2444}'::integer[], $$[{"title":"Laudato Si (Papa Francisco)","url":"https://www.vatican.va/content/francesco/pt/encyclicals/documents/papa-francesco_20150524_enciclica-laudato-si.html"},{"title":"Fratelli Tutti (Papa Francisco)","url":"https://www.vatican.va/content/francesco/pt/encyclicals/documents/papa-francesco_20201003_enciclica-fratelli-tutti.html"}]$$::jsonb),
($$judas-tadeu$$, $$São Judas Tadeu$$, $$Padroeiro das Causas Impossíveis$$, $$28 de Outubro$$, 10, 28, $$Séc. I, Galileia, Palestina$$, $$Séc. I, Pérsia (atual Irã)$$, '{"Causas impossíveis","Casos desesperados","Hospitais"}'::text[], $$Um dos doze apóstolos, irmão de São Tiago Menor. Pregou o Evangelho na Mesopotâmia e Pérsia.$$, $$São Judas Tadeu, também chamado Judas Lebeu, foi um dos doze apóstolos de Jesus Cristo. O Evangelho o distingue claramente de Judas Iscariotes: "Judas, não o Iscariotes" (Jo 14,22). É identificado como irmão de São Tiago Menor, sendo ambos parentes de Jesus.

Durante a Última Ceia, Judas Tadeu fez a Jesus a pergunta: "Senhor, por que te manifestarás a nós e não ao mundo?" (Jo 14,22), ao que Jesus respondeu ensinando sobre a habitação da Trindade nos que o amam.

Após Pentecostes, pregou na Judeia, Samaria, Idumeia, Síria, Mesopotâmia e Pérsia. A tradição relata que evangelizou junto com o apóstolo São Simão e que ambos foram martirizados na Pérsia — Judas Tadeu com uma clava (maça) e uma alabarda, instrumentos com que é frequentemente representado.

É autor da Epístola de São Judas, uma das cartas canônicas do Novo Testamento, na qual adverte contra falsos mestres e exorta à perseverança na fé. A devoção popular o invoca especialmente nas causas impossíveis e desesperadas, devido ao seu nome ter sido durante séculos evitado por confusão com o traidor Judas Iscariotes — fazendo dele um dos santos "menos procurados" e, portanto, sempre disponível para ajudar.$$, $$[{"title":"Epístola de São Judas (Novo Testamento)","url":"https://www.vatican.va/archive/bible/nova_vulgata/documents/nova-vulgata_nt_epist-iudae_lt.html"}]$$::jsonb, '{"\"Mantenham-se no amor de Deus, esperando a misericórdia de nosso Senhor Jesus Cristo para a vida eterna.\" (Jd 1,21)","\"A vocês, misericórdia, paz e amor em abundância.\" (Jd 1,2)"}'::text[], $$apostle$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Jude_the_Apostle.jpg/440px-Jude_the_Apostle.jpg$$, $$São Judas Tadeu, apóstolo glorioso, fiel servo e amigo de Jesus, o nome do traidor fez com que fôsseis esquecido por muitos. Mas a Igreja vos honra e invoca como padroeiro dos casos desesperados.$$, '{"Esperança","Perseverança","Fidelidade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$charbel$$, $$São Charbel Makhlouf$$, $$O Eremita de Annaya$$, $$24 de Julho$$, 7, 24, $$1828, Beka Kafra, Líbano$$, $$1898, Annaya, Líbano$$, '{"Pessoas doentes","Paz","Cura","Líbano"}'::text[], $$Monge maronita libanês, viveu como eremita por 23 anos. Famoso por inúmeros milagres durante e após sua vida.$$, $$Youssef Antoun Makhlouf nasceu numa pequena aldeia no norte do Líbano, o mais novo de cinco filhos. Desde a infância, demonstrou profunda inclinação à oração e ao silêncio, cuidando de um pequeno rebanho enquanto rezava por horas.

Aos 23 anos, deixou a casa sem avisar a família e entrou no mosteiro de Nossa Senhora de Mayfouq, da Ordem Libanesa Maronita, recebendo o nome de Charbel — em honra a um mártir de Antioquia do século II.

Após a ordenação sacerdotal em 1859, viveu 16 anos de vida comunitária no Mosteiro de Annaya, distinguindo-se pela obediência absoluta, pelo amor à Eucaristia e pela penitência rigorosa. Em 1875, obteve permissão para viver como eremita no eremitério de São Pedro e Paulo, onde permaneceu os últimos 23 anos de vida em intensa oração, jejum e trabalho manual.

No dia 16 de dezembro de 1898, sofreu um derrame durante a celebração da Missa, no momento da elevação do cálice. Morreu na véspera de Natal. Após o sepultamento, uma luz misteriosa foi vista sobre seu túmulo durante 45 noites. Quando o corpo foi exumado, foi encontrado incorrupto e exsudando um líquido oleoso com fragrância — fenômeno que continuou por décadas.

São Charbel é creditado com milhares de milagres no mundo inteiro, especialmente curas. Foi beatificado em 1965 durante o Concílio Vaticano II e canonizado por Paulo VI em 1977.$$, $$[]$$::jsonb, '{"\"O silêncio fala a Deus.\"","\"Quem permanece em Deus, Deus permanece nele.\""}'::text[], $$mystic$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Saint_Charbel_Makhlouf.jpg/440px-Saint_Charbel_Makhlouf.jpg$$, $$Senhor Deus Todo-Poderoso, que manifestastes ao mundo a santidade do monge Charbel, concedei-nos, por sua intercessão, a graça que humildemente vos pedimos.$$, '{"Silêncio","Oração","Penitência","Obediência"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$teresa-lisieux$$, $$Santa Teresa de Lisieux$$, $$A Pequena Flor$$, $$1 de Outubro$$, 10, 1, $$1873, Alençon, França$$, $$1897, Carmelo de Lisieux, França$$, '{"Missionários","Floristas","Aviadores","França"}'::text[], $$Carmelita descalça francesa, doutora da Igreja. Desenvolveu a "pequena via" da infância espiritual.$$, $$Marie-Françoise-Thérèse Martin foi a caçula de nove filhos de Louis e Zélie Martin — ambos canonizados como santos. Perdeu a mãe aos 4 anos, o que marcou profundamente sua sensibilidade. Desde muito cedo, sentiu o chamado à vida religiosa.

Aos 15 anos, após uma audiência com o Papa Leão XIII em Roma, obteve permissão especial para entrar no Carmelo de Lisieux, onde já estavam duas de suas irmãs. Recebeu o nome de Teresa do Menino Jesus e da Santa Face.

No Carmelo, Teresa desenvolveu sua célebre "pequena via" — um caminho de infância espiritual que consiste em fazer as coisas mais ordinárias com extraordinário amor. Compreendeu que não precisava realizar grandes feitos: "Minha vocação é o amor! No coração da Igreja, minha Mãe, eu serei o amor."

Os últimos 18 meses de vida foram marcados por uma terrível "noite da fé" — uma provação interior de dúvida contra a existência do Céu — que ela enfrentou com heroica confiança. Sofria também de tuberculose, que a consumiu lentamente.

Por obediência, escreveu sua autobiografia "História de uma Alma", que após sua morte se tornou um dos livros espirituais mais lidos do mundo. Morreu aos 24 anos dizendo: "Meu Deus, eu vos amo!" Foi canonizada em 1925 e declarada Doutora da Igreja por João Paulo II em 1997 — a mais jovem Doutora da história.$$, $$[{"title":"História de uma Alma (autobiografia)","url":"https://www.vatican.va/therese/therese_index_po.htm","year":"1895–1897"},{"title":"Poesias Completas","year":"1893–1897"},{"title":"Últimas Conversas (Novissima Verba)","year":"1897"},{"title":"Orações","year":"1889–1897"},{"title":"Peças de Teatro espirituais","year":"1893–1896"}]$$::jsonb, '{"\"Minha vocação é o amor! No coração da Igreja, minha Mãe, eu serei o amor.\"","\"Quero passar meu céu fazendo o bem na terra.\"","\"Tudo é graça.\"","\"O elevador que me há de elevar ao Céu são os vossos braços, ó Jesus!\""}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Therese_von_Lisieux.jpg/440px-Therese_von_Lisieux.jpg$$, $$Santa Teresinha do Menino Jesus, fazei cair do céu uma chuva de rosas sobre aqueles que vos invocam. Ajudai-me a encontrar a santidade nas coisas pequenas.$$, '{"Simplicidade","Confiança","Amor","Infância espiritual"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$padre-pio$$, $$São Padre Pio de Pietrelcina$$, $$O Frade Estigmatizado$$, $$23 de Setembro$$, 9, 23, $$1887, Pietrelcina, Itália$$, $$1968, San Giovanni Rotondo, Itália$$, '{"Adolescentes","Confessores","Voluntários","Curandeiros"}'::text[], $$Frade capuchinho italiano que recebeu os estigmas de Cristo. Célebre confessor que atraiu milhões de fiéis.$$, $$Francesco Forgione nasceu numa família camponesa profundamente religiosa no sul da Itália. Desde criança experimentava visões e êxtases, assim como ataques demoníacos. Aos 15 anos entrou na Ordem dos Frades Menores Capuchinhos, recebendo o nome de Frei Pio.

Em 20 de setembro de 1918, enquanto rezava diante de um crucifixo na igreja do convento de San Giovanni Rotondo, recebeu os estigmas — as cinco chagas de Cristo — que carregou visivelmente durante 50 anos. Os estigmas sangravam continuamente, exalando perfume de flores.

O Padre Pio tornou-se famoso por seus dons extraordinários: bilocação (ser visto em dois lugares ao mesmo tempo), leitura de consciências (revelando pecados confessados de penitentes antes que os declarassem), perfume de santidade, e inúmeros milagres de cura. Passava até 19 horas por dia no confessionário, recebendo fiéis do mundo inteiro.

A celebração da Missa por Padre Pio durava frequentemente horas, sendo um momento de visível sofrimento e êxtase místico que comovia todos os presentes. Sofreu durante anos investigações eclesiásticas e restrições ao exercício do ministério, que aceitou com heroica obediência.

Fundou a Casa Alívio do Sofrimento, um hospital em San Giovanni Rotondo que hoje é um dos maiores centros médicos da Itália. Morreu em 23 de setembro de 1968. Quando seu corpo foi exumado em 2008, foi encontrado em notável estado de conservação. Foi canonizado por João Paulo II em 2002.$$, $$[{"title":"Epistolário (Cartas)","url":"https://www.padrepio.it/","year":"1910–1968"},{"title":"Grupos de Oração do Padre Pio","url":"https://www.padrepio.it/en/prayer-groups/"}]$$::jsonb, '{"\"Reze, espere e não se preocupe. A preocupação é inútil.\"","\"A oração é a melhor arma que temos; é a chave do coração de Deus.\"","\"O Rosário é a arma para estes tempos.\"","\"Através do estudo dos livros busca-se a Deus; pela meditação encontra-se.\""}'::text[], $$mystic$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Padre_Pio.jpg/440px-Padre_Pio.jpg$$, $$São Padre Pio, que trouxestes em vosso corpo as chagas de Cristo, rogai a Deus por nós e intercedei por nossas necessidades.$$, '{"Oração","Sofrimento redentor","Obediência","Caridade","Dor"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$joana-arc$$, $$Santa Joana d'Arc$$, $$A Donzela de Orléans$$, $$30 de Maio$$, 5, 30, $$1412, Domrémy, França$$, $$1431, Ruão, França$$, '{"França","Soldados","Prisioneiros","Mulheres militares"}'::text[], $$Heroína francesa e santa padroeira da França. Guiada por visões divinas, liderou o exército francês durante a Guerra dos Cem Anos.$$, $$Nascida numa família camponesa durante a Guerra dos Cem Anos, Joana começou a ouvir as vozes de São Miguel Arcanjo, Santa Catarina de Alexandria e Santa Margarida de Antioquia aos 13 anos. As vozes instruíram-na a libertar a França do domínio inglês e conduzir o Delfim Carlos VII à coroação.

Aos 17 anos, após superar a desconfiança inicial, convenceu o Delfim de sua missão divina. Recebeu uma armadura e um estandarte branco com flor-de-lis, e liderou o exército francês na libertação de Orléans em apenas nove dias (maio de 1429) — uma vitória que reverteu o curso da guerra. Conduziu Carlos VII à coroação em Reims em julho de 1429.

Capturada pelos borgonheses em Compiègne em maio de 1430, foi vendida aos ingleses, que a submeteram a um longo e cruel julgamento eclesiástico em Ruão. Acusada de heresia e bruxaria por vestir roupas masculinas e alegar comunicação direta com Deus, manteve suas afirmações com extraordinária coragem e lucidez, apesar de ser uma jovem camponesa analfabeta enfrentando os mais eruditos teólogos da época.

Foi condenada e queimada na fogueira em 30 de maio de 1431, aos 19 anos. Suas últimas palavras foram "Jesus! Jesus!" O processo foi anulado em 1456, e Joana foi canonizada por Bento XV em 1920.$$, $$[{"title":"Atas do Processo de Condenação (1431)","url":"https://www.sofrancois.org/jeanne-arc/proces/index.html","year":"1431"},{"title":"Atas do Processo de Reabilitação (1456)","year":"1456"},{"title":"Cartas de Joana d'Arc","year":"1429–1431"}]$$::jsonb, '{"\"Não tenho medo; para isto nasci.\"","\"Aja, e Deus agirá.\"","\"Prefiro morrer a fazer algo que sei ser pecado.\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Joan_of_Arc_miniature_graded.jpg/440px-Joan_of_Arc_miniature_graded.jpg$$, $$Santa Joana d'Arc, que com vossa coragem inabalável seguistes a vontade de Deus até o martírio, dai-nos a fortaleza para enfrentar as batalhas da nossa vida com fé.$$, '{"Coragem","Fé","Obediência a Deus","Fortaleza"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$antonio-padua$$, $$Santo Antônio de Pádua$$, $$Doutor Evangélico$$, $$13 de Junho$$, 6, 13, $$1195, Lisboa, Portugal$$, $$1231, Pádua, Itália$$, '{"Objetos perdidos","Pobres","Viajantes","Portugal","Casamentos"}'::text[], $$Frade franciscano português, famoso por sua pregação eloquente e profundo conhecimento das Escrituras.$$, $$Fernando Martins de Bulhões nasceu numa família nobre de Lisboa. Estudou com os cônegos regrantes de Santo Agostinho, onde adquiriu profundo conhecimento bíblico. A visão dos corpos dos primeiros mártires franciscanos em Marrocos acendeu nele o desejo do martírio, levando-o a ingressar na Ordem Franciscana, recebendo o nome de Antônio.

Partiu para Marrocos, mas uma doença grave forçou-o a regressar. Uma tempestade desviou o navio para a Sicília, onde participou de um capítulo geral da Ordem em Assis. Ali, por acaso, foi convidado a pregar quando nenhum outro pregador estava disponível — e revelou-se um orador tão extraordinário que São Francisco o encarregou de ensinar teologia aos frades.

Tornou-se o maior pregador de sua época, atraindo multidões tão grandes que igrejas não comportavam os ouvintes — pregava ao ar livre para dezenas de milhares. Seus sermões, profundamente bíblicos, combatiam a avareza, a usura e a heresia cátara. Era chamado "Arca do Testamento" pelo domínio enciclopédico das Escrituras.

Morreu aos 36 anos em Pádua. Foi canonizado apenas 11 meses após sua morte — a canonização mais rápida da história. Em 1946, foi proclamado Doutor da Igreja por Pio XII.$$, $$[{"title":"Sermões Dominicais e Festivos","url":"https://www.santantonio.org/it/content/i-sermoni","year":"1228–1231"},{"title":"Sermões para os Dias de Santos","year":"1229–1231"}]$$::jsonb, '{"\"As ações falam mais alto que as palavras; que as vossas palavras ensinem e as vossas ações falem.\"","\"Quem tem o Espírito Santo no coração sente facilidade no caminho de Deus.\""}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Saint_Anthony_of_Padua.jpg/440px-Saint_Anthony_of_Padua.jpg$$, $$Santo Antônio, protetor dos pobres e patrono das coisas perdidas, intercedei por nós junto ao Senhor.$$, '{"Eloquência","Caridade","Humildade","Zelo"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$faustina$$, $$Santa Faustina Kowalska$$, $$Apóstola da Divina Misericórdia$$, $$5 de Outubro$$, 10, 5, $$1905, Głogowiec, Polônia$$, $$1938, Cracóvia, Polônia$$, '{"Divina Misericórdia"}'::text[], $$Religiosa polonesa que recebeu revelações de Jesus sobre a Divina Misericórdia, difundindo esta devoção por todo o mundo.$$, $$Helena Kowalska, terceira de dez filhos de uma família camponesa pobre, sentiu o chamado religioso desde os 7 anos. Após ser inicialmente rejeitada por várias congregações por falta de dote, foi aceita na Congregação das Irmãs de Nossa Senhora da Misericórdia em 1925, recebendo o nome de Irmã Maria Faustina.

A partir de 1931, recebeu uma série de visões e revelações de Jesus Cristo, que lhe pediu para propagar a devoção à Divina Misericórdia. Jesus apareceu-lhe vestido de branco, com raios vermelho e pálido emanando do coração, e pediu que fosse pintada esta imagem com a inscrição "Jesus, eu confio em Vós."

Jesus transmitiu-lhe a Coroa da Misericórdia, pediu a instituição da Festa da Misericórdia (Segundo Domingo de Páscoa) e revelou a Hora da Misericórdia (15h). Faustina registrou todas estas experiências no seu Diário — "A Misericórdia Divina na Minha Alma" — que se tornou um dos textos místicos mais importantes do século XX.

Apesar de sua pouca instrução formal, Faustina demonstrou uma profundidade teológica extraordinária em seus escritos. Sofreu incompreensão de suas superioras e de alguns confessores, mas encontrou apoio decisivo no Padre Michał Sopoćko.

Morreu de tuberculose aos 33 anos. Foi canonizada por João Paulo II em 2000, que também instituiu a Festa da Divina Misericórdia para toda a Igreja.$$, $$[{"title":"Diário: A Misericórdia Divina na Minha Alma","url":"https://www.faustyna.pl/zmbm/pt/","year":"1934–1938"}]$$::jsonb, '{"\"Jesus, eu confio em Vós.\"","\"A humanidade não encontrará paz enquanto não se voltar com confiança para a Minha Misericórdia.\"","\"Secretária da Minha Misericórdia, escreve, fala às almas sobre esta Minha grande Misericórdia.\"","\"Quanto maior o pecador, tanto maior o direito que tem à Minha Misericórdia.\""}'::text[], $$mystic$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Faustina_Kowalska.jpg/440px-Faustina_Kowalska.jpg$$, $$Jesus, eu confio em Vós! Santa Faustina, apóstola da Divina Misericórdia, ensinai-nos a confiar na infinita misericórdia de Deus.$$, '{"Confiança","Misericórdia","Oração","Abandono a Deus"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$joao-paulo-ii$$, $$São João Paulo II$$, $$O Grande$$, $$22 de Outubro$$, 10, 22, $$1920, Wadowice, Polônia$$, $$2005, Vaticano$$, '{"Jornada Mundial da Juventude","Famílias"}'::text[], $$Papa de 1978 a 2005, o segundo pontificado mais longo da história. Fundamental na queda do comunismo e no diálogo inter-religioso.$$, $$Karol Józef Wojtyła perdeu a mãe aos 8 anos, o irmão aos 12 e o pai aos 20 — sofrimentos que moldaram sua profunda espiritualidade. Durante a ocupação nazista da Polônia, trabalhou em pedreiras e fábricas químicas enquanto estudava clandestinamente no seminário.

Ordenado sacerdote em 1946, doutorou-se em ética e tornou-se professor universitário. Nomeado bispo auxiliar de Cracóvia aos 38 anos, participou ativamente do Concílio Vaticano II. Em 1978, foi eleito Papa — o primeiro não-italiano em 455 anos.

Seu pontificado de 26 anos transformou a Igreja e o mundo. Realizou 104 viagens internacionais, visitando 129 países. Seus encontros com a Jornada Mundial da Juventude atraíram milhões de jovens. Sobreviveu a um atentado em 13 de maio de 1981, atribuindo sua sobrevivência à intercessão de Nossa Senhora de Fátima. Depois visitou seu agressor na prisão e o perdoou.

Foi instrumental na queda do comunismo no Leste Europeu. Promoveu o diálogo inter-religioso, sendo o primeiro Papa a visitar uma sinagoga (1986) e uma mesquita (2001). Canonizou mais santos que todos os seus predecessores juntos. Publicou 14 encíclicas e a Teologia do Corpo, uma revolucionária catequese sobre o significado do corpo humano e da sexualidade.$$, $$[{"title":"Fides et Ratio (Fé e Razão)","url":"https://www.vatican.va/content/john-paul-ii/pt/encyclicals/documents/hf_jp-ii_enc_14091998_fides-et-ratio.html","year":"1998"},{"title":"Veritatis Splendor","url":"https://www.vatican.va/content/john-paul-ii/pt/encyclicals/documents/hf_jp-ii_enc_06081993_veritatis-splendor.html","year":"1993"},{"title":"Redemptor Hominis","url":"https://www.vatican.va/content/john-paul-ii/pt/encyclicals/documents/hf_jp-ii_enc_04031979_redemptor-hominis.html","year":"1979"},{"title":"Evangelium Vitae","url":"https://www.vatican.va/content/john-paul-ii/pt/encyclicals/documents/hf_jp-ii_enc_25031995_evangelium-vitae.html","year":"1995"},{"title":"Teologia do Corpo (catequeses)","url":"https://www.vatican.va/content/john-paul-ii/pt/audiences.index.html","year":"1979–1984"},{"title":"Cruzando o Limiar da Esperança","year":"1994"}]$$::jsonb, '{"\"Não tenhais medo! Abri as portas a Cristo!\"","\"A fé e a razão são como as duas asas com as quais o espírito humano se eleva à contemplação da verdade.\"","\"O futuro começa hoje, não amanhã.\""}'::text[], $$pope$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/John_Paul_II_Medal_of_Freedom_2004.jpg/440px-John_Paul_II_Medal_of_Freedom_2004.jpg$$, $$São João Paulo II, que nos ensinastes a não ter medo, intercedei por nós para que vivamos com a mesma coragem e esperança.$$, '{"Coragem","Perdão","Amor pelos jovens","Perseverança"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$madre-teresa$$, $$Santa Teresa de Calcutá$$, $$Mãe dos Pobres$$, $$5 de Setembro$$, 9, 5, $$1910, Skopje, Macedônia$$, $$1997, Calcutá, Índia$$, '{"Missionárias da Caridade","Pobres","Doentes"}'::text[], $$Fundadora das Missionárias da Caridade, dedicou sua vida aos mais pobres entre os pobres, servindo Cristo nos moribundos de Calcutá.$$, $$Anjezë Gonxhe Bojaxhiu nasceu numa família albanesa católica em Skopje. Aos 18 anos, ingressou nas Irmãs de Loreto na Irlanda e foi enviada à Índia, onde lecionou por quase 20 anos no colégio de Santa Maria em Calcutá.

Em 10 de setembro de 1946, durante uma viagem de trem para Darjeeling, recebeu o que chamou de "chamado dentro do chamado" — Jesus pedia-lhe que deixasse o convento para servir os mais pobres entre os pobres. Após dois anos de discernimento, recebeu permissão e fundou as Missionárias da Caridade em 1950.

Começou recolhendo moribundos das ruas de Calcutá, dando-lhes dignidade nos últimos momentos. A congregação cresceu exponencialmente, chegando a mais de 4.500 irmãs em 133 países, operando orfanatos, hospícios, centros de AIDS e casas para moribundos.

Recebeu o Prêmio Nobel da Paz em 1979. Quando lhe perguntaram o que o mundo poderia fazer para promover a paz, respondeu: "Vá para casa e ame a sua família."

Após sua morte, a publicação de suas cartas revelou que durante quase 50 anos viveu uma profunda "noite escura da alma" — sentindo a ausência completa de Deus — mas perseverou no serviço com fé heroica.$$, $$[{"title":"Vem, Sê Minha Luz (cartas privadas)","year":"2007 (publicação póstuma)"},{"title":"Caminho Simples","year":"1995"},{"title":"Sede Tenho (meditações)","year":"1998"}]$$::jsonb, '{"\"Se você julga as pessoas, não tem tempo para amá-las.\"","\"Não podemos todos fazer grandes coisas. Mas podemos fazer pequenas coisas com grande amor.\"","\"A paz começa com um sorriso.\"","\"Vá para casa e ame a sua família.\""}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Mother_Teresa_1.jpg/440px-Mother_Teresa_1.jpg$$, $$Santa Teresa de Calcutá, que servistes Cristo nos mais pobres entre os pobres, ajudai-nos a ver o rosto de Jesus em cada pessoa que encontramos.$$, '{"Caridade","Humildade","Serviço","Perseverança na fé"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$dulce-pobres$$, $$Santa Dulce dos Pobres$$, $$O Anjo Bom da Bahia$$, $$13 de Agosto$$, 8, 13, $$1914, Salvador, Bahia, Brasil$$, $$1992, Salvador, Bahia, Brasil$$, '{"Pobres","Doentes","Bahia"}'::text[], $$Primeira santa nascida no Brasil. Religiosa das Irmãs Missionárias da Imaculada Conceição da Mãe de Deus, dedicou sua vida ao serviço dos mais necessitados.$$, $$Maria Rita de Sousa Brito Lopes Pontes nasceu numa família de classe média em Salvador. Aos 13 anos, começou a ajudar pobres e doentes nos bairros mais carentes, guiada pelo tio, Frei Hildebrando. Aos 18 anos, ingressou na Congregação das Irmãs Missionárias da Imaculada Conceição da Mãe de Deus, recebendo o nome de Irmã Dulce.

Em 1939, começou a acolher doentes e operários em casas abandonadas e num galinheiro ao lado do convento. Desse gesto nasceram as Obras Sociais Irmã Dulce (OSID), que hoje constituem um dos maiores complexos de saúde e assistência social do Brasil, atendendo milhões de pessoas por ano.

Fundou o Hospital Santo Antônio, centros de acolhimento, escolas e centros profissionalizantes. Saía pelas ruas de Salvador pedindo esmolas para sustentar suas obras, sendo chamada carinhosamente de "O Anjo Bom da Bahia".

Em 1979, foi indicada ao Prêmio Nobel da Paz. O Papa João Paulo II, ao visitá-la em Salvador em 1980, beijou sua mão e disse: "Irmã Dulce, continue fazendo o que faz." Sofreu problemas respiratórios graves nos últimos anos, sendo internada e operada diversas vezes.

Foi beatificada em 2011 e canonizada pelo Papa Francisco em 13 de outubro de 2019, tornando-se a primeira santa nascida no Brasil. Seu corpo repousa no Santuário de Irmã Dulce, em Salvador.$$, $$[{"title":"Obras Sociais Irmã Dulce (OSID)","url":"https://www.irmadulce.org.br/"}]$$::jsonb, '{"\"Não posso ver ninguém sofrer sem sofrer junto.\"","\"Quem ajuda os outros, ajuda a si mesmo.\"","\"O amor é a única revolução capaz de transformar o mundo.\""}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Irm%C3%A3_Dulce.jpg/440px-Irm%C3%A3_Dulce.jpg$$, $$Santa Dulce dos Pobres, Anjo Bom da Bahia, intercedei por nós junto a Deus para que possamos servir os mais necessitados com o mesmo amor que ardia em vosso coração.$$, '{"Caridade","Pobreza","Compaixão","Perseverança"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$jose-anchieta$$, $$São José de Anchieta$$, $$Apóstolo do Brasil$$, $$9 de Junho$$, 6, 9, $$1534, San Cristóbal de La Laguna, Tenerife, Espanha$$, $$1597, Reritiba (atual Anchieta), Espírito Santo, Brasil$$, '{"Brasil","Catequistas","Educadores"}'::text[], $$Jesuíta espanhol, missionário no Brasil colonial. Fundador de São Paulo e autor da primeira gramática da língua tupi.$$, $$José de Anchieta nasceu nas Ilhas Canárias e ingressou na Companhia de Jesus aos 17 anos, em Coimbra. Em 1553, com apenas 19 anos, foi enviado ao Brasil, onde dedicaria os 44 anos seguintes de sua vida.

Chegou a São Vicente e logo se destacou pelo dom das línguas, aprendendo rapidamente o tupi. Compôs a primeira gramática da língua tupi ("Arte de Gramática da Língua Mais Usada na Costa do Brasil"), instrumento fundamental para a evangelização e para a preservação da cultura indígena.

Em 25 de janeiro de 1554, junto com o Padre Manuel da Nóbrega, fundou o colégio de São Paulo de Piratininga — núcleo que deu origem à cidade de São Paulo. Dedicou-se intensamente à catequese dos indígenas, aprendendo seus costumes e defendendo-os contra a escravidão.

Em 1563, durante negociações de paz com os tamoios em Iperoig (atual Ubatuba), foi mantido como refém por cinco meses. Durante o cativeiro, compôs na areia da praia o poema épico "De Beata Virgine Dei Matre Maria" — com mais de 5.000 versos em latim, memorizados integralmente.

Anchieta escreveu autos teatrais bilíngues (tupi e português), poemas, catecismos e cartas que são documentos históricos inestimáveis. Foi provincial dos jesuítas no Brasil e fundou diversas aldeias e missões. Morreu em Reritiba, no Espírito Santo.

Foi beatificado por João Paulo II em 1980 e canonizado pelo Papa Francisco em 2014.$$, $$[{"title":"Arte de Gramática da Língua Mais Usada na Costa do Brasil","year":"1595"},{"title":"De Beata Virgine Dei Matre Maria (Poema à Virgem)","year":"1563"},{"title":"Auto de São Lourenço","year":"c. 1583"},{"title":"Cartas, Informações, Fragmentos Históricos e Sermões","url":"https://digital.bbm.usp.br/handle/bbm/4784","year":"1554–1594"},{"title":"Catecismo na Língua Brasílica","year":"c. 1567"}]$$::jsonb, '{"\"Não há melhor maneira de pregar o Evangelho do que pelo exemplo.\"","\"A palavra de Deus deve ser pregada na língua que o povo entende.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Padre_Jos%C3%A9_de_Anchieta.jpg/440px-Padre_Jos%C3%A9_de_Anchieta.jpg$$, $$São José de Anchieta, apóstolo do Brasil, que trouxestes a luz do Evangelho a esta terra, intercedei por nós para que sejamos evangelizadores corajosos.$$, '{"Zelo missionário","Cultura","Defesa dos indígenas","Pobreza"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$roque-gonzalez$$, $$São Roque González de Santa Cruz$$, $$Mártir das Reduções$$, $$17 de Novembro$$, 11, 17, $$1576, Assunção, Paraguai$$, $$1628, Caaró, Rio Grande do Sul, Brasil$$, '{"Rio Grande do Sul","Missionários","Catequistas"}'::text[], $$Padre jesuíta, missionário entre os guaranis, fundador de diversas reduções no sul do Brasil. Martirizado em Caaró.$$, $$Roque González nasceu em Assunção, capital do Paraguai, filho de uma das famílias mais ilustres da cidade. Desde jovem dominava a língua guarani, o que seria fundamental para sua missão. Ordenado sacerdote diocesano aos 23 anos, tornou-se vigário-geral da diocese de Assunção.

Em 1609, aos 33 anos, deixou sua posição privilegiada e ingressou na Companhia de Jesus para dedicar-se inteiramente à evangelização dos povos guaranis. Nos 19 anos seguintes, fundou pelo menos sete reduções (missões) no atual Rio Grande do Sul, entre elas São Nicolau, Candelária e Assunção do Ijuí.

As reduções jesuíticas eram comunidades onde os indígenas viviam em liberdade, protegidos da escravidão imposta pelos colonizadores. Roque González defendia vigorosamente os direitos dos guaranis e denunciava a exploração colonial.

Em 15 de novembro de 1628, enquanto instalava um sino na recém-fundada redução de Todos os Santos de Caaró (atual município de Caaró, RS), foi atacado e morto a golpes de itaicá (machado de pedra) pelo cacique Nheçu, instigado por pajés que viam na evangelização uma ameaça ao seu poder. Junto com ele foram martirizados seus companheiros jesuítas Afonso Rodríguez e Juan del Castillo.

Seu coração foi arrancado do peito e lançado ao fogo, mas não se consumiu — a relíquia é preservada até hoje na capela de Caaró. Foi canonizado por João Paulo II em 1988, junto com seus companheiros mártires.$$, $$[{"title":"Cartas Ânuas das Reduções","year":"1615–1628"}]$$::jsonb, '{"\"Por estes índios darei com gosto a minha vida.\"","\"A cruz é a nossa única esperança.\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Roque_Gonz%C3%A1lez_de_Santa_Cruz.jpg/440px-Roque_Gonz%C3%A1lez_de_Santa_Cruz.jpg$$, $$São Roque González, que destes vossa vida pela evangelização dos povos guaranis, intercedei por nós para que sejamos missionários corajosos do Evangelho.$$, '{"Zelo missionário","Coragem","Defesa dos indígenas","Martírio"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$estanislau$$, $$Santo Estanislau de Cracóvia$$, $$Bispo e Mártir$$, $$11 de Abril$$, 4, 11, $$1030, Szczepanów, Polônia$$, $$1079, Cracóvia, Polônia$$, '{"Polônia","Cracóvia","Estudantes morais"}'::text[], $$Bispo de Cracóvia e um dos primeiros santos poloneses. Conhecido por sua coragem ao confrontar a imoralidade do Rei Boleslau II, o que lhe custou a vida.$$, $$Estanislau nasceu em Szczepanów e estudou em Gniezno e Paris antes de ser ordenado sacerdote. Em 1072, foi consagrado Bispo de Cracóvia. Durante seu episcopado, foi um zeloso pastor, conhecido por sua caridade com os pobres e por sua reforma do clero.

O conflito com o Rei Boleslau II começou quando Estanislau denunciou publicamente a vida imoral do monarca e sua conduta tirânica. Quando o rei sequestrou a esposa de um nobre, Estanislau o excomungou. Furioso, o rei tentou fazer com que seus soldados matassem o bispo enquanto ele celebrava a missa na capela de São Miguel, mas eles se recusaram. O próprio rei então entrou na capela e assassinou Estanislau com suas próprias mãos.

O martírio de Estanislau provocou tamanha indignação que o rei foi forçado ao exílio. Estanislau tornou-se o primeiro polonês a ser canonizado (em 1253) e é considerado o símbolo da unidade e da independência da Polônia.$$, $$[]$$::jsonb, '{"\"Prefiro morrer a trair a lei de Deus.\"","\"O dever de um bispo é proteger seu rebanho, mesmo contra reis.\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Stanislaus_of_Szczepanow.jpg/440px-Stanislaus_of_Szczepanow.jpg$$, $$Ó Deus, por cuja honra o glorioso Bispo Estanislau caiu sob as espadas dos ímpios, concedei-nos a graça de sermos fortes na fé e constantes na prática da vossa lei.$$, '{"Coragem","Fidelidade","Zelo Pastoral","Integridade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$rita-cassia$$, $$Santa Rita de Cássia$$, $$Advogada das Causas Impossíveis$$, $$22 de Maio$$, 5, 22, $$1381, Roccaporena, Itália$$, $$1457, Cássia, Itália$$, '{"Causas impossíveis","Casamentos difíceis","Viúvas","Doentes"}'::text[], $$Mística agostiniana conhecida como a "Santa dos Impossíveis". Viveu os estados de esposa, mãe, viúva e religiosa, sempre com profunda paciência e fé.$$, $$Rita nasceu numa família humilde e, embora desejasse ser freira, foi dada em casamento a um homem violento e temperamental. Durante 18 anos, sofreu com paciência as infidelidades e maus-tratos do marido, convertendo-o finalmente pelo amor e pela oração antes de ele ser assassinado num conflito entre famílias.

Após a morte do marido e de seus dois filhos (que morreram de peste antes de poderem vingar a morte do pai), Rita ingressou no Mosteiro Agostiniano em Cássia. Durante sua vida religiosa, destacou-se pela caridade e por sua participação mística na Paixão de Cristo. Em 1441, recebeu um espinho da coroa de Jesus na testa, uma chaga que carregou por 15 anos até sua morte.

É chamada "Santa dos Impossíveis" por ter superado situações humanas desesperadoras com confiança absoluta em Deus. Sua devoção é uma das mais populares no mundo católico, especialmente no Brasil e na Itália.$$, $$[]$$::jsonb, '{"\"Não há nada impossível para Deus.\"","\"A paciência é o caminho para a paz.\""}'::text[], $$mystic$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Santa_Rita_da_Cascia_-_Santuario_Roccaporena.jpg/440px-Santa_Rita_da_Cascia_-_Santuario_Roccaporena.jpg$$, $$Ó poderosa e gloriosa Santa Rita, chamada Advogada das Causas Impossíveis, venho a vós com confiança em minhas necessidades. Intercedei por mim junto ao Pai, para que eu possa glorificá-Lo para sempre.$$, '{"Paciência","Perdão","Penitência","Confiança"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$nha-chica$$, $$Beata Nhá Chica$$, $$A Mãe dos Pobres de Baependi$$, $$14 de Junho$$, 6, 14, $$1808, São João del-Rei, Minas Gerais, Brasil$$, $$1895, Baependi, Minas Gerais, Brasil$$, '{"Pobres","Baependi","Causas impossíveis"}'::text[], $$Leiga mineira, filha de uma escrava liberta, dedicou sua vida à oração, à caridade e à construção da Igreja de Nossa Senhora da Conceição em Baependi.$$, $$Francisca de Paula de Jesus, conhecida como Nhá Chica, nasceu em São João del-Rei, filha de uma escrava alforriada. Órfã desde jovem, mudou-se com a mãe para Baependi, no sul de Minas Gerais, onde viveria o resto de sua longa vida.

Mestiça e pobre, Nhá Chica nunca frequentou escola e não sabia ler nem escrever, mas possuía uma sabedoria espiritual que atraía pessoas de todas as classes sociais. Vivia em extrema simplicidade numa pequena casa, dedicando-se à oração contemplativa — passava horas ajoelhada em oração — e à caridade com os mais necessitados.

Seu grande sonho era construir uma igreja dedicada a Nossa Senhora da Conceição. Com esmolas que recolhia e doações que conseguia, realizou esse sonho: a Igreja de Nossa Senhora da Conceição de Baependi foi inaugurada em 1867 e permanece até hoje como centro de peregrinação.

Nhá Chica era procurada como conselheira espiritual por ricos e pobres. Tinha o dom do conselho e muitos relataram graças obtidas por sua intercessão, tanto em vida quanto após sua morte. Faleceu aos 87 anos, sendo sepultada na igreja que ajudou a construir.

Foi beatificada pelo Papa Bento XVI em 4 de maio de 2013, em cerimônia presidida pelo Cardeal Angelo Amato no Santuário de Nhá Chica, em Baependi, com a presença de mais de 30 mil fiéis.$$, $$[]$$::jsonb, '{"\"Quem reza e trabalha não precisa de mais nada.\"","\"Confiem em Nossa Senhora, ela nunca abandona seus filhos.\"","\"A caridade é a maior de todas as virtudes.\""}'::text[], $$mystic$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Nh%C3%A1_Chica.jpg/440px-Nh%C3%A1_Chica.jpg$$, $$Beata Nhá Chica, mulher de oração e caridade, intercedei por nós junto a Deus, para que saibamos servir aos mais pobres com o mesmo amor que ardia em vosso coração.$$, '{"Oração","Caridade","Simplicidade","Devoção mariana"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$madre-paulina$$, $$Santa Paulina do Coração Agonizante de Jesus$$, $$Madre Paulina$$, $$9 de Julho$$, 7, 9, $$1865, Vigolo Vattaro, Trentino, Itália$$, $$1942, São Paulo, Brasil$$, '{"Diabéticos","Imigrantes","Santa Catarina"}'::text[], $$Fundadora da Congregação das Irmãzinhas da Imaculada Conceição. Imigrante italiana no Brasil, dedicou sua vida ao serviço dos doentes e pobres.$$, $$Amabile Lucia Visintainer nasceu no Trentino, então parte do Império Austro-Húngaro, e emigrou com a família para o Brasil em 1875, estabelecendo-se na colônia italiana de Vígolo, em Nova Trento, Santa Catarina.

Aos 14 anos, junto com sua amiga Virginia Nicolodi, começou a cuidar de uma mulher com câncer terminal que vivia abandonada. Esse gesto de caridade foi a semente da futura congregação. Em 12 de julho de 1890, as duas jovens fundaram a Congregação das Irmãzinhas da Imaculada Conceição, dedicada ao serviço dos doentes, órfãos e idosos.

Amabile recebeu o nome religioso de Irmã Paulina do Coração Agonizante de Jesus. A congregação cresceu rapidamente, abrindo casas em várias cidades de Santa Catarina e São Paulo. Madre Paulina era conhecida por sua humildade extrema, obediência e amor aos sofredores.

Em 1909, por determinação do bispo diocesano, Madre Paulina foi afastada da direção da congregação que fundara — uma prova dolorosíssima que aceitou com heroica obediência, sem nunca se queixar. Passou seus últimos 30 anos de vida realizando os trabalhos mais humildes: costurando, lavando roupa e cuidando de doentes no hospital.

Nos últimos anos, ficou cega e diabética, mas manteve sua alegria e serenidade. Morreu em São Paulo em 1942. Foi beatificada por João Paulo II em 1991 e canonizada pelo mesmo Papa em 19 de maio de 2002, tornando-se a primeira santa do sul do Brasil.$$, $$[{"title":"Congregação das Irmãzinhas da Imaculada Conceição","url":"https://www.irmazinhas.org.br/"}]$$::jsonb, '{"\"Quero ser santa a qualquer custo.\"","\"Tudo posso naquele que me dá forças.\"","\"Ó meu Jesus, fazei de mim o que quiserdes.\""}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Madre_Paulina.jpg/440px-Madre_Paulina.jpg$$, $$Santa Paulina, que aceitastes com amor as maiores provações, intercedei por nós para que saibamos encontrar Deus no serviço humilde aos que sofrem.$$, '{"Humildade","Obediência","Caridade","Paciência"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$maria-mae-deus$$, $$Santa Maria, Mãe de Deus$$, $$Theotokos$$, $$1 de Janeiro$$, 1, 1, $$Séc. I a.C., Nazaré$$, $$Séc. I, Éfeso ou Jerusalém$$, '{"Humanidade","Mães"}'::text[], $$Mãe de Jesus Cristo, a Virgem Maria é a mais venerada de todos os santos. Sua obediência ao plano de Deus abriu caminho para a Redenção.$$, $$Mãe de Jesus Cristo, a Virgem Maria é a mais venerada de todos os santos. Sua obediência ao plano de Deus abriu caminho para a Redenção.$$, $$[]$$::jsonb, '{"\"Eis a serva do Senhor, faça-se em mim segundo a tua palavra.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{"Obediência","Pureza","Fé"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$basilio-gregorio$$, $$São Basílio Magno e São Gregório Nazianzeno$$, $$Doutores da Igreja$$, $$2 de Janeiro$$, 1, 2, $$329/330, Capadócia$$, $$379/390, Capadócia$$, '{"Monges","Educadores"}'::text[], $$Dois dos três Padres Capadócios, defensores da doutrina trinitária contra o arianismo. Basílio fundou o monaquismo oriental.$$, $$Dois dos três Padres Capadócios, defensores da doutrina trinitária contra o arianismo. Basílio fundou o monaquismo oriental.$$, $$[]$$::jsonb, '{"\"A Bíblia é a carta de Deus para a humanidade.\""}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Sv_Vasilii_Velikii_%28765%29.jpg/440px-Sv_Vasilii_Velikii_%28765%29.jpg$$, NULL, '{"Sabedoria","Caridade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$nome-jesus$$, $$Santíssimo Nome de Jesus$$, $$Nome acima de todo nome$$, $$3 de Janeiro$$, 1, 3, NULL, NULL, '{"Cristãos"}'::text[], $$Festa que celebra o santo Nome de Jesus, dado pelo anjo Gabriel antes da sua concepção, e que significa "Deus salva".$$, $$Festa que celebra o santo Nome de Jesus, dado pelo anjo Gabriel antes da sua concepção, e que significa "Deus salva".$$, $$[]$$::jsonb, '{"\"Ao nome de Jesus se dobre todo joelho.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Bernardino_siena.jpg/440px-Bernardino_siena.jpg$$, NULL, '{"Devoção"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$isabel-seton$$, $$Santa Isabel Ana Seton$$, $$Primeira Santa Americana$$, $$4 de Janeiro$$, 1, 4, $$1774, Nova York$$, $$1821, Emmitsburg, Maryland$$, '{"Viúvas","Escolas católicas"}'::text[], $$Convertida ao catolicismo, fundou as Irmãs da Caridade e o sistema de escolas paroquiais nos Estados Unidos.$$, $$Convertida ao catolicismo, fundou as Irmãs da Caridade e o sistema de escolas paroquiais nos Estados Unidos.$$, $$[]$$::jsonb, '{"\"Vivam simplesmente para que outros possam simplesmente viver.\""}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Elizabeth_Ann_Seton.jpg/440px-Elizabeth_Ann_Seton.jpg$$, NULL, '{"Caridade","Fé"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$joao-neumann$$, $$São João Neumann$$, $$Bispo de Filadélfia$$, $$5 de Janeiro$$, 1, 5, $$1811, Boêmia$$, $$1860, Filadélfia$$, '{"Educação católica"}'::text[], $$Bispo redentorista que construiu dezenas de escolas e igrejas na Filadélfia.$$, $$Bispo redentorista que construiu dezenas de escolas e igrejas na Filadélfia.$$, $$[]$$::jsonb, '{"\"Todo momento é um momento de graça.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/St._John_Neumann.jpg/440px-St._John_Neumann.jpg$$, NULL, '{"Zelo","Humildade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$epifania$$, $$Epifania do Senhor$$, $$Manifestação aos Gentios$$, $$6 de Janeiro$$, 1, 6, NULL, NULL, '{"Missionários"}'::text[], $$Solenidade que celebra a visita dos Reis Magos ao Menino Jesus, representando a revelação de Cristo a todos os povos.$$, $$Solenidade que celebra a visita dos Reis Magos ao Menino Jesus, representando a revelação de Cristo a todos os povos.$$, $$[]$$::jsonb, '{"\"Viemos do Oriente para adorar o Rei.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Adorazione_dei_Magi_-_Gentile_da_Fabriano.jpg/440px-Adorazione_dei_Magi_-_Gentile_da_Fabriano.jpg$$, NULL, '{"Fé","Busca"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$raimundo-penafort$$, $$São Raimundo de Peñafort$$, $$Padroeiro dos Canonistas$$, $$7 de Janeiro$$, 1, 7, $$1175, Barcelona$$, $$1275, Barcelona$$, '{"Advogados","Canonistas"}'::text[], $$Dominicano e grande jurista, compilou as Decretais de Gregório IX, sistematizando o Direito Canônico.$$, $$Dominicano e grande jurista, compilou as Decretais de Gregório IX, sistematizando o Direito Canônico.$$, $$[]$$::jsonb, '{"\"A justiça sem misericórdia é crueldade.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Ramon_de_Penyafort.jpg/440px-Ramon_de_Penyafort.jpg$$, NULL, '{"Justiça","Sabedoria"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$batismo-senhor$$, $$Batismo do Senhor$$, $$Início da Vida Pública$$, $$13 de Janeiro$$, 1, 13, NULL, NULL, '{"Catecúmenos"}'::text[], $$Festa que celebra o batismo de Jesus no rio Jordão por João Batista, quando o Espírito Santo desceu como pomba.$$, $$Festa que celebra o batismo de Jesus no rio Jordão por João Batista, quando o Espírito Santo desceu como pomba.$$, $$[]$$::jsonb, '{"\"Tu és o meu Filho amado, em Ti me comprazo.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Baptism-of-Christ-Pietro-Perugino.jpg/440px-Baptism-of-Christ-Pietro-Perugino.jpg$$, NULL, '{"Humildade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$antonio-abade$$, $$Santo Antão do Deserto$$, $$Pai do Monaquismo$$, $$17 de Janeiro$$, 1, 17, $$251, Egito$$, $$356, Egito$$, '{"Eremitas","Animais"}'::text[], $$Pai do monaquismo cristão, viveu mais de 80 anos como eremita no deserto egípcio, combatendo as tentações do demônio.$$, $$Pai do monaquismo cristão, viveu mais de 80 anos como eremita no deserto egípcio, combatendo as tentações do demônio.$$, $$[]$$::jsonb, '{"\"Vi todas as armadilhas do inimigo espalhadas pelo mundo e gemi: quem poderá escapar delas? Ouvi uma voz que me disse: A humildade.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Zurbaran_-_St._Anthony_the_Abbot.jpg/440px-Zurbaran_-_St._Anthony_the_Abbot.jpg$$, NULL, '{"Ascese","Oração"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sebastiao$$, $$São Sebastião$$, $$Mártir da Guarda Pretoriana$$, $$20 de Janeiro$$, 1, 20, $$256, Narbona$$, $$288, Roma$$, '{"Soldados","Atletas","Rio de Janeiro"}'::text[], $$Oficial romano que professava a fé cristã em segredo. Descoberto, foi condenado a ser flechado, sobreviveu e voltou a denunciar o imperador.$$, $$Oficial romano que professava a fé cristã em segredo. Descoberto, foi condenado a ser flechado, sobreviveu e voltou a denunciar o imperador.$$, $$[]$$::jsonb, '{"\"A fé em Cristo é mais forte que qualquer flecha.\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Andrea_Mantegna_089.jpg/440px-Andrea_Mantegna_089.jpg$$, NULL, '{"Coragem","Fé"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$agnes$$, $$Santa Inês$$, $$Virgem e Mártir$$, $$21 de Janeiro$$, 1, 21, $$291, Roma$$, $$304, Roma$$, '{"Jovens","Noivas","Pureza"}'::text[], $$Jovem romana que consagrou sua virgindade a Cristo e foi martirizada aos 12 anos durante a perseguição de Diocleciano.$$, $$Jovem romana que consagrou sua virgindade a Cristo e foi martirizada aos 12 anos durante a perseguição de Diocleciano.$$, $$[]$$::jsonb, '{"\"Já estou unida Àquele a quem os anjos servem.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Jos%C3%A9_de_Ribera_064.jpg/440px-Jos%C3%A9_de_Ribera_064.jpg$$, NULL, '{"Pureza","Coragem"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$conversao-paulo$$, $$Conversão de São Paulo$$, $$Apóstolo dos Gentios$$, $$25 de Janeiro$$, 1, 25, $$5 d.C., Tarso$$, $$64/67, Roma$$, '{"Missionários","Teólogos"}'::text[], $$A conversão de Saulo de Tarso no caminho de Damasco é um dos eventos mais importantes do cristianismo.$$, $$A conversão de Saulo de Tarso no caminho de Damasco é um dos eventos mais importantes do cristianismo.$$, $$[]$$::jsonb, '{"\"Já não sou eu quem vive, é Cristo que vive em mim.\""}'::text[], $$apostle$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Caravaggio_-_La_conversione_di_San_Paolo.jpg/440px-Caravaggio_-_La_conversione_di_San_Paolo.jpg$$, NULL, '{"Conversão","Zelo"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$brígida-irlanda$$, $$Santa Brígida da Irlanda$$, $$A Maria dos Gaélicos$$, $$1 de Fevereiro$$, 2, 1, $$451, Irlanda$$, $$525, Kildare$$, '{"Irlanda","Poetas"}'::text[], $$Uma das padroeiras da Irlanda, fundou o mosteiro de Kildare, centro de arte e cultura cristã.$$, $$Uma das padroeiras da Irlanda, fundou o mosteiro de Kildare, centro de arte e cultura cristã.$$, $$[]$$::jsonb, '{"\"Cristo é visto em cada estranho.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/St_Brigid%27s_Cross.jpg/440px-St_Brigid%27s_Cross.jpg$$, NULL, '{"Generosidade","Hospitalidade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$apresentacao-senhor$$, $$Apresentação do Senhor$$, $$Candelária$$, $$2 de Fevereiro$$, 2, 2, NULL, NULL, '{"Vida consagrada"}'::text[], $$Festa que celebra a apresentação de Jesus no Templo por Maria e José, quando Simeão o reconheceu como "luz para iluminar as nações".$$, $$Festa que celebra a apresentação de Jesus no Templo por Maria e José, quando Simeão o reconheceu como "luz para iluminar as nações".$$, $$[]$$::jsonb, '{"\"Os meus olhos viram a tua salvação.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Andrea_Mantegna_049.jpg/440px-Andrea_Mantegna_049.jpg$$, NULL, '{"Obediência","Esperança"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$bras$$, $$São Brás$$, $$Bispo e Mártir$$, $$3 de Fevereiro$$, 2, 3, $$Séc. III, Armênia$$, $$316, Sebaste$$, '{"Doenças de garganta"}'::text[], $$Bispo e médico armênio, é invocado contra doenças da garganta. Salvou um menino engasgado com uma espinha de peixe.$$, $$Bispo e médico armênio, é invocado contra doenças da garganta. Salvou um menino engasgado com uma espinha de peixe.$$, $$[]$$::jsonb, '{"\"A cura do corpo começa pela cura da alma.\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Hans_Memling_-_St_Blaise_-_WGA15003.jpg/440px-Hans_Memling_-_St_Blaise_-_WGA15003.jpg$$, NULL, '{"Cura","Compaixão"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$agata$$, $$Santa Ágata$$, $$Virgem e Mártir$$, $$5 de Fevereiro$$, 2, 5, $$Séc. III, Catânia$$, $$251, Catânia$$, '{"Bombeiros","Joalheiros","Catânia"}'::text[], $$Jovem siciliana que resistiu aos avanços do prefeito Quintiano e foi horrivelmente torturada por sua fé.$$, $$Jovem siciliana que resistiu aos avanços do prefeito Quintiano e foi horrivelmente torturada por sua fé.$$, $$[]$$::jsonb, '{"\"Senhor, que me criastes e me protegestes desde a infância.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Francisco_de_Zurbar%C3%A1n_-_Saint_Agatha_-_Google_Art_Project.jpg/440px-Francisco_de_Zurbar%C3%A1n_-_Saint_Agatha_-_Google_Art_Project.jpg$$, NULL, '{"Castidade","Fortaleza"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$paulo-miki$$, $$São Paulo Miki e Companheiros$$, $$Mártires do Japão$$, $$6 de Fevereiro$$, 2, 6, $$1562, Japão$$, $$1597, Nagasáqui$$, '{"Japão"}'::text[], $$Jesuíta japonês, crucificado em Nagasáqui com outros 25 mártires, os primeiros mártires do Japão.$$, $$Jesuíta japonês, crucificado em Nagasáqui com outros 25 mártires, os primeiros mártires do Japão.$$, $$[]$$::jsonb, '{"\"Agradeço a Deus por morrer neste dia.\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Martyrs_of_Japan.jpg/440px-Martyrs_of_Japan.jpg$$, NULL, '{"Martírio","Fé"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$escolastica$$, $$Santa Escolástica$$, $$Irmã de São Bento$$, $$10 de Fevereiro$$, 2, 10, $$480, Núrsia$$, $$547, Monte Cassino$$, '{"Monjas","Tempestades"}'::text[], $$Irmã gêmea de São Bento, fundadora do ramo feminino dos beneditinos. Sua oração provocou uma tempestade para reter o irmão.$$, $$Irmã gêmea de São Bento, fundadora do ramo feminino dos beneditinos. Sua oração provocou uma tempestade para reter o irmão.$$, $$[]$$::jsonb, '{"\"O amor é mais forte que qualquer regra.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Ary_Scheffer_-_Saints_Augustine_and_Monica_%281846%29.jpg/440px-Ary_Scheffer_-_Saints_Augustine_and_Monica_%281846%29.jpg$$, NULL, '{"Oração","Amor fraterno"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$nossa-senhora-lourdes$$, $$Nossa Senhora de Lourdes$$, $$A Imaculada Conceição$$, $$11 de Fevereiro$$, 2, 11, NULL, NULL, '{"Enfermos"}'::text[], $$Em 1858, a Virgem Maria apareceu 18 vezes a Santa Bernadette na gruta de Massabielle, em Lourdes, França.$$, $$Em 1858, a Virgem Maria apareceu 18 vezes a Santa Bernadette na gruta de Massabielle, em Lourdes, França.$$, $$[]$$::jsonb, '{"\"Eu sou a Imaculada Conceição.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Lourdes_-_Pair_of_statues.jpg/440px-Lourdes_-_Pair_of_statues.jpg$$, NULL, '{"Pureza","Cura"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$cirilo-metodio$$, $$Santos Cirilo e Metódio$$, $$Apóstolos dos Eslavos$$, $$14 de Fevereiro$$, 2, 14, $$826/827, Tessalônica$$, $$869/885$$, '{"Europa","Eslavos"}'::text[], $$Irmãos gregos que evangelizaram os povos eslavos. Cirilo criou o alfabeto glagolítico, base do cirílico.$$, $$Irmãos gregos que evangelizaram os povos eslavos. Cirilo criou o alfabeto glagolítico, base do cirílico.$$, $$[]$$::jsonb, '{"\"A Palavra de Deus deve ser ouvida na língua de cada povo.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Slavonic_wenceslas_bible.jpg/440px-Slavonic_wenceslas_bible.jpg$$, NULL, '{"Evangelização","Cultura"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$catedra-pedro$$, $$Cátedra de São Pedro$$, $$Pedra da Igreja$$, $$22 de Fevereiro$$, 2, 22, NULL, NULL, '{"Papado"}'::text[], $$Festa que celebra a autoridade de ensino que Cristo confiou a Pedro e seus sucessores como chefe da Igreja.$$, $$Festa que celebra a autoridade de ensino que Cristo confiou a Pedro e seus sucessores como chefe da Igreja.$$, $$[]$$::jsonb, '{"\"Tu és Pedro e sobre esta pedra edificarei a minha Igreja.\""}'::text[], $$apostle$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Cathedra_Petri_adjusted.JPG/440px-Cathedra_Petri_adjusted.JPG$$, NULL, '{"Autoridade","Fé"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;
