INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-inacio-laconi$$, $$São Inácio de Laconi$$, $$Frade Capuchinho$$, $$11 de Maio$$, 5, 11, NULL, NULL, '{}'::text[], $$Humilde frade capuchinho sardo famoso pela caridade e milagres.$$, $$Humilde frade capuchinho sardo famoso pela caridade e milagres.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santos-nereu-aquiles$$, $$Santos Nereu e Aquiles$$, $$Mártires de Roma$$, $$12 de Maio$$, 5, 12, NULL, NULL, '{}'::text[], $$Soldados romanos convertidos que abandonaram as armas e foram martirizados.$$, $$Soldados romanos convertidos que abandonaram as armas e foram martirizados.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-isidoro-lavrador$$, $$São Isidoro Lavrador$$, $$Padroeiro dos Agricultores$$, $$15 de Maio$$, 5, 15, NULL, NULL, '{}'::text[], $$Camponês espanhol cuja fé e trabalho eram acompanhados de milagres.$$, $$Camponês espanhol cuja fé e trabalho eram acompanhados de milagres.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-simao-stock$$, $$São Simão Stock$$, $$General dos Carmelitas$$, $$16 de Maio$$, 5, 16, NULL, NULL, '{}'::text[], $$Superior geral dos Carmelitas que recebeu o escapulário de Nossa Senhora.$$, $$Superior geral dos Carmelitas que recebeu o escapulário de Nossa Senhora.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-pascoal$$, $$São Pascoal Bailão$$, $$Padroeiro da Eucaristia$$, $$17 de Maio$$, 5, 17, NULL, NULL, '{}'::text[], $$Frade franciscano espanhol com grande devoção à Eucaristia.$$, $$Frade franciscano espanhol com grande devoção à Eucaristia.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-joao-papa-i$$, $$São João I$$, $$Papa e Mártir$$, $$18 de Maio$$, 5, 18, NULL, NULL, '{}'::text[], $$Papa martirizado pelo rei ostrogodo Teodorico por defender a fé católica.$$, $$Papa martirizado pelo rei ostrogodo Teodorico por defender a fé católica.$$, $$[]$$::jsonb, '{}'::text[], $$pope$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Cathedra_Petri_adjusted.JPG/440px-Cathedra_Petri_adjusted.JPG$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-celestino-v$$, $$São Celestino V$$, $$Papa Eremita$$, $$19 de Maio$$, 5, 19, NULL, NULL, '{}'::text[], $$Eremita eleito Papa que renunciou após cinco meses para retornar à vida contemplativa.$$, $$Eremita eleito Papa que renunciou após cinco meses para retornar à vida contemplativa.$$, $$[]$$::jsonb, '{}'::text[], $$pope$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Cathedra_Petri_adjusted.JPG/440px-Cathedra_Petri_adjusted.JPG$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-bernardino-sena$$, $$São Bernardino de Sena$$, $$Apóstolo do Nome de Jesus$$, $$20 de Maio$$, 5, 20, NULL, NULL, '{}'::text[], $$Pregador franciscano que difundiu a devoção ao Santíssimo Nome de Jesus.$$, $$Pregador franciscano que difundiu a devoção ao Santíssimo Nome de Jesus.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-cristobal-magallanes$$, $$São Cristóbal Magallanes$$, $$Mártir do México$$, $$21 de Maio$$, 5, 21, NULL, NULL, '{}'::text[], $$Sacerdote mexicano martirizado durante a perseguição dos Cristeros.$$, $$Sacerdote mexicano martirizado durante a perseguição dos Cristeros.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-joao-rossi$$, $$São João Batista de Rossi$$, $$Sacerdote Romano$$, $$23 de Maio$$, 5, 23, NULL, NULL, '{}'::text[], $$Sacerdote romano que se dedicou especialmente aos pobres e enfermos.$$, $$Sacerdote romano que se dedicou especialmente aos pobres e enfermos.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$nsa-auxiliadora$$, $$Nossa Senhora Auxiliadora$$, $$Auxilium Christianorum$$, $$24 de Maio$$, 5, 24, NULL, NULL, '{}'::text[], $$Devoção mariana promovida por São João Bosco como padroeira dos Salesianos.$$, $$Devoção mariana promovida por São João Bosco como padroeira dos Salesianos.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-beda$$, $$São Beda Venerável$$, $$Doutor da Igreja$$, $$25 de Maio$$, 5, 25, NULL, NULL, '{}'::text[], $$Monge inglês considerado o pai da história inglesa e grande escritor eclesiástico.$$, $$Monge inglês considerado o pai da história inglesa e grande escritor eclesiástico.$$, $$[]$$::jsonb, '{}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-filipe-neri$$, $$São Filipe Néri$$, $$Apóstolo de Roma$$, $$26 de Maio$$, 5, 26, NULL, NULL, '{}'::text[], $$Sacerdote alegre e carismático que fundou o Oratório, renovando a vida cristã em Roma.$$, $$Sacerdote alegre e carismático que fundou o Oratório, renovando a vida cristã em Roma.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-agostinha$$, $$Santa Agostinha Liautaud$$, $$Fundadora$$, $$27 de Maio$$, 5, 27, NULL, NULL, '{}'::text[], $$Religiosa francesa que fundou a congregação de Nossa Senhora da Assunção.$$, $$Religiosa francesa que fundou a congregação de Nossa Senhora da Assunção.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-germano-paris$$, $$São Germano de Paris$$, $$Bispo$$, $$28 de Maio$$, 5, 28, NULL, NULL, '{}'::text[], $$Bispo de Paris que combateu a idolatria e promoveu a vida monástica.$$, $$Bispo de Paris que combateu a idolatria e promoveu a vida monástica.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-maximino$$, $$São Maximino de Tréveris$$, $$Bispo$$, $$29 de Maio$$, 5, 29, NULL, NULL, '{}'::text[], $$Bispo que acolheu Santo Atanásio exilado e defendeu a fé nicena.$$, $$Bispo que acolheu Santo Atanásio exilado e defendeu a fé nicena.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santos-carlos-lwanga$$, $$Santos Carlos Lwanga e Companheiros$$, $$Mártires de Uganda$$, $$3 de Junho$$, 6, 3, NULL, NULL, '{}'::text[], $$22 jovens ugandenses martirizados por se recusarem aos abusos do rei Mwanga.$$, $$22 jovens ugandenses martirizados por se recusarem aos abusos do rei Mwanga.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-francisco-caracciolo$$, $$São Francisco Caracciolo$$, $$Fundador$$, $$4 de Junho$$, 6, 4, NULL, NULL, '{}'::text[], $$Sacerdote napolitano que fundou os Clérigos Regulares Menores.$$, $$Sacerdote napolitano que fundou os Clérigos Regulares Menores.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-norberto$$, $$São Norberto$$, $$Fundador dos Premonstratenses$$, $$6 de Junho$$, 6, 6, NULL, NULL, '{}'::text[], $$Bispo que se converteu radicalmente e fundou a Ordem dos Premonstratenses.$$, $$Bispo que se converteu radicalmente e fundou a Ordem dos Premonstratenses.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$bem-ana-bartolomea$$, $$Beata Ana de São Bartolomeu$$, $$Companheira de Teresa$$, $$7 de Junho$$, 6, 7, NULL, NULL, '{}'::text[], $$Carmelita espanhola companheira de Santa Teresa de Ávila na reforma do Carmelo.$$, $$Carmelita espanhola companheira de Santa Teresa de Ávila na reforma do Carmelo.$$, $$[]$$::jsonb, '{}'::text[], $$mystic$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Giovanni_Battista_Tiepolo_-_Saint_Catherine_of_Siena.jpg/440px-Giovanni_Battista_Tiepolo_-_Saint_Catherine_of_Siena.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-medardo$$, $$São Medardo de Noyon$$, $$Bispo$$, $$8 de Junho$$, 6, 8, NULL, NULL, '{}'::text[], $$Bispo francês famoso por sua caridade.$$, $$Bispo francês famoso por sua caridade.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$bem-diana-andalo$$, $$Beata Diana de Andaló$$, $$Dominicana$$, $$10 de Junho$$, 6, 10, NULL, NULL, '{}'::text[], $$Nobre bolonhesa que se tornou religiosa dominicana apesar da oposição familiar.$$, $$Nobre bolonhesa que se tornou religiosa dominicana apesar da oposição familiar.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-barnabe$$, $$São Barnabé$$, $$Apóstolo$$, $$11 de Junho$$, 6, 11, NULL, NULL, '{}'::text[], $$Companheiro de São Paulo nas primeiras viagens missionárias, apóstolo de Chipre.$$, $$Companheiro de São Paulo nas primeiras viagens missionárias, apóstolo de Chipre.$$, $$[]$$::jsonb, '{}'::text[], $$apostle$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/El_Greco_-_Apostles_Peter_and_Paul_-_WGA10537.jpg/440px-El_Greco_-_Apostles_Peter_and_Paul_-_WGA10537.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-gaspar-bertoni$$, $$São Gaspar Bertoni$$, $$Fundador dos Estigmatinos$$, $$12 de Junho$$, 6, 12, NULL, NULL, '{}'::text[], $$Sacerdote italiano que fundou os Estigmatinos.$$, $$Sacerdote italiano que fundou os Estigmatinos.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-germana-cousin$$, $$Santa Germana Cousin$$, $$A Cinderela dos Santos$$, $$15 de Junho$$, 6, 15, NULL, NULL, '{}'::text[], $$Pastora humilde e maltratada que viveu com santidade heroica.$$, $$Pastora humilde e maltratada que viveu com santidade heroica.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-joao-regis$$, $$São João Francisco Régis$$, $$Apóstolo de Vivarais$$, $$16 de Junho$$, 6, 16, NULL, NULL, '{}'::text[], $$Jesuíta francês que percorreu montanhas evangelizando comunidades esquecidas.$$, $$Jesuíta francês que percorreu montanhas evangelizando comunidades esquecidas.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-gregorio-barbarigo$$, $$São Gregório Barbarigo$$, $$Bispo de Pádua$$, $$17 de Junho$$, 6, 17, NULL, NULL, '{}'::text[], $$Cardeal que implementou as reformas do Concílio de Trento na sua diocese.$$, $$Cardeal que implementou as reformas do Concílio de Trento na sua diocese.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-gregorio-agrigento$$, $$São Gregório de Agrigento$$, $$Bispo da Sicília$$, $$18 de Junho$$, 6, 18, NULL, NULL, '{}'::text[], $$Bispo siciliano que defendeu a fé contra acusações injustas.$$, $$Bispo siciliano que defendeu a fé contra acusações injustas.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-romualdo$$, $$São Romualdo$$, $$Fundador dos Camaldulenses$$, $$19 de Junho$$, 6, 19, NULL, NULL, '{}'::text[], $$Monge que fundou a Congregação dos Camaldulenses.$$, $$Monge que fundou a Congregação dos Camaldulenses.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$bem-michelina$$, $$Beata Michelina de Pesaro$$, $$Penitente Franciscana$$, $$20 de Junho$$, 6, 20, NULL, NULL, '{}'::text[], $$Nobre viúva que abandonou tudo para viver como terciária franciscana.$$, $$Nobre viúva que abandonou tudo para viver como terciária franciscana.$$, $$[]$$::jsonb, '{}'::text[], $$mystic$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Giovanni_Battista_Tiepolo_-_Saint_Catherine_of_Siena.jpg/440px-Giovanni_Battista_Tiepolo_-_Saint_Catherine_of_Siena.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-luis-gonzaga$$, $$São Luís Gonzaga$$, $$Padroeiro da Juventude$$, $$21 de Junho$$, 6, 21, NULL, NULL, '{}'::text[], $$Jovem jesuíta que renunciou ao título de marquês e morreu cuidando de pestíferos aos 23 anos.$$, $$Jovem jesuíta que renunciou ao título de marquês e morreu cuidando de pestíferos aos 23 anos.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-paulino-nola$$, $$São Paulino de Nola$$, $$Bispo e Poeta$$, $$22 de Junho$$, 6, 22, NULL, NULL, '{}'::text[], $$Senador romano que se tornou bispo, conhecido por sua generosidade e poesia cristã.$$, $$Senador romano que se tornou bispo, conhecido por sua generosidade e poesia cristã.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-jose-cafasso$$, $$São José Cafasso$$, $$Pai dos Sacerdotes$$, $$23 de Junho$$, 6, 23, NULL, NULL, '{}'::text[], $$Sacerdote piemontês, mestre de São João Bosco e grande confessor.$$, $$Sacerdote piemontês, mestre de São João Bosco e grande confessor.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-guilherme-vercelli$$, $$São Guilherme de Vercelli$$, $$Eremita$$, $$25 de Junho$$, 6, 25, NULL, NULL, '{}'::text[], $$Fundador da Congregação de Monte Virgine na Itália.$$, $$Fundador da Congregação de Monte Virgine na Itália.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-josemaria-escriva$$, $$São Josemaría Escrivá$$, $$Fundador do Opus Dei$$, $$26 de Junho$$, 6, 26, NULL, NULL, '{}'::text[], $$Sacerdote espanhol que fundou o Opus Dei, promovendo a santificação no trabalho.$$, $$Sacerdote espanhol que fundou o Opus Dei, promovendo a santificação no trabalho.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-cirilo-alexandria$$, $$São Cirilo de Alexandria$$, $$Defensor da Maternidade Divina$$, $$27 de Junho$$, 6, 27, NULL, NULL, '{}'::text[], $$Patriarca que defendeu o título Theotokos no Concílio de Éfeso.$$, $$Patriarca que defendeu o título Theotokos no Concílio de Éfeso.$$, $$[]$$::jsonb, '{}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santo-irineu-lyon$$, $$Santo Irineu de Lyon$$, $$Pai da Teologia$$, $$28 de Junho$$, 6, 28, NULL, NULL, '{}'::text[], $$Bispo de Lyon, discípulo de São Policarpo, grande defensor contra as heresias gnósticas.$$, $$Bispo de Lyon, discípulo de São Policarpo, grande defensor contra as heresias gnósticas.$$, $$[]$$::jsonb, '{}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$primeiros-martires-roma$$, $$Santos Protomártires de Roma$$, $$Mártires do Circo de Nero$$, $$30 de Junho$$, 6, 30, NULL, NULL, '{}'::text[], $$Os primeiros cristãos martirizados em Roma por ordem do imperador Nero.$$, $$Os primeiros cristãos martirizados em Roma por ordem do imperador Nero.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-junipero-serra$$, $$São Junípero Serra$$, $$Apóstolo da Califórnia$$, $$1 de Julho$$, 7, 1, NULL, NULL, '{}'::text[], $$Frade franciscano espanhol que fundou as missões da Califórnia.$$, $$Frade franciscano espanhol que fundou as missões da Califórnia.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-bernardino-realino$$, $$São Bernardino Realino$$, $$Jesuíta Santo$$, $$2 de Julho$$, 7, 2, NULL, NULL, '{}'::text[], $$Jesuíta italiano famoso por sua caridade e milagres na cidade de Lecce.$$, $$Jesuíta italiano famoso por sua caridade e milagres na cidade de Lecce.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;
