INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$santa-isabel-portugal$$, $$Santa Isabel de Portugal$$, $$Rainha da Paz$$, $$4 de Julho$$, 7, 4, NULL, NULL, '{}'::text[], $$Rainha de Portugal que mediou a paz entre reis e se dedicou aos pobres.$$, $$Rainha de Portugal que mediou a paz entre reis e se dedicou aos pobres.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santo-antonio-zaccaria$$, $$Santo Antônio Maria Zaccaria$$, $$Fundador dos Barnabitas$$, $$5 de Julho$$, 7, 5, NULL, NULL, '{}'::text[], $$Médico que se tornou sacerdote e fundou a Ordem dos Barnabitas.$$, $$Médico que se tornou sacerdote e fundou a Ordem dos Barnabitas.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-maria-goretti$$, $$Santa Maria Goretti$$, $$Virgem e Mártir$$, $$6 de Julho$$, 7, 6, NULL, NULL, '{}'::text[], $$Jovem italiana que perdoou seu assassino e morreu aos 12 anos defendendo sua pureza.$$, $$Jovem italiana que perdoou seu assassino e morreu aos 12 anos defendendo sua pureza.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-vilibaldo$$, $$São Vilibaldo$$, $$Bispo Viajante$$, $$7 de Julho$$, 7, 7, NULL, NULL, '{}'::text[], $$Monge inglês que peregrinou até a Terra Santa e se tornou bispo na Baviera.$$, $$Monge inglês que peregrinou até a Terra Santa e se tornou bispo na Baviera.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-quiliano$$, $$São Quiliano$$, $$Apóstolo da Francônia$$, $$8 de Julho$$, 7, 8, NULL, NULL, '{}'::text[], $$Monge irlandês missionário martirizado na Alemanha.$$, $$Monge irlandês missionário martirizado na Alemanha.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$santa-veronica-giuliani$$, $$Santa Verônica Giuliani$$, $$Mística Capuchinha$$, $$10 de Julho$$, 7, 10, NULL, NULL, '{}'::text[], $$Abadessa capuchinha que recebeu os estigmas e viveu profundas experiências místicas.$$, $$Abadessa capuchinha que recebeu os estigmas e viveu profundas experiências místicas.$$, $$[]$$::jsonb, '{}'::text[], $$mystic$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Giovanni_Battista_Tiepolo_-_Saint_Catherine_of_Siena.jpg/440px-Giovanni_Battista_Tiepolo_-_Saint_Catherine_of_Siena.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-joao-gualberto$$, $$São João Gualberto$$, $$Fundador de Vallombrosa$$, $$12 de Julho$$, 7, 12, NULL, NULL, '{}'::text[], $$Monge que fundou a Congregação de Vallombrosa após perdoar o assassino de seu irmão.$$, $$Monge que fundou a Congregação de Vallombrosa após perdoar o assassino de seu irmão.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-henrique$$, $$Santo Henrique II$$, $$Imperador Santo$$, $$13 de Julho$$, 7, 13, NULL, NULL, '{}'::text[], $$Imperador do Sacro Império Romano que promoveu a reforma da Igreja.$$, $$Imperador do Sacro Império Romano que promoveu a reforma da Igreja.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-camilo-lellis$$, $$São Camilo de Léllis$$, $$Padroeiro dos Enfermeiros$$, $$14 de Julho$$, 7, 14, NULL, NULL, '{}'::text[], $$Ex-soldado que se converteu e fundou os Ministros dos Enfermos.$$, $$Ex-soldado que se converteu e fundou os Ministros dos Enfermos.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-boaventura$$, $$São Boaventura$$, $$Doutor Seráfico$$, $$15 de Julho$$, 7, 15, NULL, NULL, '{}'::text[], $$Cardeal franciscano, teólogo e biógrafo de São Francisco de Assis.$$, $$Cardeal franciscano, teólogo e biógrafo de São Francisco de Assis.$$, $$[]$$::jsonb, '{}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$santa-hedviges$$, $$Santa Hedviges da Silésia$$, $$Duquesa Santa$$, $$17 de Julho$$, 7, 17, NULL, NULL, '{}'::text[], $$Duquesa que viveu em grande austeridade e fundou hospitais e mosteiros.$$, $$Duquesa que viveu em grande austeridade e fundou hospitais e mosteiros.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-frederico$$, $$São Frederico de Utrecht$$, $$Bispo e Mártir$$, $$18 de Julho$$, 7, 18, NULL, NULL, '{}'::text[], $$Bispo de Utrecht assassinado após denunciar o casamento incestuoso do imperador.$$, $$Bispo de Utrecht assassinado após denunciar o casamento incestuoso do imperador.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-arsenio$$, $$Santo Arsênio o Grande$$, $$Pai do Deserto$$, $$19 de Julho$$, 7, 19, NULL, NULL, '{}'::text[], $$Tutor dos filhos do imperador que abandonou a corte para viver como eremita no Egito.$$, $$Tutor dos filhos do imperador que abandonou a corte para viver como eremita no Egito.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santo-elias$$, $$Santo Elias Profeta$$, $$Pai dos Carmelitas$$, $$20 de Julho$$, 7, 20, NULL, NULL, '{}'::text[], $$Grande profeta de Israel que combateu a idolatria e foi arrebatado ao céu num carro de fogo.$$, $$Grande profeta de Israel que combateu a idolatria e foi arrebatado ao céu num carro de fogo.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-lourenco-brindisi$$, $$São Lourenço de Bríndisi$$, $$Doutor da Igreja$$, $$21 de Julho$$, 7, 21, NULL, NULL, '{}'::text[], $$Frade capuchinho poliglota que pregou em muitas línguas e converteu muitos hereges.$$, $$Frade capuchinho poliglota que pregou em muitas línguas e converteu muitos hereges.$$, $$[]$$::jsonb, '{}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$santa-brigida-suecia$$, $$Santa Brígida da Suécia$$, $$Padroeira da Europa$$, $$23 de Julho$$, 7, 23, NULL, NULL, '{}'::text[], $$Mística sueca que fundou a Ordem do Santíssimo Salvador e recebeu revelações.$$, $$Mística sueca que fundou a Ordem do Santíssimo Salvador e recebeu revelações.$$, $$[]$$::jsonb, '{}'::text[], $$mystic$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Giovanni_Battista_Tiepolo_-_Saint_Catherine_of_Siena.jpg/440px-Giovanni_Battista_Tiepolo_-_Saint_Catherine_of_Siena.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santos-joaquim-ana$$, $$Santos Joaquim e Ana$$, $$Pais de Nossa Senhora$$, $$26 de Julho$$, 7, 26, NULL, NULL, '{}'::text[], $$Avós de Jesus, pais da Virgem Maria segundo a tradição.$$, $$Avós de Jesus, pais da Virgem Maria segundo a tradição.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-pantaleao$$, $$São Pantaleão$$, $$Médico e Mártir$$, $$27 de Julho$$, 7, 27, NULL, NULL, '{}'::text[], $$Médico do imperador que se converteu e foi martirizado por curar em nome de Cristo.$$, $$Médico do imperador que se converteu e foi martirizado por curar em nome de Cristo.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-pedro-crisologo$$, $$São Pedro Crisólogo$$, $$Doutor da Igreja$$, $$28 de Julho$$, 7, 28, NULL, NULL, '{}'::text[], $$Arcebispo de Ravena chamado Crisólogo (palavra de ouro) por sua eloquência.$$, $$Arcebispo de Ravena chamado Crisólogo (palavra de ouro) por sua eloquência.$$, $$[]$$::jsonb, '{}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-pedro-crisologo-jul$$, $$São Pedro Crisólogo$$, $$Palavra de Ouro$$, $$30 de Julho$$, 7, 30, NULL, NULL, '{}'::text[], $$Celebração do arcebispo de Ravena célebre por seus sermões sobre a Encarnação.$$, $$Celebração do arcebispo de Ravena célebre por seus sermões sobre a Encarnação.$$, $$[]$$::jsonb, '{}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$santo-inacio-loyola$$, $$Santo Inácio de Loyola$$, $$Fundador dos Jesuítas$$, $$31 de Julho$$, 7, 31, NULL, NULL, '{}'::text[], $$Soldado basco convertido que fundou a Companhia de Jesus.$$, $$Soldado basco convertido que fundou a Companhia de Jesus.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santo-eusebio$$, $$Santo Eusébio de Vercelli$$, $$Bispo Exilado$$, $$2 de Agosto$$, 8, 2, NULL, NULL, '{}'::text[], $$Primeiro bispo do Piemonte, exilado por defender a fé contra o arianismo.$$, $$Primeiro bispo do Piemonte, exilado por defender a fé contra o arianismo.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-pedro-eymard$$, $$São Pedro Julião Eymard$$, $$Apóstolo da Eucaristia$$, $$3 de Agosto$$, 8, 3, NULL, NULL, '{}'::text[], $$Sacerdote francês que fundou os Padres do Santíssimo Sacramento.$$, $$Sacerdote francês que fundou os Padres do Santíssimo Sacramento.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-joao-vianney$$, $$São João Maria Vianney$$, $$Cura d Ars$$, $$4 de Agosto$$, 8, 4, NULL, NULL, '{}'::text[], $$O mais famoso pároco da história, passava até 16 horas por dia no confessionário.$$, $$O mais famoso pároco da história, passava até 16 horas por dia no confessionário.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$nsa-neves$$, $$Nossa Senhora das Neves$$, $$Basílica de Santa Maria Maior$$, $$5 de Agosto$$, 8, 5, NULL, NULL, '{}'::text[], $$Festa da maior basílica mariana do mundo, em Roma.$$, $$Festa da maior basílica mariana do mundo, em Roma.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-caetano$$, $$São Caetano de Tiene$$, $$Fundador dos Teatinos$$, $$7 de Agosto$$, 8, 7, NULL, NULL, '{}'::text[], $$Sacerdote que fundou os Clérigos Regulares para reformar o clero.$$, $$Sacerdote que fundou os Clérigos Regulares para reformar o clero.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-teresa-benedicta$$, $$Santa Teresa Benedita da Cruz$$, $$Edith Stein$$, $$9 de Agosto$$, 8, 9, NULL, NULL, '{}'::text[], $$Filósofa judia convertida, carmelita, martirizada em Auschwitz.$$, $$Filósofa judia convertida, carmelita, martirizada em Auschwitz.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-lourenco$$, $$São Lourenço$$, $$Diácono e Mártir$$, $$10 de Agosto$$, 8, 10, NULL, NULL, '{}'::text[], $$Diácono de Roma que distribuiu os bens da Igreja aos pobres e foi assado numa grelha.$$, $$Diácono de Roma que distribuiu os bens da Igreja aos pobres e foi assado numa grelha.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-joana-chantal$$, $$Santa Joana Francisca de Chantal$$, $$Fundadora da Visitação$$, $$12 de Agosto$$, 8, 12, NULL, NULL, '{}'::text[], $$Viúva que, com São Francisco de Sales, fundou a Ordem da Visitação.$$, $$Viúva que, com São Francisco de Sales, fundou a Ordem da Visitação.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-maximiliano-kolbe$$, $$São Maximiliano Maria Kolbe$$, $$Mártir da Caridade$$, $$14 de Agosto$$, 8, 14, NULL, NULL, '{}'::text[], $$Frade franciscano que se ofereceu para morrer no lugar de outro em Auschwitz.$$, $$Frade franciscano que se ofereceu para morrer no lugar de outro em Auschwitz.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-estevao-hungria$$, $$Santo Estêvão da Hungria$$, $$Rei e Apóstolo$$, $$16 de Agosto$$, 8, 16, NULL, NULL, '{}'::text[], $$Primeiro rei cristão da Hungria que converteu seu povo ao cristianismo.$$, $$Primeiro rei cristão da Hungria que converteu seu povo ao cristianismo.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-joana-delanoue$$, $$Santa Joana Delanoue$$, $$Serva dos Pobres$$, $$17 de Agosto$$, 8, 17, NULL, NULL, '{}'::text[], $$Comerciante francesa convertida que fundou as Irmãs de Santa Ana da Providência.$$, $$Comerciante francesa convertida que fundou as Irmãs de Santa Ana da Providência.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-helena$$, $$Santa Helena$$, $$Mãe de Constantino$$, $$18 de Agosto$$, 8, 18, NULL, NULL, '{}'::text[], $$Imperatriz que encontrou a Vera Cruz de Cristo em Jerusalém.$$, $$Imperatriz que encontrou a Vera Cruz de Cristo em Jerusalém.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-joao-eudes$$, $$São João Eudes$$, $$Apóstolo dos Corações$$, $$19 de Agosto$$, 8, 19, NULL, NULL, '{}'::text[], $$Sacerdote francês que propagou a devoção aos Sagrados Corações de Jesus e Maria.$$, $$Sacerdote francês que propagou a devoção aos Sagrados Corações de Jesus e Maria.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-pio-x$$, $$São Pio X$$, $$Papa da Eucaristia$$, $$21 de Agosto$$, 8, 21, NULL, NULL, '{}'::text[], $$Papa que promoveu a comunhão frequente e combatendo o modernismo.$$, $$Papa que promoveu a comunhão frequente e combatendo o modernismo.$$, $$[]$$::jsonb, '{}'::text[], $$pope$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Cathedra_Petri_adjusted.JPG/440px-Cathedra_Petri_adjusted.JPG$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$maria-rainha$$, $$Maria Rainha$$, $$Rainha do Céu e da Terra$$, $$22 de Agosto$$, 8, 22, NULL, NULL, '{}'::text[], $$Festa que celebra a realeza de Maria, Mãe do Rei dos Reis.$$, $$Festa que celebra a realeza de Maria, Mãe do Rei dos Reis.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-rosa-lima$$, $$Santa Rosa de Lima$$, $$Primeira Santa da América$$, $$23 de Agosto$$, 8, 23, NULL, NULL, '{}'::text[], $$Mística peruana, primeira santa canonizada das Américas.$$, $$Mística peruana, primeira santa canonizada das Américas.$$, $$[]$$::jsonb, '{}'::text[], $$mystic$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Giovanni_Battista_Tiepolo_-_Saint_Catherine_of_Siena.jpg/440px-Giovanni_Battista_Tiepolo_-_Saint_Catherine_of_Siena.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-luis-rei$$, $$São Luís IX$$, $$Rei de França$$, $$25 de Agosto$$, 8, 25, NULL, NULL, '{}'::text[], $$Rei francês que viveu com grande piedade e liderou duas Cruzadas.$$, $$Rei francês que viveu com grande piedade e liderou duas Cruzadas.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$nsa-czestochowa$$, $$Nossa Senhora de Częstochowa$$, $$Rainha da Polônia$$, $$26 de Agosto$$, 8, 26, NULL, NULL, '{}'::text[], $$Venerada imagem na Polônia, símbolo da identidade católica polonesa.$$, $$Venerada imagem na Polônia, símbolo da identidade católica polonesa.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-monica$$, $$Santa Mônica$$, $$Mãe de Santo Agostinho$$, $$27 de Agosto$$, 8, 27, NULL, NULL, '{}'::text[], $$Mãe que rezou durante 30 anos pela conversão do filho Agostinho.$$, $$Mãe que rezou durante 30 anos pela conversão do filho Agostinho.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;
