INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-graciano$$, $$São Graciano de Tours$$, $$Primeiro Bispo$$, $$18 de Dezembro$$, 12, 18, NULL, NULL, '{}'::text[], $$Primeiro bispo de Tours, que evangelizou a Gália.$$, $$Primeiro bispo de Tours, que evangelizou a Gália.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$bem-urbano-v$$, $$Beato Urbano V$$, $$Papa em Avignon$$, $$19 de Dezembro$$, 12, 19, NULL, NULL, '{}'::text[], $$Papa que tentou restaurar a Santa Sé de Avignon para Roma.$$, $$Papa que tentou restaurar a Santa Sé de Avignon para Roma.$$, $$[]$$::jsonb, '{}'::text[], $$pope$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Cathedra_Petri_adjusted.JPG/440px-Cathedra_Petri_adjusted.JPG$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-domingos-silos$$, $$São Domingos de Silos$$, $$Abade$$, $$20 de Dezembro$$, 12, 20, NULL, NULL, '{}'::text[], $$Abade beneditino que reconstruiu o mosteiro de Silos na Espanha.$$, $$Abade beneditino que reconstruiu o mosteiro de Silos na Espanha.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-pedro-canisio$$, $$São Pedro Canísio$$, $$Doutor da Igreja$$, $$21 de Dezembro$$, 12, 21, NULL, NULL, '{}'::text[], $$Jesuíta que combateu a Reforma Protestante na Alemanha com catecismos e pregação.$$, $$Jesuíta que combateu a Reforma Protestante na Alemanha com catecismos e pregação.$$, $$[]$$::jsonb, '{}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-francisca-cabrini-dez$$, $$Santa Francisca Xavier Cabrini$$, $$Padroeira dos Emigrantes$$, $$22 de Dezembro$$, 12, 22, NULL, NULL, '{}'::text[], $$Primeira cidadã americana a ser canonizada.$$, $$Primeira cidadã americana a ser canonizada.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-joao-kety$$, $$São João de Kęty$$, $$Professor e Santo$$, $$23 de Dezembro$$, 12, 23, NULL, NULL, '{}'::text[], $$Professor da Universidade de Cracóvia famoso por sua caridade aos estudantes pobres.$$, $$Professor da Universidade de Cracóvia famoso por sua caridade aos estudantes pobres.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-irmina$$, $$Santa Irmina de Oeren$$, $$Abadessa$$, $$24 de Dezembro$$, 12, 24, NULL, NULL, '{}'::text[], $$Princesa franca que se tornou abadessa e fundou o mosteiro de Oeren.$$, $$Princesa franca que se tornou abadessa e fundou o mosteiro de Oeren.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$natal-senhor$$, $$Natal de Nosso Senhor Jesus Cristo$$, $$O Verbo se fez carne$$, $$25 de Dezembro$$, 12, 25, $$0, Belém$$, $$33, Jerusalém$$, '{"Humanidade"}'::text[], $$A maior festa cristã depois da Páscoa, celebrando o nascimento do Salvador.$$, $$A maior festa cristã depois da Páscoa, celebrando o nascimento do Salvador.$$, $$[]$$::jsonb, '{"\"Glória a Deus nas alturas e paz na terra aos homens de boa vontade.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Fra_Angelico_019.jpg/440px-Fra_Angelico_019.jpg$$, NULL, '{"Humildade","Amor"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$estevao-martir$$, $$Santo Estêvão$$, $$Primeiro Mártir$$, $$26 de Dezembro$$, 12, 26, $$Séc. I, Jerusalém$$, $$34, Jerusalém$$, '{"Diáconos","Pedreiros"}'::text[], $$Um dos sete primeiros diáconos da Igreja, martirizado por apedrejamento.$$, $$Um dos sete primeiros diáconos da Igreja, martirizado por apedrejamento.$$, $$[]$$::jsonb, '{"\"Senhor Jesus, recebe o meu espírito.\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Fra_Angelico_013.jpg/440px-Fra_Angelico_013.jpg$$, NULL, '{"Coragem","Perdão"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$joao-apostolo$$, $$São João Evangelista$$, $$O Discípulo Amado$$, $$27 de Dezembro$$, 12, 27, $$Séc. I, Galileia$$, $$100, Éfeso$$, '{"Teólogos","Escritores"}'::text[], $$Autor do quarto Evangelho, das Epístolas e do Apocalipse. O único apóstolo que não foi martirizado.$$, $$Autor do quarto Evangelho, das Epístolas e do Apocalipse. O único apóstolo que não foi martirizado.$$, $$[]$$::jsonb, '{"\"Deus é amor.\""}'::text[], $$apostle$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Hans_Memling_-_Saint_John_the_Evangelist_-_WGA14819.jpg/440px-Hans_Memling_-_Saint_John_the_Evangelist_-_WGA14819.jpg$$, NULL, '{"Amor","Fidelidade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$santos-inocentes$$, $$Santos Inocentes$$, $$Mártires de Belém$$, $$28 de Dezembro$$, 12, 28, $$Séc. I, Belém$$, $$Séc. I, Belém$$, '{"Crianças"}'::text[], $$Crianças de Belém mortas por Herodes que buscava matar o Menino Jesus.$$, $$Crianças de Belém mortas por Herodes que buscava matar o Menino Jesus.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Giotto_-_Scrovegni_-_-19-_Massacre_of_the_Innocents.jpg/440px-Giotto_-_Scrovegni_-_-19-_Massacre_of_the_Innocents.jpg$$, NULL, '{"Inocência"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-tomas-becket$$, $$São Tomás Becket$$, $$Mártir de Canterbury$$, $$29 de Dezembro$$, 12, 29, NULL, NULL, '{}'::text[], $$Arcebispo de Canterbury assassinado na catedral por ordem do rei Henrique II.$$, $$Arcebispo de Canterbury assassinado na catedral por ordem do rei Henrique II.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sagrada-familia$$, $$Sagrada Família de Jesus, Maria e José$$, $$Modelo de Família$$, $$30 de Dezembro$$, 12, 30, NULL, NULL, '{"Famílias"}'::text[], $$Festa que celebra a união santa entre Jesus, Maria e José em Nazaré.$$, $$Festa que celebra a união santa entre Jesus, Maria e José em Nazaré.$$, $$[]$$::jsonb, '{"\"A família que reza unida, permanece unida.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Murillo_Sagrada_Familia_del_Pajarito.jpg/440px-Murillo_Sagrada_Familia_del_Pajarito.jpg$$, NULL, '{"União","Fé"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-silvestre-papa$$, $$São Silvestre I$$, $$Papa$$, $$31 de Dezembro$$, 12, 31, NULL, NULL, '{}'::text[], $$Papa durante o reinado de Constantino, quando o cristianismo se tornou religião oficial.$$, $$Papa durante o reinado de Constantino, quando o cristianismo se tornou religião oficial.$$, $$[]$$::jsonb, '{}'::text[], $$pope$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Cathedra_Petri_adjusted.JPG/440px-Cathedra_Petri_adjusted.JPG$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;
