INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-joao-capistrano$$, $$São João de Capistrano$$, $$Pregador das Cruzadas$$, $$23 de Outubro$$, 10, 23, NULL, NULL, '{}'::text[], $$Frade franciscano que pregou a cruzada contra os turcos otomanos.$$, $$Frade franciscano que pregou a cruzada contra os turcos otomanos.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santo-antonio-claret$$, $$Santo Antônio Maria Claret$$, $$Fundador dos Claretianos$$, $$24 de Outubro$$, 10, 24, NULL, NULL, '{}'::text[], $$Arcebispo missionário que fundou os Missionários Filhos do Coração de Maria.$$, $$Arcebispo missionário que fundou os Missionários Filhos do Coração de Maria.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-crispim$$, $$Santos Crispim e Crispiniano$$, $$Padroeiros dos Sapateiros$$, $$25 de Outubro$$, 10, 25, NULL, NULL, '{}'::text[], $$Irmãos sapateiros que evangelizavam enquanto trabalhavam e foram martirizados.$$, $$Irmãos sapateiros que evangelizavam enquanto trabalhavam e foram martirizados.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-cedda$$, $$São Cedda de Lichfield$$, $$Bispo Missionário$$, $$26 de Outubro$$, 10, 26, NULL, NULL, '{}'::text[], $$Monge anglo-saxão que evangelizou a Mércia.$$, $$Monge anglo-saxão que evangelizou a Mércia.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-frumencio$$, $$São Frumêncio$$, $$Apóstolo da Etiópia$$, $$27 de Outubro$$, 10, 27, NULL, NULL, '{}'::text[], $$Jovem sírio que evangelizou a Etiópia e se tornou seu primeiro bispo.$$, $$Jovem sírio que evangelizou a Etiópia e se tornou seu primeiro bispo.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-narciso$$, $$São Narciso de Jerusalém$$, $$Bispo Centenário$$, $$29 de Outubro$$, 10, 29, NULL, NULL, '{}'::text[], $$Bispo de Jerusalém que viveu até os 116 anos.$$, $$Bispo de Jerusalém que viveu até os 116 anos.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-afonso-rodriguez$$, $$Santo Afonso Rodrigues$$, $$Porteiro Santo$$, $$30 de Outubro$$, 10, 30, NULL, NULL, '{}'::text[], $$Jesuíta espanhol que serviu como porteiro durante 46 anos com heroica humildade.$$, $$Jesuíta espanhol que serviu como porteiro durante 46 anos com heroica humildade.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-volfango$$, $$São Volfango de Ratisbona$$, $$Bispo Reformador$$, $$31 de Outubro$$, 10, 31, NULL, NULL, '{}'::text[], $$Bispo que reformou mosteiros e escolas na Baviera.$$, $$Bispo que reformou mosteiros e escolas na Baviera.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-martinho-porres$$, $$São Martinho de Porres$$, $$O Santo da Vassoura$$, $$3 de Novembro$$, 11, 3, NULL, NULL, '{}'::text[], $$Irmão leigo dominicano peruano, mestiço, dedicado aos pobres e doentes.$$, $$Irmão leigo dominicano peruano, mestiço, dedicado aos pobres e doentes.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-zacarias-nov$$, $$Santos Zacarias e Isabel$$, $$Pais do Precursor$$, $$5 de Novembro$$, 11, 5, NULL, NULL, '{}'::text[], $$Festa dos pais de São João Batista.$$, $$Festa dos pais de São João Batista.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-leonardo$$, $$São Leonardo de Noblac$$, $$Padroeiro dos Prisioneiros$$, $$6 de Novembro$$, 11, 6, NULL, NULL, '{}'::text[], $$Eremita francês que conseguiu do rei a libertação de muitos prisioneiros.$$, $$Eremita francês que conseguiu do rei a libertação de muitos prisioneiros.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-ernesto$$, $$São Ernesto de Zwiefalten$$, $$Abade$$, $$7 de Novembro$$, 11, 7, NULL, NULL, '{}'::text[], $$Abade beneditino que reformou a vida monástica em seu mosteiro.$$, $$Abade beneditino que reformou a vida monástica em seu mosteiro.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-godofredo$$, $$São Godofredo de Amiens$$, $$Bispo Reformador$$, $$8 de Novembro$$, 11, 8, NULL, NULL, '{}'::text[], $$Bispo que lutou contra a simonia e reformou seu clero.$$, $$Bispo que lutou contra a simonia e reformou seu clero.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$dedicacao-latrao$$, $$Dedicação da Basílica de Latrão$$, $$Mãe de Todas as Igrejas$$, $$9 de Novembro$$, 11, 9, NULL, NULL, '{}'::text[], $$Festa da catedral do Papa, a mais antiga basílica do Ocidente.$$, $$Festa da catedral do Papa, a mais antiga basílica do Ocidente.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-leao-magno$$, $$São Leão Magno$$, $$Papa e Doutor$$, $$10 de Novembro$$, 11, 10, NULL, NULL, '{}'::text[], $$Papa que salvou Roma de Átila e definiu a doutrina cristológica.$$, $$Papa que salvou Roma de Átila e definiu a doutrina cristológica.$$, $$[]$$::jsonb, '{}'::text[], $$pope$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Cathedra_Petri_adjusted.JPG/440px-Cathedra_Petri_adjusted.JPG$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-josafa$$, $$São Josafá$$, $$Bispo e Mártir$$, $$12 de Novembro$$, 11, 12, NULL, NULL, '{}'::text[], $$Arcebispo ucraniano que trabalhou pela unidade da Igreja.$$, $$Arcebispo ucraniano que trabalhou pela unidade da Igreja.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-francisca-cabrini$$, $$Santa Francisca Xavier Cabrini$$, $$Padroeira dos Imigrantes$$, $$13 de Novembro$$, 11, 13, NULL, NULL, '{}'::text[], $$Religiosa italiana que emigrou para os EUA e fundou hospitais, orfanatos e escolas.$$, $$Religiosa italiana que emigrou para os EUA e fundou hospitais, orfanatos e escolas.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-nicolau-tavelic$$, $$São Nicolau Tavelić$$, $$Mártir da Terra Santa$$, $$14 de Novembro$$, 11, 14, NULL, NULL, '{}'::text[], $$Frade franciscano croata martirizado em Jerusalém por pregar aos muçulmanos.$$, $$Frade franciscano croata martirizado em Jerusalém por pregar aos muçulmanos.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santo-alberto-magno$$, $$Santo Alberto Magno$$, $$Doutor Universal$$, $$15 de Novembro$$, 11, 15, NULL, NULL, '{}'::text[], $$Dominicano, mestre de São Tomás de Aquino, enciclopedista e cientista.$$, $$Dominicano, mestre de São Tomás de Aquino, enciclopedista e cientista.$$, $$[]$$::jsonb, '{}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-margarida-escocia$$, $$Santa Margarida da Escócia$$, $$Rainha e Santa$$, $$16 de Novembro$$, 11, 16, NULL, NULL, '{}'::text[], $$Rainha da Escócia que promoveu a reforma da Igreja e a caridade aos pobres.$$, $$Rainha da Escócia que promoveu a reforma da Igreja e a caridade aos pobres.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$dedicacao-basilicas$$, $$Dedicação das Basílicas de São Pedro e São Paulo$$, $$Pilares da Igreja$$, $$18 de Novembro$$, 11, 18, NULL, NULL, '{}'::text[], $$Festa que celebra as duas maiores basílicas de Roma.$$, $$Festa que celebra as duas maiores basílicas de Roma.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-roque-gonzalez$$, $$São Roque González de Santa Cruz$$, $$Mártir do Paraguai$$, $$19 de Novembro$$, 11, 19, NULL, NULL, '{}'::text[], $$Jesuíta que fundou reduções guaranis e foi martirizado pelos indígenas.$$, $$Jesuíta que fundou reduções guaranis e foi martirizado pelos indígenas.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-edmundo$$, $$Santo Edmundo$$, $$Rei e Mártir$$, $$20 de Novembro$$, 11, 20, NULL, NULL, '{}'::text[], $$Rei inglês morto pelos vikings por se recusar a renegar a fé cristã.$$, $$Rei inglês morto pelos vikings por se recusar a renegar a fé cristã.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-clemente-roma$$, $$São Clemente de Roma$$, $$Papa e Mártir$$, $$23 de Novembro$$, 11, 23, NULL, NULL, '{}'::text[], $$Quarto Papa, autor da mais antiga carta cristã fora do Novo Testamento.$$, $$Quarto Papa, autor da mais antiga carta cristã fora do Novo Testamento.$$, $$[]$$::jsonb, '{}'::text[], $$pope$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Cathedra_Petri_adjusted.JPG/440px-Cathedra_Petri_adjusted.JPG$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santos-andre-dung-lac$$, $$Santos André Dung-Lac e Companheiros$$, $$Mártires do Vietnã$$, $$24 de Novembro$$, 11, 24, NULL, NULL, '{}'::text[], $$117 mártires vietnamitas que deram a vida pela fé.$$, $$117 mártires vietnamitas que deram a vida pela fé.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$santa-catarina-alexandria$$, $$Santa Catarina de Alexandria$$, $$Virgem e Mártir$$, $$25 de Novembro$$, 11, 25, NULL, NULL, '{}'::text[], $$Jovem sábia que converteu filósofos pagãos e foi martirizada na roda.$$, $$Jovem sábia que converteu filósofos pagãos e foi martirizada na roda.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-silvestre-guzzolini$$, $$São Silvestre Guzzolini$$, $$Fundador dos Silvestrinos$$, $$26 de Novembro$$, 11, 26, NULL, NULL, '{}'::text[], $$Monge beneditino que reformou a vida monástica.$$, $$Monge beneditino que reformou a vida monástica.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$nsa-medalha$$, $$Nossa Senhora da Medalha Milagrosa$$, $$Medalhinha$$, $$27 de Novembro$$, 11, 27, NULL, NULL, '{}'::text[], $$Em 1830, a Virgem Maria apareceu a Santa Catarina Labouré pedindo a cunhagem da Medalha Milagrosa.$$, $$Em 1830, a Virgem Maria apareceu a Santa Catarina Labouré pedindo a cunhagem da Medalha Milagrosa.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-catarina-laboure$$, $$Santa Catarina Labouré$$, $$Vidente da Medalha$$, $$28 de Novembro$$, 11, 28, NULL, NULL, '{}'::text[], $$Religiosa vicentina que recebeu as aparições de Nossa Senhora da Medalha Milagrosa.$$, $$Religiosa vicentina que recebeu as aparições de Nossa Senhora da Medalha Milagrosa.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-saturnino$$, $$São Saturnino de Toulouse$$, $$Primeiro Bispo e Mártir$$, $$29 de Novembro$$, 11, 29, NULL, NULL, '{}'::text[], $$Primeiro bispo de Toulouse, arrastado por um touro selvagem até a morte.$$, $$Primeiro bispo de Toulouse, arrastado por um touro selvagem até a morte.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$santo-eloi$$, $$Santo Elói$$, $$Padroeiro dos Ourives$$, $$1 de Dezembro$$, 12, 1, NULL, NULL, '{}'::text[], $$Ourives e bispo de Noyon, famoso por sua arte sacra e caridade.$$, $$Ourives e bispo de Noyon, famoso por sua arte sacra e caridade.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-bibiana$$, $$Santa Bibiana$$, $$Virgem e Mártir$$, $$2 de Dezembro$$, 12, 2, NULL, NULL, '{}'::text[], $$Jovem romana martirizada por se recusar a sacrificar aos ídolos.$$, $$Jovem romana martirizada por se recusar a sacrificar aos ídolos.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-sabas$$, $$São Sabas$$, $$Abade do Deserto$$, $$5 de Dezembro$$, 12, 5, NULL, NULL, '{}'::text[], $$Monge que fundou a Grande Laura no deserto da Judeia, ainda habitada.$$, $$Monge que fundou a Grande Laura no deserto da Judeia, ainda habitada.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-joao-diego$$, $$São João Diego$$, $$Vidente de Guadalupe$$, $$9 de Dezembro$$, 12, 9, NULL, NULL, '{}'::text[], $$Indígena mexicano que recebeu as aparições de Nossa Senhora de Guadalupe.$$, $$Indígena mexicano que recebeu as aparições de Nossa Senhora de Guadalupe.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$nsa-loreto$$, $$Nossa Senhora de Loreto$$, $$Padroeira dos Aviadores$$, $$10 de Dezembro$$, 12, 10, NULL, NULL, '{}'::text[], $$Devoção ligada à Santa Casa de Nazaré, transportada a Loreto.$$, $$Devoção ligada à Santa Casa de Nazaré, transportada a Loreto.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-damaso$$, $$São Dâmaso I$$, $$Papa e Doutor$$, $$11 de Dezembro$$, 12, 11, NULL, NULL, '{}'::text[], $$Papa que encomendou a São Jerônimo a tradução da Bíblia para o latim.$$, $$Papa que encomendou a São Jerônimo a tradução da Bíblia para o latim.$$, $$[]$$::jsonb, '{}'::text[], $$pope$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Cathedra_Petri_adjusted.JPG/440px-Cathedra_Petri_adjusted.JPG$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-luzia$$, $$Santa Luzia$$, $$Padroeira dos Olhos$$, $$13 de Dezembro$$, 12, 13, NULL, NULL, '{}'::text[], $$Virgem e mártir de Siracusa, invocada contra doenças dos olhos.$$, $$Virgem e mártir de Siracusa, invocada contra doenças dos olhos.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-virginia$$, $$Santa Virgínia Centurione$$, $$Viúva Santa$$, $$15 de Dezembro$$, 12, 15, NULL, NULL, '{}'::text[], $$Nobre genovesa que, viúva, fundou as Irmãs de Nossa Senhora do Refúgio.$$, $$Nobre genovesa que, viúva, fundou as Irmãs de Nossa Senhora do Refúgio.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-adelaide$$, $$Santa Adelaide$$, $$Imperatriz$$, $$16 de Dezembro$$, 12, 16, NULL, NULL, '{}'::text[], $$Imperatriz do Sacro Império que dedicou sua viuvez à caridade e fundação de mosteiros.$$, $$Imperatriz do Sacro Império que dedicou sua viuvez à caridade e fundação de mosteiros.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-joao-matha$$, $$São João da Mata$$, $$Fundador dos Trinitários$$, $$17 de Dezembro$$, 12, 17, NULL, NULL, '{}'::text[], $$Sacerdote francês que fundou a Ordem dos Trinitários para resgatar escravos cristãos.$$, $$Sacerdote francês que fundou a Ordem dos Trinitários para resgatar escravos cristãos.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;
