INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$degolacao-joao-batista$$, $$Degolação de São João Batista$$, $$O Precursor Mártir$$, $$29 de Agosto$$, 8, 29, NULL, NULL, '{}'::text[], $$Memória do martírio de João Batista, decapitado por Herodes.$$, $$Memória do martírio de João Batista, decapitado por Herodes.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-margarida-ward$$, $$Santa Margarida Ward$$, $$Mártir Inglesa$$, $$30 de Agosto$$, 8, 30, NULL, NULL, '{}'::text[], $$Leiga inglesa martirizada por ajudar um sacerdote a escapar da prisão.$$, $$Leiga inglesa martirizada por ajudar um sacerdote a escapar da prisão.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-raimundo-nonato$$, $$São Raimundo Nonato$$, $$Padroeiro das Gestantes$$, $$31 de Agosto$$, 8, 31, NULL, NULL, '{}'::text[], $$Mercedário que se ofereceu como refém para libertar escravos cristãos.$$, $$Mercedário que se ofereceu como refém para libertar escravos cristãos.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-genoveva-torres$$, $$Santa Genoveva Torres Morales$$, $$Anjo dos Desamparados$$, $$1 de Setembro$$, 9, 1, NULL, NULL, '{}'::text[], $$Religiosa espanhola que fundou a Congregação das Irmãs do Sagrado Coração.$$, $$Religiosa espanhola que fundou a Congregação das Irmãs do Sagrado Coração.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$bem-ingrid$$, $$Beata Ingrid da Suécia$$, $$Princesa Dominicana$$, $$2 de Setembro$$, 9, 2, NULL, NULL, '{}'::text[], $$Princesa sueca que se tornou religiosa dominicana.$$, $$Princesa sueca que se tornou religiosa dominicana.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-gregorio-magno$$, $$São Gregório Magno$$, $$Papa e Doutor$$, $$3 de Setembro$$, 9, 3, NULL, NULL, '{}'::text[], $$Papa que enviou missionários à Inglaterra e reformou a liturgia e o canto gregoriano.$$, $$Papa que enviou missionários à Inglaterra e reformou a liturgia e o canto gregoriano.$$, $$[]$$::jsonb, '{}'::text[], $$pope$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Cathedra_Petri_adjusted.JPG/440px-Cathedra_Petri_adjusted.JPG$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-rosa-viterbo-set$$, $$Santa Rosa de Viterbo$$, $$Pregadora Jovem$$, $$4 de Setembro$$, 9, 4, NULL, NULL, '{}'::text[], $$Jovem terciária franciscana que pregou contra a heresia aos 12 anos.$$, $$Jovem terciária franciscana que pregou contra a heresia aos 12 anos.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-zacarias-isabel$$, $$Santos Zacarias e Isabel$$, $$Pais de João Batista$$, $$6 de Setembro$$, 9, 6, NULL, NULL, '{}'::text[], $$O sacerdote idoso e sua esposa que geraram o Precursor por um milagre de Deus.$$, $$O sacerdote idoso e sua esposa que geraram o Precursor por um milagre de Deus.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-regina$$, $$Santa Regina de Alésia$$, $$Virgem e Mártir$$, $$7 de Setembro$$, 9, 7, NULL, NULL, '{}'::text[], $$Jovem borgonhesa martirizada por recusar casar-se com um pagão.$$, $$Jovem borgonhesa martirizada por recusar casar-se com um pagão.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-pedro-claver$$, $$São Pedro Claver$$, $$Escravo dos Escravos$$, $$9 de Setembro$$, 9, 9, NULL, NULL, '{}'::text[], $$Jesuíta espanhol que se dedicou aos escravos africanos em Cartagena das Índias.$$, $$Jesuíta espanhol que se dedicou aos escravos africanos em Cartagena das Índias.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-nicolau-tolentino$$, $$São Nicolau de Tolentino$$, $$Padroeiro das Almas$$, $$10 de Setembro$$, 9, 10, NULL, NULL, '{}'::text[], $$Agostiniano italiano que tinha visões do Purgatório e rezava constantemente pelos defuntos.$$, $$Agostiniano italiano que tinha visões do Purgatório e rezava constantemente pelos defuntos.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-proto-jacinto$$, $$Santos Proto e Jacinto$$, $$Mártires de Roma$$, $$11 de Setembro$$, 9, 11, NULL, NULL, '{}'::text[], $$Irmãos romanos que foram mestres de Santa Eugênia e martirizados pela fé.$$, $$Irmãos romanos que foram mestres de Santa Eugênia e martirizados pela fé.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-joao-crisostomo$$, $$São João Crisóstomo$$, $$Boca de Ouro$$, $$13 de Setembro$$, 9, 13, NULL, NULL, '{}'::text[], $$Patriarca de Constantinopla, o maior pregador da Igreja oriental.$$, $$Patriarca de Constantinopla, o maior pregador da Igreja oriental.$$, $$[]$$::jsonb, '{}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santos-cornelio-cipriano$$, $$Santos Cornélio e Cipriano$$, $$Papa e Bispo Mártires$$, $$16 de Setembro$$, 9, 16, NULL, NULL, '{}'::text[], $$Papa Cornélio e o bispo Cipriano de Cartago, defensores da unidade da Igreja.$$, $$Papa Cornélio e o bispo Cipriano de Cartago, defensores da unidade da Igreja.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-hildegarda$$, $$Santa Hildegarda de Bingen$$, $$Doutora da Igreja$$, $$17 de Setembro$$, 9, 17, NULL, NULL, '{}'::text[], $$Abadessa beneditina, mística, compositora, cientista e Doutora da Igreja.$$, $$Abadessa beneditina, mística, compositora, cientista e Doutora da Igreja.$$, $$[]$$::jsonb, '{}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-jose-cupertino$$, $$São José de Cupertino$$, $$O Santo Voador$$, $$18 de Setembro$$, 9, 18, NULL, NULL, '{}'::text[], $$Frade franciscano famoso por seus êxtases e levitações durante a oração.$$, $$Frade franciscano famoso por seus êxtases e levitações durante a oração.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-januario$$, $$São Januário$$, $$Bispo e Mártir$$, $$19 de Setembro$$, 9, 19, NULL, NULL, '{}'::text[], $$Bispo de Benevento cujo sangue se liquefaz milagrosamente em Nápoles.$$, $$Bispo de Benevento cujo sangue se liquefaz milagrosamente em Nápoles.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santos-andre-kim$$, $$Santos André Kim e Companheiros$$, $$Mártires da Coreia$$, $$20 de Setembro$$, 9, 20, NULL, NULL, '{}'::text[], $$103 mártires coreanos que deram a vida pela fé.$$, $$103 mártires coreanos que deram a vida pela fé.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-mauricio$$, $$São Maurício e Companheiros$$, $$Legião Tebana$$, $$22 de Setembro$$, 9, 22, NULL, NULL, '{}'::text[], $$Soldados cristãos egípcios massacrados por recusarem sacrificar aos deuses.$$, $$Soldados cristãos egípcios massacrados por recusarem sacrificar aos deuses.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$nsa-merces$$, $$Nossa Senhora das Mercês$$, $$Redentora dos Cativos$$, $$24 de Setembro$$, 9, 24, NULL, NULL, '{}'::text[], $$Devoção mariana ligada à libertação dos escravos cristãos.$$, $$Devoção mariana ligada à libertação dos escravos cristãos.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-sergio-baco$$, $$Santos Sérgio e Baco$$, $$Mártires da Síria$$, $$25 de Setembro$$, 9, 25, NULL, NULL, '{}'::text[], $$Oficiais romanos martirizados por se recusarem a sacrificar em um templo pagão.$$, $$Oficiais romanos martirizados por se recusarem a sacrificar em um templo pagão.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santos-cosme-damiao$$, $$Santos Cosme e Damião$$, $$Padroeiros dos Médicos$$, $$26 de Setembro$$, 9, 26, NULL, NULL, '{}'::text[], $$Irmãos gêmeos médicos que curavam gratuitamente e foram martirizados.$$, $$Irmãos gêmeos médicos que curavam gratuitamente e foram martirizados.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-vicente-paulo$$, $$São Vicente de Paulo$$, $$Pai dos Pobres$$, $$27 de Setembro$$, 9, 27, NULL, NULL, '{}'::text[], $$Sacerdote francês que fundou as Filhas da Caridade e os Lazaristas.$$, $$Sacerdote francês que fundou as Filhas da Caridade e os Lazaristas.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-venceslau$$, $$São Venceslau$$, $$Duque da Boêmia$$, $$28 de Setembro$$, 9, 28, NULL, NULL, '{}'::text[], $$Duque da Boêmia assassinado pelo próprio irmão por sua fé cristã.$$, $$Duque da Boêmia assassinado pelo próprio irmão por sua fé cristã.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-jeronimo$$, $$São Jerônimo$$, $$Doutor da Igreja$$, $$30 de Setembro$$, 9, 30, NULL, NULL, '{}'::text[], $$Tradutor da Bíblia para o latim (Vulgata), grande erudito e penitente.$$, $$Tradutor da Bíblia para o latim (Vulgata), grande erudito e penitente.$$, $$[]$$::jsonb, '{}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-francisco-borja$$, $$São Francisco de Borja$$, $$De Duque a Jesuíta$$, $$3 de Outubro$$, 10, 3, NULL, NULL, '{}'::text[], $$Duque de Gandía que se tornou terceiro geral dos Jesuítas.$$, $$Duque de Gandía que se tornou terceiro geral dos Jesuítas.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-bruno$$, $$São Bruno$$, $$Fundador dos Cartuxos$$, $$6 de Outubro$$, 10, 6, NULL, NULL, '{}'::text[], $$Fundou a Ordem dos Cartuxos na Grande Chartreuse.$$, $$Fundou a Ordem dos Cartuxos na Grande Chartreuse.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-pelagia$$, $$Santa Pelágia$$, $$Penitente de Antioquia$$, $$8 de Outubro$$, 10, 8, NULL, NULL, '{}'::text[], $$Atriz que se converteu após ouvir uma homilia e viveu como eremita penitente.$$, $$Atriz que se converteu após ouvir uma homilia e viveu como eremita penitente.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-dionisio$$, $$São Dionísio de Paris$$, $$Bispo e Mártir$$, $$9 de Outubro$$, 10, 9, NULL, NULL, '{}'::text[], $$Primeiro bispo de Paris, decapitado no Monte dos Mártires (Montmartre).$$, $$Primeiro bispo de Paris, decapitado no Monte dos Mártires (Montmartre).$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-daniel-comboni$$, $$São Daniel Comboni$$, $$Apóstolo da África$$, $$10 de Outubro$$, 10, 10, NULL, NULL, '{}'::text[], $$Bispo missionário italiano que dedicou sua vida à evangelização da África Central.$$, $$Bispo missionário italiano que dedicou sua vida à evangelização da África Central.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-joao-xxiii$$, $$São João XXIII$$, $$O Papa Bom$$, $$11 de Outubro$$, 10, 11, NULL, NULL, '{}'::text[], $$Papa que convocou o Concílio Vaticano II.$$, $$Papa que convocou o Concílio Vaticano II.$$, $$[]$$::jsonb, '{}'::text[], $$pope$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Cathedra_Petri_adjusted.JPG/440px-Cathedra_Petri_adjusted.JPG$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$nsa-aparecida$$, $$Nossa Senhora Aparecida$$, $$Padroeira do Brasil$$, $$12 de Outubro$$, 10, 12, NULL, NULL, '{}'::text[], $$Imagem encontrada por pescadores no rio Paraíba, padroeira do Brasil desde 1930.$$, $$Imagem encontrada por pescadores no rio Paraíba, padroeira do Brasil desde 1930.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-eduardo$$, $$Santo Eduardo Confessor$$, $$Rei da Inglaterra$$, $$13 de Outubro$$, 10, 13, NULL, NULL, '{}'::text[], $$Último rei anglo-saxão, famoso por sua piedade e reconstrução de Westminster.$$, $$Último rei anglo-saxão, famoso por sua piedade e reconstrução de Westminster.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-calisto$$, $$São Calisto I$$, $$Papa e Mártir$$, $$14 de Outubro$$, 10, 14, NULL, NULL, '{}'::text[], $$Papa que expandiu as catacumbas de Roma e acolheu os pecadores arrependidos.$$, $$Papa que expandiu as catacumbas de Roma e acolheu os pecadores arrependidos.$$, $$[]$$::jsonb, '{}'::text[], $$pope$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Cathedra_Petri_adjusted.JPG/440px-Cathedra_Petri_adjusted.JPG$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-teresa-avila$$, $$Santa Teresa de Ávila$$, $$Doutora Mística$$, $$15 de Outubro$$, 10, 15, NULL, NULL, '{}'::text[], $$Reformadora do Carmelo, mística e Doutora da Igreja.$$, $$Reformadora do Carmelo, mística e Doutora da Igreja.$$, $$[]$$::jsonb, '{}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$santa-margarida-alacoque$$, $$Santa Margarida Maria Alacoque$$, $$Apóstola do Sagrado Coração$$, $$16 de Outubro$$, 10, 16, NULL, NULL, '{}'::text[], $$Religiosa visitandina que recebeu revelações do Sagrado Coração de Jesus.$$, $$Religiosa visitandina que recebeu revelações do Sagrado Coração de Jesus.$$, $$[]$$::jsonb, '{}'::text[], $$mystic$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Giovanni_Battista_Tiepolo_-_Saint_Catherine_of_Siena.jpg/440px-Giovanni_Battista_Tiepolo_-_Saint_Catherine_of_Siena.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santo-inacio-antioquia$$, $$Santo Inácio de Antioquia$$, $$Bispo e Mártir$$, $$17 de Outubro$$, 10, 17, NULL, NULL, '{}'::text[], $$Terceiro bispo de Antioquia, devorado pelas feras no Coliseu de Roma.$$, $$Terceiro bispo de Antioquia, devorado pelas feras no Coliseu de Roma.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-joao-brebeuf$$, $$Santos João de Brébeuf e Isaac Jogues$$, $$Mártires da América do Norte$$, $$19 de Outubro$$, 10, 19, NULL, NULL, '{}'::text[], $$Jesuítas franceses martirizados pelos iroqueses enquanto evangelizavam o Canadá.$$, $$Jesuítas franceses martirizados pelos iroqueses enquanto evangelizavam o Canadá.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-maria-bertilla$$, $$Santa Maria Bertilla Boscardin$$, $$Enfermeira Santa$$, $$20 de Outubro$$, 10, 20, NULL, NULL, '{}'::text[], $$Religiosa italiana que se dedicou ao cuidado dos doentes com amor heroico.$$, $$Religiosa italiana que se dedicou ao cuidado dos doentes com amor heroico.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-ursola$$, $$Santa Úrsula$$, $$Virgem e Mártir$$, $$21 de Outubro$$, 10, 21, NULL, NULL, '{}'::text[], $$Princesa britânica martirizada com suas companheiras pelos hunos em Colônia.$$, $$Princesa britânica martirizada com suas companheiras pelos hunos em Colônia.$$, $$[]$$::jsonb, '{}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg/440px-Sassoferrato_-_Jungfrun_i_b%C3%B6n_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;
