INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$oswaldo-worcester$$, $$Santo Oswaldo de Worcester$$, $$Bispo de Worcester$$, $$29 de Fevereiro$$, 2, 29, $$Séc. X, Inglaterra$$, $$992, Worcester$$, '{"Worcester"}'::text[], $$Bispo beneditino inglês que reformou os mosteiros e a vida eclesiástica na Inglaterra anglo-saxã, promovendo a cultura e a disciplina monástica.$$, $$Bispo beneditino inglês que reformou os mosteiros e a vida eclesiástica na Inglaterra anglo-saxã, promovendo a cultura e a disciplina monástica.$$, $$[]$$::jsonb, '{"\"A disciplina é a mãe da paz.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{"Reforma","Cultura"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$casimiro$$, $$São Casimiro$$, $$Príncipe da Polônia$$, $$4 de Março$$, 3, 4, $$1458, Cracóvia$$, $$1484, Grodno$$, '{"Polônia","Lituânia"}'::text[], $$Príncipe polonês que viveu em castidade e penitência, recusando a coroa da Hungria por amor à justiça.$$, $$Príncipe polonês que viveu em castidade e penitência, recusando a coroa da Hungria por amor à justiça.$$, $$[]$$::jsonb, '{"\"Prefiro morrer a pecar.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Daniel_Schultz_-_%C5%9Aw._Kazimierz.jpg/440px-Daniel_Schultz_-_%C5%9Aw._Kazimierz.jpg$$, NULL, '{"Castidade","Justiça"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$perpetua-felicidade$$, $$Santas Perpétua e Felicidade$$, $$Mártires de Cartago$$, $$7 de Março$$, 3, 7, $$Séc. II, Cartago$$, $$203, Cartago$$, '{"Mães","Gestantes"}'::text[], $$Perpétua, uma nobre, e Felicidade, sua escrava, foram martirizadas juntas na arena de Cartago por se recusarem a renegar Cristo.$$, $$Perpétua, uma nobre, e Felicidade, sua escrava, foram martirizadas juntas na arena de Cartago por se recusarem a renegar Cristo.$$, $$[]$$::jsonb, '{"\"Somos cristãos; não podemos negar Cristo.\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Sv._Perpetua_in_Felicita.jpg/440px-Sv._Perpetua_in_Felicita.jpg$$, NULL, '{"Coragem","Fidelidade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$joao-deus$$, $$São João de Deus$$, $$Fundador dos Hospitalários$$, $$8 de Março$$, 3, 8, $$1495, Portugal$$, $$1550, Granada$$, '{"Doentes","Hospitais","Enfermeiros"}'::text[], $$Português convertido que fundou a Ordem dos Irmãos Hospitaleiros de São João de Deus, dedicados ao cuidado dos enfermos.$$, $$Português convertido que fundou a Ordem dos Irmãos Hospitaleiros de São João de Deus, dedicados ao cuidado dos enfermos.$$, $$[]$$::jsonb, '{"\"Se olhássemos para o futuro, jamais deixaríamos de fazer o bem.\""}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Murillo_john_of_god.jpg/440px-Murillo_john_of_god.jpg$$, NULL, '{"Caridade","Compaixão"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$patricio$$, $$São Patrício$$, $$Apóstolo da Irlanda$$, $$17 de Março$$, 3, 17, $$385, Britânia$$, $$461, Irlanda$$, '{"Irlanda","Engenheiros"}'::text[], $$Britânico escravizado na Irlanda, retornou como missionário e converteu toda a ilha ao cristianismo.$$, $$Britânico escravizado na Irlanda, retornou como missionário e converteu toda a ilha ao cristianismo.$$, $$[]$$::jsonb, '{"\"Cristo comigo, Cristo diante de mim, Cristo atrás de mim.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Saint_Patrick_Catholic_Church_%28Junction_City%2C_Ohio%29_-_stained_glass%2C_Saint_Patrick_-_detail.jpg/440px-Saint_Patrick_Catholic_Church_%28Junction_City%2C_Ohio%29_-_stained_glass%2C_Saint_Patrick_-_detail.jpg$$, NULL, '{"Perseverança","Evangelização"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$jose$$, $$São José$$, $$Esposo da Virgem Maria$$, $$19 de Março$$, 3, 19, $$Séc. I a.C., Belém$$, $$Séc. I, Nazaré$$, '{"Trabalhadores","Pais","Igreja Universal"}'::text[], $$Esposo de Maria e pai adotivo de Jesus. Homem justo que obedeceu a Deus em silêncio e fidelidade.$$, $$Esposo de Maria e pai adotivo de Jesus. Homem justo que obedeceu a Deus em silêncio e fidelidade.$$, $$[]$$::jsonb, '{"\"José, filho de Davi, não temas receber Maria, tua esposa.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Guido_Reni_-_St_Joseph_with_the_Infant_Jesus_-_WGA19304.jpg/440px-Guido_Reni_-_St_Joseph_with_the_Infant_Jesus_-_WGA19304.jpg$$, NULL, '{"Silêncio","Obediência","Trabalho"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$anunciacao$$, $$Anunciação do Senhor$$, $$O Verbo se fez carne$$, $$25 de Março$$, 3, 25, NULL, NULL, '{"Vida nascente"}'::text[], $$Solenidade que celebra o anúncio do anjo Gabriel a Maria e a encarnação do Filho de Deus.$$, $$Solenidade que celebra o anúncio do anjo Gabriel a Maria e a encarnação do Filho de Deus.$$, $$[]$$::jsonb, '{"\"Eis a serva do Senhor, faça-se em mim segundo a tua palavra.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Leonardo_da_Vinci_-_Annunciation_-_WGA12681.jpg/440px-Leonardo_da_Vinci_-_Annunciation_-_WGA12681.jpg$$, NULL, '{"Obediência","Fé"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$hugo-grenoble$$, $$São Hugo de Grenoble$$, $$Bispo de Grenoble$$, $$1 de Abril$$, 4, 1, $$1053, França$$, $$1132, Grenoble$$, '{"Grenoble"}'::text[], $$Bispo reformador que acolheu São Bruno e os primeiros cartuxos na Grande Chartreuse.$$, $$Bispo reformador que acolheu São Bruno e os primeiros cartuxos na Grande Chartreuse.$$, $$[]$$::jsonb, '{"\"A solidão é a escola da verdadeira caridade.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Francisco_de_Zurbar%C3%A1n_-_San_Hugo_en_el_refectorio_de_los_Cartujos_%28detalle%29.jpg/440px-Francisco_de_Zurbar%C3%A1n_-_San_Hugo_en_el_refectorio_de_los_Cartujos_%28detalle%29.jpg$$, NULL, '{"Reforma","Acolhimento"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$francisco-paula$$, $$São Francisco de Paula$$, $$Fundador dos Mínimos$$, $$2 de Abril$$, 4, 2, $$1416, Paola$$, $$1507, Tours$$, '{"Marinheiros"}'::text[], $$Eremita calabrês que fundou a Ordem dos Mínimos, a mais austera das ordens mendicantes.$$, $$Eremita calabrês que fundou a Ordem dos Mínimos, a mais austera das ordens mendicantes.$$, $$[]$$::jsonb, '{"\"A caridade é a rainha de todas as virtudes.\""}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Fco_de_paula.jpg/440px-Fco_de_paula.jpg$$, NULL, '{"Penitência","Humildade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$isidoro-sevilha$$, $$Santo Isidoro de Sevilha$$, $$Doutor da Igreja$$, $$4 de Abril$$, 4, 4, $$560, Sevilha$$, $$636, Sevilha$$, '{"Internet","Programadores"}'::text[], $$Arcebispo de Sevilha, escreveu as Etimologias, considerada a primeira enciclopédia do Ocidente.$$, $$Arcebispo de Sevilha, escreveu as Etimologias, considerada a primeira enciclopédia do Ocidente.$$, $$[]$$::jsonb, '{"\"O aprendizado é uma jornada, não um destino.\""}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Isidor_von_Sevilla.jpeg/440px-Isidor_von_Sevilla.jpeg$$, NULL, '{"Sabedoria","Erudição"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$joao-batista-salle$$, $$São João Batista de La Salle$$, $$Padroeiro dos Educadores$$, $$7 de Abril$$, 4, 7, $$1651, Reims$$, $$1719, Rouen$$, '{"Professores","Educadores"}'::text[], $$Sacerdote francês que fundou os Irmãos das Escolas Cristãs e revolucionou a educação popular.$$, $$Sacerdote francês que fundou os Irmãos das Escolas Cristãs e revolucionou a educação popular.$$, $$[]$$::jsonb, '{"\"Para educar as crianças, é preciso primeiro amá-las.\""}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/De_La_Salle.jpg/440px-De_La_Salle.jpg$$, NULL, '{"Educação","Caridade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$liduina$$, $$Santa Liduína$$, $$Padroeira dos Patinadores$$, $$14 de Abril$$, 4, 14, $$1380, Schiedam, Holanda$$, $$1433, Schiedam$$, '{"Patinadores","Doentes crônicos"}'::text[], $$Jovem holandesa que sofreu um grave acidente aos 15 anos e passou o resto da vida acamada, oferecendo seus sofrimentos pela conversão das almas.$$, $$Jovem holandesa que sofreu um grave acidente aos 15 anos e passou o resto da vida acamada, oferecendo seus sofrimentos pela conversão das almas.$$, $$[]$$::jsonb, '{"\"O sofrimento aceito por amor pode salvar almas.\""}'::text[], $$mystic$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Lidwina.jpg/440px-Lidwina.jpg$$, NULL, '{"Paciência","Oferecimento"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$bernadette$$, $$Santa Bernadette Soubirous$$, $$Vidente de Lourdes$$, $$16 de Abril$$, 4, 16, $$1844, Lourdes$$, $$1879, Nevers$$, '{"Doentes","Pastores"}'::text[], $$Jovem camponesa que testemunhou 18 aparições de Nossa Senhora na gruta de Massabielle em Lourdes.$$, $$Jovem camponesa que testemunhou 18 aparições de Nossa Senhora na gruta de Massabielle em Lourdes.$$, $$[]$$::jsonb, '{"\"Não me prometeram felicidade neste mundo, mas no outro.\""}'::text[], $$mystic$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Bernadette_Soubirous_1_publicdomain.jpg/440px-Bernadette_Soubirous_1_publicdomain.jpg$$, NULL, '{"Simplicidade","Obediência"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$expedito$$, $$Santo Expedito$$, $$Padroeiro das Causas Urgentes$$, $$19 de Abril$$, 4, 19, $$Séc. III, Armênia$$, $$303, Melitene$$, '{"Causas urgentes","Militares","Estudantes"}'::text[], $$Comandante de uma legião romana martirizado por sua fé. É invocado para problemas que precisam de solução imediata.$$, $$Comandante de uma legião romana martirizado por sua fé. É invocado para problemas que precisam de solução imediata.$$, $$[]$$::jsonb, '{"\"Hodie! — Hoje!\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/St_Expeditus.jpg/440px-St_Expeditus.jpg$$, NULL, '{"Prontidão","Fidelidade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$anselmo$$, $$Santo Anselmo de Cantuária$$, $$Doutor da Igreja$$, $$21 de Abril$$, 4, 21, $$1033, Aosta$$, $$1109, Cantuária$$, '{"Filósofos"}'::text[], $$Arcebispo de Cantuária e pai da Escolástica, autor do argumento ontológico para a existência de Deus.$$, $$Arcebispo de Cantuária e pai da Escolástica, autor do argumento ontológico para a existência de Deus.$$, $$[]$$::jsonb, '{"\"Creio para entender.\""}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Anselm_of_Canterbury.jpg/440px-Anselm_of_Canterbury.jpg$$, NULL, '{"Fé","Razão"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$jorge$$, $$São Jorge$$, $$O Matador de Dragões$$, $$23 de Abril$$, 4, 23, $$Séc. III, Capadócia$$, $$303, Lídia$$, '{"Soldados","Escoteiros","Inglaterra"}'::text[], $$Soldado romano martirizado na perseguição de Diocleciano. A lenda do dragão simboliza sua vitória sobre o mal.$$, $$Soldado romano martirizado na perseguição de Diocleciano. A lenda do dragão simboliza sua vitória sobre o mal.$$, $$[]$$::jsonb, '{"\"A fé é a armadura que vence todos os inimigos.\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Raphael_-_Saint_George_and_the_Dragon_-_Google_Art_Project.jpg/440px-Raphael_-_Saint_George_and_the_Dragon_-_Google_Art_Project.jpg$$, NULL, '{"Coragem","Fé"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$marcos-evangelista$$, $$São Marcos Evangelista$$, $$O Evangelista do Leão$$, $$25 de Abril$$, 4, 25, $$Séc. I, Cirene$$, $$68, Alexandria$$, '{"Veneza","Escribas"}'::text[], $$Autor do segundo Evangelho, discípulo de São Pedro. Fundou a Igreja de Alexandria, no Egito.$$, $$Autor do segundo Evangelho, discípulo de São Pedro. Fundou a Igreja de Alexandria, no Egito.$$, $$[]$$::jsonb, '{"\"O início do Evangelho de Jesus Cristo, Filho de Deus.\""}'::text[], $$apostle$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Andrea_Mantegna_-_St._Mark_the_Evangelist.jpg/440px-Andrea_Mantegna_-_St._Mark_the_Evangelist.jpg$$, NULL, '{"Evangelização"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$catarina-sena$$, $$Santa Catarina de Sena$$, $$Doutora da Igreja$$, $$29 de Abril$$, 4, 29, $$1347, Sena$$, $$1380, Roma$$, '{"Europa","Enfermeiros","Itália"}'::text[], $$Mística e doutora da Igreja, convenceu o Papa a retornar de Avignon a Roma. Autora do Diálogo.$$, $$Mística e doutora da Igreja, convenceu o Papa a retornar de Avignon a Roma. Autora do Diálogo.$$, $$[]$$::jsonb, '{"\"Sê quem Deus quis que fosses e incendiarás o mundo.\""}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Giovanni_Battista_Tiepolo_-_Saint_Catherine_of_Siena.jpg/440px-Giovanni_Battista_Tiepolo_-_Saint_Catherine_of_Siena.jpg$$, NULL, '{"Misticismo","Coragem"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$jose-operario$$, $$São José Operário$$, $$Padroeiro dos Trabalhadores$$, $$1 de Maio$$, 5, 1, NULL, NULL, '{"Trabalhadores"}'::text[], $$Festa instituída por Pio XII em 1955 para celebrar a dignidade do trabalho humano através do exemplo de São José.$$, $$Festa instituída por Pio XII em 1955 para celebrar a dignidade do trabalho humano através do exemplo de São José.$$, $$[]$$::jsonb, '{"\"O trabalho é oração quando feito com amor a Deus.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Guido_Reni_-_St_Joseph_with_the_Infant_Jesus_-_WGA19304.jpg/440px-Guido_Reni_-_St_Joseph_with_the_Infant_Jesus_-_WGA19304.jpg$$, NULL, '{"Trabalho","Silêncio"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$atanasio$$, $$Santo Atanásio$$, $$Defensor da Fé$$, $$2 de Maio$$, 5, 2, $$296, Alexandria$$, $$373, Alexandria$$, '{"Teólogos"}'::text[], $$Bispo de Alexandria que lutou durante toda a vida contra a heresia ariana, sendo exilado cinco vezes.$$, $$Bispo de Alexandria que lutou durante toda a vida contra a heresia ariana, sendo exilado cinco vezes.$$, $$[]$$::jsonb, '{"\"Deus se fez homem para que o homem se tornasse Deus.\""}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Sv_Atanasij_Veliki.jpg/440px-Sv_Atanasij_Veliki.jpg$$, NULL, '{"Perseverança","Ortodoxia"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$filipe-tiago$$, $$Santos Filipe e Tiago$$, $$Apóstolos$$, $$3 de Maio$$, 5, 3, $$Séc. I, Galileia$$, $$Séc. I$$, '{"Chapeleiros"}'::text[], $$Dois dos doze apóstolos celebrados juntos. Filipe trouxe Natanael a Jesus; Tiago é autor de uma epístola canônica.$$, $$Dois dos doze apóstolos celebrados juntos. Filipe trouxe Natanael a Jesus; Tiago é autor de uma epístola canônica.$$, $$[]$$::jsonb, '{"\"A fé sem obras é morta.\""}'::text[], $$apostle$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Albrecht_D%C3%BCrer_-_The_Apostles_Philip_and_James_-_WGA07067.jpg/440px-Albrecht_D%C3%BCrer_-_The_Apostles_Philip_and_James_-_WGA07067.jpg$$, NULL, '{"Fé","Obras"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$nossa-senhora-fatima$$, $$Nossa Senhora de Fátima$$, $$Rainha do Rosário$$, $$13 de Maio$$, 5, 13, NULL, NULL, '{"Portugal","Paz mundial"}'::text[], $$Em 1917, a Virgem Maria apareceu seis vezes a três pastorinhos em Fátima, Portugal, pedindo oração e penitência.$$, $$Em 1917, a Virgem Maria apareceu seis vezes a três pastorinhos em Fátima, Portugal, pedindo oração e penitência.$$, $$[]$$::jsonb, '{"\"Rezai o terço todos os dias para alcançar a paz no mundo.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Our_Lady_of_F%C3%A1tima.jpg/440px-Our_Lady_of_F%C3%A1tima.jpg$$, NULL, '{"Oração","Penitência"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$matias$$, $$São Matias$$, $$O Apóstolo Escolhido$$, $$14 de Maio$$, 5, 14, $$Séc. I, Judeia$$, $$Séc. I$$, '{"Carpinteiros"}'::text[], $$Escolhido por sorteio para substituir Judas Iscariotes como o décimo segundo apóstolo.$$, $$Escolhido por sorteio para substituir Judas Iscariotes como o décimo segundo apóstolo.$$, $$[]$$::jsonb, '{"\"A sorte do Senhor caiu sobre mim.\""}'::text[], $$apostle$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Peter_Paul_Rubens_-_St_Matthias_-_WGA20202.jpg/440px-Peter_Paul_Rubens_-_St_Matthias_-_WGA20202.jpg$$, NULL, '{"Disponibilidade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$visitacao$$, $$Visitação de Nossa Senhora$$, $$Maria visita Isabel$$, $$31 de Maio$$, 5, 31, NULL, NULL, '{"Grávidas"}'::text[], $$Festa que celebra a visita de Maria a sua prima Isabel, quando o Magnificat foi proclamado.$$, $$Festa que celebra a visita de Maria a sua prima Isabel, quando o Magnificat foi proclamado.$$, $$[]$$::jsonb, '{"\"A minha alma glorifica o Senhor.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Mariotto_Albertinelli_-_Visitation_-_WGA0413.jpg/440px-Mariotto_Albertinelli_-_Visitation_-_WGA0413.jpg$$, NULL, '{"Serviço","Alegria"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$justino$$, $$São Justino Mártir$$, $$Filósofo e Mártir$$, $$1 de Junho$$, 6, 1, $$100, Nablus$$, $$165, Roma$$, '{"Filósofos"}'::text[], $$Filósofo pagão convertido, escreveu as primeiras Apologias do cristianismo e foi martirizado em Roma.$$, $$Filósofo pagão convertido, escreveu as primeiras Apologias do cristianismo e foi martirizado em Roma.$$, $$[]$$::jsonb, '{"\"Encontrei na filosofia cristã a única verdadeira filosofia.\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Justin_Martyr.jpg/440px-Justin_Martyr.jpg$$, NULL, '{"Verdade","Coragem"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$marcelo-matias$$, $$Santos Marcelino e Pedro$$, $$Mártires de Roma$$, $$2 de Junho$$, 6, 2, $$Séc. III, Roma$$, $$304, Roma$$, '{"Roma"}'::text[], $$Sacerdote e exorcista martirizados durante a perseguição de Diocleciano. Mencionados no Cânon Romano.$$, $$Sacerdote e exorcista martirizados durante a perseguição de Diocleciano. Mencionados no Cânon Romano.$$, $$[]$$::jsonb, '{"\"Cristo é nossa força na perseguição.\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{"Fidelidade"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$bonifacio$$, $$São Bonifácio$$, $$Apóstolo da Germânia$$, $$5 de Junho$$, 6, 5, $$675, Inglaterra$$, $$754, Frísia$$, '{"Alemanha","Cervejeiros"}'::text[], $$Monge inglês que evangelizou a Germânia, derrubando o carvalho de Thor. Martirizado na Frísia.$$, $$Monge inglês que evangelizou a Germânia, derrubando o carvalho de Thor. Martirizado na Frísia.$$, $$[]$$::jsonb, '{"\"Não nos deixemos esmagar pelo medo, pois temos ao nosso lado o Deus dos exércitos.\""}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Bonifatius_von_Fulda.jpg/440px-Bonifatius_von_Fulda.jpg$$, NULL, '{"Coragem","Evangelização"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$natividade-joao-batista$$, $$Natividade de São João Batista$$, $$O Precursor$$, $$24 de Junho$$, 6, 24, $$Séc. I a.C., Ain Karim$$, $$29 d.C., Maqueronte$$, '{"Florença","Quebec"}'::text[], $$O maior dos profetas, precursor de Cristo. Batizou Jesus no Jordão e morreu decapitado por Herodes.$$, $$O maior dos profetas, precursor de Cristo. Batizou Jesus no Jordão e morreu decapitado por Herodes.$$, $$[]$$::jsonb, '{"\"É preciso que Ele cresça e que eu diminua.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Caravaggio_Baptist_Toledo.jpg/440px-Caravaggio_Baptist_Toledo.jpg$$, NULL, '{"Humildade","Profecia"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$pedro-paulo$$, $$Santos Pedro e Paulo$$, $$Pilares da Igreja$$, $$29 de Junho$$, 6, 29, $$Séc. I, Galileia/Tarso$$, $$64/67, Roma$$, '{"Roma","Papado"}'::text[], $$Os dois maiores apóstolos: Pedro, a pedra sobre a qual a Igreja foi edificada; Paulo, o apóstolo dos gentios.$$, $$Os dois maiores apóstolos: Pedro, a pedra sobre a qual a Igreja foi edificada; Paulo, o apóstolo dos gentios.$$, $$[]$$::jsonb, '{"\"Tu és o Cristo, o Filho do Deus vivo.\""}'::text[], $$apostle$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/El_Greco_-_Apostles_Peter_and_Paul_-_WGA10537.jpg/440px-El_Greco_-_Apostles_Peter_and_Paul_-_WGA10537.jpg$$, NULL, '{"Fé","Missão"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$tomas-apostolo$$, $$São Tomé Apóstolo$$, $$O Apóstolo da Índia$$, $$3 de Julho$$, 7, 3, $$Séc. I, Galileia$$, $$Séc. I, Índia$$, '{"Índia","Arquitetos"}'::text[], $$Apóstolo que duvidou da Ressurreição mas confessou "Meu Senhor e meu Deus!". Evangelizou a Índia.$$, $$Apóstolo que duvidou da Ressurreição mas confessou "Meu Senhor e meu Deus!". Evangelizou a Índia.$$, $$[]$$::jsonb, '{"\"Meu Senhor e meu Deus!\""}'::text[], $$apostle$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/The_Incredulity_of_Saint_Thomas-Caravaggio_%281601-2%29.jpg/440px-The_Incredulity_of_Saint_Thomas-Caravaggio_%281601-2%29.jpg$$, NULL, '{"Fé","Missão"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$bento$$, $$São Bento de Núrsia$$, $$Pai do Monaquismo Ocidental$$, $$11 de Julho$$, 7, 11, $$480, Núrsia$$, $$547, Monte Cassino$$, '{"Europa","Monges","Estudantes"}'::text[], $$Fundador da Ordem de São Bento e autor da Regra de São Bento, documento fundamental do monaquismo ocidental.$$, $$Fundador da Ordem de São Bento e autor da Regra de São Bento, documento fundamental do monaquismo ocidental.$$, $$[]$$::jsonb, '{"\"Ora et Labora — Reza e Trabalha.\""}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{"Oração","Trabalho","Ordem"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$nossa-senhora-carmo$$, $$Nossa Senhora do Carmo$$, $$Flor do Carmelo$$, $$16 de Julho$$, 7, 16, NULL, NULL, '{"Carmelitas","Marinheiros"}'::text[], $$Devoção mariana ligada à Ordem do Carmelo. A Virgem entregou o escapulário a São Simão Stock.$$, $$Devoção mariana ligada à Ordem do Carmelo. A Virgem entregou o escapulário a São Simão Stock.$$, $$[]$$::jsonb, '{"\"Quem morrer vestindo este escapulário não padecerá o fogo eterno.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Tiepolo_-_Our_Lady_of_Mount_Carmel_and_Saints.jpg/440px-Tiepolo_-_Our_Lady_of_Mount_Carmel_and_Saints.jpg$$, NULL, '{"Devoção","Proteção"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$maria-madalena$$, $$Santa Maria Madalena$$, $$Apóstola dos Apóstolos$$, $$22 de Julho$$, 7, 22, $$Séc. I, Magdala$$, $$Séc. I$$, '{"Convertidos","Perfumistas"}'::text[], $$Discípula fiel de Jesus, testemunha da crucificação e primeira a ver o Senhor Ressuscitado.$$, $$Discípula fiel de Jesus, testemunha da crucificação e primeira a ver o Senhor Ressuscitado.$$, $$[]$$::jsonb, '{"\"Rabbuni! — Mestre!\""}'::text[], $$mystic$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Guido_Reni_-_The_Penitent_Magdalene_-_Google_Art_Project.jpg/440px-Guido_Reni_-_The_Penitent_Magdalene_-_Google_Art_Project.jpg$$, NULL, '{"Arrependimento","Amor"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$tiago-maior$$, $$São Tiago Maior$$, $$Apóstolo de Compostela$$, $$25 de Julho$$, 7, 25, $$Séc. I, Galileia$$, $$44, Jerusalém$$, '{"Espanha","Peregrinos"}'::text[], $$Irmão de São João, primeiro apóstolo mártir. Seu sepulcro em Santiago de Compostela é destino de peregrinação.$$, $$Irmão de São João, primeiro apóstolo mártir. Seu sepulcro em Santiago de Compostela é destino de peregrinação.$$, $$[]$$::jsonb, '{"\"Podemos beber do cálice do Senhor.\""}'::text[], $$apostle$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Rembrandt_Harmensz._van_Rijn_-_Apostle_James_-_Google_Art_Project.jpg/440px-Rembrandt_Harmensz._van_Rijn_-_Apostle_James_-_Google_Art_Project.jpg$$, NULL, '{"Zelo","Martírio"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$marta$$, $$Santa Marta$$, $$A Anfitriã de Jesus$$, $$29 de Julho$$, 7, 29, $$Séc. I, Betânia$$, $$Séc. I$$, '{"Cozinheiros","Hoteleiros"}'::text[], $$Irmã de Maria e Lázaro, acolheu Jesus em sua casa. Confessou: "Tu és o Cristo, o Filho de Deus."$$, $$Irmã de Maria e Lázaro, acolheu Jesus em sua casa. Confessou: "Tu és o Cristo, o Filho de Deus."$$, $$[]$$::jsonb, '{"\"Sim, Senhor, eu creio que tu és o Cristo.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Vermeer_-_Christ_in_the_House_of_Martha_and_Mary.jpg/440px-Vermeer_-_Christ_in_the_House_of_Martha_and_Mary.jpg$$, NULL, '{"Hospitalidade","Fé"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;

INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$afonso-liguori$$, $$Santo Afonso de Ligório$$, $$Doutor da Igreja$$, $$1 de Agosto$$, 8, 1, $$1696, Nápoles$$, $$1787, Pagani$$, '{"Moralistas","Confessores"}'::text[], $$Fundador dos Redentoristas e grande moralista, autor das Glórias de Maria.$$, $$Fundador dos Redentoristas e grande moralista, autor das Glórias de Maria.$$, $$[]$$::jsonb, '{"\"Quem reza se salva, quem não reza se condena.\""}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Alfonso_Maria_de_Ligorio.jpg/440px-Alfonso_Maria_de_Ligorio.jpg$$, NULL, '{"Misericórdia","Zelo"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$transfiguracao$$, $$Transfiguração do Senhor$$, $$A Glória de Cristo$$, $$6 de Agosto$$, 8, 6, NULL, NULL, '{"Contemplação"}'::text[], $$Festa que celebra quando Jesus revelou sua glória divina a Pedro, Tiago e João no Monte Tabor.$$, $$Festa que celebra quando Jesus revelou sua glória divina a Pedro, Tiago e João no Monte Tabor.$$, $$[]$$::jsonb, '{"\"Este é o meu Filho amado. Escutai-o.\""}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Transfiguration_Raphael.jpg/440px-Transfiguration_Raphael.jpg$$, NULL, '{"Contemplação"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$domingos$$, $$São Domingos de Gusmão$$, $$Fundador dos Dominicanos$$, $$8 de Agosto$$, 8, 8, $$1170, Caleruega$$, $$1221, Bolonha$$, '{"Astrônomos","Pregadores"}'::text[], $$Fundador da Ordem dos Pregadores (Dominicanos), propagou o Rosário como arma espiritual.$$, $$Fundador da Ordem dos Pregadores (Dominicanos), propagou o Rosário como arma espiritual.$$, $$[]$$::jsonb, '{"\"Não tenhais medo, porque a Mãe de Deus está convosco.\""}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{"Pregação","Oração"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$clara-assis$$, $$Santa Clara de Assis$$, $$Fundadora das Clarissas$$, $$11 de Agosto$$, 8, 11, $$1194, Assis$$, $$1253, Assis$$, '{"Televisão","Bordadeiras"}'::text[], $$Seguidora de São Francisco, fundou a Ordem das Damas Pobres (Clarissas), dedicada à pobreza e contemplação.$$, $$Seguidora de São Francisco, fundou a Ordem das Damas Pobres (Clarissas), dedicada à pobreza e contemplação.$$, $$[]$$::jsonb, '{"\"Olhai para o espelho da perfeição, que é Cristo.\""}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Simone_Martini_047.jpg/440px-Simone_Martini_047.jpg$$, NULL, '{"Pobreza","Contemplação"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$assuncao$$, $$Assunção de Nossa Senhora$$, $$Glória de Maria$$, $$15 de Agosto$$, 8, 15, NULL, NULL, '{"Humanidade"}'::text[], $$Solenidade que celebra a elevação de Maria ao Céu em corpo e alma, dogma definido por Pio XII em 1950.$$, $$Solenidade que celebra a elevação de Maria ao Céu em corpo e alma, dogma definido por Pio XII em 1950.$$, $$[]$$::jsonb, '{"\"Todas as gerações me chamarão bem-aventurada.\""}'::text[], $$virgin$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Guido_Reni_-_The_Assumption_of_the_Virgin_Mary_-_Google_Art_Project.jpg/440px-Guido_Reni_-_The_Assumption_of_the_Virgin_Mary_-_Google_Art_Project.jpg$$, NULL, '{"Glória","Pureza"}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;
