BEGIN;
INSERT INTO public.catechism_official (paragraph, content) VALUES (1, 'Deus, infinitamente perfeito e bem-aventurado em Si mesmo, num desígnio de pura bondade, criou livremente o homem para o tornar participante da sua vida bem-aventurada. Por isso, sempre e em toda a parte, Ele está próximo do homem. Chama-o e ajuda-o a procurá-Lo, a conhecê-Lo e a amá-Lo com todas as suas forças. Convoca todos os homens, dispersos pelo pecado, para a unidade da sua família que é a Igreja. Para tal, enviou o seu Filho como Redentor e Salvador na plenitude dos tempos. N''Ele e por Ele, chama os homens a tornarem-se, no Espírito Santo, seus filhos adoptivos e, portanto, herdeiros da sua vida bem-aventurada.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (2, 'Para que este convite se fizesse ouvir por toda a Terra, Cristo enviou os Apóstolos que escolhera, dando-lhes o mandato de anunciar o Evangelho: «Ide, pois, fazei discípulos de todas as nações, baptizando-os em nome do Pai e do Filho e do Espírito Santo, ensinando-os a cumprirem tudo quanto vos prescrevi. E eis que Eu estou convosco todos os dias até ao fim do mundo» (Mt 28, 19-20). Fortalecidos por esta missão, os Apóstolos «partiram a pregar por toda a parte e o Senhor cooperava com eles confirmando a Palavra com os sinais que a acom­panhavam» (Mc 16, 20).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (3, 'Aqueles que, com a ajuda de Deus, aceitaram o convite de Cristo e livremente Lhe responderam, foram por sua vez impelidos, pelo amor do mesmo Cristo, a anunciar por toda a parte a Boa-Nova. Este tesouro, recebido dos Apóstolos, foi fielmente guardado pelos seus sucessores. Todos os fiéis de Cristo são chamados a transmiti-lo de geração em geração, anunciando a fé, vivendo-a em partilha fraterna e celebrando-a na liturgia e na oração (1).

II. Transmitir a fé – a catequese') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (4, 'Bem cedo se chamou catequese ao conjunto de esforços empreendidos na Igreja para fazer discípulos, para ajudar os homens a acreditar que Jesus é o Filho de Deus, a fim de, pela fé, terem a vida em seu nome, e para os educar e instruir nessa vida, construindo assim o Corpo de Cristo (2).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (5, '«A catequese é uma educação da fé das crianças, dos jovens e dos adultos, que compreende especialmente o ensino da doutrina cristã, ministrado em geral dum modo orgânico e sistemático, em ordem à iniciação na plenitude da vida cristã» (3).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (6, 'Sem se confundir com eles, a catequese articula-se com um certo número de elementos da missão pastoral da Igreja que têm um aspecto catequético, preparam para a catequese ou dela derivam: o primeiro anúncio do Evangelho ou pregação missionária, para suscitar a fé; a busca das razões de acreditar; a experiência da vida cristã; a celebração dos sacramentos; a integração na comunidade eclesial; o testemunho apostólico e missionário (4)') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (7, '«A catequese está intimamente ligada a toda a vida da Igreja. Dependem essencialmente dela não só a expansão geográfica e o crescimento numérico, mas também, e muito mais ainda, o crescimento interior da Igreja e a sua conformidade com o desígnio de Deus» (5).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (8, 'Os períodos de renovação da Igreja são também tempos fortes de catequese. Assim, na grande época dos Padres da Igreja, vemos santos bispos consagrarem parte importante do seu ministério à catequese, como por exemplo São Cirilo de Jerusalém, São João Crisóstomo, Santo Ambrósio, Santo Agostinho e tantos outros Padres, cujas obras catequéticas continuam a ser modelo.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (9, 'O ministério da catequese vai buscar energias sempre novas aos concílios. O Concílio de Trento constitui, a este respeito, um exemplo a sublinhar: nas suas constituições e decretos, deu prioridade à catequese; está na origem do Catecismo Romano que tem o seu nome e que constitui um trabalho de primeira ordem como compêndio da doutrina cristã; fez nascer na Igreja uma organização notável da catequese; e, graças a santos bispos e teólogos, como São Pedro Canísio, São Carlos Borromeo, São Toríbio de Mogrovejo e São Roberto Belarmino, levou à publicação de numerosos catecismos.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (10, 'Não admira, pois, que, na sequência do II Concílio do Vaticano (que o Papa Paulo VI considerava como o grande catecismo dos tempos modernos), a catequese da Igreja tenha de novo chamado a atenção. O Directório catequético geral, de 1971; as sessões do Sínodo dos Bispos consagradas à evangelização (1974) e à catequese (1977): e as exortações apostólicas correspondentes — Evangelii nuntiandi (1975) e Catechesi tradendae (1979) — são disso bom testemunho. A assembleia extraordinária do Sínodo dos Bispos de 1985 pediu: «que seja redigido um catecismo ou compêndio de toda a doutrina católica, tanto no tocante à fé como no que respeita à moral» (6). O Santo Padre João Paulo II fez seu este voto do Sínodo dos Bispos. Reconheceu que «tal desejo corresponde inteiramente a uma verdadeira necessidade da Igreja universal e das Igrejas particulares»(7). E pôs todo o seu empenho cm que se concretizasse este desejo dos Padres sinodais.

III. Finalidade e destinatários deste catecismo') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (11, 'A finalidade deste Catecismo é apresentar uma exposição orgânica e sintética dos conteúdos essenciais e fundamentais da doutrina católica, tanto sobre a fé como sobre a moral, à luz do II Concilio do Vaticano e do conjunto da Tradição da Igreja. As suas fontes principais são a Sagrada Escritura, os santos Padres, a liturgia e o Magistério da Igreja. E destina-se a servir «como ponto de referência aos catecismos ou compêndios a publicar nos diversos países» (8).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (12, 'Este Catecismo destina-se principalmente aos responsáveis pela catequese, que são em primeiro lugar os bispos, enquanto doutores da fé e pastores da Igreja. É-lhes oferecido como instrumento para o desempenho da sua missão de ensinar o povo de Deus. E, através dos bispos, dirige-se aos redactores de catecismos, aos sacerdotes e aos catequistas. Será também uma leitura útil para todos os outros fiéis cristãos.

IV. Estrutura deste catecismo') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (13, 'O plano deste Catecismo inspira-se na grande tradição dos catecismos que articulam a catequese cm torno de quatro «pilares»: a profissão da fé baptismal (Símbolo), os sacramentos da fé, a vida da fé (Mandamentos) e  a oração do crente (o Pai Nosso).

PRIMEIRA PARTE: A PROFISSÃO DA FÉ') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (14, 'Aqueles que, pela fé e pelo Baptismo, pertencem a Cristo, devem confessar a sua fé baptismal diante dos homens (9). Por isso, o Catecismo começa por expor em que consiste a Revelação, pela qual Deus Se dirige e Se dá ao homem, e a fé pela qual o homem responde a Deus (Primeira Secção). O Símbolo da fé resume os dons que Deus faz ao homem, como Autor de todo o bem, Redentor e Santificador, e articula-os em volta dos «três capítulos» do nosso Baptismo – a fé num só Deus: o Pai Todo-poderoso, Criador; e o seu Filho Jesus Cristo, nosso Senhor e Salvador: e o Espírito Santo, na Santa Igreja (Segunda Secção).

SEGUNDA PARTE: OS SACRAMENTOS DA FÉ') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (15, 'A segunda parte do Catecismo expõe como a salvação de Deus, realizada uma vez por todas por Jesus Cristo e pelo Espírito Santo, se toma presente nas acções sagradas da liturgia da Igreja(Primeira Secção), e em especial nos sete sacramentos (Segunda Secção).

TERCEIRA PARTE: A VIDA DA FÉ') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (16, 'A terceira parte do Catecismo apresenta o fim último do homem, criado à imagem de Deus – a bem-aventurança e os caminhos para a ela chegar: um comportamento recto e livre, com a ajuda da lei de Deus e da sua graça (Primeira Secção); um comportamento que realize o duplo mandamento da caridade, explicitado nos dez Mandamentos de Deus (Segunda Secção).

QUARTA PARTE: A ORAÇÃO NA VIDA DA FÉ

V. Indicações práticas para o uso deste catecismo') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (18, 'Este Catecismo foi concebido como uma exposição orgânica de toda a fé católica. Deve, portanto, ser lido como um todo. Numerosas notas remissivas à margem do texto (números impressos em tipos menores remetendo para outros parágrafos que tratam do mesmo assunto) e o índice analítico no fim do volume, permitem encarar cada tema na sua ligação com o conjunto da fé.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (19, 'Muitas vezes, os textos da Sagrada Escritura não são citados literalmente, mas com a simples indicação da referência (por meio dum cf.) feita em nota. Para uma inteligência aprofundada desses passos, convém recorrer aos próprios textos. Tais referências bíblicas são um instrumento de trabalho para a catequese.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (20, 'Quando, cm certas passagens, se emprega a letra miúda, isso quer dizer que se trata de anotações de tipo histórico ou apologético, ou de exposições doutrinais complementares.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (21, 'As citações, em letra miúda, de fontes patrísticas, litúrgicas, do Magistério ou da hagiografia, destinam-se a enriquecer a exposição doutrinal. Frequentemente, esses textos foram escolhidos a pensar num emprego directamente catequético.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (22, 'No fim de cada unidade temática, uma série de textos breves resume, em fórmulas escolhidas, o essencial do ensinamento. Estes «RESUMINDO» têm por fim dar à catequese local sugestões de fórmulas sintéticas e fáceis de decorar.

VI. Adaptações necessárias') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (23, 'A tónica deste Catecismo incide sobre a exposição doutrinal. Com efeito, a sua intenção é ajudar a aprofundar o conhecimento da fé. Todo ele se orienta no sentido do amadurecimento da mesma fé, do seu enraizamento na vida e da sua irradiação no testemunho (10).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (24, 'Pela sua própria finalidade, este Catecismo não se propõe realizar as adaptações da exposição e dos métodos catequéticos, exigidas pelas diferenças de culturas, idades, maturidade espiritual, situações sociais e eclesiais daqueles a quem a catequese se dirige. Essas indispensáveis adaptações pertencem aos catecismos apropriados e, sobretudo, àqueles que ministram o ensino aos fiéis:

«Aquele que ensina deve "fazer-se tudo para todos" (1 Cor 9, 22) para a todos atrair a Jesus Cristo. [...] Sobretudo, não julgue que lhe está confiada apenas uma categoria de almas e que, portanto, lhe incumbe o trabalho de ensinar e formar de modo idêntico, na verdadeira piedade, todos os fiéis, usando sempre um só e mesmo método! Atendendo a que, em Cristo Jesus, uns são como crianças recém-nascidas, outros como adolescentes e outro, finalmente, já são efectivamente adultos, é necessário que pondere com toda a diligência quais são os que precisam de leite e quais os que carecem de um alimento mais sólido. [...] Isto mesmo testemunhava de si próprio o Apóstolo. [...] Os que são chamados ao ministério da pregação devem, ao transmitir o ensino dos mistérios da fé e das normas dos costumes, adaptar as suas palavras à mentalidade e à inteligência dos seus ouvintes» (11).

ACIMA DE TUDO — A CARIDADE') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (25, 'A concluir esta apresentação, é oportuno Lembrar este princípio pastoral enunciado pelo Catecismo Romano:

Este é sem dúvida o caminho melhor, que o mesmo apóstolo seguia quando fundamentava a sua doutrina e ensino na caridade que não acaba nunca. A finalidade da doutrina e do ensino deve fixar-se toda no amor, que não acaba. Podemos expor muito bem o que se deve crer, esperar ou fazer; mas, sobretudo, devemos pôr sempre em evidência o amor de nosso Senhor, de modo que cada qual compreenda que qualquer acto de virtude perfeitamente cristão, não tem outra origem nem outro fim senão o amor (12).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (26, 'Quando professamos a nossa fé, começamos por dizer: «Creio», ou «Cremos». Portanto, antes de expor a fé da Igreja, tal como é confessada no Credo, celebrada na liturgia, vivida na prática dos mandamentos e na oração, perguntemos a nós mesmos o que significa «crer». A fé é a resposta do homem a Deus, que a ele Se revela e Se oferece, resposta que, ao mesmo tempo, traz uma luz superabundante ao homem que busca o sentido último da sua vida. Comecemos, pois, por considerar esta busca do homem (capítulo primeiro): depois, a Revelação divina pela qual Deus vem ao encontro do homem (capítulo segundo); finalmente, a resposta da fé (capítulo terceiro).

CAPÍTULO PRIMEIRO

O HOMEM É «CAPAZ» DE DEUS

I. O desejo de Deus') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (27, 'O desejo de Deus é um sentimento inscrito no coração do homem, porque o homem foi criado por Deus e para Deus. Deus não cessa de atrair o homem para Si e só em Deus é que o homem encontra a verdade e a felicidade que procura sem descanso:

«A razão mais sublime da dignidade humana consiste na sua vocação à comunhão com Deus. Desde o começo da sua existência, o homem é convidado a dialogar com Deus: pois se existe, é só porque, criado por Deus por amor, é por Ele, e por amor, constantemente conservado: nem pode viver plenamente segundo a verdade, se não reconhecer livremente esse amor e não se entregar ao seu Criador»(1).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (28, 'De muitos modos, na sua história e até hoje, os homens exprimiram a sua busca de Deus em crenças e comportamentos religiosos (orações, sacrifícios, cultos, meditações, etc.). Apesar das ambiguidades de que podem enfermar, estas formas de expressão são tão universais que bem podemos chamar ao homem um ser religioso:

Deus «criou de um só homem todo o género humano, para habitar sobre a superfície da terra, e fixou períodos determinados e os limites da sua habitação, para que os homens procurassem a Deus e se esforçassem realmente por O atingir e encontrar. Na verdade, Ele não está longe de cada um de nós. É n''Ele que vivemos, nos movemos e existimos» (Act 17, 26-28).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (29, 'Mas esta «relação íntima e vital que une o homem a Deus»(2) pode ser esquecida, desconhecida e até explicitamente rejeitada pelo homem. Tais atitudes podem ter origens diversas (3) a revolta contra o mal existente no mundo, a ignorância ou a indiferença religiosas, as preocupações do mundo e das riquezas(4), o mau exemplo dos crentes, as correntes de pensamento hostis à religião e, finalmente, a atitude do homem pecador que, por medo, se esconde de Deus(5) e foge quando Ele o chama (6).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (30, '«Exulte o coração dos que procuram o Senhor» (Sl 105, 3). Se o homem pode esquecer ou rejeitar Deus, Deus é que nunca deixa de chamar todo o homem a que O procure, para que encontre a vida e a felicidade. Mas esta busca exige do homem todo o esforço da sua inteligência, a rectidão da sua vontade, «um coração recto», e também o testemunho de outros que o ensinam a procurar Deus.

És grande, Senhor, e altamente louvável; grande é o teu poder e a tua sabedoria é sem medida. E o homem, pequena parcela da tua criação, pretende louvar-Te – precisamente ele que, revestido da sua condição mortal, traz em si o testemunho do seu pecado, o testemunho de que Tu resistes aos soberbos. Apesar de tudo, o homem, pequena parcela da tua criação, quer louvar-Te. Tu próprio a isso o incitas, fazendo com que ele encontre as suas delícias no teu louvor, porque nos fizeste para Ti e o nosso coração não descansa enquanto não repousar em Ti (7).

II. Os caminhos de acesso ao conhecimento de Deus') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (31, 'Criado à imagem de Deus, chamado a conhecer e a amar a Deus, c homem que procura Deus descobre certos «caminhos» de acesso ao conhecimento de Deus. Também se lhes chama «provas da existência de Deus» – não no sentido das provas que as ciências naturais indagam mas no de «argumentos convergentes e convincentes» que permitem chegar a verdadeiras certezas.

Estes «caminhos» para atingir Deus têm como ponto de partida criação: o mundo material e a pessoa humana.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (32, 'O mundo: A partir do movimento e do devir, da contingência, da ordem e da beleza do mundo, pode chegar-se ao conhecimento de Deu: como origem e fim do universo.

São Paulo afirma a respeito dos pagãos: «O que se pode conhecer de Deus manifesto para eles, porque Deus lho manifestou. Desde a criação do mundo, a perfeições invisíveis de Deus, o seu poder eterno e a sua divindade tornam-se pelas suas obras, visíveis à inteligência» (Rm 1, 19-20) (8).

E Santo Agostinho: «Interroga a beleza da terra, interroga a beleza do mar interroga a beleza do ar que se dilata e difunde, interroga a beleza do céu [...] interroga todas estas realidades. Todas te respondem: Estás a ver como somo belas. A beleza delas é o seu testemunho de louvor [«confessio»]. Essas belezas sujeitas à mudança, quem as fez senão o Belo [«Ptdcher»], que não está sujeite à mudança?» (9).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (33, 'O homem: Com a sua abertura à verdade e à beleza, com o seu sentido do bem moral, com a sua liberdade e a voz da sua consciência, com a sua ânsia de infinito e de felicidade, o homem interroga-se sobre a existência de Deus. Nestas aberturas, ele detecta sinais da sua alma espiritual. «Gérmen de eternidade que traz em si mesmo, irredutível à simples matéria» (10), a sua alma só em Deus pode ter origem.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (34, 'O mundo e o homem atestam que não têm em si mesmos, nem o seu primeiro princípio, nem o seu fim último, mas que participam do Ser-em-si, sem princípio nem fim. Assim, por estes diversos «caminhos», o homem pode ter acesso ao conhecimento da existência duma realidade que é a causa primeira e o fim último de tudo, «e a que todos chamam Deus» (11).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (35, 'As faculdades do homem tornam-no capaz de conhecer a existência de um Deus pessoal. Mas, para que o homem possa entrar na sua intimidade, Deus quis revelar-Se ao homem e dar-lhe a graça de poder receber com fé esta revelação. Todavia, as provas da existência de Deus podem dispor para a fé e ajudar a perceber que a fé não se opõe à razão humana.

III. O conhecimento de Deus segundo a Igreja') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (36, '«A Santa Igreja, nossa Mãe, atesta e ensina que Deus, princípio e fim de todas as coisas, pode ser conhecido, com certeza, pela luz natural da razão humana, a partir das coisas criadas» (12). Sem esta capacidade, o homem não poderia acolher a revelação de Deus. O homem tem esta capacidade porque foi criado «à imagem de Deus» (Gn 1, 27).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (37, 'Nas condições históricas em que se encontra, o homem experimenta, no entanto, muitas dificuldades para chegar ao conhecimento de Deus só com as luzes da razão:

«Com efeito, para falar com simplicidade, apesar de a razão humana poder verdadeiramente, pelas suas forças e luz naturais, chegar a um conhecimento verdadeiro e certo de um Deus pessoal, que protege e governa o mundo pela sua providência, bem como de uma lei natural inscrita pelo Criador nas nossas almas, há, contudo, bastantes obstáculos que impedem esta mesma razão de usar eficazmente e com fruto o seu poder natural, porque as verdades que dizem respeito a Deus e aos homens ultrapassam absolutamente a ordem das coisas sensíveis; e quando devem traduzir-se em actos e informar a vida, exigem que nos dêmos e renunciemos a nós próprios. O espírito humano, para adquirir semelhantes verdades, sofre dificuldade da parte dos sentidos e da imaginação, bem como dos maus desejos nascidos do pecado original. Daí deriva que, em tais matérias, os homens se persuadem facilmente da falsidade ou, pelo menos, da incerteza das coisas que não desejariam fossem verdadeiras» (13).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (38, 'É por isso que o homem tem necessidade de ser esclarecido pela Revelação de Deus, não somente no que diz respeito ao que excede o seu entendimento, mas também sobre «as verdades religiosas e morais que, de si, não são inacessíveis à razão, para que possam ser, no estado actual do género humano, conhecidas por todos sem dificuldade, com uma certeza firme e sem mistura de erro» (14).

IV. Como falar de Deus?') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (39, 'Ao defender a capacidade da razão humana para conhecer Deus, a Igreja exprime a sua confiança na possibilidade de falar de Deus a todos os homens e com todos os homens. Esta convicção está na base do seu diálogo com as outras religiões, com a filosofia e as ciências, e também com os descrentes e os ateus.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (40, 'Mas dado que o nosso conhecimento de Deus é limitado, a nossa linguagem, ao falar de Deus, também o é. Não podemos falar de Deus senão a partir das criaturas e segundo o nosso modo humano limitado de conhecer e de pensar.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (41, 'Todas as criaturas são portadoras duma certa semelhança de Deus, muito especialmente o homem, criado à imagem e semelhança de Deus. As múltiplas perfeições das criaturas (a sua verdade, a sua bondade, a sua beleza) reflectem, pois, a perfeição infinita de Deus. Daí que possamos falar de Deus a partir das perfeições das suas criaturas: «porque a grandeza e a beleza das criaturas conduzem, por analogia, à contemplação do seu Autor» (Sb 13, 5).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (42, 'Deus transcende toda a criatura. Devemos, portanto, purificar incessantemente a nossa linguagem no que ela tem de limitado, de ilusório, de imperfeito, para não confundir o Deus «inefável, incompreensível, invisível, impalpável» (15) com as nossas representações humanas. As nossas palavras humanas ficam sempre aquém do mistério de Deus.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (43, 'Ao falar assim de Deus, a nossa linguagem exprime-se, evidentemente, de modo humano. Mas atinge realmente o próprio Deus, sem todavia poder exprimi-Lo na sua infinita simplicidade. Devemos lembrar-nos de que, «entre o Criador e a criatura, não é possível notar uma semelhança sem que a dissemelhança seja ainda maior» (16), e de que «não nos é possível apreender de Deus o que Ele é, senão apenas o que Ele não é, e como se situam os outros seres em relação a Ele»(17).

Resumindo:') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (44, 'O homem é, por natureza e vocação, um ser religioso. Vindo de Deus e caminhando para Deus, o homem não vive uma vida plenamente humana senão na medida em que livremente viver a sua relação com Deus.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (45, 'O homem foi feito para viver em comunhão com Deus, em quem encontra a sua felicidade: «Quando eu estiver todo em Ti, não mais haverá tristeza nem angústia; inteiramente repleta de Ti, a minha vida será vida plena»(18).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (46, 'Quando escuta a mensagem das criaturas e a voz da sua consciência, o homem pode alcançar a certeza da existência de Deus, causa e fim de tudo.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (47, 'A Igreja ensina que o Deus único e verdadeiro, nosso Criador e Senhor; pode ser conhecido com certeza pelas suas obras, graças à luz natural da razão humana  (19).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (48, 'Nós podemos realmente falar de Deus partindo das múltiplas perfeições das criaturas, semelhanças de Deus infinitamente perfeito, ainda que a nossa linguagem limitada não consiga esgotar o mistério.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (49, '«A criatura sem o Criador esvai-se» (20). Por isso, os crentes sentem-se pressionados pelo amor de Cristo a levar a luz do Deus vivo aos que O ignoram ou rejeitam.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (50, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 10: AAS 58 (1966) 822.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (51, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 10: AAS 58 (1966) 822.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (52, 'II Concílio do Vaticano. Const. dogm. Dei Verbum, 10: AAS 58 (1966) 822.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (53, 'Cf. II Concílio do Vaticano, Const. dogm. Lumen Gentium, 20: AAS 57 (1965) 24.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (54, 'Cf. Jo 8, 31-32.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (55, 'Cf. I Concílio do Vaticano, Const. dogm. Dei Filius,  c. 4: DS 3016 «mysteriorum nexus». Cf. II Concílio do Vaticano, Const. dogm. Lumen Gentium, 25: AAS 57 (1965) 29.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (56, 'II Concílio do Vaticano, Decr. Unitatis redintegratio, 11: AAS 57 (1965) 99.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (57, 'Cf. 1 Jo 2, 20. 27.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (58, 'II Concílio do Vaticano, Const. dogm. Lumen Gentium, 12: AAS 57 (1965) 16.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (59, 'II Concílio do Vaticano. Const. dogm. Lumen Gentium, 12: AAS 57 (1965) 16.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (60, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 8: AAS 58 (1966) 821.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (61, 'II Concílio do Vaticano, Const. past. Gaudium et spes, 62: AAS 58 (1966) 1084: cf. Ibid.. 44: AAS 58 (1966) 1065; Const. dogm. Dei Verbum, 23: AAS 58 (1966) 828; Ibid. 24: AAS 58 (1966) 828-829: Decr. Unitatis redintegratio, 4: AAS 57 (1965) 94.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (62, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 8: AAS 58 (1966) 821.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (63, 'São Gregório Magno, Homilia in Ezechielem 1. 7, 8: CCL 142. 87 (PL 76, 843 D).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (64, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 8: AAS 58 (1966) 821.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (65, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 10: AAS 58 (1966) 822.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (66, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 10: AAS 58 (1966) 822.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (67, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 8: AAS 58 (1966) 821.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (68, 'II Concílio do Vaticano. Const. dogm. Dei Verbum, 13: AAS 58 (1966) 824.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (69, 'Cf. Heb 1, 1-3.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (70, 'Santo Agostinho, Enarratio in Psalmum 103, 4, 1: CCL 40, 1521 (PL 37, 1378).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (71, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 21: AAS 58 (1966) 827.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (72, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 24: AAS 58 (1966) 829.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (73, 'Cf. 1 Ts 2, 13.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (74, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 21: AAS 58 (1966) 827-828.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (75, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 11: AAS 58 (1966) 822-823.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (76, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 11: AAS 58 (1966) 823.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (77, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 11: AAS 58 (1966) 823.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (78, 'São Bernardo de Claraval, Homilia super "Missus est", 4, 11: Opera, ed. J. Leclercq – H. Rochais, V. 4, Roma 1966, p. 57.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (79, 'Cf. Lc 24, 45.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (80, 'II Concílio do Vaticano, Const. dogm. Dei Verbum 12: AAS 58 11966) 823.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (81, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 12: AAS 58 (1966) 823.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (82, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 12: AAS 58 (1966) 824.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (83, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 12: AAS 58 (1966) 824.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (84, 'Cf. Lc 24. 25-27. 44-46.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (85, 'Cf. Sl 22, 15.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (86, 'São Tomás de Aquino, Expositio in Psalmos, 21, 11: Opera omnia. v. 18. Paris 1876, p. 350.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (87, 'Cf. Santo Hilário de Poitiers, Liber ad Constantium Imperatorem 9: CSEL 65. 204 PL 10, 570); São Jerónimo. Commentarius in epistulam ad Galatas I 1, 11-12: PL 26. 347.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (88, 'Orígenes, Homiliae in Leviticum 5, 5: SC 286, 228 (PG 12, 454).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (89, 'Cf. Rm 12, 6.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (90, 'São Tomás de Aquino, Summa theologiae I, q. 1, a. 10, ad I: Ed. Leon. 4, 25.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (91, 'Cf. 1 Cor 10, 2.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (92, 'Cf. Heb 3-4, 11.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (93, 'Cf. Ap 21, 1-22, 5.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (94, 'Agostinho de Dácia, Rotulus pugillaris, I: ed. A. Waltz: Angelicum 6(1929) 256.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (95, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 12: AAS 58 (1966) 824.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (96, 'Santo Agostinho, Contra Epistulam Manichaei quam vocant fundamenti 5. 6: CSEL 25, 197 (PL 42, 176).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (97, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 8: AAS 58 (1966) 821.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (98, 'Cf. Decretum Damasi: DS 179-180: Concílio de Florença, Decretum pro Iacobitis: DS 1334-1336; Concílio de Trento. Sess. 4ª. Decretum de Libris Sacris et de traditionibus recipiendis: DS 1501-1504.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (99, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 14: AAS 58 (1966) 825.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (100, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 15: AAS 58 (1966) 825.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (101, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 17: AAS 58 (1966) 826.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (102, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 20: AAS 58 (1966) 827.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (103, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 18: AAS 58 (1966) 826.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (104, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 19: AAS 58 (1966) 826-827.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (105, 'Santa Cesária, A Jovem, Epistula ad Richildam et Radegundem: SC 345, 480.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (106, 'Santa Teresa do Menino Jesus, Manuscrit A, 83v: Manuscrits autobiographiques, Paris 1929, p. 268. [Santa Teresa do Menino Jesus e da Santa Face, Obras Completas (Paço de Arcos. Edições do Carmelo 1996) p. 213].') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (107, 'Cf. 1 Cor 10, 6: Heb 10, 1; 1 Pe 3, 21.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (108, 'Cf. Mc 12, 29-31.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (109, 'Cf. 1 Cor 5, 6-8: 10, 1-11.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (110, 'Santo Agostinho, Quaestiones in Heptateucumt 2, 73: CCL 33. 106 (PL 34, 623); cf. II Concílio do Vaticano, Const. dogm. Dei Verbum, 16: AAS 58 (1966) 825.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (111, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 21: A AS 58 (1966) 828.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (112, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 22: AAS 58 (1966) 828.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (113, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 24: AAS 58 (1966) 829.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (114, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 25: AAS 58 (1966) 829: cf. São Jerónimo, Commentarii in Isaiam, Prologus: CCL 73, 1 (PL 24, 17).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (115, 'Hugo de São Vítor, De arca Noe II, 8: PL 176, 642: cf. Ibid. 2. 9: PL 176, 642-643.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (116, 'II Concílio do Vaticano, Const. dogm. Dei Verbum. 24: AAS 58 (1966) 829.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (117, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 11: AAS 58 (1966) 822-823.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (118, 'Cf. Orígenes, Homiliae in Exodum 4, 5: SC 321, 128 (PG 12, 320).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (119, 'II Concílio do Vaticano, Const. dogm. Dei Verbum, 21: AAS 58 (1966) 827.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (120, 'Cf. Is 50, 4.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (121, 'O Antigo Testamento é uma parte da Sagrada Escritura de que não se pode prescindir. Os seus livros são divinamente inspirados e conservam um valor permanente (99), porque a Antiga Aliança nunca foi revogada.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (122, 'Efectivamente, «a "economia"do Antigo Testamento destinava-se, sobretudo, a preparar [...] o advento de Cristo, redentor universal».

Os livros do Antigo Testamento, «apesar de conterem também coisas imperfeitas e transitórias», dão testemunho de toda a divina pedagogia do amor salvífico de Deus: neles «encontram-se sublimes doutrinas a respeito de Deus, uma sabedoria salutar a respeito da vida humana, bem como admiráveis tesouros de preces»; neles, em suma, está latente o mistério da nossa salvação» (100).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (123, 'Os cristãos veneram o Antigo Testamento como verdadeira Palavra de Deus. A Igreja combateu sempre vigorosamente a ideia de rejeitar o Antigo Testamento, sob o pretexto de que o Novo o teria feito caducar (Marcionismo).

O NOVO TESTAMENTO') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (124, '«A Palavra de Deus, que é força de Deus para salvação de quem acredita, apresenta-se e manifesta o seu poder dum modo eminente nos escritos do Novo Testamento»(101). Estes escritos transmitem-nos a verdade definitiva da Revelação divina. O seu objecto central é Jesus Cristo, o Filho de Deus encarnado, os seus actos, os seus ensinamentos, a sua Paixão e glorificação, bem como os primórdios da sua Igreja sob a acção do Espírito Santo (102).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (125, 'Os evangelhos são o coração de todas as Escrituras, «enquanto são o principal testemunho da vida e da doutrina do Verbo encarnado, nosso Salvador» (103).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (126, 'Na formação dos evangelhos podemos distinguir três etapas:') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (127, 'O Evangelho quadriforme ocupa na Igreja um lugar único, de que são testemunhas a veneração de que a Liturgia o rodeia e o atractivo incomparável que em todos os tempos exerceu sobre os santos:

«Não há doutrina melhor, mais preciosa e esplêndida do que o texto do Evangelho. Vede e retende o que nosso Senhor e Mestre, Cristo, ensinou pelas suas palavras e realizou pelos seus actos» (105).

«É sobretudo o Evangelho que me ocupa durante as minhas orações. Nele encontro tudo o que é necessário à minha pobre alma. Nele descubro sempre novas luzes, sentidos escondidos e misteriosos» (106).

A UNIDADE DO ANTIGO E DO NOVO TESTAMENTO') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (128, 'A Igreja, já nos tempos apostólicos (107), e depois constantemente na sua Tradição, pôs em evidência a unidade, do plano divino nos dois Testamentos, graças à tipologia. Esta descobre nas obras de Deus, na Antiga Aliança, prefigurações do que o mesmo Deus realizou na plenitude dos tempos, na pessoa do seu Filho encarnado.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (129, 'Os cristãos lêem, pois, o Antigo Testamento à luz de Cristo morto e ressuscitado. Esta leitura tipológica manifesta o conteúdo inesgotável do Antigo Testamento. Mas não deve fazer-nos esquecer de que ele mantém o seu valor próprio de Revelação, reafirmado pelo próprio Jesus, nosso Senhor (108). Aliás, também o Novo Testamento requer ser lido à luz do Antigo. A catequese cristã primitiva recorreu constantemente a este método (109). Segundo um velho adágio, o Novo Testamento está oculto no Antigo, enquanto o Antigo é desvendado no Novo: « Novum in Vetere latet et in Novo Vetus patet» – «O Novo está oculto no Antigo, e o Antigo está patente no Novo» (110).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (130, 'A tipologia significa o dinamismo em ordem ao cumprimento do plano divino, quando «Deus for tudo em todos» (1 Cor 15, 28). Assim, a vocação dos patriarcas e o êxodo do Egipto, por exemplo, não perdem o seu valor próprio no plano de Deus pelo facto de, ao mesmo tempo, serem etapas intermédias desse mesmo plano.

V. A Sagrada Escritura na vida da Igreja') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (131, '«É tão grande a força e a virtude da Palavra de Deus, que ela se torna para a Igreja apoio e vigor e, para os filhos da Igreja, solidez da fé, alimento da alma, fonte pura e perene de vida espiritual» (111). É necessário que «os fiéis tenham largo acesso à Sagrada Escritura» (112).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (132, '«O estudo das Páginas sagradas deve ser como que a "alma" da sagrada teologia. Também o ministério da Palavra, isto é, a pregação pastoral, a catequese, e toda a espécie de instrução cristã, na qual a homilia litúrgica deve ter um lugar principal, com proveito se alimenta e santamente se revigora com a palavra da Escritura» (113).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (133, 'A Igreja «exorta com ardor e insistência todos os fiéis [...] a que aprendam "a sublime ciência de Jesus Cristo" (Fl. 3, 8) na leitura frequente da Sagrada Escritura. Porque "a ignorância das Escrituras é ignorância de Cristo"» (114).

Resumindo:') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (134, 'Omnis Scriptura divina unus liber est, et ille unus liber Christus est, «quia omnis Scriptura divina de Christo loquitur; et omnis Scriptura divina in Christo impletur» – Toda a Escritura divina é um só livro, e esse livro único é Cristo, «porque toda a Escritura divina fala de Cristo e toda a Escritura divina se cumpre em Cristo» (115).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (135, '«As Sagradas Escrituras contêm a Palavra de Deus; e, pelo facto de serem inspiradas, são verdadeiramente a Palavra de Deus» (116).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (136, 'Deus é o autor da Sagrada Escritura, ao inspirar os seus autores humanos: age neles e por eles. E assim nos dá a garantia de que os seus escritos ensinam, sem erro, a verdade da salvação (117).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (137, 'A interpretação das Escrituras inspiradas deve, antes de mais nada, estar atenta ao que Deus quer revelar, por meio dos autores sagrados, para nossa salvação. O que vem do Espírito não é plenamente entendido senão pela acção do Espírito (118).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (138, 'A Igreja recebe e venera, como inspirados, os 46 livros do Antigo e os 27 do Novo Testamento.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (139, 'Os quatro evangelhos ocupam um lugar central, dado que Jesus Cristo é o seu centro.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (140, 'A unidade dos dois Testamentos deriva da unidade do plano de Deus e da sua Revelação. O Antigo Testamento prepara o Novo, ao passo que o Novo dá cumprimento ao Antigo. Os dois esclarecem-se mutuamente; ambos são verdadeira Palavra de Deus.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (141, '«A Igreja sempre venerou as Divinas Escrituras, tal como o próprio Corpo do Senhor» (119) ambos alimentam e regem toda a vida cristã. «A vossa Palavra é farol para os meus passos e luz para os meus caminhos» (Sl 119, 105)(120).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (142, 'Pela sua revelação,  «Deus invisível, na riqueza do seu amor, fala aos homens como amigos e convive com eles, para os convidar e admitir à comunhão com Ele» (1). A resposta adequada a este convite é a fé.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (143, 'Pela fé,  o homem submete completamente a Deus a inteligência e a vontade; com todo o seu ser, o homem dá assentimento a Deus revelador (2). A Sagrada Escritura chama «obediência da fé» a esta resposta do homem a Deus revelador (3).

ARTIGO 1

EU CREIO

I. A «obediência da fé»') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (144, 'Obedecer  (ob-audire)  na fé é submeter-se livremente à palavra escutada, por a sua verdade ser garantida por Deus, que é a própria verdade. Desta obediência, o modelo que a Sagrada Escritura nos propõe é Abraão. A sua realização mais perfeita é a da Virgem Maria.

ABRAÃO – «O PAI DE TODOS OS CRENTES»') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (145, 'A Epístola aos Hebreus, no grande elogio que faz da fé dos antepassados, insiste particularmente na fé de Abraão: «Pela fé, Abraão  obedeceu  ao chamamento de Deus, e partiu para uma terra que viria a receber como herança: partiu, sem saber para onde ia»  (Heb 11, 8) (4). Pela fé, viveu como estrangeiro e peregrino na terra prometida (5). Pela fé, Sara recebeu a graça de conceber o filho da promessa. Pela fé, finalmente, Abraão ofereceu em sacrifício o seu filho único (6).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (146, 'Abraão realiza assim a definição da fé dada pela Epístola aos Hebreus: «A fé constitui a garantia dos bens que se esperam, e a prova de que existem as coisas que não se vêem» (Heb 11, 1). «Abraão acreditou em Deus, e isto foi-lhe atribuído como justiça» (Rm 4, 3) (7). «Fortalecido» por esta fé (Rm 4, 20), Abraão tornou-se «o pai de todos os crentes» (Rm 4, 11. 18) (8).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (147, 'O Antigo Testamento é rico em testemunhos desta fé. A Epístola aos Hebreus faz o elogio da fé exemplar dos antigos, «que lhes valeu um bom testemunho» (Heb 11, 2. 39). No entanto, para nós, «Deus previra destino melhor»: a graça de crer no seu Filho Jesus, «guia da nossa fé, que Ele leva à perfeição» (Heb 11, 40; 12, 2).

MARIA – «FELIZ AQUELA QUE ACREDITOU»') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (148, 'A Virgem Maria realiza, do modo mais perfeito, a «obediência da fé». Na fé, Maria acolheu o anúncio e a promessa trazidos pelo anjo Gabriel, acreditando que «a Deus nada é impossível» (Lc 1, 37) (9) e dando o seu assentimento: «Eis a serva do Senhor, faça-se em mim segundo a tua palavra» (Lc 1, 38). Isabel saudou-a: «Feliz aquela que acreditou no cumprimento de quanto lhe foi dito da parte do Senhor» (Lc 1, 45). É em virtude desta fé que todas as gerações a hão-de proclamar bem-aventurada (10).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (149, 'Durante toda a sua vida e até à última provação (11), quando Jesus, seu filho, morreu na cruz, a sua fé jamais vacilou. Maria nunca deixou de crer «no cumprimento» da Palavra de Deus. Por isso, a Igreja venera em Maria a mais pura realização da fé.

II. «Eu sei em quem pus a minha fé» (2 Tm 1, 12)

CRER SÓ EM DEUS') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (150, 'Antes de mais, a fé é uma adesão pessoal do homem a Deus. Ao mesmo tempo, e inseparavelmente, é o assentimento livre a toda a verdade revelada por Deus. Enquanto adesão pessoal a Deus e assentimento à verdade por Ele revelada, a fé cristã difere da fé numa pessoa humana. É justo e bom confiar totalmente em Deus e crer absolutamente no que Ele diz. Seria vão e falso ter semelhante fé numa criatura (12).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (151, 'Para o cristão, crer em Deus é crer inseparavelmente n''Aquele que Deus enviou – «no seu Filho muito amado» em quem Ele pôs todas as suas complacências (13): Deus mandou-nos que O escutássemos (14). O próprio Senhor disse aos seus discípulos: «Acreditais em Deus, acreditai também em Mim»  (Jo  14, 1). Podemos crer em Jesus Cristo, porque Ele próprio é Deus, o Verbo feito carne: «A Deus, nunca ninguém O viu. O Filho Unigénito, que está no seio do Pai, é que O deu a conhecer»  (Jo  1, 18). Porque «viu o Pai» (Jo 6, 46), Ele é o único que O conhece e O pode revelar (15).

CRER NO ESPÍRITO SANTO') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (152, 'Não é possível acreditar em Jesus Cristo sem ter parte no seu Espírito. É o Espírito Santo que revela aos homens quem é Jesus. Porque «ninguém é capaz de dizer: "Jesus é Senhor", a não ser pela acção do Espírito Santo»  (1 Cor  12, 3). «O Espírito penetra todas as coisas, até o que há de mais profundo em Deus [...]. Ninguém conhece o que há em Deus senão o Espírito de Deus» (1 Cor 2, 10-11). Só Deus conhece inteiramente Deus. Nós cremos no Espírito Santo, porque Ele é Deus.

A Igreja não cessa de confessar a sua fé num só Deus, Pai, Filho e  Espírito Santo.

III. As características da fé

A FÉ É UMA GRAÇA') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (153, 'Quando Pedro confessa que Jesus é o Cristo, o Filho do Deus vivo, Jesus declara-lhe que esta revelação não lhe veio «da carne nem do sangue, mas do seu Pai que está nos Céus»  (Mt  16, 17)  (16). A fé é um dom de Deus, uma virtude sobrenatural infundida por Ele. «Para prestar esta adesão da fé, são necessários a prévia e concomitante ajuda da graça divina e os interiores auxílios do Espírito Santo, o qual move e converte o coração para Deus, abre os olhos do entendimento, e dá "a todos a suavidade em aceitar e crer a verdade"» (17).

A FÉ É UM ACTO HUMANO') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (154, 'O acto de fé só é possível pela graça e pelos auxílios interiores do Espírito Santo. Mas não é menos verdade que crer é um acto autenticamente humano. Não é contrário nem à liberdade nem à inteligência do homem confiar em Deus e aderir às verdades por Ele reveladas. Mesmo nas relações humanas, não é contrário à nossa própria dignidade acreditar no que outras pessoas nos dizem acerca de si próprias e das suas intenções, e confiar nas suas promessas (como, por exemplo, quando um homem e uma mulher se casam), para assim entrarem em mútua comunhão. Por isso, é ainda menos contrário à nossa dignidade «prestar, pela fé, submissão plena da nossa inteligência e da nossa vontade a Deus revelador» (18) e entrar assim em comunhão intima com Ele.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (155, 'Na fé, a inteligência e a vontade humanas cooperam com a graça divina: «Credere est actas intellectus assentientis veritati divinae ex imperio voluntatis, a Deo motae per gratiam» — «Crer é o acto da inteligência que presta o seu assentimento à verdade divina, por determinação da vontade, movida pela graça de Deus» (19).

A FÉ E A INTELIGÊNCIA') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (156, 'O motivo de crer não é o facto de as verdades reveladas aparecerem como verdadeiras e inteligíveis à luz da nossa razão natural. Nós cremos «por causa da autoridade do próprio Deus revelador, que não pode enganar-se nem enganar-nos» (20). «Contudo, para que a homenagem da nossa fé fosse conforme à razão, Deus quis que os auxílios interiores do Espírito Santo fossem acompanhados de provas exteriores da sua Revelação» (21). Assim, os milagres de Cristo e dos santos (22), as profecias, a propagação e a santidade da Igreja, a sua fecundidade e estabilidade «são sinais certos da Revelação, adaptados à inteligência de todos» (23), «motivos de credibilidade», mostrando que o assentimento da fé não é, «de modo algum, um movimento cego do espírito» (24).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (157, 'A fé é certa, mais certa que qualquer conhecimento humano, porque se funda na própria Palavra de Deus, que não pode mentir. Sem dúvida, as verdades reveladas podem parecer obscuras à razão e à experiência humanas; mas «a certeza dada pela luz divina é maior do que a dada pela luz da razão natural» (25). «Dez mil dificuldades não fazem uma só dúvida» (26).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (158, '«A fé procura compreender» (27): é inerente à fé o desejo do crente de conhecer melhor Aquele em quem acreditou, e de compreender melhor o que Ele revelou; um conhecimento mais profundo exigirá, por sua vez, uma fé maior e cada vez mais abrasada em amor. A graça da fé abre «os olhos do coração» (Ef 1, 18) para uma inteligência viva dos conteúdos da Revelação, isto é, do conjunto do desígnio de Deus e dos mistérios da fé, da íntima conexão que os Liga entre si e com Cristo, centro do mistério revelado. Ora, para «que a compreensão da Revelação seja cada vez mais profunda, o mesmo Espírito Santo aperfeiçoa sem cessar a fé, mediante os seus dons» (28). Assim, conforme o dito de Santo Agostinho, «eu creio para compreender e compreendo para crer melhor» (29).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (159, 'Fé e ciência. «Muito embora a fé esteja acima da razão, nunca pode haver verdadeiro desacordo entre ambas: o mesmo Deus, que revela os mistérios e comunica a fé, também acendeu no espírito humano a luz da razão. E Deus não pode negar-Se a Si próprio, nem a verdade pode jamais contradizer a verdade» (30). «É por isso que a busca metódica, em todos os domínios do saber, se for conduzida de modo verdadeiramente científico e segundo as normas da moral, jamais estará em oposição à fé: as realidades profanas e as da fé encontram a sua origem num só e mesmo Deus. Mais ainda: aquele que se esforça, com perseverança e humildade, por penetrar no segredo das coisas, é como que conduzido pela mão de Deus, que sustenta todos os seres e faz que eles sejam o que são, mesmo que não tenha consciência disso» (31).

A LIBERDADE DA FÉ') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (160, 'Para ser humana, «a resposta da fé, dada pelo homem a Deus, deve ser voluntária. Por conseguinte, ninguém deve ser constrangido a abraçara fé contra vontade. Efectivamente, o acto de fé é voluntário por sua própria natureza» (32). «E certo que Deus chama o homem a servi-Lo em espírito e verdade; mas, se é verdade que este apelo obriga o homem em consciência, isso não quer dizer que o constranja [...]. Isto foi evidente, no mais alto grau, em Jesus Cristo» (33). De facto, Cristo convidou à fé e à conversão, mas de modo nenhum constrangeu alguém. «Deu testemunho da verdade, mas não a impôs pela força aos seus contraditores. O seu Reino [...] dilata-se graças ao amor, pelo qual, levantado na cruz, Cristo atrai a Si todos os homens (34)».

A NECESSIDADE DA FÉ') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (161, 'Para obter a salvação é necessário acreditar em Jesus Cristo e n''Aquele que O enviou para nos salvar (35). «Porque "sem a fé não é possível agradar a Deus" (Heb 11, 6) e chegar a partilhar a condição de filhos seus; ninguém jamais pode justificar-se sem ela e ninguém que não "persevere nela até ao fim" (Mt 10, 22; 24, 13) poderá alcançar a vida eterna» (36).

A PERSEVERANÇA NA FÉ') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (162, 'A fé á um dom gratuito de Deus ao homem. Mas nós podemos perder este dom inestimável. Paulo adverte Timóteo a respeito dessa possibilidade: «Combate o bom combate, guardando a fé e a boa consciência; por se afastarem desse princípio é que muitos naufragaram na fé» (1 Tm 1, 18-19). Para viver, crescer e perseverar até ao fim na fé, temos de a alimentar com a Palavra de Deus; temos de pedir ao Senhor que no-la aumente (37); ela deve «agir pela caridade» (Gl 5, 6) (38), ser sustentada pela esperança (39) e permanecer enraizada na fé da Igreja.

A FÉ – VIDA ETERNA INICIADA') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (163, 'A fé faz que saboreemos, como que de antemão, a alegria e a luz da visão beatifica, termo da nossa caminhada nesta Terra. Então veremos Deus «face a face» (1 Cor 13, 12), «tal como Ele é» (1 Jo 3, 2). A fé, portanto, é já o princípio da vida eterna:

«Enquanto, desde já, contemplamos os benefícios da fé, como reflexo num espelho, é como se possuíssemos já as maravilhas que a nossa fé nos garante havermos de gozar um dia» (40).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (165, 'É então que nos devemos voltar para as  testemunhas da fé:  Abraão, que acreditou, «esperando contra toda a esperança» (Rm 4, 18); a Virgem Maria que, na «peregrinação da fé» (41), foi até à «noite da fé» (42), comungando no sofrimento do seu Filho e na noite do seu sepulcro (43); e tantas outras testemunhas da fé: «envoltos em tamanha nuvem de testemunhas, devemos desembaraçar-nos de todo o fardo e do pecado que nos cerca, e correr com constância o risco que nos é proposto, fixando os olhos no guia da nossa fé, o qual a leva à perfeição»  (Heb  12, 1-2).

ARTIGO 2

NÓS CREMOS') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (166, 'A fé é um acto pessoal, uma resposta livre do homem à proposta de Deus que Se revela. Mas não é um acto isolado. Ninguém pode acreditar sozinho, tal como ninguém pode viver só. Ninguém se deu a fé a si mesmo, como ninguém a si mesmo se deu a vida. Foi de outrem que o crente recebeu a fé; a outrem a deve transmitir. O nosso amor a Jesus e aos homens impele-nos a falar aos outros da nossa fé. Cada crente é, assim, um elo na grande cadeia dos crentes. Não posso crer sem ser amparado pela fé dos outros, e pela minha fé contribuo também para amparar os outros na fé.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (167, '«Eu creio» (44): é a fé da Igreja, professada pessoalmente por cada crente, principalmente por ocasião do Baptismo. «Nós cremos» (45): é a fé da Igreja, confessada pelos bispos reunidos em Concílio ou, de modo mais geral, pela assembleia litúrgica dos crentes. «Eu creio»: é também a Igreja, nossa Mãe, que responde a Deus pela sua fé e nos ensina a dizer: «Eu creio», «Nós cremos».

I. «Olhai, Senhor, para a fé da vossa Igreja»') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (168, 'É, antes de mais, a Igreja que crê, e que assim suporta, nutre e sustenta a minha fé. É primeiro a Igreja que, por toda a parte, confessa o Senhor («Te per orbem terrarum sancta confitetur Ecclesia» – «A Santa Igreja anuncia por toda a terra a glória do vosso nome» – como cantamos no «Te Deum»). Com ela e nela, também nós somos atraídos e levados a confessar: «Eu creio», «Nós cremos». É da Igreja que recebemos a fé e a vida nova em Cristo, pelo Baptismo. No Ritual Romano, o ministro do Baptismo pergunta ao catecúmeno: «Que vens pedir à Igreja de Deus?» E ele responde: – «A fé». – «Para que te serve a fé?» – «Para alcançar a vida eterna» (46).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (169, 'A salvação vem só de Deus. Mas porque é através da Igreja que recebemos a vida da fé, a Igreja é nossa Mãe. «Cremos que a Igreja é como que a mãe do nosso novo nascimento, mas não cremos na Igreja como se ela fosse a autora da nossa salvação»(47). É porque é nossa Mãe, é também a educadora da nossa fé.

II. A linguagem da fé') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (170, 'Não acreditamos em fórmulas, mas sim nas realidades que as fórmulas exprimem e que a fé nos permite «tocar». «O acto [de fé] do crente não se detém no enunciado, mas na realidade [enunciada]» (48). No entanto, é através das fórmulas da fé que nos aproximamos dessas realidades. As fórmulas permitem-nos exprimir e transmitir a fé, celebrá-la em comunidade, assimilá-la e dela viver cada vez mais.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (171, 'A Igreja, que é «coluna e apoio da verdade» (1 Tm 3, 15), guarda fielmente a fé transmitida aos santos de uma vez por todas (49). É ela que guarda a memória das palavras de Cristo. É ela que transmite, de geração em geração, a confissão de fé dos Apóstolos. Tal como uma mãe ensina os seus filhos a falar e, dessa forma, a compreender e a comunicar, a Igreja, nossa Mãe, ensina-nos a linguagem da fé, para nos introduzir na inteligência e na vida da fé.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (172, 'Desde há séculos, através de tantas línguas, culturas, povos e nações, a Igreja não cessa de confessar a sua fé única, recebida de um só Senhor, transmitida por um só Baptismo, enraizada na convicção de que todos os homens têm apenas um só Deus e Pai (50). Santo Ireneu de Lião, testemunha desta fé, declara:') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (173, '«A Igreja, embora dispersa por todo o mundo até aos confins da Terra, tendo recebido dos Apóstolos e dos seus discípulos a fé, [...] guarda [esta pregação e esta fé] com tanto cuidado como se habitasse numa só casa; nela crê de modo idêntico, como tendo um só coração e uma só alma; prega-a e ensina-a e transmite-a com voz unânime, como se tivesse uma só boca» (51).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (174, '«Através do mundo, as línguas diferem: mas o conteúdo da Tradição é um só e o mesmo. Nem as Igrejas estabelecidas na Germania têm outra fé ou outra tradição, nem as que se estabeleceram entre os Iberos ou entre os Celtas, as do Oriente, do Egipto ou da Líbia, nem as que se fundaram no centro do mundo» (52). «A mensagem da Igreja é verídica e sólida, porque nela aparece um só e o mesmo caminho de salvação, em todo o mundo» (53).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (175, 'Esta fé, «que recebemos da Igreja, guardamo-la nós cuidadosamente, porque sem cessar, sob a acção do Espírito de Deus, tal como um depósito de grande valor encerrado num vaso excelente, ela rejuvenesce e faz rejuvenescer o próprio vaso que a contém» (54).

Resumindo:') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (176, 'A fé é uma adesão pessoal, do homem todo, a Deus que Se revela. Comporta uma adesão da inteligência e da vontade à Revelação que Deus fez de Si mesmo, pelas suas acções e palavras.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (177, '«Crer» tem, pois, uma dupla referência: à pessoa e à verdade; à verdade, pela confiança na pessoa que a atesta.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (178, 'Não devermos crer em mais ninguém senão em Deus, Pai, Filho e Espírito Santo.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (180, '«Crer» é um acto humano, consciente e livre, que está de acordo com a dignidade da pessoa humana.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (181, '«Crer» é um acto eclesial. A fé da Igreja precede, gera, suporta e nutre a nossa fé. A Igreja é a Mãe de todos os crentes. «Ninguém pode ter a Deus por Pai, se não tiver a Igreja por Mãe» (55).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (182, '«Nós cremos em tudo quanto está contido na Palavra de Deus, escrita ou transmitida, e que a Igreja propõe à nossa fé como divinamente revelado»  (56).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (183, 'A fé é necessária para a salvação. O próprio Senhor o afirma: «Quem acreditar e for baptizado salvar-se-á, mas quem não acreditar será condenado» (Mc 16, 16).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (184, '«A fé é um antegozo do conhecimento que nos tornará felizes na vida futura» (57).

CREDO

SÍMBOLO DOS APÓSTOLOS (58)

CREDO DE NICEIA–CONSTANTINOPLA (59)

Creio em Deus, Pai todo-poderoso,Criador do Céu e da Terra;

Creio em um só Deus, Pai todo-poderoso, Criador do Céu e da Terra,  de todas as coisas visíveis e invisíveis.

e em Jesus Cristo, seu único Filho,nosso Senhor,

Creio em um só Senhor, Jesus Cristo, Filho Unigénito de Deus, nascido do Pai antes de todos os séculos:Deus de Deus, luz da luz, Deus verdadeiro de Deus verdadeiro; gerado, não criado, consubstancial ao Pai.  Por Ele todas as coisas foram feitas. E por nós, homens, e para nossa salvação desceu dos Céus.

que foi concebido pelo poder do Espírito Santo; nasceu da Virgem Maria;

E encarnou pelo Espírito Santo, no seio da Virgem Maria, e Se fez homem.

padeceu sob Pôncio Pilatos, foi crucificado, morto e sepultado; desceu à mansão dos mortos; ressuscitou ao terceiro dia; subiu aos Céus; está sentado à direita de Deus Pai todo-poderoso, de onde há-de vir a julgar  os vivos e os mortos.

Também por nós foi crucificado sob Pôncio Pilatos; padeceu e foi sepultado.

Ressuscitou ao terceiro dia, conforme as Escrituras; e subiu aos Céus, onde está sentado à direita do Pai. De novo há-de vir em sua glória,  para julgar os vivos e os mortos; e o seu Reino não terá fim.

Creio no Espírito Santo;

Creio no Espírito Santo, Senhor que dá a vida, e procede do Pai e do Filho; e com o Pai e o Filho é adorado e glorificado: Ele que falou pelos profetas.

na santa Igreja Católica; na comunhão dos Santos;

Creio na Igreja una, santa, católica e apostólica.

na remissão dos pecados; na ressurreição da carne;na vida eterna.  Amen

Professo um só Baptismo para remissão dos pecados. E espero a ressurreição dos mortos, e a vida do mundo que há-de vir. Amen.

10 Cf. Lc l, 48.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (185, 'Quem diz «Creio» afirma: «dou a minha adesão àquilo em que nós cremos». A comunhão na fé tem necessidade duma linguagem comum da fé, normativa para todos e a todos unindo na mesma confissão de fé.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (186, 'Desde a origem, a Igreja apostólica exprimiu e transmitiu a sua própria fé em fórmulas breves e normativas para todos (1). Mas bem cedo a Igreja quis também recolher o essencial da sua fé em resumos orgânicos e articulados, destinados sobretudo aos candidatos ao Baptismo.

«Esta síntese da fé não foi feita segundo as opiniões humanas: mas recolheu-se de toda a Escritura o que nela há de mais importante, para apresentar na integra aquilo e só aquilo que a fé ensina. E, tal como a semente de mostarda contém, num pequeno grão, numerosos ramos, do mesmo modo este resumo da fé encerra em algumas palavras todo o conhecimento da verdadeira piedade contido no Antigo e no Novo Testamento» (2).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (187, 'A estas sínteses da fé chamamos-lhes «profissões de fé», porque resumem a fé professada pelos cristãos. Chamamos-lhes «Credo», pelo facto de elas normalmente começarem pela palavra: «Creio». Igualmente lhes chamamos «símbolos da fé».') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (188, 'A palavra grega «symbolon» significava a metade dum objecto partido (por exemplo, um selo), que se apresentava como um sinal de identificação. As duas partes eram justapostas para verificar a identidade do portador. O «símbolo da fé» é, pois, um sinal de identificação e de comunhão entre os crentes. «Symbolon» também significa resumo, colectânea ou sumário. O «símbolo da fé» é o sumário das principais verdades da fé. Por isso, serve de ponto de referência primário e fundamental da catequese.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (189, 'A primeira «profissão de fé» faz-se por ocasião do Baptismo. O «símbolo da fé» é, antes de mais nada, o símbolo baptismal. E uma vez que o Baptismo é conferido «em nome do Pai e do Filho e do Espírito Santo»(Mt 28, 19), as verdades da fé professadas por ocasião do Baptismo articulam-se segundo a sua referência às três pessoas da Santíssima Trindade.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (190, 'O Símbolo divide-se, portanto, em três partes: «na primeira, trata da Primeira Pessoa divina e da obra admirável da criação: na segunda, da Segunda Pessoa divina e do mistério da Redenção dos homens; na terceira, da Terceira Pessoa divina, fonte e princípio da nossa santificação» (3). São estes «os três capítulos do nosso selo [baptismal]» (4).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (191, 'O Símbolo «está estruturado em três partes [...] subdivididas em fórmulas variadas e muito adequadas. Segundo uma comparação frequentemente empregada pelos Padres, chamamos-lhes artigos. De facto, assim como nos nossos membros há certas articulações que os distinguem e separam, do mesmo modo, nesta profissão de fé, foi com razão e propriedade que se deu o nome de artigos às verdades que devemos crer em particular e de modo distinto» (5). Segundo uma antiga tradição, já atestada por Santo Ambrósio, é costume enumerar doze artigos do Credo, simbolizando, com o número dos doze Apóstolos, o conjunto da fé apostólica (6).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (192, 'Foram numerosas, ao longo dos séculos, e correspondendo sempre às necessidades das diferentes épocas, as profissões ou símbolos da fé: os símbolos das diferentes Igrejas apostólicas e antigas (7), o símbolo «Quicumque», chamado de Santo Atanásio (8), as profissões de fé de certos concílios (Toledo (9); Latrão (10): Lião (11) Trento (12)) ou de certos papas, como a «Fides Damasi» (13) ou o «Credo do Povo de Deus», de Paulo VI (1968) (14).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (193, 'Nenhum dos símbolos dos diferentes períodos da vida da Igreja pode ser considerado ultrapassado ou inútil. Todos nos ajudam a abraçar e a aprofundar hoje a fé de sempre, através dos diversos resumos que dela se fizeram.

Entre todos os símbolos da fé, há dois que têm um lugar muito especial na vida da Igreja:') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (194, 'O Símbolo dos Apóstolos, assim chamado porque se considera, com justa razão, o resumo fiel da fé dos Apóstolos. É o antigo símbolo baptismal da Igreja de Roma. A sua grande autoridade vem-lhe deste facto: «É o símbolo adoptado pela Igreja romana, aquela em que Pedro, o primeiro dos Apóstolos, teve a sua cátedra, e para a qual ele trouxe a expressão da fé comum» (15).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (195, 'O Símbolo dito de Niceia-Constantinopla deve a sua grande autoridade ao facto de ser proveniente desses dois primeiros concílios ecuménicos (dos anos de 325 e 381). Ainda hoje continua a ser comum a todas as grandes Igrejas do Oriente e do Ocidente.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (196, 'A exposição da fé, que vamos fazer, seguirá o Símbolo dos Apóstolos, que constitui, por assim dizer, «o mais antigo catecismo romano». Entretanto, a nossa exposição será completada por constantes referências ao Símbolo Niceno-Constantinopolitano, muitas vezes mais explícito e pormenorizado.') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO public.catechism_official (paragraph, content) VALUES (197, 'Como no dia do nosso Baptismo, quando toda a nossa vida foi confiada «a esta regra de doutrina» (Rm 6, 17), acolhemos o Símbolo da nossa fé que dá a vida. Recitar com fé o Credo é entrar em comunhão com Deus Pai, Filho e Espírito Santo. E é também entrar em comunhão com toda a Igreja, que nos transmite a fé e em cujo seio nós acreditamos:

«Este Símbolo é o selo espiritual [...], é a meditação do nosso coração e a sentinela sempre presente; é, sem dúvida, o tesouro da nossa alma» (16).') ON CONFLICT (paragraph) DO UPDATE SET content = EXCLUDED.content;
COMMIT;
