INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$sao-josafa$$, $$São Josafá$$, $$Bispo e Mártir$$, $$12 de Novembro$$, 11, 12, NULL, NULL, '{}'::text[], $$Arcebispo ucraniano que trabalhou pela unidade da Igreja.$$, $$Arcebispo ucraniano que trabalhou pela unidade da Igreja.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-francisca-cabrini$$, $$Santa Francisca Xavier Cabrini$$, $$Padroeira dos Imigrantes$$, $$13 de Novembro$$, 11, 13, NULL, NULL, '{}'::text[], $$Religiosa italiana que emigrou para os EUA e fundou hospitais, orfanatos e escolas.$$, $$Religiosa italiana que emigrou para os EUA e fundou hospitais, orfanatos e escolas.$$, $$[]$$::jsonb, '{}'::text[], $$founder$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg/440px-Fra_Angelico_-_Saint_Dominic_-_Google_Art_Project.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-nicolau-tavelic$$, $$São Nicolau Tavelić$$, $$Mártir da Terra Santa$$, $$14 de Novembro$$, 11, 14, NULL, NULL, '{}'::text[], $$Frade franciscano croata martirizado em Jerusalém por pregar aos muçulmanos.$$, $$Frade franciscano croata martirizado em Jerusalém por pregar aos muçulmanos.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santo-alberto-magno$$, $$Santo Alberto Magno$$, $$Doutor Universal$$, $$15 de Novembro$$, 11, 15, NULL, NULL, '{}'::text[], $$Dominicano, mestre de São Tomás de Aquino, enciclopedista e cientista.$$, $$Dominicano, mestre de São Tomás de Aquino, enciclopedista e cientista.$$, $$[]$$::jsonb, '{}'::text[], $$doctor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/St-thomas-aquinas.jpg/440px-St-thomas-aquinas.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santa-margarida-escocia$$, $$Santa Margarida da Escócia$$, $$Rainha e Santa$$, $$16 de Novembro$$, 11, 16, NULL, NULL, '{}'::text[], $$Rainha da Escócia que promoveu a reforma da Igreja e a caridade aos pobres.$$, $$Rainha da Escócia que promoveu a reforma da Igreja e a caridade aos pobres.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;
