INSERT INTO public.saints (id, name, title, feast_day, feast_month, feast_day_num, born, died, patron_of, bio, full_bio, works, quotes, category, image, prayer, virtues, bible_refs, catechism_refs, church_doc_refs) VALUES
($$dedicacao-basilicas$$, $$Dedicação das Basílicas de São Pedro e São Paulo$$, $$Pilares da Igreja$$, $$18 de Novembro$$, 11, 18, NULL, NULL, '{}'::text[], $$Festa que celebra as duas maiores basílicas de Roma.$$, $$Festa que celebra as duas maiores basílicas de Roma.$$, $$[]$$::jsonb, '{}'::text[], $$confessor$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Fra_Angelico_031.jpg/440px-Fra_Angelico_031.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-roque-gonzalez$$, $$São Roque González de Santa Cruz$$, $$Mártir do Paraguai$$, $$19 de Novembro$$, 11, 19, NULL, NULL, '{}'::text[], $$Jesuíta que fundou reduções guaranis e foi martirizado pelos indígenas.$$, $$Jesuíta que fundou reduções guaranis e foi martirizado pelos indígenas.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-edmundo$$, $$Santo Edmundo$$, $$Rei e Mártir$$, $$20 de Novembro$$, 11, 20, NULL, NULL, '{}'::text[], $$Rei inglês morto pelos vikings por se recusar a renegar a fé cristã.$$, $$Rei inglês morto pelos vikings por se recusar a renegar a fé cristã.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$sao-clemente-roma$$, $$São Clemente de Roma$$, $$Papa e Mártir$$, $$23 de Novembro$$, 11, 23, NULL, NULL, '{}'::text[], $$Quarto Papa, autor da mais antiga carta cristã fora do Novo Testamento.$$, $$Quarto Papa, autor da mais antiga carta cristã fora do Novo Testamento.$$, $$[]$$::jsonb, '{}'::text[], $$pope$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Cathedra_Petri_adjusted.JPG/440px-Cathedra_Petri_adjusted.JPG$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb),
($$santos-andre-dung-lac$$, $$Santos André Dung-Lac e Companheiros$$, $$Mártires do Vietnã$$, $$24 de Novembro$$, 11, 24, NULL, NULL, '{}'::text[], $$117 mártires vietnamitas que deram a vida pela fé.$$, $$117 mártires vietnamitas que deram a vida pela fé.$$, $$[]$$::jsonb, '{}'::text[], $$martyr$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fra_Angelico_052.jpg/440px-Fra_Angelico_052.jpg$$, NULL, '{}'::text[], $$[]$$::jsonb, '{}'::integer[], $$[]$$::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_day = EXCLUDED.feast_day,
    feast_month = EXCLUDED.feast_month,
    feast_day_num = EXCLUDED.feast_day_num,
    born = EXCLUDED.born,
    died = EXCLUDED.died,
    patron_of = EXCLUDED.patron_of,
    bio = EXCLUDED.bio,
    full_bio = EXCLUDED.full_bio,
    works = EXCLUDED.works,
    quotes = EXCLUDED.quotes,
    category = EXCLUDED.category,
    image = EXCLUDED.image,
    prayer = EXCLUDED.prayer,
    virtues = EXCLUDED.virtues,
    bible_refs = EXCLUDED.bible_refs,
    catechism_refs = EXCLUDED.catechism_refs,
    church_doc_refs = EXCLUDED.church_doc_refs;
