import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Icons } from '@/constants';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/integrations/supabase/client';
import { format } from 'date-fns';
import { ptBR } from 'date-fns/locale';
import { CathedraCard } from './CathedraCard';
import ContemplativeLayout from './ContemplativeLayout';
import { getLevelInfo } from '@/lib/levels';
import { Button } from '@/components/ui/button';
import { useNavigate } from 'react-router-dom';
import { Database } from '@/integrations/supabase/types';

type UserHistory = Database['public']['Tables']['user_history']['Row'];
type JourneyProgressRow = Database['public']['Tables']['journey_progress']['Row'] & { journeys: { title: string } | null };

interface JourneyProgress {
  id: string;
  title: string;
  progress: number;
  last_visited: string;
}

const SpiritualProfile: React.FC = () => {
  const { user, profile } = useAuth();
  const navigate = useNavigate();
  const [recentReadings, setRecentReadings] = useState<UserHistory[]>([]);
  const [activeJourneys, setActiveJourneys] = useState<JourneyProgress[]>([]);
  const [contemplatedThemes, setContemplatedThemes] = useState<string[]>(profile?.spiritual_themes || []);
  const [preferences, setPreferences] = useState<any>(profile?.contemplative_preferences || {
    rhythm: 'moderate',
    suggestion_mode: 'balanced',
    recurring_themes: []
  });
  const [favoriteReflections, setFavoriteReflections] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  const updatePreference = async (key: string, value: any) => {
    if (!user) return;
    const newPrefs = { ...preferences, [key]: value };
    setPreferences(newPrefs);
    await supabase.from('profiles').update({ contemplative_preferences: newPrefs }).eq('id', user.id);
  };

  const toggleEmailReminders = async () => {
    if (!user) return;
    const newSettings = { ...profile.notification_settings, email_reminders: !profile.notification_settings?.email_reminders };
    await supabase.from('profiles').update({ notification_settings: newSettings }).eq('id', user.id);
    window.location.reload(); // Refresh to update profile context
  };

  useEffect(() => {
    if (!user) return;

    const fetchSpiritualData = async () => {
      setLoading(true);
      try {
        // Fetch recent history
        const { data: historyData } = await supabase
          .from('user_history')
          .select('*')
          .eq('user_id', user.id)
          .order('visited_at', { ascending: false })
          .limit(6);

        // Fetch active journeys (completed steps)
        const { data: journeyData } = await supabase
          .from('journey_progress')
          .select('journey_id, journeys(title), completed_at')
          .eq('user_id', user.id)
          .order('completed_at', { ascending: false });

        // Group by journey_id and get last completed_at
        const uniqueJourneys = Array.from(new Set((journeyData || []).map(j => j.journey_id)));
        const journeyList: JourneyProgress[] = uniqueJourneys.slice(0, 3).map(id => {
          const matching = (journeyData as any[])?.filter(j => j.journey_id === id) || [];
          return {
            id,
            title: matching[0]?.journeys?.title || 'Jornada',
            progress: Math.min(Math.round((matching.length / 10) * 100), 100),
            last_visited: matching[0]?.completed_at || new Date().toISOString()
          };
        });

        // Fetch favorite reflections
        const { data: reflectionsData } = await supabase
          .from('spiritual_journal')
          .select('*')
          .eq('user_id', user.id)
          .order('created_at', { ascending: false })
          .limit(3);

        setRecentReadings(historyData || []);
        setActiveJourneys(journeyList);
        setFavoriteReflections(reflectionsData || []);
        
        // Extract themes from profile (automatically generated by AI)
        setContemplatedThemes(profile?.spiritual_themes || ['Aguardando Logos...']);
        setPreferences(profile?.contemplative_preferences || {
          rhythm: 'moderate',
          suggestion_mode: 'balanced',
          recurring_themes: []
        });

      } catch (error) {
        console.error('Error fetching spiritual profile data:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchSpiritualData();
  }, [user]);

  if (!profile) return null;

  const { levelName, progress: xpProgress } = getLevelInfo(profile.xp || 0);

  return (
    <ContemplativeLayout
      subtitle="Itinerarium Animae"
      title="Perfil Espiritual"
      maxW="max-w-5xl"
    >
      <div className="space-y-4xl md:space-y-4xl">
        {/* Header/Summary */}
        <section className="text-center space-y-xl animate-in fade-in slide-in-from-bottom-md duration-1000">
          <div className="relative w-4xl h-4xl mx-auto mb-xl">
            <div className="absolute inset-0 rounded-full border border-primary/10 animate-pulse" />
            <div className="absolute -inset-md rounded-full border border-primary/5 animate-slow-spin" />
            <div className="w-full h-full rounded-full bg-primary/5 flex items-center justify-center overflow-hidden border border-primary/10">
              {profile.avatar_url ? (
                <img src={profile.avatar_url} alt={profile.name} className="w-full h-full object-cover opacity-80" />
              ) : (
                <Icons.User className="w-2xl h-2xl text-primary/60" strokeWidth={0.5} />
              )}
            </div>
          </div>
          
          <div className="space-y-xs">
            <h2 className="text-3xl font-display font-bold text-primary">{profile.name || 'Peregrino'}</h2>
            <p className="text-xs font-black uppercase tracking-[0.4em] text-primary/60">{levelName}</p>
          </div>

          <div className="flex justify-center gap-2xl pt-xl">
            <div className="text-center">
              <p className="text-2xl font-display text-primary">{profile.streak || 0}</p>
              <p className="text-[9px] font-black uppercase tracking-widest text-primary/60">Dias em Oração</p>
            </div>
            <div className="text-center">
              <p className="text-2xl font-display text-primary">{profile.xp || 0}</p>
              <p className="text-[9px] font-black uppercase tracking-widest text-primary/60">Graças (XP)</p>
            </div>
          </div>
        </section>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3xl md:gap-4xl">
          {/* Continuar Jornada */}
          <section className="space-y-xl">
            <div className="flex items-center gap-lg opacity-30">
              <Icons.Compass className="w-md h-md" strokeWidth={1} />
              <h3 className="text-[10px] font-black uppercase tracking-[0.4em]">Itinerários Ativos</h3>
            </div>
            
            <div className="space-y-lg">
              {activeJourneys.length > 0 ? (
                activeJourneys.map((j) => (
                  <CathedraCard 
                    key={j.id}
                    padding="none"
                    variant="interactive"
                    onClick={() => navigate(`/jornadas/${j.id}`)}
                    className="group cursor-pointer hover:border-primary/20 transition-all duration-700"
                  >
                    <div className="flex items-center justify-between gap-lg p-lg">
                      <div className="space-y-xs">
                        <p className="text-xs text-primary/40 font-bold uppercase tracking-widest">Em progresso</p>
                        <h4 className="text-lg font-serif font-bold text-primary">{j.title}</h4>
                      </div>
                      <div className="text-right">
                        <p className="text-xl font-display text-primary">{j.progress}%</p>
                        <div className="w-4xl h-2xs bg-primary/5 rounded-full mt-xs overflow-hidden">
                          <motion.div 
                            initial={{ width: 0 }}
                            animate={{ width: `${j.progress}%` }}
                            className="h-full bg-primary/20"
                          />
                        </div>
                      </div>
                    </div>
                  </CathedraCard>
                ))
              ) : (
                <div className="p-2xl border border-dashed border-primary/10 rounded-premium text-center opacity-30">
                  <p className="font-serif italic text-sm">Nenhuma jornada iniciada...</p>
                  <Button 
                    variant="ghost" 
                    className="mt-lg text-[10px] font-black uppercase tracking-widest"
                    onClick={() => navigate('/jornadas')}
                  >
                    Explorar Itinerários
                  </Button>
                </div>
              )}
            </div>
          </section>

          {/* Temas Contemplados (Dynamic) */}
          <section className="space-y-xl">
            <div className="flex items-center gap-lg opacity-30">
              <Icons.Sparkles className="w-md h-md" strokeWidth={1} />
              <h3 className="text-[10px] font-black uppercase tracking-[0.4em]">Temas da Caminhada</h3>
            </div>
            
            <div className="flex flex-wrap gap-md">
              {contemplatedThemes.length > 0 ? (
                contemplatedThemes.map((theme) => (
                  <div 
                    key={theme}
                    className="px-lg py-sm rounded-full bg-primary/[0.02] border border-primary/[0.05] text-[11px] font-bold text-primary/60 tracking-wider hover:bg-primary/5 hover:border-primary/20 transition-all duration-500 cursor-default"
                  >
                    {theme}
                  </div>
                ))
              ) : (
                <p className="text-xs text-primary/60 font-serif italic">Logos IA está analisando sua caminhada...</p>
              )}
            </div>
          </section>

          {/* Preferências Contemplativas */}
          <section className="space-y-xl md:col-span-2 pt-2xl">
            <div className="flex items-center gap-lg opacity-30">
              <Icons.Settings className="w-md h-md" strokeWidth={1} />
              <h3 className="text-[10px] font-black uppercase tracking-[0.4em]">Preferências Contemplativas</h3>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-xl">
              <div className="p-xl rounded-premium bg-primary/[0.01] border border-primary/[0.03] space-y-md">
                <p className="text-[9px] font-black uppercase tracking-widest text-primary/60">Ritmo</p>
                <div className="flex items-center justify-between">
                  <span className="text-sm font-serif text-primary/70">{preferences.rhythm === 'soft' ? 'Suave' : preferences.rhythm === 'moderate' ? 'Moderado' : 'Intenso'}</span>
                  <Button variant="ghost" size="sm" className="text-[9px]" onClick={() => updatePreference('rhythm', preferences.rhythm === 'soft' ? 'moderate' : preferences.rhythm === 'moderate' ? 'intense' : 'soft')}>Alterar</Button>
                </div>
              </div>
              <div className="p-xl rounded-premium bg-primary/[0.01] border border-primary/[0.03] space-y-md">
                <p className="text-[9px] font-black uppercase tracking-widest text-primary/60">Sugestões Logos</p>
                <div className="flex items-center justify-between">
                  <span className="text-sm font-serif text-primary/70">{preferences.suggestion_mode === 'balanced' ? 'Equilibrado' : 'Aprofundado'}</span>
                  <Button variant="ghost" size="sm" className="text-[9px]" onClick={() => updatePreference('suggestion_mode', preferences.suggestion_mode === 'balanced' ? 'deep' : 'balanced')}>Alterar</Button>
                </div>
              </div>
              <div className="p-xl rounded-premium bg-primary/[0.01] border border-primary/[0.03] space-y-md">
                <p className="text-[9px] font-black uppercase tracking-widest text-primary/60">Lembretes</p>
                <div className="flex items-center justify-between">
                  <span className="text-sm font-serif text-primary/70">{profile.notification_settings?.email_reminders ? 'Email e Push' : 'Apenas Push'}</span>
                  <Button variant="ghost" size="sm" className="text-[9px]" onClick={() => toggleEmailReminders()}>Alternar</Button>
                </div>
              </div>
            </div>
          </section>

          {/* Últimas Leituras */}
          <section className="space-y-xl md:col-span-2">
            <div className="flex items-center gap-lg opacity-30">
              <Icons.BookOpen className="w-md h-md" strokeWidth={1} />
              <h3 className="text-[10px] font-black uppercase tracking-[0.4em]">Memória de Leitura</h3>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-xl">
              {recentReadings.length > 0 ? (
                recentReadings.map((reading) => (
                  <div key={reading.id} className="space-y-md p-xl rounded-premium bg-primary/[0.01] border border-primary/[0.03] group hover:bg-primary/[0.02] transition-all duration-700">
                    <p className="text-[9px] font-black uppercase tracking-widest text-primary/60">
                      {format(new Date(reading.visited_at), "d 'de' MMM", { locale: ptBR })}
                    </p>
                    <h4 className="text-base font-serif font-bold text-primary/80 line-clamp-1">{reading.title || 'Leitura'}</h4>
                    <p className="text-xs text-primary/40 italic line-clamp-2">Continuar contemplação...</p>
                  </div>
                ))
              ) : (
                <p className="col-span-3 text-center py-2xl font-serif italic text-primary/60">O silêncio das páginas aguarda sua visita.</p>
              )}
            </div>
          </section>

          {/* Reflexões Favoritas */}
          <section className="space-y-xl md:col-span-2">
            <div className="flex items-center gap-lg opacity-30">
              <Icons.Feather className="w-md h-md" strokeWidth={1} />
              <h3 className="text-[10px] font-black uppercase tracking-[0.4em]">Reflexões Guardadas</h3>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-2xl">
              {favoriteReflections.length > 0 ? (
                favoriteReflections.map((ref) => (
                  <div key={ref.id} className="relative p-xl rounded-premium border border-primary/5 bg-primary/[0.01] hover:bg-primary/[0.03] transition-all duration-1000 group">
                    <Icons.Quote className="absolute top-lg left-lg w-xl h-xl text-primary/5 group-hover:text-primary/60 transition-colors" />
                    <p className="text-lg font-serif italic text-primary/70 leading-relaxed mb-lg pt-md">
                      "{ref.content.length > 150 ? `${ref.content.substring(0, 150)}...` : ref.content}"
                    </p>
                    <p className="text-[9px] font-black uppercase tracking-widest text-primary/60">
                      {format(new Date(ref.created_at), "d 'de' MMMM", { locale: ptBR })}
                    </p>
                  </div>
                ))
              ) : (
                <p className="col-span-2 text-center py-2xl font-serif italic text-primary/60">Suas reflexões serão guardadas aqui.</p>
              )}
            </div>
          </section>
        </div>

        {/* Logos Suggestion */}
        <section className="pt-4xl border-t border-primary/5">
          <div className="premium-card p-2xl md:p-3xl bg-primary/[0.005] border-primary/[0.02] text-center space-y-2xl relative overflow-hidden">
            <div className="absolute top-0 left-0 w-full h-2xs bg-gradient-to-r from-transparent via-primary/5 to-transparent" />
            
            <div className="space-y-lg">
              <div className="w-2xl h-2xl rounded-full bg-primary/[0.02] border border-primary/[0.05] flex items-center justify-center mx-auto text-primary/60">
                <Icons.Sparkles className="w-md h-md" strokeWidth={0.5} />
              </div>
              <h3 className="text-xl md:text-2xl font-serif font-bold text-primary/80">O que sua alma busca hoje?</h3>
              <p className="text-sm md:text-base text-primary/40 font-serif italic max-w-xl mx-auto">
                "A Logos IA pode ajudar a conectar os temas de sua jornada e sugerir novos caminhos de contemplação."
              </p>
            </div>

            <div className="flex justify-center pt-xl">
              <Button 
                variant="ghost" 
                className="rounded-full px-2xl h-2xl border border-primary/10 hover:bg-primary/5 text-primary/60 font-bold uppercase tracking-widest text-[10px] transition-all duration-700"
                onClick={() => navigate('/logos')}
              >
                Conversar com Logos
              </Button>
            </div>
          </div>
        </section>
      </div>
    </ContemplativeLayout>
  );
};

export default SpiritualProfile;