/**
 * Catálogo Oficial de Coleções — Onda 3 · Coleções Inteligentes.
 *
 * Fonte única de verdade editorial para as trilhas de formação do Cathedra.
 * Organizadas em 4 tracks: Formação Fundamental, Santos e Espiritualidade,
 * Liturgia e Vida Cristã. Cada entrada abastece `public.collections` com
 * metadados editoriais (hero_quote, learning_objectives, difficulty_level,
 * estimated_reading_time_minutes, track, program_slug).
 *
 * Os itens de cada coleção continuam a ser curados via /admin/collections/:id
 * (ContentPicker), evitando duplicar catálogo de conteúdo aqui.
 */

export type OfficialTrack =
  | 'formacao-fundamental'
  | 'santos-espiritualidade'
  | 'liturgia'
  | 'vida-crista';

export const TRACK_LABEL: Record<OfficialTrack, string> = {
  'formacao-fundamental': 'Formação Fundamental',
  'santos-espiritualidade': 'Santos e Espiritualidade',
  liturgia: 'Liturgia',
  'vida-crista': 'Vida Cristã',
};

export interface OfficialCollectionSeed {
  slug: string;
  title: string;
  subtitle: string;
  track: OfficialTrack;
  category: string;
  difficulty_level: 'iniciante' | 'intermediario' | 'avancado';
  estimated_reading_time_minutes: number;
  hero_quote?: string;
  hero_quote_author?: string;
  learning_objectives: string[];
  recommended_for: string[];
  completion_message: string;
  program_slug?: string;
}

export const OFFICIAL_COLLECTIONS: OfficialCollectionSeed[] = [
  // ── Formação Fundamental ─────────────────────────────────────────────
  {
    slug: 'primeiros-passos-na-fe',
    title: 'Primeiros Passos na Fé Católica',
    subtitle: 'O ponto de partida para quem chega — ou volta — à fé.',
    track: 'formacao-fundamental',
    category: 'formacao',
    difficulty_level: 'iniciante',
    estimated_reading_time_minutes: 90,
    hero_quote: 'Vinde a mim, todos vós que estais cansados e sobrecarregados, e eu vos aliviarei.',
    hero_quote_author: 'Mt 11,28',
    learning_objectives: [
      'Compreender o essencial do Credo católico',
      'Reconhecer os sacramentos como encontros com Cristo',
      'Aprender a estrutura básica da oração cristã',
    ],
    recommended_for: ['Novos católicos', 'Retornantes', 'Catecúmenos'],
    completion_message: 'Você deu o primeiro passo. A fé é caminho — continue.',
    program_slug: 'formacao-catolica-essencial',
  },
  {
    slug: 'introducao-a-biblia',
    title: 'Introdução à Bíblia',
    subtitle: 'Como a Igreja lê a Palavra de Deus.',
    track: 'formacao-fundamental',
    category: 'formacao',
    difficulty_level: 'iniciante',
    estimated_reading_time_minutes: 120,
    hero_quote: 'Ignorar as Escrituras é ignorar a Cristo.',
    hero_quote_author: 'São Jerônimo',
    learning_objectives: [
      'Reconhecer a estrutura dos 73 livros do cânon católico',
      'Distinguir Antigo e Novo Testamento e sua unidade em Cristo',
      'Aplicar os sentidos literal, alegórico, moral e anagógico',
    ],
    recommended_for: ['Leitores iniciantes da Escritura'],
    completion_message: 'Toda página da Escritura fala de Cristo — continue lendo.',
    program_slug: 'escola-biblica',
  },
  {
    slug: 'introducao-ao-catecismo',
    title: 'Introdução ao Catecismo',
    subtitle: 'A arquitetura da fé em quatro pilares.',
    track: 'formacao-fundamental',
    category: 'formacao',
    difficulty_level: 'iniciante',
    estimated_reading_time_minutes: 150,
    hero_quote: 'Este catecismo tem por fim apresentar uma exposição orgânica e sintética dos conteúdos essenciais da fé católica.',
    hero_quote_author: 'João Paulo II, Fidei Depositum',
    learning_objectives: [
      'Conhecer os quatro pilares: Credo, Sacramentos, Mandamentos, Oração',
      'Situar o CIC como norma segura de fé',
      'Aprender a consultar o Catecismo com os índices analíticos',
    ],
    recommended_for: ['Catequistas', 'Estudantes de teologia iniciantes'],
    completion_message: 'A fé tem estrutura. Agora você tem o mapa.',
    program_slug: 'formacao-catolica-essencial',
  },
  {
    slug: 'como-rezar-diariamente',
    title: 'Como Rezar Diariamente',
    subtitle: 'Construir um ritmo estável de oração.',
    track: 'formacao-fundamental',
    category: 'oracao',
    difficulty_level: 'iniciante',
    estimated_reading_time_minutes: 60,
    hero_quote: 'Orai sem cessar.',
    hero_quote_author: '1Ts 5,17',
    learning_objectives: [
      'Estabelecer uma regra pessoal de oração',
      'Incorporar Laudes, Vésperas e o Angelus ao cotidiano',
      'Rezar o Rosário e a Lectio Divina',
    ],
    recommended_for: ['Todos os fiéis'],
    completion_message: 'A oração é respiração da alma. Continue respirando.',
    program_slug: 'escola-da-oracao',
  },
  {
    slug: 'como-estudar-a-doutrina',
    title: 'Como Estudar a Doutrina Católica',
    subtitle: 'Método e disciplina para o estudo da fé.',
    track: 'formacao-fundamental',
    category: 'formacao',
    difficulty_level: 'intermediario',
    estimated_reading_time_minutes: 90,
    learning_objectives: [
      'Distinguir dogma, doutrina e opinião teológica',
      'Usar fontes primárias: Escritura, CIC, Magistério, Padres, Doutores',
      'Ler documentos magisteriais com precisão',
    ],
    recommended_for: ['Estudantes autodidatas', 'Catequistas'],
    completion_message: 'Estudar a fé é ato de amor. Prossiga com humildade.',
    program_slug: 'formacao-catolica-essencial',
  },

  // ── Santos e Espiritualidade ─────────────────────────────────────────
  {
    slug: 'doutores-da-igreja',
    title: 'Doutores da Igreja',
    subtitle: 'Os grandes mestres proclamados pela Igreja.',
    track: 'santos-espiritualidade',
    category: 'santos',
    difficulty_level: 'intermediario',
    estimated_reading_time_minutes: 240,
    hero_quote: 'Doctor Ecclesiae — mestres cuja santidade e ciência iluminaram o Povo de Deus.',
    learning_objectives: [
      'Conhecer os 37 Doutores proclamados',
      'Distinguir suas escolas espirituais',
      'Ler trechos essenciais de cada mestre',
    ],
    recommended_for: ['Estudantes intermediários'],
    completion_message: 'Os Doutores continuam ensinando. Volte sempre a eles.',
    program_slug: 'escola-dos-santos',
  },
  {
    slug: 'padres-da-igreja',
    title: 'Padres da Igreja',
    subtitle: 'A geração que fixou a fé apostólica.',
    track: 'santos-espiritualidade',
    category: 'santos',
    difficulty_level: 'intermediario',
    estimated_reading_time_minutes: 300,
    hero_quote: 'A tradição vem dos Apóstolos, faz parte da Escritura como sua exposição viva.',
    hero_quote_author: 'São Basílio Magno',
    learning_objectives: [
      'Situar Padres Apostólicos, Apologistas e Padres do Deserto',
      'Ler Inácio, Ireneu, Cipriano, Basílio, Crisóstomo, Ambrósio',
      'Compreender o desenvolvimento do dogma',
    ],
    recommended_for: ['Estudantes de teologia', 'Formadores'],
    completion_message: 'Os Padres são a voz viva da Igreja primitiva. Ouvi-los é ouvir Cristo.',
    program_slug: 'escola-dos-santos',
  },
  {
    slug: 'misticos-carmelitas',
    title: 'Místicos Carmelitas',
    subtitle: 'Teresa, João da Cruz, Teresinha, Edith Stein.',
    track: 'santos-espiritualidade',
    category: 'santos',
    difficulty_level: 'avancado',
    estimated_reading_time_minutes: 300,
    hero_quote: 'Nada te turbe, nada te espante; tudo passa, Deus não muda.',
    hero_quote_author: 'Santa Teresa de Ávila',
    learning_objectives: [
      'Percorrer as sete moradas do Castelo Interior',
      'Compreender a noite escura de São João da Cruz',
      'Aprender a "pequena via" de Santa Teresinha',
    ],
    recommended_for: ['Almas contemplativas'],
    completion_message: 'O Carmelo é escola de amor. Você é chamado a esse mesmo amor.',
    program_slug: 'escola-dos-santos',
  },
  {
    slug: 'santos-franciscanos',
    title: 'Santos Franciscanos',
    subtitle: 'A pobreza que gera fecundidade.',
    track: 'santos-espiritualidade',
    category: 'santos',
    difficulty_level: 'intermediario',
    estimated_reading_time_minutes: 180,
    hero_quote: 'Meu Deus e meu tudo.',
    hero_quote_author: 'São Francisco de Assis',
    learning_objectives: [
      'Conhecer Francisco, Clara, Antônio, Boaventura',
      'Compreender a espiritualidade da pobreza evangélica',
    ],
    recommended_for: ['Todos os fiéis'],
    completion_message: 'A pobreza franciscana é liberdade. Deixe Cristo ser seu tudo.',
    program_slug: 'escola-dos-santos',
  },
  {
    slug: 'santos-dominicanos',
    title: 'Santos Dominicanos',
    subtitle: 'Contemplar e transmitir aos outros o contemplado.',
    track: 'santos-espiritualidade',
    category: 'santos',
    difficulty_level: 'avancado',
    estimated_reading_time_minutes: 220,
    hero_quote: 'Contemplata aliis tradere.',
    hero_quote_author: 'Lema da Ordem dos Pregadores',
    learning_objectives: [
      'Conhecer Domingos, Tomás, Alberto Magno, Catarina de Sena',
      'Compreender a síntese entre estudo e pregação',
    ],
    recommended_for: ['Estudantes de teologia', 'Pregadores'],
    completion_message: 'A verdade contemplada torna-se palavra que evangeliza.',
    program_slug: 'escola-dos-santos',
  },
  {
    slug: 'grandes-missionarios',
    title: 'Grandes Missionários',
    subtitle: 'Levar Cristo até os confins da terra.',
    track: 'santos-espiritualidade',
    category: 'santos',
    difficulty_level: 'intermediario',
    estimated_reading_time_minutes: 180,
    hero_quote: 'Ai de mim se eu não evangelizar!',
    hero_quote_author: '1Cor 9,16',
    learning_objectives: [
      'Conhecer Francisco Xavier, Anchieta, Padre Vieira, Frei Damião',
      'Compreender o dinamismo missionário da Igreja',
    ],
    recommended_for: ['Missionários', 'Catequistas'],
    completion_message: 'A Igreja é missionária por natureza. Você também.',
    program_slug: 'escola-dos-santos',
  },
  {
    slug: 'santos-do-brasil',
    title: 'Santos do Brasil',
    subtitle: 'A santidade brotada em solo brasileiro.',
    track: 'santos-espiritualidade',
    category: 'santos',
    difficulty_level: 'iniciante',
    estimated_reading_time_minutes: 150,
    hero_quote: 'A messe é grande e os operários são poucos.',
    hero_quote_author: 'Mt 9,37',
    learning_objectives: [
      'Conhecer Frei Galvão, Madre Paulina, Irmã Dulce, Anchieta',
      'Reconhecer marcas da santidade brasileira',
    ],
    recommended_for: ['Todos os fiéis'],
    completion_message: 'A santidade é possível aqui, agora, em nosso chão.',
  },
  {
    slug: 'mulheres-doutoras',
    title: 'Mulheres Doutoras da Igreja',
    subtitle: 'Teresa, Catarina, Teresinha, Hildegarda.',
    track: 'santos-espiritualidade',
    category: 'santos',
    difficulty_level: 'intermediario',
    estimated_reading_time_minutes: 200,
    hero_quote: 'A alma é como um castelo todo de diamante.',
    hero_quote_author: 'Santa Teresa de Ávila',
    learning_objectives: [
      'Percorrer as 4 Doutoras proclamadas',
      'Reconhecer o gênio feminino no magistério espiritual',
    ],
    recommended_for: ['Todos os fiéis'],
    completion_message: 'A voz feminina da Igreja é indispensável. Continue ouvindo-a.',
  },

  // ── Liturgia ─────────────────────────────────────────────────────────
  {
    slug: 'advento',
    title: 'Advento',
    subtitle: 'Vigilância que espera o Senhor.',
    track: 'liturgia',
    category: 'liturgia',
    difficulty_level: 'iniciante',
    estimated_reading_time_minutes: 120,
    hero_quote: 'Vigiai, pois não sabeis em que dia vem o vosso Senhor.',
    hero_quote_author: 'Mt 24,42',
    learning_objectives: [
      'Compreender o tríplice sentido da vinda de Cristo',
      'Rezar cada semana do Advento',
    ],
    recommended_for: ['Todos os fiéis'],
    completion_message: 'Maranatha — vem, Senhor Jesus.',
    program_slug: 'escola-liturgica',
  },
  {
    slug: 'natal',
    title: 'Natal',
    subtitle: 'Deus se fez pequeno para nos alcançar.',
    track: 'liturgia',
    category: 'liturgia',
    difficulty_level: 'iniciante',
    estimated_reading_time_minutes: 90,
    hero_quote: 'E o Verbo se fez carne e habitou entre nós.',
    hero_quote_author: 'Jo 1,14',
    learning_objectives: [
      'Contemplar a encarnação em suas oitavas',
      'Rezar as festas litúrgicas do tempo natalino',
    ],
    recommended_for: ['Todos os fiéis'],
    completion_message: 'O Verbo continua nascendo em cada Eucaristia.',
    program_slug: 'escola-liturgica',
  },
  {
    slug: 'caminho-da-quaresma',
    title: 'Caminho da Quaresma',
    subtitle: '40 dias de conversão, oração e caridade.',
    track: 'liturgia',
    category: 'liturgia',
    difficulty_level: 'iniciante',
    estimated_reading_time_minutes: 200,
    hero_quote: 'Rasgai vossos corações e não vossas vestes.',
    hero_quote_author: 'Jl 2,13',
    learning_objectives: [
      'Viver oração, jejum e esmola como caminho de conversão',
      'Rezar a Via Sacra com fruto',
    ],
    recommended_for: ['Todos os fiéis'],
    completion_message: 'A Quaresma é caminho para a Páscoa. Continue a subir.',
    program_slug: 'escola-liturgica',
  },
  {
    slug: 'semana-santa',
    title: 'Semana Santa',
    subtitle: 'Os dias em que Cristo redime o mundo.',
    track: 'liturgia',
    category: 'liturgia',
    difficulty_level: 'intermediario',
    estimated_reading_time_minutes: 180,
    hero_quote: 'Amou-nos até o fim.',
    hero_quote_author: 'Jo 13,1',
    learning_objectives: [
      'Percorrer o Tríduo Pascal em profundidade',
      'Compreender a liturgia da Paixão e Ressurreição',
    ],
    recommended_for: ['Fiéis engajados na liturgia'],
    completion_message: 'A Cruz é a chave da história. Contemple-a sempre.',
    program_slug: 'escola-liturgica',
  },
  {
    slug: 'tempo-pascal',
    title: 'Tempo Pascal',
    subtitle: '50 dias de alegria: Cristo vive.',
    track: 'liturgia',
    category: 'liturgia',
    difficulty_level: 'iniciante',
    estimated_reading_time_minutes: 150,
    hero_quote: 'Ele não está aqui: ressuscitou!',
    hero_quote_author: 'Lc 24,6',
    learning_objectives: [
      'Rezar cada semana da Páscoa',
      'Compreender a Ascensão como plenitude da Páscoa',
    ],
    recommended_for: ['Todos os fiéis'],
    completion_message: 'A Páscoa se prolonga em cada dia da nossa vida.',
    program_slug: 'escola-liturgica',
  },
  {
    slug: 'pentecostes',
    title: 'Pentecostes',
    subtitle: 'O Espírito Santo funda a Igreja.',
    track: 'liturgia',
    category: 'liturgia',
    difficulty_level: 'iniciante',
    estimated_reading_time_minutes: 90,
    hero_quote: 'Recebei o Espírito Santo.',
    hero_quote_author: 'Jo 20,22',
    learning_objectives: [
      'Compreender os dons e frutos do Espírito',
      'Invocar o Espírito Santo na vida cotidiana',
    ],
    recommended_for: ['Todos os fiéis'],
    completion_message: 'O mesmo Espírito de Pentecostes age em você.',
    program_slug: 'escola-liturgica',
  },
  {
    slug: 'ano-liturgico',
    title: 'Ano Litúrgico',
    subtitle: 'O tempo santificado pela Igreja.',
    track: 'liturgia',
    category: 'liturgia',
    difficulty_level: 'intermediario',
    estimated_reading_time_minutes: 180,
    learning_objectives: [
      'Percorrer os tempos: Advento, Natal, Comum, Quaresma, Pascal',
      'Compreender santoral e mistérios do Senhor',
    ],
    recommended_for: ['Catequistas', 'Liturgistas'],
    completion_message: 'Cada ano é uma nova imersão no mistério de Cristo.',
    program_slug: 'escola-liturgica',
  },
  {
    slug: 'a-santa-missa',
    title: 'A Santa Missa',
    subtitle: 'O sacrifício e a comunhão que sustentam a Igreja.',
    track: 'liturgia',
    category: 'liturgia',
    difficulty_level: 'intermediario',
    estimated_reading_time_minutes: 180,
    hero_quote: 'Fazei isto em memória de mim.',
    hero_quote_author: 'Lc 22,19',
    learning_objectives: [
      'Compreender cada parte da Missa e seu significado',
      'Participar frutuosamente da liturgia eucarística',
    ],
    recommended_for: ['Todos os fiéis'],
    completion_message: 'A Missa é o coração da Igreja. Volte sempre a ela.',
    program_slug: 'escola-liturgica',
  },

  // ── Vida Cristã ──────────────────────────────────────────────────────
  {
    slug: 'virtudes',
    title: 'Virtudes',
    subtitle: 'Fé, esperança, caridade, prudência, justiça, fortaleza, temperança.',
    track: 'vida-crista',
    category: 'vida-crista',
    difficulty_level: 'intermediario',
    estimated_reading_time_minutes: 180,
    hero_quote: 'A virtude é uma disposição habitual e firme para fazer o bem.',
    hero_quote_author: 'CIC 1803',
    learning_objectives: [
      'Distinguir virtudes teologais e cardeais',
      'Cultivar hábitos concretos de virtude',
    ],
    recommended_for: ['Todos os fiéis'],
    completion_message: 'A virtude se aprende praticando. Comece hoje.',
  },
  {
    slug: 'vida-interior',
    title: 'Vida Interior',
    subtitle: 'A morada de Deus dentro de nós.',
    track: 'vida-crista',
    category: 'vida-crista',
    difficulty_level: 'intermediario',
    estimated_reading_time_minutes: 180,
    hero_quote: 'Não sabeis que sois templo de Deus?',
    hero_quote_author: '1Cor 3,16',
    learning_objectives: [
      'Cultivar silêncio, recolhimento e oração pessoal',
      'Aprender a lutar contra distrações e tibieza',
    ],
    recommended_for: ['Todos os fiéis'],
    completion_message: 'A vida interior é o segredo dos santos. É também o seu.',
    program_slug: 'escola-da-oracao',
  },
  {
    slug: 'oracao',
    title: 'Oração',
    subtitle: 'Elevação da alma a Deus.',
    track: 'vida-crista',
    category: 'vida-crista',
    difficulty_level: 'iniciante',
    estimated_reading_time_minutes: 120,
    hero_quote: 'Senhor, ensina-nos a orar.',
    hero_quote_author: 'Lc 11,1',
    learning_objectives: [
      'Percorrer as formas de oração: vocal, meditativa, contemplativa',
      'Rezar o Pai-Nosso com profundidade',
    ],
    recommended_for: ['Todos os fiéis'],
    completion_message: 'Orar é possível — e necessário. Continue conversando com Deus.',
    program_slug: 'escola-da-oracao',
  },
  {
    slug: 'discernimento',
    title: 'Discernimento',
    subtitle: 'Reconhecer a voz de Deus em meio às vozes.',
    track: 'vida-crista',
    category: 'vida-crista',
    difficulty_level: 'avancado',
    estimated_reading_time_minutes: 180,
    hero_quote: 'Provai os espíritos, para ver se são de Deus.',
    hero_quote_author: '1Jo 4,1',
    learning_objectives: [
      'Compreender as regras de discernimento de Santo Inácio',
      'Distinguir consolação e desolação espiritual',
    ],
    recommended_for: ['Fiéis em busca de decisões importantes'],
    completion_message: 'Deus fala. Aprenda a ouvi-lo em silêncio.',
  },
  {
    slug: 'eucaristia',
    title: 'Eucaristia',
    subtitle: 'Fonte e ápice de toda vida cristã.',
    track: 'vida-crista',
    category: 'vida-crista',
    difficulty_level: 'intermediario',
    estimated_reading_time_minutes: 150,
    hero_quote: 'Quem come a minha carne e bebe o meu sangue permanece em mim e eu nele.',
    hero_quote_author: 'Jo 6,56',
    learning_objectives: [
      'Compreender a presença real de Cristo',
      'Preparar-se para a Comunhão',
    ],
    recommended_for: ['Todos os fiéis'],
    completion_message: 'Cada Eucaristia é o Céu antecipado. Comungue com fé.',
  },
  {
    slug: 'confissao',
    title: 'Confissão',
    subtitle: 'O sacramento da misericórdia.',
    track: 'vida-crista',
    category: 'vida-crista',
    difficulty_level: 'iniciante',
    estimated_reading_time_minutes: 90,
    hero_quote: 'Recebei o Espírito Santo. A quem perdoardes os pecados, ser-lhes-ão perdoados.',
    hero_quote_author: 'Jo 20,22-23',
    learning_objectives: [
      'Fazer um bom exame de consciência',
      'Compreender contrição, confissão e satisfação',
    ],
    recommended_for: ['Todos os fiéis'],
    completion_message: 'Nunca desanime. A misericórdia de Deus é maior que sua queda.',
  },
  {
    slug: 'familia-crista',
    title: 'Família Cristã',
    subtitle: 'Igreja doméstica.',
    track: 'vida-crista',
    category: 'vida-crista',
    difficulty_level: 'iniciante',
    estimated_reading_time_minutes: 150,
    hero_quote: 'Quanto a mim e à minha casa, serviremos ao Senhor.',
    hero_quote_author: 'Js 24,15',
    learning_objectives: [
      'Viver o matrimônio como sacramento',
      'Educar os filhos na fé',
    ],
    recommended_for: ['Esposos', 'Pais e mães'],
    completion_message: 'A família é a primeira escola de fé. Zele por ela.',
  },
  {
    slug: 'santidade-no-cotidiano',
    title: 'Santidade no Cotidiano',
    subtitle: 'A santidade é para todos — inclusive para você.',
    track: 'vida-crista',
    category: 'vida-crista',
    difficulty_level: 'iniciante',
    estimated_reading_time_minutes: 120,
    hero_quote: 'Sede perfeitos como perfeito é vosso Pai celeste.',
    hero_quote_author: 'Mt 5,48',
    learning_objectives: [
      'Reconhecer o chamado universal à santidade (LG 5)',
      'Santificar trabalho, descanso e relacionamentos',
    ],
    recommended_for: ['Todos os fiéis'],
    completion_message: 'A santidade se faz nas pequenas coisas. Comece agora.',
  },
];

export function findOfficialCollection(slug: string): OfficialCollectionSeed | undefined {
  return OFFICIAL_COLLECTIONS.find((c) => c.slug === slug);
}
