import React, { forwardRef } from 'react';
import { 
  Activity,
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  Anchor,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  Award,
  BarChart,
  Bell,
  Bird,
  Book,
  BookMarked,
  BookOpen,
  BookText,
  Bookmark,
  Brain,
  Building2,
  Calendar,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Church,
  Circle,
  Clock,
  Code,
  Coffee,
  Columns,
  Compass,
  Contrast,
  Copy,
  CornerRightUp,
  CreditCard,
  Cross,
  Crown,
  Database,
  Disc,
  DollarSign,
  Dot,
  Download,
  Droplets,
  Edit,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  Feather,
  FileCode,
  FileDown,
  FileSpreadsheet,
  FileText,
  Filter,
  Flame,
  FlaskConical,
  Frown,
  Globe,
  Grid,
  GripVertical,
  Hand,
  Handshake,
  Hash,
  Headphones,
  Heart,
  HelpCircle,
  Highlighter,
  History,
  Home,
  Image,
  Info,
  Instagram,
  Key,
  Languages,
  Layers,
  Layout,
  LayoutGrid,
  LayoutPanelLeft,
  Library,
  Lightbulb,
  LineChart,
  Link,
  List,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  Maximize2,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Minimize2,
  Minus,
  MonitorSmartphone,
  Moon,
  MoreHorizontal,
  Mountain,
  Music,
  Orbit,
  Palette,
  PartyPopper,
  Pause,
  PenLine,
  PenTool,
  Pin,
  Play,
  Plus,
  Printer,
  Quote,
  RefreshCcw,
  RefreshCw,
  RotateCcw,
  Route,
  Save,
  ScrollText,
  Search,
  Send,
  Settings,
  Settings2,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldQuestion,
  Shuffle,
  Skull,
  Smartphone,
  Sparkle,
  Sparkles,
  Square,
  Star,
  Stethoscope,
  StopCircle,
  Store,
  Sun,
  Swords,
  Tag,
  Target,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Twitter,
  Type,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserMinus,
  UserPlus,
  Users,
  Video,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Wallet,
  Wheat,
  Wifi,
  WifiOff,
  Wind,
  Wine,
  X,
  XCircle,
  Youtube,
  Zap,
  ZapOff
} from 'lucide-react';


import { cn } from './lib/utils';
import { AppRoute } from './types';

export const COLORS = {
  primary: '#0F172A',
  secondary: '#D4AF37',
  background: '#F8F5EE',
  text: '#0F172A',
  accent: '#D4AF37',
};

export const NAV_ITEMS = (t: (key: string) => string, lang: string) => [
  { label: lang === 'pt' ? 'Início' : 'Home', icon: 'Home', route: '/' },
  { label: lang === 'pt' ? 'Bíblia' : 'Bible', icon: 'Bible', route: AppRoute.BIBLE },
  { label: lang === 'pt' ? 'Catecismo' : 'Catechism', icon: 'Catechism', route: AppRoute.CATECHISM },
  { label: lang === 'pt' ? 'Santos' : 'Saints', icon: 'Saints', route: AppRoute.SAINTS },
  { label: t('menu') || 'Menu', icon: 'Menu', isMenu: true },
];

import cathedraLogo from './assets/cathedra-logo.webp';

export const Logo = forwardRef<HTMLDivElement, { className?: string, variant?: 'gold' | 'light' | 'dark' | 'blue' }>(({ 
  className = "w-spacing-2xl h-spacing-2xl", 
  variant = 'gold' 
}, ref) => {
  return (
    <div ref={ref} className={cn(
      "relative flex items-center justify-center group overflow-hidden", 
      variant === 'blue' && "bg-primary rounded-premium-full p-spacing-xs border border-primary/10 dark:bg-primary/20",
      className
    )}>
      <img 
        src={cathedraLogo} 
        alt="Cathedra - Digital Sanctuarium" 
        loading="lazy"
        width="64"
        height="64"
        className={cn(
          "w-full h-full object-contain transition-all duration-1000 group-hover:scale-105",
          variant === 'light' && "brightness-0 invert opacity-80",
          variant === 'dark' && "brightness-0 opacity-80",
          variant === 'blue' && "brightness-0 invert"
        )}
      />
      {variant === 'gold' && (
        <div className="absolute inset-0 bg-secondary/5 rounded-premium-full -z-10 opacity-0 group-hover:opacity-100 transition-opacity duration-1000" />
      )}
    </div>
  );
});

Logo.displayName = 'Logo';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  size?: number | string;
  strokeWidth?: number;
}

const createIcon = (IconComponent: any) => 
  forwardRef<SVGSVGElement, IconProps>(({ className, strokeWidth, size, 'aria-hidden': ariaHidden, 'aria-label': ariaLabel, ...props }, ref) => (
    <IconComponent 
      ref={ref} 
      strokeWidth={strokeWidth || 1.2} 
      size={size || 20}
      className={cn("transition-all duration-1000 shrink-0", className)}
      aria-hidden={ariaHidden ?? (ariaLabel ? undefined : "true")}
      aria-label={ariaLabel}
      role={ariaLabel ? "img" : undefined}
      {...props} 
    />
  ));

const IconsInternal = {
  Logo: Logo,
  Activity: createIcon(Activity),
  AlertCircle: createIcon(AlertCircle),
  AlertTriangle: createIcon(AlertTriangle),
  AlignCenter: createIcon(AlignCenter),
  AlignJustify: createIcon(AlignJustify),
  AlignLeft: createIcon(AlignLeft),
  Anchor: createIcon(Anchor),
  ArrowDown: createIcon(ArrowDown),
  ArrowLeft: createIcon(ArrowLeft),
  ArrowRight: createIcon(ArrowRight),
  ArrowUp: createIcon(ArrowUp),
  ArrowUpDown: createIcon(ArrowUpDown),
  ArrowUpRight: createIcon(ArrowUpRight),
  Award: createIcon(Award),
  Bell: createIcon(Bell),
  Bird: createIcon(Bird),
  Book: createIcon(Book),
  BookMarked: createIcon(BookMarked),
  BookOpen: createIcon(BookOpen),
  BookText: createIcon(BookText),
  Bookmark: createIcon(Bookmark),
  Brain: createIcon(Brain),
  Building2: createIcon(Building2),
  Calendar: createIcon(Calendar),
  Check: createIcon(Check),
  CheckCircle: createIcon(CheckCircle),
  CheckCircle2: createIcon(CheckCircle2),
  ChevronDown: createIcon(ChevronDown),
  ChevronLeft: createIcon(ChevronLeft),
  ChevronRight: createIcon(ChevronRight),
  ChevronUp: createIcon(ChevronUp),
  Church: createIcon(Church),
  Circle: createIcon(Circle),
  Clock: createIcon(Clock),
  Code: createIcon(Code),
  Coffee: createIcon(Coffee),
  Columns: createIcon(Columns),
  Compass: createIcon(Compass),
  Contrast: createIcon(Contrast),
  Copy: createIcon(Copy),
  CornerRightUp: createIcon(CornerRightUp),
  CreditCard: createIcon(CreditCard),
  Cross: createIcon(Cross),
  Crown: createIcon(Crown),
  Database: createIcon(Database),
  Disc: createIcon(Disc),
  DollarSign: createIcon(DollarSign),
  Dot: createIcon(Dot),
  Download: createIcon(Download),
  Droplets: createIcon(Droplets),
  Edit: createIcon(Edit),
  Edit2: createIcon(Edit2),
  Edit3: createIcon(Edit3),
  ExternalLink: createIcon(ExternalLink),
  Eye: createIcon(Eye),
  EyeOff: createIcon(EyeOff),
  Facebook: createIcon(Facebook),
  Feather: createIcon(Feather),
  FileCode: createIcon(FileCode),
  FileDown: createIcon(FileDown),
  FileSpreadsheet: createIcon(FileSpreadsheet),
  FileText: createIcon(FileText),
  Filter: createIcon(Filter),
  Flame: createIcon(Flame),
  FlaskConical: createIcon(FlaskConical),
  Frown: createIcon(Frown),
  Globe: createIcon(Globe),
  Grid: createIcon(Grid),
  GripVertical: createIcon(GripVertical),
  Hand: createIcon(Hand),
  Handshake: createIcon(Handshake),
  Hash: createIcon(Hash),
  Headphones: createIcon(Headphones),
  Heart: createIcon(Heart),
  HelpCircle: createIcon(HelpCircle),
  Highlighter: createIcon(Highlighter),
  History: createIcon(History),
  Home: createIcon(Home),
  Image: createIcon(Image),
  Info: createIcon(Info),
  Instagram: createIcon(Instagram),
  Key: createIcon(Key),
  Languages: createIcon(Languages),
  Layers: createIcon(Layers),
  Layout: createIcon(Layout),
  LayoutGrid: createIcon(LayoutGrid),
  LayoutPanelLeft: createIcon(LayoutPanelLeft),
  Library: createIcon(Library),
  Lightbulb: createIcon(Lightbulb),
  LineChart: createIcon(LineChart),
  Link: createIcon(Link),
  List: createIcon(List),
  Loader2: createIcon(Loader2),
  Lock: createIcon(Lock),
  LogOut: createIcon(LogOut),
  Mail: createIcon(Mail),
  Map: createIcon(Map),
  MapPin: createIcon(MapPin),
  Maximize2: createIcon(Maximize2),
  Megaphone: createIcon(Megaphone),
  Menu: createIcon(Menu),
  MessageCircle: createIcon(MessageCircle),
  MessageSquare: createIcon(MessageSquare),
  Minimize2: createIcon(Minimize2),
  Minus: createIcon(Minus),
  MonitorSmartphone: createIcon(MonitorSmartphone),
  Moon: createIcon(Moon),
  MoreHorizontal: createIcon(MoreHorizontal),
  Mountain: createIcon(Mountain),
  Music: createIcon(Music),
  Orbit: createIcon(Orbit),
  Palette: createIcon(Palette),
  PartyPopper: createIcon(PartyPopper),
  Pause: createIcon(Pause),
  PenLine: createIcon(PenLine),
  PenTool: createIcon(PenTool),
  Pin: createIcon(Pin),
  Play: createIcon(Play),
  Plus: createIcon(Plus),
  Printer: createIcon(Printer),
  Quote: createIcon(Quote),
  RefreshCcw: createIcon(RefreshCcw),
  RefreshCw: createIcon(RefreshCw),
  RotateCcw: createIcon(RotateCcw),
  Route: createIcon(Route),
  Save: createIcon(Save),
  ScrollText: createIcon(ScrollText),
  Search: createIcon(Search),
  Send: createIcon(Send),
  Settings: createIcon(Settings),
  Settings2: createIcon(Settings2),
  Share2: createIcon(Share2),
  Shield: createIcon(Shield),
  ShieldAlert: createIcon(ShieldAlert),
  ShieldCheck: createIcon(ShieldCheck),
  ShieldQuestion: createIcon(ShieldQuestion),
  Shuffle: createIcon(Shuffle),
  Skull: createIcon(Skull),
  Smartphone: createIcon(Smartphone),
  Sparkle: createIcon(Sparkle),
  Sparkles: createIcon(Sparkles),
  Square: createIcon(Square),
  Star: createIcon(Star),
  Stethoscope: createIcon(Stethoscope),
  StopCircle: createIcon(StopCircle),
  Store: createIcon(Store),
  Sun: createIcon(Sun),
  Swords: createIcon(Swords),
  Tag: createIcon(Tag),
  Target: createIcon(Target),
  Timer: createIcon(Timer),
  Trash2: createIcon(Trash2),
  TrendingDown: createIcon(TrendingDown),
  TrendingUp: createIcon(TrendingUp),
  Trophy: createIcon(Trophy),
  Twitter: createIcon(Twitter),
  Type: createIcon(Type),
  Upload: createIcon(Upload),
  User: createIcon(User),
  UserCheck: createIcon(UserCheck),
  UserCog: createIcon(UserCog),
  UserMinus: createIcon(UserMinus),
  UserPlus: createIcon(UserPlus),
  Users: createIcon(Users),
  Video: createIcon(Video),
  Volume: createIcon(Volume),
  Volume1: createIcon(Volume1),
  Volume2: createIcon(Volume2),
  VolumeX: createIcon(VolumeX),
  Wallet: createIcon(Wallet),
  Wheat: createIcon(Wheat),
  Wifi: createIcon(Wifi),
  WifiOff: createIcon(WifiOff),
  Wind: createIcon(Wind),
  Wine: createIcon(Wine),
  X: createIcon(X),
  XCircle: createIcon(XCircle),
  Youtube: createIcon(Youtube),
  Zap: createIcon(Zap),
  ZapOff: createIcon(ZapOff)
};


export const Icons = {
  ...IconsInternal,
  
  // Semantic Aliases & Compatibility
  Dashboard: IconsInternal.LayoutGrid,
  Creator: IconsInternal.Crown,
  Notifications: IconsInternal.Bell,
  Help: IconsInternal.HelpCircle,
  Bible: IconsInternal.BookOpen,
  HolyBible: IconsInternal.BookOpen,
  Catechism: IconsInternal.Book,
  CatechismShield: IconsInternal.ShieldCheck,
  Magisterium: IconsInternal.ScrollText,
  MagisteriumGlobe: IconsInternal.Globe,
  Saints: IconsInternal.Flame,
  SaintHalo: IconsInternal.Flame,
  Aquinas: IconsInternal.Feather,
  Scroll: IconsInternal.ScrollText,
  Glossary: IconsInternal.BookMarked,
  AZ: IconsInternal.Languages,
  Themes: IconsInternal.Layers,
  Liturgy: IconsInternal.Wine,
  DailyLiturgy: IconsInternal.Sun,
  Chalice: IconsInternal.Wine,
  Lectio: IconsInternal.Flame,
  PrayingHands: IconsInternal.Hand,
  Rosary: IconsInternal.Orbit,
  ViaCrucis: IconsInternal.Cross,
  Church: IconsInternal.Home,
  LiturgicalCalendar: IconsInternal.Calendar,
  Oracao: IconsInternal.Hand,
  Journeys: IconsInternal.Route,
  JourneysMap: IconsInternal.Map,
  Flag: IconsInternal.Award,
  Certamen: IconsInternal.Trophy,
  Community: IconsInternal.Users,
  Message: IconsInternal.MessageCircle,
  Share: IconsInternal.Share2,
  Audio: IconsInternal.Volume2,
  Maximize: IconsInternal.Maximize2,
  Minimize: IconsInternal.Minimize2,
  Trash: IconsInternal.Trash2,
  CheckCircle: IconsInternal.CheckCircle2,
  Loader: IconsInternal.Loader2,
  Whatsapp: IconsInternal.MessageCircle,
  Google: IconsInternal.Globe,
  Apple: IconsInternal.Smartphone,
  PanelLeft: IconsInternal.Layout, 
  ImageIcon: IconsInternal.Image,
  Stop: IconsInternal.StopCircle,
  StopCircle: IconsInternal.StopCircle,
};

if (import.meta.env.DEV) {
  const iconKeys = Object.keys(Icons);
  const duplicates = iconKeys.filter((key, index) => iconKeys.indexOf(key) !== index);
  if (duplicates.length > 0) {
    console.warn('Duplicate icon keys found in constants:', duplicates);
  }
}
