import React, { forwardRef } from 'react';
import { 
  Home,
  Book,
  BookOpen, 
  BookText,
  Cross, 
  Map, 
  Users, 
  Flame, 
  Sparkle, 
  FileText, 
  Database,
  Type, 
  Columns,
  Search,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Star,
  MessageCircle,
  Zap,
  Layout,
  Globe,
  ExternalLink,
  Pin,
  Heart,
  Download,
  RotateCcw,
  Instagram,
  Facebook,
  Twitter,
  Youtube,
  Menu,
  Feather,
  History,
  Volume2,
  Volume1,
  Volume,
  Square,
  Brain,
  Sparkles,
  User,
  Crown,
  ArrowDown,
  ArrowLeft,
  Music,
  Bell,
  Sun,
  Moon,
  LogOut,
  PenLine,
  Calendar,
  Compass,
  Loader2,
  Award,
  ArrowRight,
  Quote,
  Share2,
  Check,
  Circle,
  Dot,
  X,
  ShieldQuestion,
  MessageSquare,
  Send,
  Trophy,
  ShieldCheck,
  Clock,
  CheckCircle2,
  PenTool,
  Copy,
  Plus,
  Trash2,
  GripVertical,
  Lock,
  HelpCircle,
  PartyPopper,
  MoreHorizontal,
  Coffee,
  Church,
  Bookmark,
  Smartphone,
  MonitorSmartphone,
  Activity,
  UserCog,
  LayoutGrid,
  UserCheck,
  Stethoscope,
  Route, 
  Library, 
  Hand,
  Handshake,
  ScrollText,
  Swords,
  Mail,
  Settings,
  Info,
  Maximize2,
  Minimize2,
  List,
  Grid,
  Filter,
  Eye,
  EyeOff,
  AlertTriangle,
  XCircle,
  CreditCard,
  WifiOff,
  Wine,
  Play,
  Target,
  Link,
  Video,
  Tag,
  Orbit,
  Disc,
  Layers,
  Languages,
  BookMarked,
  Wifi,
  Printer,
  UserMinus,
  Edit2,
  AlertCircle,
  Anchor,
  ArrowUpDown,
  ArrowUpRight,
  Bird,
  CheckCircle,
  Contrast,
  CornerRightUp,
  Droplets,
  FileCode,
  FileDown,
  FlaskConical,
  Frown,
  Headphones,
  Highlighter,
  Key,
  LayoutPanelLeft,
  Lightbulb,
  Megaphone,
  Mountain,
  Pause,
  RefreshCcw,
  RefreshCw,
  Save,
  Settings2,
  ShieldAlert,
  Skull,
  StopCircle,
  Store,
  TrendingUp,
  Wheat,
  Wind,
  ZapOff,
  Building2,
  DollarSign,
  Upload,
  FileSpreadsheet,
  ArrowUp,
  Minus,
  TrendingDown,
  UserPlus,
  Palette,
  Wallet,
  Edit,
  Edit3,
  AlignLeft,
  Timer,
  Image,
  Code,
  MapPin,
  LineChart
} from 'lucide-react';

import { cn } from './lib/utils';
import { AppRoute } from './types';

export const COLORS = {
  primary: '#0F172A',
  secondary: '#D4AF37',
  background: '#F8F5EE',
  text: '#0F172A',
  accent: '#D4AF37',
};

export const NAV_ITEMS = (t: (key: string) => string, lang: string) => [
  { label: lang === 'pt' ? 'Início' : 'Home', icon: 'Home', route: '/' },
  { label: lang === 'pt' ? 'Bíblia' : 'Bible', icon: 'Bible', route: AppRoute.BIBLE },
  { label: lang === 'pt' ? 'Catecismo' : 'Catechism', icon: 'Catechism', route: AppRoute.CATECHISM },
  { label: 'Logos', icon: 'Sparkles', route: '/logos' },
  { label: t('menu') || 'Menu', icon: 'Menu', isMenu: true },
];

import cathedraLogo from './assets/cathedra-logo.png';

export const Logo = forwardRef<HTMLDivElement, { className?: string, variant?: 'gold' | 'light' | 'dark' | 'blue' }>(({ 
  className = "w-spacing-2xl h-spacing-2xl", 
  variant = 'gold' 
}, ref) => {
  return (
    <div ref={ref} className={cn(
      "relative flex items-center justify-center group overflow-hidden", 
      variant === 'blue' && "bg-primary rounded-premium-full p-spacing-xs border border-primary/10 dark:bg-primary/20",
      className
    )}>
      <img 
        src={cathedraLogo} 
        alt="Cathedra" 
        className={cn(
          "w-full h-full object-contain transition-all duration-1000 group-hover:scale-105",
          variant === 'light' && "brightness-0 invert opacity-80",
          variant === 'dark' && "brightness-0 opacity-80",
          variant === 'blue' && "brightness-0 invert"
        )}
      />
      {variant === 'gold' && (
        <div className="absolute inset-0 bg-secondary/5 rounded-premium-full -z-10 opacity-0 group-hover:opacity-100 transition-opacity duration-1000" />
      )}
    </div>
  );
});

Logo.displayName = 'Logo';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  size?: number | string;
  strokeWidth?: number;
}

const createIcon = (IconComponent: any) => 
  forwardRef<SVGSVGElement, IconProps>(({ className, strokeWidth, size, 'aria-hidden': ariaHidden, 'aria-label': ariaLabel, ...props }, ref) => (
    <IconComponent 
      ref={ref} 
      strokeWidth={strokeWidth || 1.2} 
      size={size || 20}
      className={cn("transition-all duration-1000 shrink-0", className)}
      aria-hidden={ariaHidden ?? (ariaLabel ? undefined : "true")}
      aria-label={ariaLabel}
      role={ariaLabel ? "img" : undefined}
      {...props} 
    />
  ));


// Semantic Groups for better organization
// Internal icon components to ensure consistency
const IconsInternal = {
  Logo: Logo,
  Home: createIcon(Church),
  Dashboard: createIcon(LayoutGrid),
  Layout: createIcon(Layout),
  Menu: createIcon(Menu),
  Search: createIcon(Search),
  Settings: createIcon(Settings),
  Database: createIcon(Database),
  User: createIcon(User),
  Creator: createIcon(Crown),
  UserCog: createIcon(UserCog),
  LogOut: createIcon(LogOut),
  Bell: createIcon(Bell),
  Calendar: createIcon(Calendar),
  Clock: createIcon(Clock),
  HelpCircle: createIcon(HelpCircle),
  Info: createIcon(Info),
  Plus: createIcon(Plus),
  X: createIcon(X),
  Check: createIcon(Check),
  Circle: createIcon(Circle),
  Dot: createIcon(Dot),
  Award: createIcon(Award),
  Trophy: createIcon(Trophy),
  Star: createIcon(Star),
  Heart: createIcon(Heart),
  Zap: createIcon(Zap),
  Globe: createIcon(Globe),
  Handshake: createIcon(Handshake),
  ShieldCheck: createIcon(ShieldCheck),
  ShieldQuestion: createIcon(ShieldQuestion),
  PartyPopper: createIcon(PartyPopper),
  BookText: createIcon(BookText),
  Book: createIcon(Book),
  BookOpen: createIcon(BookOpen),
  Library: createIcon(Library),
  FileText: createIcon(FileText),
  ScrollText: createIcon(ScrollText),
  Columns: createIcon(Columns),
  Brain: createIcon(Brain),
  Feather: createIcon(Feather),
  PenLine: createIcon(PenLine),
  PenTool: createIcon(PenTool),
  Quote: createIcon(Quote),
  Type: createIcon(Type),
  BookMarked: createIcon(BookMarked),
  Languages: createIcon(Languages),
  History: createIcon(History),
  Bookmark: createIcon(Bookmark),
  Tag: createIcon(Tag),
  Swords: createIcon(Swords),
  Cross: createIcon(Cross),
  Sun: createIcon(Sun),
  Moon: createIcon(Moon),
  Wine: createIcon(Wine),
  Flame: createIcon(Flame),
  Sparkle: createIcon(Sparkle),
  Sparkles: createIcon(Sparkles),
  Hand: createIcon(Hand),
  Orbit: createIcon(Orbit),
  Map: createIcon(Map),
  Compass: createIcon(Compass),
  Route: createIcon(Route),
  Target: createIcon(Target),
  Activity: createIcon(Activity),
  Stethoscope: createIcon(Stethoscope),
  Users: createIcon(Users),
  UserCheck: createIcon(UserCheck),
  MessageCircle: createIcon(MessageCircle),
  MessageSquare: createIcon(MessageSquare),
  Send: createIcon(Send),
  Share2: createIcon(Share2),
  ExternalLink: createIcon(ExternalLink),
  Link: createIcon(Link),
  Mail: createIcon(Mail),
  Volume2: createIcon(Volume2),
  Volume1: createIcon(Volume1),
  Volume: createIcon(Volume),
  Play: createIcon(Play),
  Square: createIcon(Square),
  Music: createIcon(Music),
  Download: createIcon(Download),
  RotateCcw: createIcon(RotateCcw),
  Maximize2: createIcon(Maximize2),
  Minimize2: createIcon(Minimize2),
  ChevronLeft: createIcon(ChevronLeft),
  ChevronRight: createIcon(ChevronRight),
  ChevronDown: createIcon(ChevronDown),
  ChevronUp: createIcon(ChevronUp),
  ArrowLeft: createIcon(ArrowLeft),
  ArrowRight: createIcon(ArrowRight),
  ArrowDown: createIcon(ArrowDown),
  Video: createIcon(Video),
  Copy: createIcon(Copy),
  Trash2: createIcon(Trash2),
  GripVertical: createIcon(GripVertical),
  Lock: createIcon(Lock),
  Pin: createIcon(Pin),
  Filter: createIcon(Filter),
  List: createIcon(List),
  Grid: createIcon(Grid),
  Eye: createIcon(Eye),
  EyeOff: createIcon(EyeOff),
  AlertTriangle: createIcon(AlertTriangle),
  XCircle: createIcon(XCircle),
  CheckCircle2: createIcon(CheckCircle2),
  Loader2: createIcon(Loader2),
  CreditCard: createIcon(CreditCard),
  Smartphone: createIcon(Smartphone),
  MonitorSmartphone: createIcon(MonitorSmartphone),
  WifiOff: createIcon(WifiOff),
  Wifi: createIcon(Wifi),
  Instagram: createIcon(Instagram),
  Facebook: createIcon(Facebook),
  Twitter: createIcon(Twitter),
  Youtube: createIcon(Youtube),
  Printer: createIcon(Printer),
  Layers: createIcon(Layers),
  PanelLeft: createIcon(Layout),
  Hash: createIcon(Type),
  Shield: createIcon(ShieldCheck),
  VolumeX: createIcon(Volume),
  Coffee: createIcon(Coffee),
  UserMinus: createIcon(UserMinus),
  Edit2: createIcon(Edit2),
  AlertCircle: createIcon(AlertCircle),
  Anchor: createIcon(Anchor),
  ArrowUpDown: createIcon(ArrowUpDown),
  ArrowUpRight: createIcon(ArrowUpRight),
  Bird: createIcon(Bird),
  CheckCircle: createIcon(CheckCircle),
  Contrast: createIcon(Contrast),
  CornerRightUp: createIcon(CornerRightUp),
  Droplets: createIcon(Droplets),
  FileCode: createIcon(FileCode),
  FileDown: createIcon(FileDown),
  FlaskConical: createIcon(FlaskConical),
  Frown: createIcon(Frown),
  Headphones: createIcon(Headphones),
  Highlighter: createIcon(Highlighter),
  Key: createIcon(Key),
  LayoutPanelLeft: createIcon(LayoutPanelLeft),
  Lightbulb: createIcon(Lightbulb),
  Megaphone: createIcon(Megaphone),
  Mountain: createIcon(Mountain),
  Pause: createIcon(Pause),
  RefreshCcw: createIcon(RefreshCcw),
  RefreshCw: createIcon(RefreshCw),
  Save: createIcon(Save),
  Settings2: createIcon(Settings2),
  ShieldAlert: createIcon(ShieldAlert),
  Skull: createIcon(Skull),
  StopCircle: createIcon(StopCircle),
  Store: createIcon(Store),
  TrendingUp: createIcon(TrendingUp),
  Wheat: createIcon(Wheat),
  Wind: createIcon(Wind),
  ZapOff: createIcon(ZapOff),
  MoreHorizontal: createIcon(MoreHorizontal),
  Building2: createIcon(Building2),
  DollarSign: createIcon(DollarSign),
  Upload: createIcon(Upload),
  FileSpreadsheet: createIcon(FileSpreadsheet),
  ArrowUp: createIcon(ArrowUp),
  Minus: createIcon(Minus),
  TrendingDown: createIcon(TrendingDown),
  UserPlus: createIcon(UserPlus),
  Palette: createIcon(Palette),
  Wallet: createIcon(Wallet),
  Edit: createIcon(Edit),
  MapPin: createIcon(Pin),
  LineChart: createIcon(Activity),
};


// Semantic Groups for better organization
export const Icons = {
  ...IconsInternal,
  Logo: IconsInternal.Logo,

  
  // Navigation & Core
  Home: IconsInternal.Home,
  Dashboard: IconsInternal.Dashboard,
  LayoutGrid: IconsInternal.Dashboard,
  Layout: IconsInternal.Layout,
  Menu: IconsInternal.Menu,
  Search: IconsInternal.Search,
  Settings: IconsInternal.Settings,
  Database: IconsInternal.Database,
  User: IconsInternal.User,
  Creator: IconsInternal.Creator,
  UserCog: IconsInternal.UserCog,
  LogOut: IconsInternal.LogOut,
  Notifications: IconsInternal.Bell,
  Bell: IconsInternal.Bell,
  Calendar: IconsInternal.Calendar,
  Clock: IconsInternal.Clock,
  Help: IconsInternal.HelpCircle,
  HelpCircle: IconsInternal.HelpCircle,
  Info: IconsInternal.Info,
  Plus: IconsInternal.Plus,
  X: IconsInternal.X,
  Check: IconsInternal.Check,
  Circle: IconsInternal.Circle,
  Dot: IconsInternal.Dot,
  Award: IconsInternal.Award,
  Trophy: IconsInternal.Trophy,
  Star: IconsInternal.Star,
  Heart: IconsInternal.Heart,
  Zap: IconsInternal.Zap,
  Globe: IconsInternal.Globe,
  Handshake: IconsInternal.Handshake,
  ShieldCheck: IconsInternal.ShieldCheck,
  ShieldQuestion: IconsInternal.ShieldQuestion,
  PartyPopper: IconsInternal.PartyPopper,
  
  // Library & Study
  Bible: IconsInternal.BookOpen,
  HolyBible: IconsInternal.BookOpen,
  Book: IconsInternal.Book,
  BookOpen: IconsInternal.BookOpen,
  Library: IconsInternal.Library,
  Catechism: IconsInternal.Book,
  CatechismShield: IconsInternal.ShieldCheck,
  FileText: IconsInternal.FileText,
  Magisterium: IconsInternal.ScrollText,
  MagisteriumGlobe: IconsInternal.Globe,
  Saints: IconsInternal.Flame,
  SaintHalo: IconsInternal.Flame,
  Aquinas: IconsInternal.Feather,
  Columns: IconsInternal.Columns,
  Brain: IconsInternal.Brain,
  Feather: IconsInternal.Feather,
  PenLine: IconsInternal.PenLine,
  PenTool: IconsInternal.PenTool,
  Scroll: IconsInternal.ScrollText,
  ScrollText: IconsInternal.ScrollText,
  Quote: IconsInternal.Quote,
  Type: IconsInternal.Type,
  Glossary: IconsInternal.BookMarked,
  AZ: IconsInternal.Languages,
  History: IconsInternal.History,
  Bookmark: IconsInternal.Bookmark,
  Tag: IconsInternal.Tag,
  Themes: IconsInternal.Layers,
  Swords: IconsInternal.Swords,
  
  // Spiritual Life
  Liturgy: IconsInternal.Wine,
  DailyLiturgy: IconsInternal.Sun,
  Sun: IconsInternal.Sun,
  Moon: IconsInternal.Moon,
  Cross: IconsInternal.Cross,
  Chalice: IconsInternal.Wine,
  Flame: IconsInternal.Flame,
  Lectio: IconsInternal.Flame,
  Sparkle: IconsInternal.Sparkle,
  Sparkles: IconsInternal.Sparkles,
  PrayingHands: IconsInternal.Hand,
  Hand: IconsInternal.Hand,
  Rosary: IconsInternal.Orbit,
  ViaCrucis: IconsInternal.Cross,
  Church: IconsInternal.Home,
  LiturgicalCalendar: IconsInternal.Calendar,
  Map: IconsInternal.Map,
  Oracao: IconsInternal.Hand,
  
  // Pathways & Journeys
  Journeys: IconsInternal.Route,
  JourneysMap: IconsInternal.Map,
  Route: IconsInternal.Route,
  Compass: IconsInternal.Compass,
  Target: IconsInternal.Target,
  Flag: IconsInternal.Award,
  Activity: IconsInternal.Activity,
  Stethoscope: IconsInternal.Stethoscope,
  Certamen: IconsInternal.Trophy,
  
  // Community & Interaction
  Community: IconsInternal.Users,
  Users: IconsInternal.Users,
  UserCheck: IconsInternal.UserCheck,
  Message: IconsInternal.MessageCircle,
  MessageCircle: IconsInternal.MessageCircle,
  MessageSquare: IconsInternal.MessageSquare,
  Send: IconsInternal.Send,
  Share: IconsInternal.Share2,
  Share2: IconsInternal.Share2,
  ExternalLink: IconsInternal.ExternalLink,
  Link: IconsInternal.Link,
  Mail: IconsInternal.Mail,
  
  // Media & Controls
  Audio: IconsInternal.Volume2,
  Volume2: IconsInternal.Volume2,
  Volume1: IconsInternal.Volume1,
  Volume: IconsInternal.Volume,
  Play: IconsInternal.Play,
  Stop: IconsInternal.Square,
  Music: IconsInternal.Music,
  Download: IconsInternal.Download,
  RotateCcw: IconsInternal.RotateCcw,
  Maximize: IconsInternal.Maximize2,
  Minimize: IconsInternal.Minimize2,
  
  // Arrows & Direction
  ChevronLeft: IconsInternal.ChevronLeft,
  ChevronRight: IconsInternal.ChevronRight,
  ChevronDown: IconsInternal.ChevronDown,
  ChevronUp: IconsInternal.ChevronUp,
  ArrowLeft: IconsInternal.ArrowLeft,
  ArrowRight: IconsInternal.ArrowRight,
  ArrowDown: IconsInternal.ArrowDown,
  Video: IconsInternal.Video,
  
  // Utilities
  Copy: IconsInternal.Copy,
  Trash: IconsInternal.Trash2,
  Trash2: IconsInternal.Trash2,
  GripVertical: IconsInternal.GripVertical,
  Lock: IconsInternal.Lock,
  Pin: IconsInternal.Pin,
  Filter: IconsInternal.Filter,
  List: IconsInternal.List,
  Grid: IconsInternal.Grid,
  Eye: IconsInternal.Eye,
  EyeOff: IconsInternal.EyeOff,
  AlertTriangle: IconsInternal.AlertTriangle,
  XCircle: IconsInternal.XCircle,
  CheckCircle: IconsInternal.CheckCircle,
  CheckCircle2: IconsInternal.CheckCircle2,
  Loader: IconsInternal.Loader2,
  Loader2: IconsInternal.Loader2,
  CreditCard: IconsInternal.CreditCard,
  Smartphone: IconsInternal.Smartphone,
  MonitorSmartphone: IconsInternal.MonitorSmartphone,
  WifiOff: IconsInternal.WifiOff,
  Wifi: IconsInternal.Wifi,
  
  // Social
  Instagram: IconsInternal.Instagram,
  Facebook: IconsInternal.Facebook,
  Twitter: IconsInternal.Twitter,
  Youtube: IconsInternal.Youtube,
  Printer: IconsInternal.Printer,
  Whatsapp: IconsInternal.MessageCircle,
  Google: IconsInternal.Globe, 
  Apple: IconsInternal.Smartphone,
  Coffee: IconsInternal.Coffee,
  PanelLeft: IconsInternal.PanelLeft,
  Hash: IconsInternal.Hash,
  Shield: IconsInternal.Shield,
  VolumeX: IconsInternal.VolumeX,
  UserMinus: IconsInternal.UserMinus,
  Edit2: IconsInternal.Edit2,
  
  // New icons for consistency
  AlertCircle: IconsInternal.AlertCircle,
  Anchor: IconsInternal.Anchor,
  ArrowUpDown: IconsInternal.ArrowUpDown,
  ArrowUpRight: IconsInternal.ArrowUpRight,
  Bird: IconsInternal.Bird,
  Contrast: IconsInternal.Contrast,
  CornerRightUp: IconsInternal.CornerRightUp,
  Droplets: IconsInternal.Droplets,
  FileCode: IconsInternal.FileCode,
  FileDown: IconsInternal.FileDown,
  FlaskConical: IconsInternal.FlaskConical,
  Frown: IconsInternal.Frown,
  Headphones: IconsInternal.Headphones,
  Highlighter: IconsInternal.Highlighter,
  Key: IconsInternal.Key,
  LayoutPanelLeft: IconsInternal.LayoutPanelLeft,
  Lightbulb: IconsInternal.Lightbulb,
  Megaphone: IconsInternal.Megaphone,
  Mountain: IconsInternal.Mountain,
  Pause: IconsInternal.Pause,
  RefreshCcw: IconsInternal.RefreshCcw,
  RefreshCw: IconsInternal.RefreshCw,
  Save: IconsInternal.Save,
  Settings2: IconsInternal.Settings2,
  ShieldAlert: IconsInternal.ShieldAlert,
  Skull: IconsInternal.Skull,
  StopCircle: IconsInternal.StopCircle,
  Store: IconsInternal.Store,
  TrendingUp: IconsInternal.TrendingUp,
  Wheat: IconsInternal.Wheat,
  Wind: IconsInternal.Wind,
  ZapOff: IconsInternal.ZapOff,
  MoreHorizontal: IconsInternal.MoreHorizontal,
};

// Runtime Consistency Check
if (import.meta.env.DEV) {
  const iconKeys = Object.keys(Icons);
  const duplicates = iconKeys.filter((key, index) => iconKeys.indexOf(key) !== index);
  if (duplicates.length > 0) {
    console.warn('Duplicate icon keys found in constants:', duplicates);
  }
}