import React, { forwardRef } from 'react';
import { 
  BookOpen, 
  Cross, 
  Map, 
  Users, 
  Flame, 
  Sparkle, 
  FileText, 
  Type, 
  Columns,
  Search,
  ChevronLeft,
  ChevronRight,
  Star,
  MessageCircle,
  Zap,
  Layout,
  Globe,
  ExternalLink,
  Pin,
  Heart,
  Download,
  RotateCcw,
  Instagram,
  Facebook,
  Twitter,
  Youtube,
  Menu,
  Feather,
  History,
  Volume2,
  Square,
  Brain,
  Sparkles,
  User,
  ArrowDown,
  ArrowLeft,
  Music,
  Bell,
  Sun,
  Moon,
  LogOut,
  PenLine,
  Calendar,
  Compass,
  Loader2,
  Award,
  ArrowRight,
  Quote,
  Share2,
  Check,
  Circle,
  Dot,
  X,
  ShieldQuestion,
  MessageSquare,
  Send,
  Trophy,
  ShieldCheck,
  Clock,
  CheckCircle2,
  PenTool,
  Copy,
  Plus,
  Trash2,
  GripVertical,
  Lock,
  HelpCircle,
  PartyPopper,
  MoreHorizontal,
  Coffee,
  Church,
  Bookmark,
  Smartphone,
  MonitorSmartphone,
  Activity,
  UserCog,
  LayoutGrid,
  UserCheck,
  Stethoscope,
  Route,
  Library,
  Hand
} from 'lucide-react';
import { cn } from './lib/utils';

export const COLORS = {
  primary: '#0A192F', // Azul escuro profundo
  secondary: '#D4AF37', // Dourado suave
  background: '#F8FAFC', // Neutro claro
  accent: '#C5A02D',
};

export const Logo = forwardRef<HTMLDivElement, { className?: string }>(({ className = "w-12 h-12" }, ref) => (
  <div ref={ref} className={cn("relative flex items-center justify-center group", className)}>
    <img 
      src="/src/assets/cathedra-logo.webp" 
      alt="Cathedra" 
      className="relative w-full h-full object-contain transition-all duration-700 group-hover:scale-110 drop-shadow-[0_0_15px_rgba(212,175,55,0.3)]"
    />
  </div>
));

Logo.displayName = 'Logo';

const createIcon = (IconComponent: any) => 
  forwardRef<SVGSVGElement, React.SVGProps<SVGSVGElement>>(({ className, ...props }, ref) => (
    <IconComponent 
      ref={ref} 
      strokeWidth={1.5} 
      size={20}
      className={cn("transition-colors duration-200", className)}
      {...props} 
    />
  ));

export const Icons = {
  // Lucide Names (Direct)
  BookOpen: createIcon(BookOpen),
  Cross: createIcon(Cross),
  Map: createIcon(Map),
  Users: createIcon(Users),
  Flame: createIcon(Flame),
  Sparkle: createIcon(Sparkle),
  FileText: createIcon(FileText),
  Type: createIcon(Type),
  Columns: createIcon(Columns),
  Search: createIcon(Search),
  ChevronLeft: createIcon(ChevronLeft),
  ChevronRight: createIcon(ChevronRight),
  Star: createIcon(Star),
  MessageCircle: createIcon(MessageCircle),
  Zap: createIcon(Zap),
  Layout: createIcon(Layout),
  Globe: createIcon(Globe),
  ExternalLink: createIcon(ExternalLink),
  Pin: createIcon(Pin),
  Heart: createIcon(Heart),
  Download: createIcon(Download),
  RotateCcw: createIcon(RotateCcw),
  Instagram: createIcon(Instagram),
  Facebook: createIcon(Facebook),
  Twitter: createIcon(Twitter),
  Youtube: createIcon(Youtube),
  Menu: createIcon(Menu),
  Feather: createIcon(Feather),
  History: createIcon(History),
  Volume2: createIcon(Volume2),
  Square: createIcon(Square),
  Brain: createIcon(Brain),
  Sparkles: createIcon(Sparkles),
  User: createIcon(User),
  ArrowDown: createIcon(ArrowDown),
  ArrowLeft: createIcon(ArrowLeft),
  Music: createIcon(Music),
  Bell: createIcon(Bell),
  Sun: createIcon(Sun),
  Moon: createIcon(Moon),
  LogOut: createIcon(LogOut),
  PenLine: createIcon(PenLine),
  Calendar: createIcon(Calendar),
  Compass: createIcon(Compass),
  Loader2: createIcon(Loader2),
  Loader: createIcon(Loader2),
  Award: createIcon(Award),
  ArrowRight: createIcon(ArrowRight),
  Quote: createIcon(Quote),
  Share2: createIcon(Share2),
  Check: createIcon(Check),
  Circle: createIcon(Circle),
  Dot: createIcon(Dot),
  X: createIcon(X),
  ShieldQuestion: createIcon(ShieldQuestion),
  MessageSquare: createIcon(MessageSquare),
  Send: createIcon(Send),
  Trophy: createIcon(Trophy),
  ShieldCheck: createIcon(ShieldCheck),
  Clock: createIcon(Clock),
  CheckCircle2: createIcon(CheckCircle2),
  CheckCircle: createIcon(CheckCircle2),
  PenTool: createIcon(PenTool),
  Copy: createIcon(Copy),
  Plus: createIcon(Plus),
  Trash2: createIcon(Trash2),
  Trash: createIcon(Trash2),
  GripVertical: createIcon(GripVertical),
  Lock: createIcon(Lock),
  HelpCircle: createIcon(HelpCircle),
  PartyPopper: createIcon(PartyPopper),
  MoreHorizontal: createIcon(MoreHorizontal),
  Coffee: createIcon(Coffee),
  Church: createIcon(Church),
  Bookmark: createIcon(Bookmark),
  Smartphone: createIcon(Smartphone),
  MonitorSmartphone: createIcon(MonitorSmartphone),
  Activity: createIcon(Activity),
  UserCog: createIcon(UserCog),
  LayoutGrid: createIcon(LayoutGrid),
  UserCheck: createIcon(UserCheck),
  Stethoscope: createIcon(Stethoscope),
  Route: createIcon(Route),
  Library: createIcon(Library),
  Hand: createIcon(Hand),

  // Semantic Aliases & Backward Compatibility
  Bible: createIcon(BookOpen),
  HolyBible: createIcon(BookOpen),
  Liturgy: createIcon(Cross),
  Chalice: createIcon(Sparkle),
  Journeys: createIcon(Map),
  Community: createIcon(Users),
  Lectio: createIcon(Flame),
  Saints: createIcon(Sparkles),
  SaintHalo: createIcon(Sparkles),
  Catechism: createIcon(FileText),
  CatechismShield: createIcon(FileText),
  Glossary: createIcon(Type),
  Aquinas: createIcon(Columns),
  Dove: createIcon(Sparkles),
  LiturgicalCalendar: createIcon(Map),
  PrayingHands: createIcon(Sparkles),
  Rosary: createIcon(Sparkles),
  ViaCrucis: createIcon(Cross),
  Scroll: createIcon(FileText),
  Cathedral: createIcon(Columns),
  Home: createIcon(Layout),
  Book: createIcon(BookOpen),
  Message: createIcon(MessageCircle),
  Handshake: createIcon(Users),
  Whatsapp: createIcon(MessageCircle),
  Google: createIcon(Sparkles),
  Apple: createIcon(Sparkles),
  Share: createIcon(Share2),
  Audio: createIcon(Volume2),
  Stop: createIcon(Square),
};