// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-glossary.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient } from "npm:@supabase/supabase-js@^2.112.2";
import { z } from "npm:zod@^3.25.76";
var search_glossary_default = defineTool({
  name: "search_glossary",
  title: "Buscar no Gloss\xE1rio",
  description: "Busca verbetes publicados do Gloss\xE1rio Teol\xF3gico da Cathedra por termo. Retorna slug, t\xEDtulo e defini\xE7\xE3o curta. P\xFAblico (dados publicados).",
  inputSchema: {
    query: z.string().trim().min(1).max(120).describe("Termo ou fragmento a buscar."),
    limit: z.number().int().min(1).max(20).optional().describe("M\xE1ximo de resultados (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY;
    const sb = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
    const { data, error } = await sb.from("glossary").select("slug,term,short_definition,category").eq("status", "published").or(`term.ilike.%${query}%,short_definition.ilike.%${query}%,definition.ilike.%${query}%`).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-glossary-term.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_glossary_term_default = defineTool2({
  name: "get_glossary_term",
  title: "Obter verbete do Gloss\xE1rio",
  description: "Retorna o verbete completo do Gloss\xE1rio Teol\xF3gico pelo slug: defini\xE7\xE3o, interpreta\xE7\xE3o profunda, etimologia, contexto e refer\xEAncias. P\xFAblico (apenas verbetes publicados).",
  inputSchema: {
    slug: z2.string().trim().min(1).max(120).describe("Slug do verbete, ex.: 'eucaristia'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY;
    const sb = createClient2(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
    const { data, error } = await sb.from("glossary").select(
      "slug,term,short_definition,definition,deep_interpretation,etymology,historical_context,practical_application,bible_verses,catechism_references,magisterium_references,saints_refs,category,updated_at"
    ).eq("slug", slug).eq("status", "published").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: `Verbete n\xE3o encontrado: ${slug}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { term: data }
    };
  }
});

// src/lib/mcp/tools/list-journal-entries.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_journal_entries_default = defineTool3({
  name: "list_journal_entries",
  title: "Listar entradas do Di\xE1rio Espiritual",
  description: "Lista as entradas do Di\xE1rio Espiritual do usu\xE1rio autenticado, mais recentes primeiro. Requer login (OAuth).",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("M\xE1ximo de entradas (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    const sb = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("spiritual_journal").select("id,entry_date,mood,content,journey_id,step_id,is_reviewed,created_at,updated_at").eq("user_id", ctx.getUserId()).order("entry_date", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-journal-entry.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z4 } from "npm:zod@^3.25.76";
var create_journal_entry_default = defineTool4({
  name: "create_journal_entry",
  title: "Criar entrada no Di\xE1rio Espiritual",
  description: "Cria uma nova entrada no Di\xE1rio Espiritual do usu\xE1rio autenticado. Requer login (OAuth).",
  inputSchema: {
    content: z4.string().trim().min(1).max(2e4).describe("Texto da medita\xE7\xE3o/entrada."),
    mood: z4.string().trim().max(60).optional().describe("Estado interior (ex.: 'consola\xE7\xE3o', 'aridez')."),
    entry_date: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Data no formato YYYY-MM-DD (default: hoje).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ content, mood, entry_date }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    const sb = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("spiritual_journal").insert({
      user_id: ctx.getUserId(),
      content,
      mood: mood ?? null,
      entry_date: entry_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10)
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Entrada criada: ${data.id}` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/search-saints.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z5 } from "npm:zod@^3.25.76";
var search_saints_default = defineTool5({
  name: "search_saints",
  title: "Buscar Santos",
  description: "Busca santos cat\xF3licos por nome, t\xEDtulo ou patronato no acervo p\xFAblico da Cathedra. Retorna id, nome, t\xEDtulo, data festiva e categoria.",
  inputSchema: {
    query: z5.string().trim().min(1).max(120).describe("Nome, t\xEDtulo ou fragmento (ex.: 'Agostinho', 'padroeiro dos advogados')."),
    limit: z5.number().int().min(1).max(30).optional().describe("M\xE1ximo de resultados (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const sb = createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const q = query.replace(/[%_]/g, "\\$&");
    const { data, error } = await sb.from("saints").select("id,name,title,feast_day,category,century,patronages").or(`name.ilike.%${q}%,title.ilike.%${q}%,patronages.cs.{${q}}`).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-saint.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z6 } from "npm:zod@^3.25.76";
var get_saint_default = defineTool6({
  name: "get_saint",
  title: "Obter Santo",
  description: "Retorna o registro completo de um santo pelo id (slug) \u2014 biografia, virtudes, ora\xE7\xE3o, refer\xEAncias b\xEDblicas, catecismo e cita\xE7\xF5es. Dados p\xFAblicos da Cathedra.",
  inputSchema: {
    id: z6.string().trim().min(1).max(120).describe("Identificador do santo (ex.: 'agostinho-de-hipona').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const sb = createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("saints").select(
      "id,name,title,feast_day,feast_month,feast_day_num,born,died,century,category,bio,full_bio,historical_context,virtues,patronages,quotes,quotes_rich,works,prayer,bible_refs,catechism_refs,timeline,miracles,iconography,curiosities,spiritual_practice"
    ).eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `Santo '${id}' n\xE3o encontrado.` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { saint: data }
    };
  }
});

// src/lib/mcp/tools/get-prayer.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z7 } from "npm:zod@^3.25.76";
var get_prayer_default = defineTool7({
  name: "get_prayer",
  title: "Obter Ora\xE7\xE3o",
  description: "Retorna uma ora\xE7\xE3o cat\xF3lica publicada pelo slug (ex.: 'pai-nosso', 'ave-maria', 'rosario'), incluindo conte\xFAdo, medita\xE7\xE3o, blocos e refer\xEAncias. Dados p\xFAblicos.",
  inputSchema: {
    slug: z7.string().trim().min(1).max(120).describe("Slug da ora\xE7\xE3o (ex.: 'pai-nosso').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const sb = createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("prayers").select(
      "slug,title,subtitle,kicker,category,content,content_latin,explanation,meditation,estimated_seconds,duration_min,tags,source_ref,related_bible,related_catechism,related_saints,related_glossary,bible_refs,catechism_refs,blocks,engine_version"
    ).eq("slug", slug).eq("is_published", true).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `Ora\xE7\xE3o '${slug}' n\xE3o encontrada ou n\xE3o publicada.` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { prayer: data }
    };
  }
});

// src/lib/mcp/tools/get-collection.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient8 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z8 } from "npm:zod@^3.25.76";
var get_collection_default = defineTool8({
  name: "get_collection",
  title: "Obter Cole\xE7\xE3o",
  description: "Retorna uma Cole\xE7\xE3o editorial publicada da Cathedra pelo slug, com seus itens ordenados (verbetes, santos, ora\xE7\xF5es, jornadas). Dados p\xFAblicos.",
  inputSchema: {
    slug: z8.string().trim().min(1).max(120).describe("Slug da cole\xE7\xE3o (ex.: 'sete-sacramentos').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const sb = createClient8(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data: collection, error } = await sb.from("collections").select("id,slug,title,subtitle,description,cover,category,featured,nexus_refs,metadata").eq("slug", slug).eq("status", "published").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!collection) return { content: [{ type: "text", text: `Cole\xE7\xE3o '${slug}' n\xE3o encontrada ou n\xE3o publicada.` }], isError: true };
    const { data: items } = await sb.from("collection_items").select("*").eq("collection_id", collection.id).order("order_index", { ascending: true });
    const payload = { ...collection, items: items ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: { collection: payload }
    };
  }
});

// src/lib/mcp/tools/catechism-paragraph.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient9 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z9 } from "npm:zod@^3.25.76";
var catechism_paragraph_default = defineTool9({
  name: "catechism_paragraph",
  title: "Par\xE1grafo do Catecismo",
  description: "Retorna um ou mais par\xE1grafos do Catecismo da Igreja Cat\xF3lica (CIC) pelo n\xFAmero. Aceita um \xFAnico par\xE1grafo ou intervalo (ex.: 232 a 267).",
  inputSchema: {
    paragraph: z9.number().int().min(1).max(2865).describe("N\xFAmero do par\xE1grafo do CIC (1\u20132865)."),
    to: z9.number().int().min(1).max(2865).optional().describe("Fim opcional de intervalo (inclusivo). M\xE1x. 30 par\xE1grafos por chamada.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ paragraph, to }) => {
    const from = paragraph;
    const end = to ?? paragraph;
    if (end < from) return { content: [{ type: "text", text: "'to' deve ser >= 'paragraph'." }], isError: true };
    if (end - from + 1 > 30) return { content: [{ type: "text", text: "Intervalo m\xE1ximo: 30 par\xE1grafos." }], isError: true };
    const sb = createClient9(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("catechism_official").select("paragraph,content,texto_base,explicacao,interpretacao_profunda,aplicacao_pratica,reflexao_final").gte("paragraph", from).lte("paragraph", end).order("paragraph", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data || data.length === 0) return { content: [{ type: "text", text: `Nenhum par\xE1grafo encontrado no intervalo ${from}\u2013${end}.` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { paragraphs: data }
    };
  }
});

// src/lib/mcp/tools/bible-reference.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient10 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z10 } from "npm:zod@^3.25.76";
var bible_reference_default = defineTool10({
  name: "bible_reference",
  title: "Refer\xEAncia B\xEDblica",
  description: "Retorna o texto dos vers\xEDculos de uma refer\xEAncia b\xEDblica (ex.: 'Jo 3,16', 'Mt 5,3-12'). Alternativamente aceita abrevia\xE7\xE3o do livro + cap\xEDtulo + vers\xEDculo(s). Dados p\xFAblicos.",
  inputSchema: {
    reference: z10.string().trim().min(1).max(60).optional().describe("Refer\xEAncia no formato PT-BR: 'Jo 3,16' ou 'Mt 5,3-12'."),
    book: z10.string().trim().min(1).max(10).optional().describe("Abrevia\xE7\xE3o do livro (ex.: 'Jo', 'Mt', 'Gn')."),
    chapter: z10.number().int().min(1).max(200).optional(),
    verse: z10.number().int().min(1).max(200).optional(),
    verse_end: z10.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input) => {
    let book = input.book;
    let chapter = input.chapter;
    let verse = input.verse;
    let verseEnd = input.verse_end;
    if (input.reference) {
      const m = input.reference.match(/^\s*([1-3]?\s?[A-Za-zÀ-ÿ]+)\s*(\d+)\s*[,:]\s*(\d+)(?:\s*[-–]\s*(\d+))?\s*$/);
      if (!m) return { content: [{ type: "text", text: `Formato n\xE3o reconhecido: '${input.reference}'. Use 'Jo 3,16' ou 'Mt 5,3-12'.` }], isError: true };
      book = m[1].replace(/\s+/g, "");
      chapter = Number(m[2]);
      verse = Number(m[3]);
      verseEnd = m[4] ? Number(m[4]) : void 0;
    }
    if (!book || !chapter || !verse) {
      return { content: [{ type: "text", text: "Forne\xE7a `reference` ou `book`+`chapter`+`verse`." }], isError: true };
    }
    const vEnd = verseEnd ?? verse;
    if (vEnd < verse) return { content: [{ type: "text", text: "verse_end deve ser >= verse." }], isError: true };
    if (vEnd - verse + 1 > 50) return { content: [{ type: "text", text: "M\xE1ximo de 50 vers\xEDculos por chamada." }], isError: true };
    const sb = createClient10(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data: bookRow, error: bookErr } = await sb.from("bible_books").select("id,name,abbrev,testament").ilike("abbrev", book).maybeSingle();
    if (bookErr) return { content: [{ type: "text", text: bookErr.message }], isError: true };
    if (!bookRow) return { content: [{ type: "text", text: `Livro '${book}' n\xE3o encontrado. Use abrevia\xE7\xF5es can\xF4nicas (Gn, Ex, Sl, Mt, Mc, Lc, Jo, Rm, Ap\u2026).` }], isError: true };
    const { data: chapterRow, error: chErr } = await sb.from("bible_chapters").select("id,number").eq("book_id", bookRow.id).eq("number", chapter).limit(1).maybeSingle();
    if (chErr) return { content: [{ type: "text", text: chErr.message }], isError: true };
    if (!chapterRow) return { content: [{ type: "text", text: `${bookRow.name} n\xE3o tem cap\xEDtulo ${chapter}.` }], isError: true };
    const { data: verses, error: vErr } = await sb.from("bible_verses").select("number,text,translation_id").eq("chapter_id", chapterRow.id).gte("number", verse).lte("number", vEnd).order("number", { ascending: true });
    if (vErr) return { content: [{ type: "text", text: vErr.message }], isError: true };
    if (!verses || verses.length === 0) return { content: [{ type: "text", text: `Sem vers\xEDculos em ${bookRow.abbrev} ${chapter},${verse}${verseEnd ? `-${verseEnd}` : ""}.` }], isError: true };
    const primaryTranslation = verses[0].translation_id;
    const filtered = verses.filter((v) => v.translation_id === primaryTranslation);
    const label = `${bookRow.abbrev} ${chapter},${verse}${verseEnd && verseEnd !== verse ? `-${verseEnd}` : ""}`;
    const textJoined = filtered.map((v) => `${v.number} ${v.text}`).join("\n");
    return {
      content: [{ type: "text", text: `${label}
${textJoined}` }],
      structuredContent: {
        reference: label,
        book: bookRow,
        chapter,
        verses: filtered.map((v) => ({ number: v.number, text: v.text }))
      }
    };
  }
});

// src/lib/mcp/tools/search-nexus.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient11 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z11 } from "npm:zod@^3.25.76";
var search_nexus_default = defineTool11({
  name: "search_nexus",
  title: "Buscar no Nexus Theologicus",
  description: "Busca rela\xE7\xF5es do Knowledge Graph Nexus por n\xF3 (kind+ref). Retorna arestas de entrada e sa\xEDda (verbetes, santos, ora\xE7\xF5es, vers\xEDculos, CIC).",
  inputSchema: {
    kind: z11.enum(["glossary", "saint", "prayer", "bible", "catechism", "collection", "journey"]).describe("Tipo do n\xF3 (kind)."),
    ref: z11.string().trim().min(1).max(200).describe("Identificador do n\xF3 (slug, id, refer\xEAncia)."),
    limit: z11.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ kind, ref, limit }) => {
    const sb = createClient11(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const max = limit ?? 50;
    const [outgoing, incoming] = await Promise.all([
      sb.from("nexus_relations").select("relation_type,source_kind,source_ref,target_kind,target_ref,note,confidence,attributed_to").eq("source_kind", kind).eq("source_ref", ref).limit(max),
      sb.from("nexus_relations").select("relation_type,source_kind,source_ref,target_kind,target_ref,note,confidence,attributed_to").eq("target_kind", kind).eq("target_ref", ref).limit(max)
    ]);
    if (outgoing.error) return { content: [{ type: "text", text: outgoing.error.message }], isError: true };
    if (incoming.error) return { content: [{ type: "text", text: incoming.error.message }], isError: true };
    const payload = {
      node: { kind, ref },
      outgoing: outgoing.data ?? [],
      incoming: incoming.data ?? [],
      total: (outgoing.data?.length ?? 0) + (incoming.data?.length ?? 0)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/related-content.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient12 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z12 } from "npm:zod@^3.25.76";
var related_content_default = defineTool12({
  name: "related_content",
  title: "Conte\xFAdo Relacionado",
  description: "Dado um n\xF3 (kind+ref), retorna conte\xFAdos relacionados hidratados: verbetes, santos, ora\xE7\xF5es e cole\xE7\xF5es alcan\xE7ados via Nexus.",
  inputSchema: {
    kind: z12.enum(["glossary", "saint", "prayer", "bible", "catechism", "collection", "journey"]),
    ref: z12.string().trim().min(1).max(200),
    limit: z12.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ kind, ref, limit }) => {
    const sb = createClient12(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const max = limit ?? 20;
    const [outgoing, incoming] = await Promise.all([
      sb.from("nexus_relations").select("relation_type,target_kind,target_ref,note").eq("source_kind", kind).eq("source_ref", ref).limit(max),
      sb.from("nexus_relations").select("relation_type,source_kind,source_ref,note").eq("target_kind", kind).eq("target_ref", ref).limit(max)
    ]);
    const nodes = /* @__PURE__ */ new Map();
    for (const r of outgoing.data ?? []) {
      const k = `${r.target_kind}:${r.target_ref}`;
      if (!nodes.has(k)) nodes.set(k, { kind: r.target_kind, ref: r.target_ref, via: [] });
      nodes.get(k).via.push(`\u2192 ${r.relation_type}`);
    }
    for (const r of incoming.data ?? []) {
      const k = `${r.source_kind}:${r.source_ref}`;
      if (!nodes.has(k)) nodes.set(k, { kind: r.source_kind, ref: r.source_ref, via: [] });
      nodes.get(k).via.push(`\u2190 ${r.relation_type}`);
    }
    const bucket = (kk) => [...nodes.values()].filter((n) => n.kind === kk);
    const glossarySlugs = bucket("glossary").map((n) => n.ref);
    const saintIds = bucket("saint").map((n) => n.ref);
    const prayerSlugs = bucket("prayer").map((n) => n.ref);
    const collectionSlugs = bucket("collection").map((n) => n.ref);
    const [g, s, p, c] = await Promise.all([
      glossarySlugs.length ? sb.from("glossary").select("slug,term,short_definition,category").in("slug", glossarySlugs).eq("status", "published") : Promise.resolve({ data: [] }),
      saintIds.length ? sb.from("saints").select("id,name,title,feast_day,bio,category").in("id", saintIds) : Promise.resolve({ data: [] }),
      prayerSlugs.length ? sb.from("prayers").select("slug,title,category,kicker").in("slug", prayerSlugs).eq("is_published", true) : Promise.resolve({ data: [] }),
      collectionSlugs.length ? sb.from("collections").select("slug,title,subtitle,category").in("slug", collectionSlugs).eq("status", "published") : Promise.resolve({ data: [] })
    ]);
    const payload = {
      node: { kind, ref },
      glossary: g.data ?? [],
      saints: s.data ?? [],
      prayers: p.data ?? [],
      collections: c.data ?? [],
      bible: bucket("bible"),
      catechism: bucket("catechism"),
      relations_meta: [...nodes.values()]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/daily-liturgy.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient13 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z13 } from "npm:zod@^3.25.76";
var daily_liturgy_default = defineTool13({
  name: "daily_liturgy",
  title: "Missal do Dia",
  description: "Retorna os pr\xF3rios do Missal para uma data (ISO YYYY-MM-DD, default = hoje): celebra\xE7\xE3o, cor lit\xFArgica, ant\xEDfonas, coleta e ora\xE7\xE3o p\xF3s-comunh\xE3o.",
  inputSchema: {
    date: z13.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Data ISO (YYYY-MM-DD). Default: hoje (UTC).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }) => {
    const iso = date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const sb = createClient13(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("missal_propers").select(
      "iso_date,celebration_title,liturgical_color,entrance_antiphon,collect,offertory_prayer,preface_suggestion,communion_antiphon,prayer_after_communion,season_note"
    ).eq("iso_date", iso).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return {
        content: [{ type: "text", text: `Missal n\xE3o dispon\xEDvel para ${iso}. Acesse /liturgia/missa para gerar.` }],
        isError: true
      };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { missal: data }
    };
  }
});

// src/lib/mcp/tools/daily-office.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient14 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z14 } from "npm:zod@^3.25.76";
var HOURS = [
  "invitatorio",
  "laudes",
  "hora-media",
  "terca",
  "sexta",
  "noa",
  "vesperas",
  "completas",
  "oficio-leituras"
];
var daily_office_default = defineTool14({
  name: "daily_office",
  title: "Of\xEDcio Divino (Liturgia das Horas)",
  description: "Retorna uma hora can\xF4nica da Liturgia das Horas para uma data: ant\xEDfonas, salmodia, leitura breve, respons\xF3rio, c\xE2ntico evang\xE9lico e intercess\xF5es.",
  inputSchema: {
    hour: z14.enum(HOURS).describe("Hora can\xF4nica (ex.: 'laudes', 'vesperas', 'completas')."),
    date: z14.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Data ISO (YYYY-MM-DD). Default: hoje (UTC).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ hour, date }) => {
    const iso = date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const sb = createClient14(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("liturgy_hours_offices").select(
      "iso_date,hour_slug,antiphon_opening,psalmody,brief_reading_ref,brief_reading_text,responsory,gospel_canticle,intercessions,concluding_prayer,season_note"
    ).eq("iso_date", iso).eq("hour_slug", hour).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return {
        content: [{ type: "text", text: `Of\xEDcio '${hour}' n\xE3o dispon\xEDvel para ${iso}. Gere em /liturgia/horas.` }],
        isError: true
      };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { office: data }
    };
  }
});

// src/lib/mcp/tools/search-prayers.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient15 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z15 } from "npm:zod@^3.25.76";
var search_prayers_default = defineTool15({
  name: "search_prayers",
  title: "Buscar Ora\xE7\xF5es",
  description: "Busca ora\xE7\xF5es cat\xF3licas publicadas por termo (t\xEDtulo, subt\xEDtulo, categoria, tags). Retorna metadados leves; use `get_prayer` para o conte\xFAdo completo.",
  inputSchema: {
    query: z15.string().trim().min(1).max(120),
    category: z15.string().trim().max(60).optional().describe("Filtrar por categoria (ex.: 'rosario', 'novena')."),
    limit: z15.number().int().min(1).max(30).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }) => {
    const sb = createClient15(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = sb.from("prayers").select("slug,title,subtitle,kicker,category,duration_min,estimated_seconds,tags").eq("is_published", true).or(`title.ilike.%${query}%,subtitle.ilike.%${query}%,kicker.ilike.%${query}%,category.ilike.%${query}%`).limit(limit ?? 15);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-collections.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient16 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z16 } from "npm:zod@^3.25.76";
var search_collections_default = defineTool16({
  name: "search_collections",
  title: "Buscar Cole\xE7\xF5es Editoriais",
  description: "Busca Cole\xE7\xF5es editoriais publicadas por termo (t\xEDtulo, subt\xEDtulo, categoria). Use `get_collection` para itens completos.",
  inputSchema: {
    query: z16.string().trim().min(1).max(120),
    category: z16.string().trim().max(60).optional(),
    limit: z16.number().int().min(1).max(30).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }) => {
    const sb = createClient16(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = sb.from("collections").select("slug,title,subtitle,description,category,featured,cover").eq("status", "published").or(`title.ilike.%${query}%,subtitle.ilike.%${query}%,description.ilike.%${query}%,category.ilike.%${query}%`).limit(limit ?? 15);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-journey.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient17 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z17 } from "npm:zod@^3.25.76";
var get_journey_default = defineTool17({
  name: "get_journey",
  title: "Obter Jornada",
  description: "Retorna uma Jornada publicada da Cathedra pelo slug, incluindo hero editorial e etapas ordenadas (title, subtitle, step_type, conte\xFAdo, reflection, exercise, closing).",
  inputSchema: {
    slug: z17.string().trim().min(1).max(120).describe("Slug da jornada.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const sb = createClient17(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data: j, error } = await sb.from("journeys").select(
      "id,slug,title,subtitle,description,category,difficulty,estimated_days,tags,hero_kicker,hero_quote,hero_image_url,narrative_intro,closing_message,is_premium,status"
    ).eq("slug", slug).eq("status", "published").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!j)
      return {
        content: [{ type: "text", text: `Jornada '${slug}' n\xE3o encontrada ou n\xE3o publicada.` }],
        isError: true
      };
    const { data: steps } = await sb.from("journey_steps").select("step_order,title,subtitle,step_type,content,duration_minutes,is_free,reflection,exercise,closing").eq("journey_id", j.id).order("step_order", { ascending: true });
    const payload = { ...j, steps: steps ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: { journey: payload }
    };
  }
});

// src/lib/mcp/tools/search-patristics.ts
import { defineTool as defineTool18 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient18 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z18 } from "npm:zod@^3.25.76";
var search_patristics_default = defineTool18({
  name: "search_patristics",
  title: "Buscar Patr\xEDstica (Padres da Igreja)",
  description: "Busca conte\xFAdo patr\xEDstico: santos categorizados como Padres da Igreja e verbetes com refer\xEAncias patr\xEDsticas (fathers_refs).",
  inputSchema: {
    query: z18.string().trim().min(1).max(120),
    limit: z18.number().int().min(1).max(30).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const sb = createClient18(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const max = limit ?? 15;
    const like = `%${query}%`;
    const [saints, glossary] = await Promise.all([
      sb.from("saints").select("id,name,title,feast_day,bio,category").or(`name.ilike.${like},bio.ilike.${like},title.ilike.${like},category.ilike.%padre%,category.ilike.%patrist%`).limit(max),
      sb.from("glossary").select("slug,term,short_definition,fathers_refs").eq("status", "published").not("fathers_refs", "is", null).or(`term.ilike.${like},short_definition.ilike.${like},definition.ilike.${like}`).limit(max)
    ]);
    const payload = { saints: saints.data ?? [], glossary_with_fathers: glossary.data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/search-magisterium.ts
import { defineTool as defineTool19 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient19 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z19 } from "npm:zod@^3.25.76";
var search_magisterium_default = defineTool19({
  name: "search_magisterium",
  title: "Buscar Magist\xE9rio",
  description: "Busca conte\xFAdo do Magist\xE9rio: par\xE1grafos do Catecismo (CIC) e verbetes com refer\xEAncias magisteriais (enc\xEDclicas, conc\xEDlios).",
  inputSchema: {
    query: z19.string().trim().min(1).max(120),
    limit: z19.number().int().min(1).max(30).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const sb = createClient19(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const max = limit ?? 15;
    const like = `%${query}%`;
    const [cic, glossary] = await Promise.all([
      sb.from("catechism_official").select("paragraph,content,texto_base,explicacao").or(`content.ilike.${like},texto_base.ilike.${like},explicacao.ilike.${like}`).limit(max),
      sb.from("glossary").select("slug,term,short_definition,catechism_references,magisterium_references").eq("status", "published").not("magisterium_references", "is", null).or(`term.ilike.${like},short_definition.ilike.${like},definition.ilike.${like}`).limit(max)
    ]);
    const payload = {
      catechism: cic.data ?? [],
      glossary_with_magisterium: glossary.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/semantic-search.ts
import { defineTool as defineTool20 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient20 } from "npm:@supabase/supabase-js@^2.112.2";
import { z as z20 } from "npm:zod@^3.25.76";
var semantic_search_default = defineTool20({
  name: "semantic_search",
  title: "Busca Unificada Cathedra",
  description: "Busca simult\xE2nea em Gloss\xE1rio, Santos, Ora\xE7\xF5es, Cole\xE7\xF5es e Jornadas por um termo. Retorna top N por categoria.",
  inputSchema: {
    query: z20.string().trim().min(1).max(120),
    limit_per_bucket: z20.number().int().min(1).max(15).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit_per_bucket }) => {
    const sb = createClient20(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const n = limit_per_bucket ?? 5;
    const like = `%${query}%`;
    const [g, s, p, c, j] = await Promise.all([
      sb.from("glossary").select("slug,term,short_definition,category").eq("status", "published").or(`term.ilike.${like},short_definition.ilike.${like},definition.ilike.${like}`).limit(n),
      sb.from("saints").select("id,name,title,feast_day,bio").or(`name.ilike.${like},bio.ilike.${like},title.ilike.${like}`).limit(n),
      sb.from("prayers").select("slug,title,subtitle,category").eq("is_published", true).or(`title.ilike.${like},subtitle.ilike.${like},kicker.ilike.${like}`).limit(n),
      sb.from("collections").select("slug,title,subtitle,category").eq("status", "published").or(`title.ilike.${like},subtitle.ilike.${like},description.ilike.${like}`).limit(n),
      sb.from("journeys").select("slug,title,subtitle,category").eq("status", "published").or(`title.ilike.${like},subtitle.ilike.${like},description.ilike.${like}`).limit(n)
    ]);
    const payload = {
      query,
      glossary: g.data ?? [],
      saints: s.data ?? [],
      prayers: p.data ?? [],
      collections: c.data ?? [],
      journeys: j.data ?? [],
      total: (g.data?.length ?? 0) + (s.data?.length ?? 0) + (p.data?.length ?? 0) + (c.data?.length ?? 0) + (j.data?.length ?? 0)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gpwrpmoniglarqwfyryp";
var mcp_default = defineMcp({
  name: "cathedra-mcp",
  title: "Cathedra Digital MCP",
  version: "0.3.0",
  instructions: "Ferramentas MCP da Cathedra Digital \u2014 motor de conhecimento cat\xF3lico. Busca unificada: `semantic_search`. Gloss\xE1rio: `search_glossary`, `get_glossary_term`. Santos: `search_saints`, `get_saint`. Patr\xEDstica: `search_patristics`. Ora\xE7\xF5es: `search_prayers`, `get_prayer`. Cole\xE7\xF5es: `search_collections`, `get_collection`. Jornadas: `get_journey`. C\xE2nones: `catechism_paragraph`, `bible_reference`, `search_magisterium`. Liturgia di\xE1ria: `daily_liturgy` (Missal), `daily_office` (Horas). Knowledge Graph: `search_nexus`, `related_content`. Di\xE1rio do usu\xE1rio autenticado: `list_journal_entries`, `create_journal_entry`.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    semantic_search_default,
    search_glossary_default,
    get_glossary_term_default,
    search_saints_default,
    get_saint_default,
    search_patristics_default,
    search_prayers_default,
    get_prayer_default,
    search_collections_default,
    get_collection_default,
    get_journey_default,
    catechism_paragraph_default,
    bible_reference_default,
    search_magisterium_default,
    daily_liturgy_default,
    daily_office_default,
    search_nexus_default,
    related_content_default,
    list_journal_entries_default,
    create_journal_entry_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
