// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-glossary.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient } from "npm:@supabase/supabase-js@^2.49.1";
import { z } from "npm:zod@^3.25.76";
var search_glossary_default = defineTool({
  name: "search_glossary",
  title: "Buscar no Gloss\xE1rio",
  description: "Busca verbetes publicados do Gloss\xE1rio Teol\xF3gico da Cathedra por termo. Retorna slug, t\xEDtulo e defini\xE7\xE3o curta. P\xFAblico (dados publicados).",
  inputSchema: {
    query: z.string().trim().min(1).max(120).describe("Termo ou fragmento a buscar."),
    limit: z.number().int().min(1).max(20).optional().describe("M\xE1ximo de resultados (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY;
    const sb = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
    const { data, error } = await sb.from("glossary").select("slug,term,short_definition,category").eq("status", "published").or(`term.ilike.%${query}%,short_definition.ilike.%${query}%,definition.ilike.%${query}%`).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-glossary-term.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.49.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_glossary_term_default = defineTool2({
  name: "get_glossary_term",
  title: "Obter verbete do Gloss\xE1rio",
  description: "Retorna o verbete completo do Gloss\xE1rio Teol\xF3gico pelo slug: defini\xE7\xE3o, interpreta\xE7\xE3o profunda, etimologia, contexto e refer\xEAncias. P\xFAblico (apenas verbetes publicados).",
  inputSchema: {
    slug: z2.string().trim().min(1).max(120).describe("Slug do verbete, ex.: 'eucaristia'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY;
    const sb = createClient2(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
    const { data, error } = await sb.from("glossary").select(
      "slug,term,short_definition,definition,deep_interpretation,etymology,historical_context,practical_application,bible_verses,catechism_references,magisterium_references,saints_refs,category,updated_at"
    ).eq("slug", slug).eq("status", "published").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: `Verbete n\xE3o encontrado: ${slug}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { term: data }
    };
  }
});

// src/lib/mcp/tools/list-journal-entries.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.49.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_journal_entries_default = defineTool3({
  name: "list_journal_entries",
  title: "Listar entradas do Di\xE1rio Espiritual",
  description: "Lista as entradas do Di\xE1rio Espiritual do usu\xE1rio autenticado, mais recentes primeiro. Requer login (OAuth).",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("M\xE1ximo de entradas (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    const sb = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("spiritual_journal").select("id,entry_date,mood,content,journey_id,step_id,is_reviewed,created_at,updated_at").eq("user_id", ctx.getUserId()).order("entry_date", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-journal-entry.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.49.1";
import { z as z4 } from "npm:zod@^3.25.76";
var create_journal_entry_default = defineTool4({
  name: "create_journal_entry",
  title: "Criar entrada no Di\xE1rio Espiritual",
  description: "Cria uma nova entrada no Di\xE1rio Espiritual do usu\xE1rio autenticado. Requer login (OAuth).",
  inputSchema: {
    content: z4.string().trim().min(1).max(2e4).describe("Texto da medita\xE7\xE3o/entrada."),
    mood: z4.string().trim().max(60).optional().describe("Estado interior (ex.: 'consola\xE7\xE3o', 'aridez')."),
    entry_date: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Data no formato YYYY-MM-DD (default: hoje).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ content, mood, entry_date }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    const sb = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("spiritual_journal").insert({
      user_id: ctx.getUserId(),
      content,
      mood: mood ?? null,
      entry_date: entry_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10)
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Entrada criada: ${data.id}` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gpwrpmoniglarqwfyryp";
var mcp_default = defineMcp({
  name: "cathedra-mcp",
  title: "Cathedra Digital MCP",
  version: "0.1.0",
  instructions: "Ferramentas MCP da Cathedra Digital \u2014 plataforma cat\xF3lica de estudo e vida interior. Use `search_glossary` e `get_glossary_term` para consultar o Gloss\xE1rio Teol\xF3gico publicado. Use `list_journal_entries` e `create_journal_entry` para ler/gravar o Di\xE1rio Espiritual do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_glossary_default, get_glossary_term_default, list_journal_entries_default, create_journal_entry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
