-- Expand Jornada de Maria (b1b1b1b1-0003-4000-8000-000000000001) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('b1b1b1b1-0003-4000-8000-000000000001', 'Dia 8 – Maria, Mãe da Igreja', 8, '{"pch": "Eis aí a tua mãe.", "interpretation": "Jesus nos deu Maria como mãe espiritual no alto da Cruz. Ela cuida de cada fiel como cuidou do seu próprio Filho.", "practical_direction": "Faça uma oração pedindo a intercessão de Maria pela Igreja hoje.", "guided_exercise": "Imagine Maria te acolhendo sob o seu manto protetor.", "final_question": "Você recorre a Maria como um filho recorre à mãe?"}'::jsonb),
('b1b1b1b1-0003-4000-8000-000000000001', 'Dia 9 – O Silêncio de Maria em Nazaré', 9, '{"pch": "Maria guardava todas estas coisas no seu coração.", "interpretation": "O silêncio de Maria não era vazio, mas cheio de adoração e escuta. É no silêncio que a Palavra ganha corpo em nós.", "practical_direction": "Dedique 10 minutos ao silêncio interior hoje, imitando Maria.", "guided_exercise": "Peça a Maria que te ensine a arte de meditar a vontade de Deus.", "final_question": "O que o seu barulho impede você de ouvir?"}'::jsonb),
('b1b1b1b1-0003-4000-8000-000000000001', 'Dia 10 – Maria na Ressurreição e Pentecostes', 10, '{"pch": "Todos perseveravam na oração com Maria.", "interpretation": "Maria é o elo que une os apóstolos na espera pelo Espírito Santo. Ela é a Esposa do Espírito e atrai Sua vinda.", "practical_direction": "Reze um Veni Creator ou uma oração ao Espírito Santo com Maria hoje.", "guided_exercise": "Imagine-se no Cenáculo, orando ao lado da Virgem Maria.", "final_question": "Você está aberto à ação do Espírito em sua vida?"}'::jsonb),
('b1b1b1b1-0003-4000-8000-000000000001', 'Dia 11 – Rainha do Céu e da Terra', 11, '{"pch": "Apareceu no céu um grande sinal: uma mulher vestida de sol.", "interpretation": "Maria participa da glória de seu Filho. Ela é a Rainha que intercede por nós diante do trono da Graça.", "practical_direction": "Reze a Salve Rainha com especial devoção hoje.", "guided_exercise": "Contemple a glória de Maria no céu e sinta sua proteção real.", "final_question": "Você confia no poder de intercessão da Rainha?"}'::jsonb),
('b1b1b1b1-0003-4000-8000-000000000001', 'Dia 12 – Maria, Estrela da Nova Evangelização', 12, '{"pch": "Fazei tudo o que Ele vos disser.", "interpretation": "Maria sempre nos aponta para Jesus. Evangelizar com Maria é levar os outros a fazerem a vontade do Senhor.", "practical_direction": "Dê um conselho baseado no Evangelho para alguém hoje.", "guided_exercise": "Peça a Maria que te ajude a ser um canal da luz de Cristo.", "final_question": "Você aponta para Jesus ou para si mesmo?"}'::jsonb),
('b1b1b1b1-0003-4000-8000-000000000001', 'Dia 13 – O Cenáculo com Maria', 13, '{"pch": "O Espírito Santo descerá sobre ti.", "interpretation": "Viver em ''Cenáculo'' é permanecer em oração e expectativa, permitindo que o Espírito renove nossa face e a do mundo.", "practical_direction": "Renove hoje sua consagração ao Espírito Santo através de Maria.", "guided_exercise": "Sinta o fogo do Espírito inflamando seu coração.", "final_question": "Sua alma é um cenáculo de oração?"}'::jsonb),
('b1b1b1b1-0003-4000-8000-000000000001', 'Dia 14 – Ser como Maria: Um Sim Permanente', 14, '{"pch": "Faça-se em mim segundo a vossa palavra.", "interpretation": "O fim da jornada com Maria é tornar-se um ''Fiat'' vivente. Um sim alegre e total aos desígnios de Deus em cada detalhe.", "practical_direction": "Aceite com alegria um imprevisto hoje como vindo de Deus.", "guided_exercise": "Diga um Sim total a Deus por toda a sua vida.", "final_question": "Seu Sim é total ou cheio de condições?"}'::jsonb);

-- Expand Jornada de Jesus (b1b1b1b1-0004-4000-8000-000000000001) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('b1b1b1b1-0004-4000-8000-000000000001', 'Dia 8 – Jesus, o Bom Pastor', 8, '{"pch": "O bom pastor dá a vida pelas suas ovelhas.", "interpretation": "Jesus nos conhece pelo nome e nos busca quando nos perdemos. Seu cuidado é pessoal, terno e sacrificial.", "practical_direction": "Descanse na certeza de que Jesus cuida de você hoje.", "guided_exercise": "Imagine-se nos ombros do Bom Pastor, sendo levado de volta ao redil.", "final_question": "Você reconhece a voz do seu Pastor no meio do ruído?"}'::jsonb),
('b1b1b1b1-0004-4000-8000-000000000001', 'Dia 9 – A Luz da Transfiguração', 9, '{"pch": "Este é o Meu Filho amado, ouvi-O.", "interpretation": "A glória de Jesus manifestada no Tabor nos dá força para enfrentar as sombras do Calvário. É o vislumbre do céu na terra.", "practical_direction": "Busque um momento de beleza ou oração intensa que ilumine seu dia.", "guided_exercise": "Contemple o rosto resplandecente de Jesus transfigurado.", "final_question": "Sua vida tem momentos de ''Tabor'' que te sustentam na luta?"}'::jsonb),
('b1b1b1b1-0004-4000-8000-000000000001', 'Dia 10 – Jesus no Horto das Oliveiras', 10, '{"pch": "Não se faça a minha vontade, mas a Tua.", "interpretation": "No Getsêmani, Jesus enfrentou o medo e a angústia suprema, escolhendo a obediência amorosa ao Pai acima de tudo.", "practical_direction": "Entregue a Deus uma angústia ou medo que te aflige hoje.", "guided_exercise": "Acompanhe Jesus em silêncio durante sua agonia no horto.", "final_question": "Você consegue dizer ''Fiat'' nos momentos de dor?"}'::jsonb),
('b1b1b1b1-0004-4000-8000-000000000001', 'Dia 11 – O Caminho do Calvário', 11, '{"pch": "Quem não carrega sua cruz não pode ser Meu discípulo.", "interpretation": "Seguir Jesus é abraçar a cruz com amor. Cada sofrimento unido ao Dele torna-se redentor e gera vida.", "practical_direction": "Carregue uma dificuldade de hoje com paciência e sem reclamar.", "guided_exercise": "Imagine-se ajudando Jesus a carregar a cruz, como o Cireneu.", "final_question": "A cruz é para você um escândalo ou o sinal da salvação?"}'::jsonb),
('b1b1b1b1-0004-4000-8000-000000000001', 'Dia 12 – A Vitória do Ressuscitado', 12, '{"pch": "Eu venci o mundo.", "interpretation": "A ressurreição é a prova final de que o Amor é mais forte que a morte. É a base da nossa esperança e alegria.", "practical_direction": "Viva o dia de hoje com a alegria de quem sabe que Cristo ressuscitou.", "guided_exercise": "Imagine o encontro com o Jesus Ressuscitado que te chama pelo nome.", "final_question": "Sua vida é marcada pela alegria da Ressurreição?"}'::jsonb),
('b1b1b1b1-0004-4000-8000-000000000001', 'Dia 13 – A Ascensão e o Envio', 13, '{"pch": "Eis que estou convosco todos os dias.", "interpretation": "Jesus sobe ao céu para nos preparar um lugar e nos envia ao mundo para sermos Suas mãos e pés na terra.", "practical_direction": "Faça uma ação concreta que manifeste a presença de Jesus para alguém.", "guided_exercise": "Sinta a presença invisível, mas real, de Jesus ao seu lado.", "final_question": "Como você tem cumprido a missão que Jesus te confiou?"}'::jsonb),
('b1b1b1b1-0004-4000-8000-000000000001', 'Dia 14 – Viver em Cristo Jesus', 14, '{"pch": "Permanecei em Mim e Eu permanecerei em vós.", "interpretation": "O fim da jornada é a união mística. Não apenas seguir Jesus, mas viver Nele, por Ele e para Ele em tudo.", "practical_direction": "Tente manter a consciência da presença de Jesus em cada respiração de hoje.", "guided_exercise": "Peça a graça de que sua vida seja uma transparência de Cristo.", "final_question": "Quem vive em você: seu ego ou Jesus?"}'::jsonb);

-- Expand Vivendo na Graça (e7a1b2c3-d4e5-4000-8000-000000000001) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('e7a1b2c3-d4e5-4000-8000-000000000001', 'A Graça no Dever de Estado', 8, '{"pch": "Tudo o que fizerdes, fazei-o de coração para o Senhor.", "interpretation": "A graça santifica o ordinário. Realizar bem o trabalho e os deveres familiares com amor é viver na plenitude da graça.", "practical_direction": "Realize sua tarefa mais simples hoje com total dedicação e amor.", "guided_exercise": "Ofereça seu trabalho como um sacrifício agradável a Deus.", "final_question": "Você vê seu trabalho como um fardo ou como um caminho de santidade?"}'::jsonb),
('e7a1b2c3-d4e5-4000-8000-000000000001', 'Os Dons do Espírito Santo em Nós', 9, '{"pch": "O Espírito sopra onde quer.", "interpretation": "A graça nos traz os sete dons que aperfeiçoam nossas virtudes e nos tornam dóceis às inspirações divinas.", "practical_direction": "Peça hoje o dom da Sabedoria ou da Fortaleza para um desafio específico.", "guided_exercise": "Imagine o Espírito Santo soprando sobre as velas da sua alma.", "final_question": "Você é dócil ou resistente às inspirações da graça?"}'::jsonb),
('e7a1b2c3-d4e5-4000-8000-000000000001', 'A Graça que Transfigura a Dor', 10, '{"pch": "A minha graça te basta.", "interpretation": "Na fraqueza, o poder da graça se manifesta plenamente. A dor, quando aceita com graça, torna-se luz e redenção.", "practical_direction": "Não reclame de um sofrimento físico ou moral hoje; ofereça-o em silêncio.", "guided_exercise": "Apoie sua fraqueza na força inquebrantável da graça divina.", "final_question": "Você permite que a graça cure e transforme sua dor?"}'::jsonb),
('e7a1b2c3-d4e5-4000-8000-000000000001', 'Viver sob o Olhar da Graça', 11, '{"pch": "Andai na minha presença e sede perfeitos.", "interpretation": "Viver na graça é tener a consciência contínua de ser olhado por um Pai amoroso que nos sustenta em cada passo.", "practical_direction": "Tente se lembrar de Deus pelo menos uma vez a cada hora hoje.", "guided_exercise": "Sinta o olhar de amor de Deus repousando sobre você agora.", "final_question": "Você vive como quem é amado ou como um órfão espiritual?"}'::jsonb),
('e7a1b2c3-d4e5-4000-8000-000000000001', 'A Humildade como Recipiente da Graça', 12, '{"pch": "Deus resiste aos soberbos, mas dá graça aos humildes.", "interpretation": "A graça é como a água: ela sempre corre para os lugares mais baixos. A humildade é o que atrai a plenitude de Deus.", "practical_direction": "Reconheça honestamente uma falha e peça a graça de melhorar.", "guided_exercise": "Imagine-se esvaziando-se de si para ser preenchido por Deus.", "final_question": "Seu orgulho tem sido uma barreira para a graça?"}'::jsonb),
('e7a1b2c3-d4e5-4000-8000-000000000001', 'A Perseverança Final na Graça', 13, '{"pch": "Permanecei no Meu amor.", "interpretation": "A maior de todas as graças é a de perseverar no bem até o último suspiro. É um dom que devemos pedir diariamente.", "practical_direction": "Reze hoje pedindo a graça de uma boa morte e da fidelidade final.", "guided_exercise": "Confie seu último momento nas mãos misericordiosas de Deus.", "final_question": "O que você tem feito para cuidar da sua vida espiritual hoje?"}'::jsonb),
('e7a1b2c3-d4e5-4000-8000-000000000001', 'A Glória: A Graça em sua Plenitude', 14, '{"pch": "Seremos semelhantes a Ele porque O veremos como Ele é.", "interpretation": "A glória do céu nada mais é do que a graça que chegou à sua maturidade total. É a visão face a face do Amor.", "practical_direction": "Faça um ato de desejo intenso pelo céu hoje.", "guided_exercise": "Imagine a paz e a alegria indescritível da união eterna com Deus.", "final_question": "Sua alma anseia pela Pátria definitiva?"}'::jsonb);

-- Expand Pão da Vida (e7a1b2c3-d4e5-4000-8000-000000000002) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('e7a1b2c3-d4e5-4000-8000-000000000002', 'Eucaristia: Força para a Caminhada', 8, '{"pch": "Levanta-te e come, porque o caminho é longo.", "interpretation": "Como o maná no deserto, a Eucaristia nos sustenta na jornada da vida, dando-nos força para não desfalecer.", "practical_direction": "Faça uma visita ao Santíssimo Sacramento se puder hoje.", "guided_exercise": "Sinta Jesus fortalecendo sua vontade através do Seu Pão.", "final_question": "Onde você busca forças nos dias de cansaço?"}'::jsonb),
('e7a1b2c3-d4e5-4000-8000-000000000002', 'O Silêncio Adorador', 9, '{"pch": "O Senhor está no Seu santo templo: cale-se diante Dele.", "interpretation": "Adorar é silenciar o ego para deixar Deus falar. No silêncio eucarístico, as almas se comunicam sem palavras.", "practical_direction": "Dedique 15 minutos à adoração silenciosa.", "guided_exercise": "Aquiete seus pensamentos e apenas olhe para o Amado.", "final_question": "Você consegue suportar o silêncio de Deus?"}'::jsonb),
('e7a1b2c3-d4e5-4000-8000-000000000002', 'Comunhão Espiritual: Desejo de Deus', 10, '{"pch": "Minha alma tem sede de Vós.", "interpretation": "Quando não podemos receber a comunhão sacramental, o desejo ardente de Jesus atrai Sua graça para o nosso coração.", "practical_direction": "Faça um ato de comunhão espiritual agora mesmo.", "guided_exercise": "Convide Jesus a habitar em seu coração com a mesma fé de um santo.", "final_question": "Qual é a intensidade do seu desejo por Deus?"}'::jsonb),
('e7a1b2c3-d4e5-4000-8000-000000000002', 'A Eucaristia e a Caridade com o Próximo', 11, '{"pch": "O que fizestes ao menor, a Mim o fizestes.", "interpretation": "Não podemos reconhecer Cristo no altar se não O reconhecemos no irmão sofredor. A Eucaristia nos envia ao serviço.", "practical_direction": "Faça uma obra de misericórdia corporal ou espiritual hoje.", "guided_exercise": "Veja o rosto de Jesus na pessoa mais difícil que encontrar hoje.", "final_question": "Sua comunhão te torna mais caridoso?"}'::jsonb),
('e7a1b2c3-d4e5-4000-8000-000000000002', 'O Coração Eucarístico de Jesus', 12, '{"pch": "Vinde a Mim todos os que estais cansados.", "interpretation": "A Eucaristia é o Coração aberto de Jesus transbordando amor por nós. É o refúgio seguro para nossas almas inquietas.", "practical_direction": "Repouse hoje suas preocupações no Coração Eucarístico de Jesus.", "guided_exercise": "Imagine-se encostando a cabeça no peito do Senhor, como João.", "final_question": "Você confia no amor que se faz pão por você?"}'::jsonb),
('e7a1b2c3-d4e5-4000-8000-000000000002', 'A Celebração do Banquete Eterno', 13, '{"pch": "Bem-aventurados os convidados para a ceia do Cordeiro.", "interpretation": "A missa é um antegozo do banquete celestial. Cada comunhão nos prepara para a união definitiva no Reino.", "practical_direction": "Reze hoje pedindo a graça de um dia participar da glória eterna.", "guided_exercise": "Imagine a festa sem fim que Deus preparou para Seus amigos.", "final_question": "Sua alma está vestida para a festa do Rei?"}'::jsonb),
('e7a1b2c3-d4e5-4000-8000-000000000002', 'Ser Eucaristia para o Mundo', 14, '{"pch": "Ite, missa est.", "interpretation": "O fim da missa é o início da nossa missão. Devemos ser ''pão partido'' para a vida do mundo, levando a paz de Cristo.", "practical_direction": "Seja uma presença de paz e alimento espiritual para alguém hoje.", "guided_exercise": "Peça a graça de ser transformado naquilo que você recebe.", "final_question": "Sua vida tem sabor de Evangelho?"}'::jsonb);

-- Expand Coração Inquieto (e7a1b2c3-d4e5-4000-8000-000000000003) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('e7a1b2c3-d4e5-4000-8000-000000000003', 'A Oração nas Noites Escuras', 8, '{"pch": "Por que estás triste, minha alma?", "interpretation": "Na aridez, a oração torna-se puro ato de vontade e fé. É o tempo de amar a Deus sem esperar nada em troca.", "practical_direction": "Não abandone sua oração hoje mesmo que sinta total tédio ou vazio.", "guided_exercise": "Permaneça fiel no deserto, confiando na chuva da graça que virá.", "final_question": "Você reza por amor ou por prazer espiritual?"}'::jsonb),
('e7a1b2c3-d4e5-4000-8000-000000000003', 'A Intercessão que Move o Céu', 9, '{"pch": "Batei e abrir-se-vos-á.", "interpretation": "Rezar pelos outros é um dever de caridade. A oração persistente agrada o Coração de Deus e atrai Suas bênçãos.", "practical_direction": "Ofereça um terço ou uma oração fervorosa por alguém em grande aflição hoje.", "guided_exercise": "Apresente os nomes dos seus entes queridos ao Senhor.", "final_question": "Seu coração é largo para acolher as necessidades alheias?"}'::jsonb),
('e7a1b2c3-d4e5-4000-8000-000000000003', 'A Lectio Divina: Ouvir a Palavra', 10, '{"pch": "Tua Palavra é lâmpada para os meus pés.", "interpretation": "Rezar com a Bíblia é entrar em diálogo direto com Deus. Ele fala, nós ouvimos e respondemos com a vida.", "practical_direction": "Faça a leitura meditada de um salmo hoje.", "guided_exercise": "Peça ao Espírito Santo que te revele a mensagem de Deus para hoje.", "final_question": "Você deixa a Palavra questionar suas escolhas?"}'::jsonb),
('e7a1b2c3-d4e5-4000-8000-000000000003', 'A Oração de Abandono', 11, '{"pch": "Pai, em Tuas mãos entrego o meu espírito.", "interpretation": "Abandonar-se é soltar o controle e confiar que Deus sabe o que é melhor para nós, mesmo no meio da incerteza.", "practical_direction": "Sempre que se sentir ansioso hoje, diga: Senhor, eu Te entrego isso.", "guided_exercise": "Imagine-se boiando no mar da misericórdia de Deus.", "final_question": "Do que você ainda tem medo de abrir mão?"}'::jsonb),
('e7a1b2c3-d4e5-4000-8000-000000000003', 'O Ritmo da Oração Diária', 12, '{"pch": "Orai sem cessar.", "interpretation": "A oração não deve ser um evento isolado, mas o fôlego da alma que permeia todas as horas e atividades do dia.", "practical_direction": "Crie ''ilhas de oração'' durante o seu horário de trabalho.", "guided_exercise": "Respire o nome de Jesus a cada momento de consciência.", "final_question": "Sua vida é uma oração ou você apenas reza às vezes?"}'::jsonb),
('e7a1b2c3-d4e5-4000-8000-000000000003', 'A Contemplação no Meio do Mundo', 13, '{"pch": "Eles verão a Deus.", "interpretation": "A contemplação não é exclusiva dos conventos. É possível ter um coração contemplativo e mãos ocupadas no serviço do mundo.", "practical_direction": "Procure ver a digital de Deus em um colega de trabalho hoje.", "guided_exercise": "Mantenha um olhar interior fixo em Deus enquanto age.", "final_question": "Você consegue encontrar Deus no meio da agitação?"}'::jsonb),
('e7a1b2c3-d4e5-4000-8000-000000000003', 'A Unidade com o Amado', 14, '{"pch": "O meu Amado é para mim e eu sou para Ele.", "interpretation": "O fim da oração é a comunhão total de vontades. É quando o nosso coração finalmente descansa no Coração de Deus.", "practical_direction": "Faça um ato de amor puro e desinteressado a Deus hoje.", "guided_exercise": "Descanse no silêncio do amor que não precisa mais de palavras.", "final_question": "Seu coração finalmente encontrou sua morada?"}'::jsonb);

-- Update estimated_days for these journeys
UPDATE public.journeys SET estimated_days = 14 WHERE id IN (
  'b1b1b1b1-0003-4000-8000-000000000001',
  'b1b1b1b1-0004-4000-8000-000000000001',
  'e7a1b2c3-d4e5-4000-8000-000000000001',
  'e7a1b2c3-d4e5-4000-8000-000000000002',
  'e7a1b2c3-d4e5-4000-8000-000000000003'
);