-- Expand Discernimento Vocacional (b1b2c3d4-3333-4000-8000-000000000003) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('b1b2c3d4-3333-4000-8000-000000000003', 'A Importância da Direção Espiritual', 8, '{"pch": "Ninguém é bom juiz em causa própria.", "interpretation": "A direção espiritual é o auxílio de um irmão mais experiente para discernir as moções do Espírito (CIC §2690).", "practical_direction": "Procure um sacerdote ou leigo maduro para conversar sobre sua caminhada.", "guided_exercise": "Peça a Deus que coloque um guia seguro em seu caminho.", "final_question": "Você tem humildade para ser guiado?"}'::jsonb),
('b1b2c3d4-3333-4000-8000-000000000003', 'A Vontade de Deus e o Meu Desejo', 9, '{"pch": "Deus não é um tirano; Ele é o autor da nossa alegria.", "interpretation": "A vontade de Deus e o nosso desejo mais profundo muitas vezes coincidem no centro da alma.", "practical_direction": "Identifique um desejo que lhe traz paz profunda e não apenas prazer imediato.", "guided_exercise": "Apresente seus desejos a Deus e veja quais permanecem sob o Seu olhar.", "final_question": "Você acredita que Deus quer a sua felicidade?"}'::jsonb),
('b1b2c3d4-3333-4000-8000-000000000003', 'O Discernimento nas Pequenas Coisas', 10, '{"pch": "Quem é fiel no pouco, será fiel no muito.", "interpretation": "A vocação se constrói nas decisões cotidianas, não apenas nos grandes momentos.", "practical_direction": "Tome uma decisão hoje baseada no amor, não na conveniência.", "guided_exercise": "Reveja as pequenas escolhas de hoje: elas apontam para onde?", "final_question": "Como você está servindo a Deus no ordinário?"}'::jsonb),
('b1b2c3d4-3333-4000-8000-000000000003', 'Enfrentando o Medo da Decisão', 11, '{"pch": "O medo paralisante não vem de Deus.", "interpretation": "A paralisia da análise é uma armadilha. Deus nos sustenta mesmo no risco da escolha.", "practical_direction": "Identifique qual medo te impede de dar o próximo passo.", "guided_exercise": "Reze com o Salmo 23: O Senhor é meu pastor, nada me faltará.", "final_question": "O que você faria se não tivesse medo?"}'::jsonb),
('b1b2c3d4-3333-4000-8000-000000000003', 'A Vocação como Serviço e Dom', 12, '{"pch": "Quem não vive para servir, não serve para viver.", "interpretation": "Toda vocação é essencialmente um chamado ao amor e ao serviço aos outros.", "practical_direction": "Realize um ato concreto de serviço hoje, sem que ninguém perceba.", "guided_exercise": "Medite sobre o lava-pés (João 13).", "final_question": "Sua vida tem sido um dom para os outros?"}'::jsonb),
('b1b2c3d4-3333-4000-8000-000000000003', 'Perseverança no Caminho Escolhido', 13, '{"pch": "A perseverança é a coragem prolongada.", "interpretation": "O discernimento não termina na escolha; ele se confirma na fidelidade diária.", "practical_direction": "Renove hoje o seu compromisso com a sua realidade atual.", "guided_exercise": "Peça a graça da constância nas tribulações.", "final_question": "Você está disposto a carregar a cruz da sua escolha?"}'::jsonb),
('b1b2c3d4-3333-4000-8000-000000000003', 'A Confirmação do Espírito', 14, '{"pch": "A paz é o selo da vontade de Deus.", "interpretation": "A alegria espiritual e a paz interior são os sinais clássicos de que estamos no caminho certo.", "practical_direction": "Agradeça a Deus pelo caminho percorrido até aqui.", "guided_exercise": "Faça um ato de confiança total na Providência.", "final_question": "Seu coração está em paz com a direção que está tomando?"}'::jsonb);

-- Expand Teologia do Corpo (b1b2c3d4-4444-4000-8000-000000000004) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('b1b2c3d4-4444-4000-8000-000000000004', 'O Matrimônio como Sacramento', 8, '{"pch": "O amor humano é um sinal do amor divino.", "interpretation": "O matrimônio revela o mistério da união de Cristo com a Igreja (Efésios 5).", "practical_direction": "Reze por um casal que você conhece ou pela sua futura família.", "guided_exercise": "Medite sobre a entrega total na cruz como modelo de amor conjugal.", "final_question": "Como o seu amor pode se tornar mais generoso?"}'::jsonb),
('b1b2c3d4-4444-4000-8000-000000000004', 'A Virgindade pelo Reino', 9, '{"pch": "Um coração indiviso para o Senhor.", "interpretation": "A virgindade consagrada antecipa a vida eterna, onde seremos como anjos no céu.", "practical_direction": "Valorize o silêncio e a oração como momentos de intimidade exclusiva com Deus.", "guided_exercise": "Peça a graça de amar a Deus sobre todas as coisas.", "final_question": "Deus é o centro absoluto da sua vida?"}'::jsonb),
('b1b2c3d4-4444-4000-8000-000000000004', 'A Paternidade e Maternidade Responsável', 10, '{"pch": "Cooperadores da criação divina.", "interpretation": "A abertura à vida é parte essencial do amor humano, participando do poder criador de Deus.", "practical_direction": "Agradeça aos seus pais pelo dom da sua vida.", "guided_exercise": "Reflita sobre a responsabilidade de cuidar e educar para o céu.", "final_question": "Você vê a vida como um dom ou como um peso?"}'::jsonb),
('b1b2c3d4-4444-4000-8000-000000000004', 'A Ressurreição da Carne', 11, '{"pch": "Creio na ressurreição dos mortos.", "interpretation": "Nosso corpo não é uma casca descartável; ele será transfigurado e reerguido na glória.", "practical_direction": "Trate seu corpo com o respeito devido a um templo que viverá para sempre.", "guided_exercise": "Visualize a glória da ressurreição no fim dos tempos.", "final_question": "Como essa esperança muda a forma como você cuida de si?"}'::jsonb),
('b1b2c3d4-4444-4000-8000-000000000004', 'O Sentido Esponsal do Corpo na Eternidade', 12, '{"pch": "Seremos um com Deus para sempre.", "interpretation": "Na eternidade, a sede de comunhão será plenamente saciada na visão beatífica.", "practical_direction": "Busque momentos de adoração eucarística, antecipação do céu.", "guided_exercise": "Repouse no amor infinito que te espera.", "final_question": "Sua alma tem sede de Deus?"}'::jsonb),
('b1b2c3d4-4444-4000-8000-000000000004', 'Vivendo a Pureza no Mundo Moderno', 13, '{"pch": "Bem-aventurados os puros de coração.", "interpretation": "A pureza não é repressão, mas a liberdade de amar sem usar o outro como objeto.", "practical_direction": "Faça uma limpeza nos seus sentidos (olhos, ouvidos) hoje.", "guided_exercise": "Peça a intercessão da Virgem Maria pela sua castidade.", "final_question": "Seu olhar vê a dignidade ou a utilidade das pessoas?"}'::jsonb),
('b1b2c3d4-4444-4000-8000-000000000004', 'A Plenitude do Amor Humano', 14, '{"pch": "Tudo é vosso, vós sois de Cristo e Cristo é de Deus.", "interpretation": "A Teologia do Corpo nos leva a descobrir que somos feitos para o Amor infinito.", "practical_direction": "Resuma o que aprendeu nesta jornada e coloque em prática um ponto principal.", "guided_exercise": "Ofereça todo o seu ser a Deus em um ato de amor.", "final_question": "Você está pronto para viver a aventura do Amor?"}'::jsonb);

-- Update estimated_days for these journeys
UPDATE public.journeys SET estimated_days = 14 WHERE id IN ('b1b2c3d4-3333-4000-8000-000000000003', 'b1b2c3d4-4444-4000-8000-000000000004');
