-- Expand Rotina Espiritual (a1b2c3d4-1111-4000-8000-000000000001) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('a1b2c3d4-1111-4000-8000-000000000001', 'Oração ao Meio-Dia (Angelus)', 8, '{"pch": "O Verbo se fez carne e habitou entre nós.", "interpretation": "A oração do Angelus ao meio-dia é um convite para interromper a agitação e recordar o mistério da Encarnação.", "practical_direction": "Coloque um lembrete no celular para as 12h e reze o Angelus (ou uma Ave-Maria).", "guided_exercise": "Agradeça a Deus pelo dom de Jesus ter se feito homem por nós.", "final_question": "Como você pode trazer Deus para o centro do seu dia de trabalho?"}'::jsonb),
('a1b2c3d4-1111-4000-8000-000000000001', 'Santificação do Trabalho', 9, '{"pch": "Tudo o que fizerdes, fazei-o de todo o coração, como para o Senhor.", "interpretation": "O trabalho não é um castigo, mas uma oportunidade de colaborar com a criação e servir ao próximo.", "practical_direction": "Ofereça seu trabalho de hoje por uma intenção específica.", "guided_exercise": "Trabalhe com excelência, vendo a presença de Deus em cada tarefa.", "final_question": "Você enxerga seu trabalho como uma forma de amar a Deus?"}'::jsonb),
('a1b2c3d4-1111-4000-8000-000000000001', 'Oração em Família ou Comunidade', 10, '{"pch": "Onde dois ou três estiverem reunidos em meu nome, ali estarei.", "interpretation": "A rotina espiritual ganha força quando compartilhada. A família é a igreja doméstica.", "practical_direction": "Tente rezar uma pequena oração (um Pai-Nosso, por exemplo) com alguém hoje.", "guided_exercise": "Peça a Deus que abençoe seus relacionamentos e os torne santos.", "final_question": "Como você pode ser um canal de fé para quem vive com você?"}'::jsonb),
('a1b2c3d4-1111-4000-8000-000000000001', 'Visita ao Santíssimo', 11, '{"pch": "Vinde a Mim todos vós que estais cansados.", "interpretation": "Visitar Jesus no Sacrário é encontrar o amigo que sempre nos espera em silêncio.", "practical_direction": "Se puder, passe em uma igreja hoje por 5 minutos apenas para estar com Ele.", "guided_exercise": "Fique em silêncio diante de Jesus e deixe-O olhar para você.", "final_question": "Você tem buscado refúgio no Coração de Jesus?"}'::jsonb),
('a1b2c3d4-1111-4000-8000-000000000001', 'Combate Espiritual na Rotina', 12, '{"pch": "Vigiai e orai para não entrardes em tentação.", "interpretation": "A rotina é o campo de batalha onde vencemos o egoísmo e a preguiça.", "practical_direction": "Identifique a maior tentação que surge na sua rotina e prepare uma defesa (uma jaculatória).", "guided_exercise": "Reze a oração de São Miguel Arcanjo pedindo proteção.", "final_question": "Em quais momentos da rotina você se sente mais fraco espiritualmente?"}'::jsonb),
('a1b2c3d4-1111-4000-8000-000000000001', 'O Valor do Domingo', 13, '{"pch": "Lembra-te do dia de sábado para o santificar.", "interpretation": "O Domingo é o Dia do Senhor, um oásis de descanso e celebração da Ressurreição.", "practical_direction": "Prepare-se para o próximo domingo: como você vai torná-lo um dia verdadeiramente sagrado?", "guided_exercise": "Agradeça a Deus pelo dom do repouso e da Missa dominical.", "final_question": "Seu domingo tem sido diferente dos outros dias da semana?"}'::jsonb),
('a1b2c3d4-1111-4000-8000-000000000001', 'Vida como Oração Contínua', 14, '{"pch": "Orai sem cessar.", "interpretation": "O objetivo da rotina espiritual é que nossa própria vida se torne um ato de louvor a Deus.", "practical_direction": "Resuma o que mudou na sua rotina nestes 14 dias.", "guided_exercise": "Consagre todo o seu tempo e todas as suas ações ao Senhor.", "final_question": "Você percebe que Deus caminha com você em cada segundo do seu dia?"}'::jsonb);

-- Expand Vida de Oração (a1b2c3d4-2222-4000-8000-000000000002) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('a1b2c3d4-2222-4000-8000-000000000002', 'Oração de Louvor', 8, '{"pch": "Bendize, ó minha alma, ao Senhor!", "interpretation": "O louvor é a oração que reconhece a grandeza de Deus por Ele mesmo, sem pedir nada.", "practical_direction": "Passe 10 minutos apenas louvando a Deus pelas Suas qualidades.", "guided_exercise": "Use os Salmos de louvor (como o 148 ou 150) para rezar hoje.", "final_question": "Seu coração sabe ser grato pela simples existência de Deus?"}'::jsonb),
('a1b2c3d4-2222-4000-8000-000000000002', 'Oração de Ação de Graças', 9, '{"pch": "Em tudo dai graças.", "interpretation": "A gratidão abre as portas para novas graças. Reconhecer os benefícios de Deus é um dever de amor.", "practical_direction": "Escreva ou pense em 5 coisas pelas quais você é grato a Deus hoje.", "guided_exercise": "Agradeça a Deus até pelas dificuldades que te fizeram crescer.", "final_question": "Você costuma agradecer mais do que pedir?"}'::jsonb),
('a1b2c3d4-2222-4000-8000-000000000002', 'Adoração Eucarística', 10, '{"pch": "Meu Senhor e meu Deus!", "interpretation": "A adoração é o reconhecimento da nossa pequenez diante da majestade infinita de Deus presente na Eucaristia.", "practical_direction": "Procure um momento de adoração, mesmo que seja espiritual (em pensamento) se não houver igreja aberta.", "guided_exercise": "Repita interiormente: Eu Vos adoro em cada pedaço de Pão consagrado no mundo.", "final_question": "Você se sente pequeno e amado na presença de Deus?"}'::jsonb),
('a1b2c3d4-2222-4000-8000-000000000002', 'Oração Contemplativa (Interiorização)', 11, '{"pch": "Entra no teu quarto e fecha a porta.", "interpretation": "A contemplação é um olhar de fé fixo em Jesus, um silêncio amoroso onde as palavras não são mais necessárias.", "practical_direction": "Fique 5 minutos em silêncio absoluto, apenas sentindo a presença de Deus em sua alma.", "guided_exercise": "Feche os olhos e imagine Jesus sentado ao seu lado, em silêncio.", "final_question": "Você consegue suportar o silêncio para ouvir a Deus?"}'::jsonb),
('a1b2c3d4-2222-4000-8000-000000000002', 'O Dom das Lágrimas e a Compunção', 12, '{"pch": "Bem-aventurados os que choram, porque serão consolados.", "interpretation": "A compunção é a dor suave do coração que reconhece o próprio pecado diante do amor infinito de Deus.", "practical_direction": "Peça a Deus a graça de um coração arrependido e sensível ao Teu amor.", "guided_exercise": "Medite sobre a Paixão de Cristo e veja o quanto Ele te ama.", "final_question": "Seu coração é de pedra ou é sensível à graça?"}'::jsonb),
('a1b2c3d4-2222-4000-8000-000000000002', 'A Oração do Coração (Oração de Jesus)', 13, '{"pch": "Senhor Jesus Cristo, Filho de Deus, tem piedade de mim, pecador.", "interpretation": "Esta oração milenar busca sintonizar a batida do coração com o nome de Jesus, tornando a oração contínua.", "practical_direction": "Repita a Oração de Jesus ritmicamente com a sua respiração por alguns minutos.", "guided_exercise": "Inspirar: Senhor Jesus Cristo... Expirar: tem piedade de mim.", "final_question": "O nome de Jesus está gravado no seu pensamento?"}'::jsonb),
('a1b2c3d4-2222-4000-8000-000000000002', 'Unindo Oração e Vida', 14, '{"pch": "Seja feita a Vossa vontade.", "interpretation": "A oração atinge sua plenitude quando nos leva a agir com caridade e a aceitar a vontade de Deus em tudo.", "practical_direction": "Faça um propósito concreto de caridade para selar estes 14 dias de oração.", "guided_exercise": "Ofereça sua vida como um sacrifício vivo, santo e agradável a Deus.", "final_question": "Como sua vida mudou depois de intensificar sua amizade com Deus na oração?"}'::jsonb);

-- Update estimated_days for these journeys
UPDATE public.journeys SET estimated_days = 14 WHERE id IN ('a1b2c3d4-1111-4000-8000-000000000001', 'a1b2c3d4-2222-4000-8000-000000000002');