-- 1. Expand Silêncio e Escuta (d1d1d1d1-0001-4000-8000-000000000001)
INSERT INTO public.journey_steps (id, journey_id, step_order, title, content) VALUES
(gen_random_uuid(), 'd1d1d1d1-0001-4000-8000-000000000001', 8, 'O Silêncio no Sofrimento', '{"pch": "Jesus, porém, calava-se.", "interpretation": "No sofrimento, muitas vezes não há explicações. O silêncio torna-se então o lugar da entrega e da união com o Cristo sofredor.", "practical_direction": "Hoje, quando enfrentar uma dificuldade, não reclame. Ofereça o silêncio como prece.", "guided_exercise": "Acompanhe Jesus em silêncio no Horto das Oliveiras.", "final_question": "Você consegue aceitar que o silêncio de Deus às vezes é Sua resposta mais profunda?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0001-4000-8000-000000000001', 9, 'A Escuta no Serviço ao Próximo', '{"pch": "Tudo o que fizestes ao menor, a Mim o fizestes.", "interpretation": "Escutar o próximo é a primeira forma de caridade. É abrir espaço para o outro no seu coração.", "practical_direction": "Escute alguém hoje com total atenção, sem interromper ou julgar.", "guided_exercise": "Visualize a pessoa que você escutará e peça a graça de ver Cristo nela.", "final_question": "Você ouve para entender ou apenas para responder?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0001-4000-8000-000000000001', 10, 'O Silêncio da Mente: Combatendo Pensamentos', '{"pch": "Leva cativo todo pensamento à obediência de Cristo.", "interpretation": "Nossa mente é um campo de batalha. O silêncio interior exige a disciplina de afastar distrações e focar no Essencial.", "practical_direction": "Identifique uma preocupação recorrente e a entregue conscientemente a Deus.", "guided_exercise": "Sente-se em silêncio e imagine seus pensamentos como nuvens passando no céu.", "final_question": "Quem é o dono da sua mente: você ou suas preocupações?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0001-4000-8000-000000000001', 11, 'A Escuta na Criação: Deus fala na Natureza', '{"pch": "Os céus narram a glória de Deus.", "interpretation": "A natureza é o primeiro livro de Deus. Nela, o Criador deixou Sua assinatura e Sua voz suave.", "practical_direction": "Observe uma planta, o céu ou um animal hoje e agradeça pela vida.", "guided_exercise": "Contemple a beleza de algo natural por 5 minutos, em silêncio.", "final_question": "Você consegue ouvir o louvor silencioso de toda a criação?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0001-4000-8000-000000000001', 12, 'O Silêncio da Eucaristia', '{"pch": "Eis o Pão dos Anjos.", "interpretation": "Na hóstia consagrada, Deus se faz silêncio total. Adorar é sintonizar nossa alma com esse silêncio divino.", "practical_direction": "Faça uma visita ao Santíssimo e permaneça apenas olhando para Jesus.", "guided_exercise": "Adore o Senhor em espírito, no silêncio da sua alma.", "final_question": "Sua alma se aquieta diante da Presença Real?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0001-4000-8000-000000000001', 13, 'A Escuta do Mestre Interior', '{"pch": "O Reino de Deus está dentro de vós.", "interpretation": "O Espírito Santo habita no centro da nossa alma. Para ouvi-Lo, precisamos mergulhar fundo em nosso próprio deserto.", "practical_direction": "Pergunte ao Senhor: ''O que queres de mim hoje?'' e aguarde no silêncio.", "guided_exercise": "Desça para o seu coração e escute o sussurro da graça.", "final_question": "Você tem coragem de olhar para o que existe dentro de você?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0001-4000-8000-000000000001', 14, 'Viver no Centro do Silêncio', '{"pch": "Paz eu vos deixo, a minha paz vos dou.", "interpretation": "O silêncio não deve ser apenas um refúgio, mas uma fundação. Devemos agir e falar a partir de um centro silencioso.", "practical_direction": "Tente manter uma paz interior profunda enquanto realiza suas tarefas diárias.", "guided_exercise": "Imagine um mar calmo sob a tempestade das atividades diárias.", "final_question": "Sua vida é um barulho ou uma sinfonia silenciosa para Deus?"}'::jsonb);

-- 2. Expand As Bem-Aventuranças (d1d1d1d1-0002-4000-8000-000000000001)
INSERT INTO public.journey_steps (id, journey_id, step_order, title, content) VALUES
(gen_random_uuid(), 'd1d1d1d1-0002-4000-8000-000000000001', 8, 'Os Perseguidos pela Justiça', '{"pch": "Bem-aventurados os perseguidos, porque deles é o reino dos céus.", "interpretation": "Viver as Bem-Aventuranças atrai a oposição do mundo. A perseguição é o selo da fidelidade ao Evangelho.", "practical_direction": "Não esconda sua fé ou seus valores hoje, mesmo sob pressão social.", "guided_exercise": "Peça força aos mártires para sustentar suas convicções com amor.", "final_question": "Você prefere a paz do mundo ou a recompensa do Reino?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0002-4000-8000-000000000001', 9, 'A Recompensa do Reino', '{"pch": "Alegrai-vos e exultai, porque é grande a vossa recompensa.", "interpretation": "As Bem-Aventuranças não são apenas exigências, mas promessas. O fim da caminhada é a alegria plena de Deus.", "practical_direction": "Pense no céu hoje como o destino final de cada uma das suas lutas.", "guided_exercise": "Visualize a alegria de encontrar o Senhor face a face.", "final_question": "Sua esperança está ancorada nesta vida ou na eternidade?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0002-4000-8000-000000000001', 10, 'O Sal da Terra', '{"pch": "Vós sois o sal da terra.", "interpretation": "O cristão deve dar sabor ao mundo e preservá-lo da corrupção. As Bem-Aventuranças nos tornam esse tempero.", "practical_direction": "Traga alegria e sentido a uma conversa ou ambiente pesado hoje.", "guided_exercise": "Peça a Deus para que sua vida nunca perca o sabor do Evangelho.", "final_question": "Qual é o ''sabor'' que você tem deixado por onde passa?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0002-4000-8000-000000000001', 11, 'A Luz do Mundo', '{"pch": "Vós sois a luz do mundo.", "interpretation": "Nossa luz não é própria, mas o reflexo de Cristo em nós. As Bem-Aventuranças limpam o espelho da nossa alma.", "practical_direction": "Realize uma boa obra hoje com a intenção de glorificar ao Pai.", "guided_exercise": "Imagine-se como uma luz em um lugar escuro.", "final_question": "Sua presença ilumina ou escurece os ambientes?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0002-4000-8000-000000000001', 12, 'A Nova Lei: O Amor', '{"pch": "Ouvistes o que foi dito... Eu, porém, vos digo.", "interpretation": "Jesus leva a lei ao seu cumprimento: o amor total. Não basta não matar; é preciso não odiar.", "practical_direction": "Deseje o bem de coração a alguém que te incomodou hoje.", "guided_exercise": "Peça um coração semelhante ao de Jesus, capaz de amar sem limites.", "final_question": "Sua religião é de regras ou de amor?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0002-4000-8000-000000000001', 13, 'O Pai Nosso: A Oração do Reino', '{"pch": "Pai nosso, que estais no céu.", "interpretation": "As Bem-Aventuranças nos tornam filhos e filhas. A oração do Senhor é a síntese do caminho das Bem-Aventuranças.", "practical_direction": "Reze o Pai Nosso lentamente hoje, parando em cada frase.", "guided_exercise": "Sinta o abraço de Deus ao chamá-Lo de ''Pai''.", "final_question": "Você vive como um filho amado ou como um órfão?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0002-4000-8000-000000000001', 14, 'Viver as Bem-Aventuranças no Mundo', '{"pch": "Sede perfeitos como o vosso Pai é perfeito.", "interpretation": "As Bem-Aventuranças são o estilo de vida de quem já vive o Reino. É o caminho da santidade cotidiana.", "practical_direction": "Escolha a Bem-Aventurança que mais te desafia e foque nela hoje.", "guided_exercise": "Consagre sua vida a seguir o caminho traçado por Jesus no monte.", "final_question": "Qual é o seu ''monte'' de hoje?"}'::jsonb);

-- 3. Expand Espiritualidade do Trabalho (d1d1d1d1-0003-4000-8000-000000000001)
INSERT INTO public.journey_steps (id, journey_id, step_order, title, content) VALUES
(gen_random_uuid(), 'd1d1d1d1-0003-4000-8000-000000000001', 8, 'O Descanso Sagrado', '{"pch": "Ao sétimo dia, Deus descansou.", "interpretation": "O descanso não é perda de tempo, mas um ato de adoração e confiança. Reconhecemos que o mundo continua sem nós.", "practical_direction": "Desconecte-se de tarefas profissionais e dedique tempo à sua alma e família.", "guided_exercise": "Sinta a paz de saber que Deus é quem sustenta todas as coisas.", "final_question": "Você trabalha para viver ou vive para trabalhar?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0003-4000-8000-000000000001', 9, 'O Trabalho como Co-criação', '{"pch": "Deus o colocou no jardim para o cultivar.", "interpretation": "Pelo trabalho, participamos da obra criadora de Deus. Cada tarefa bem feita aperfeiçoa a criação.", "practical_direction": "Execute seu trabalho hoje com excelência, como um presente para Deus.", "guided_exercise": "Veja a beleza do que você produz e louve ao Criador.", "final_question": "Você percebe a dignidade divina no seu ofício?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0003-4000-8000-000000000001', 10, 'Vencendo a Preguiça e a Desordem', '{"pch": "Vai ter com a formiga, ó preguiçoso.", "interpretation": "A preguiça corrói a alma e desfigura nossa vocação. A ordem e a disciplina são expressões de amor ao próximo.", "practical_direction": "Organize seu ambiente de trabalho e comece pela tarefa mais difícil.", "guided_exercise": "Peça a virtude da fortaleza para vencer a inércia.", "final_question": "Onde você tem sido relapso e precisa de mais brio?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0003-4000-8000-000000000001', 11, 'A Justiça e a Solidariedade', '{"pch": "O operário é digno do seu salário.", "interpretation": "O trabalho é um meio de prover para si e de servir à comunidade. A justiça social começa na ética diária.", "practical_direction": "Trate todos os colegas e prestadores de serviço com máximo respeito.", "guided_exercise": "Agradeça por todos que tornam seu trabalho possível.", "final_question": "Você tem sido justo e generoso em suas relações profissionais?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0003-4000-8000-000000000001', 12, 'O Testemunho da Verdade', '{"pch": "A vossa palavra seja sim, sim; não, não.", "interpretation": "Integridade é ser o mesmo em casa e no trabalho. O testemunho cristão no mundo passa pela honestidade radical.", "practical_direction": "Não faça fofocas nem use de meias-verdades no ambiente profissional hoje.", "guided_exercise": "Peça a transparência de Cristo em suas palavras e atos.", "final_question": "As pessoas confiam em você por causa da sua fé?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0003-4000-8000-000000000001', 13, 'Oferecendo os Frutos ao Senhor', '{"pch": "Apresentamos o fruto do nosso trabalho.", "interpretation": "O trabalho não é um fim em si mesmo. Ele deve ser oferecido a Deus como incenso suave e sacrifício vivo.", "practical_direction": "Faça um ato de oferecimento antes de começar cada bloco de trabalho hoje.", "guided_exercise": "Imagine-se colocando seu dia de trabalho sobre o altar do Senhor.", "final_question": "O que você tem para oferecer a Deus hoje?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0003-4000-8000-000000000001', 14, 'O Fim do Trabalho: A Adoração', '{"pch": "Aquele que trabalha, ora.", "interpretation": "No final, o trabalho deve nos levar à adoração. Ele prepara o nosso coração para o descanso eterno na glória.", "practical_direction": "Agradeça pelo dia de trabalho e peça perdão pelas falhas cometidas.", "guided_exercise": "Repouse em Deus após a jornada, sabendo que cumpriu seu dever.", "final_question": "Seu trabalho te aproxima ou te afasta de Deus?"}'::jsonb);

-- 4. Expand Os Sacramentos (d1d1d1d1-0004-4000-8000-000000000001)
INSERT INTO public.journey_steps (id, journey_id, step_order, title, content) VALUES
(gen_random_uuid(), 'd1d1d1d1-0004-4000-8000-000000000001', 8, 'A Liturgia: O Mistério da Fé', '{"pch": "Isto é o Meu Corpo.", "interpretation": "Os sacramentos acontecem na Liturgia. Nela, o céu e a terra se encontram e o tempo se torna eterno.", "practical_direction": "Reze pedindo a graça de participar da Santa Missa com mais consciência.", "guided_exercise": "Imagine-se presente na Última Ceia de Jesus.", "final_question": "A Liturgia é para você um ritual ou um mistério vivo?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0004-4000-8000-000000000001', 9, 'Os Sinais: Água, Óleo e Pão', '{"pch": "A matéria é sagrada.", "interpretation": "Deus usa as coisas simples deste mundo para nos comunicar Sua vida invisível. Tudo na criação pode ser canal da graça.", "practical_direction": "Use água benta ou tenha um objeto religioso com respeito hoje.", "guided_exercise": "Agradeça pelos sentidos que te permitem perceber a presença de Deus.", "final_question": "Você consegue ver o sagrado no cotidiano?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0004-4000-8000-000000000001', 10, 'O Ano Litúrgico: O Ritmo do Tempo', '{"pch": "Há um tempo para cada coisa.", "interpretation": "Viver o ano litúrgico é viver a vida de Cristo em ciclos. É santificar o tempo em que vivemos.", "practical_direction": "Verifique em que tempo litúrgico estamos e medite sobre sua mensagem.", "guided_exercise": "Sintonize seu coração com o ritmo da Igreja.", "final_question": "O seu tempo é de Deus ou apenas das suas tarefas?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0004-4000-8000-000000000001', 11, 'A Mãe de Deus na Liturgia', '{"pch": "Salve, ó cheia de graça.", "interpretation": "Maria está no centro do mistério cristão. Ela nos ensina a acolher a Palavra e a gerar Cristo no mundo.", "practical_direction": "Reze um mistério do Rosário contemplando a presença de Maria nos sacramentos.", "guided_exercise": "Pense no ''Sim'' de Maria como a porta para todos os sacramentos.", "final_question": "Maria tem um lugar central em sua vida de oração?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0004-4000-8000-000000000001', 12, 'Os Santos: Nossos Irmãos no Céu', '{"pch": "A comunhão dos santos.", "interpretation": "Não caminhamos sozinhos. Os santos intercedem por nós e nos mostram que a vida sacramental gera frutos eternos.", "practical_direction": "Leia a vida de um santo que você admira e peça sua intercessão.", "guided_exercise": "Imagine-se rodeado por uma multidão de santos que te apoiam.", "final_question": "Com qual santo você mais se identifica em sua caminhada?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0004-4000-8000-000000000001', 13, 'O Reino que Vem: Escatologia', '{"pch": "Vem, Senhor Jesus!", "interpretation": "Os sacramentos são sementes da glória futura. Eles nos preparam para o banquete eterno no Reino de Deus.", "practical_direction": "Faça um ato de desejo pelo céu e pela vinda de Cristo hoje.", "guided_exercise": "Visualize o triunfo final da luz sobre as trevas.", "final_question": "Sua vida está orientada para o encontro definitivo com o Senhor?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0004-4000-8000-000000000001', 14, 'Viver em Estado de Graça e Aliança', '{"pch": "Fazei tudo o que Ele vos disser.", "interpretation": "A vida cristã é uma aliança de amor com Deus selada nos sacramentos. Viver na graça é permanecer fiel a essa aliança.", "practical_direction": "Renove interiormente suas promessas de batismo hoje.", "guided_exercise": "Diga um ''Sim'' alegre e total a Deus por toda a sua vida.", "final_question": "Você tem cuidado da sua veste batismal com carinho?"}'::jsonb);

-- 5. Expand A Cruz e a Esperança (d1d1d1d1-0005-4000-8000-000000000001)
INSERT INTO public.journey_steps (id, journey_id, step_order, title, content) VALUES
(gen_random_uuid(), 'd1d1d1d1-0005-4000-8000-000000000001', 8, 'A Vitória da Ressurreição', '{"pch": "Por que buscais o Vivente entre os mortos?", "interpretation": "A cruz não foi a última palavra. A esperança cristã nasce do túmulo vazio. Jesus está vivo e governa a história.", "practical_direction": "Cante um Aleluia interior hoje, mesmo se as circunstâncias forem difíceis.", "guided_exercise": "Sinta a força da vida nova de Jesus expulsando as sombras da sua alma.", "final_question": "Sua vida é marcada pelo brilho da Ressurreição?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0005-4000-8000-000000000001', 9, 'A Ascensão e a Promessa do Paráclito', '{"pch": "Eu estarei convosco todos os dias.", "interpretation": "Jesus sobe ao céu mas permanece em nós pelo Espírito. A esperança é a certeza da companhia invisível mas real.", "practical_direction": "Peça a vinda do Espírito Santo para iluminar uma dúvida de hoje.", "guided_exercise": "Aquiete-se e sinta a presença terna do Consolador ao seu lado.", "final_question": "Você se sente sozinho ou acompanhado pelo Mestre?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0005-4000-8000-000000000001', 10, 'O Pentecostes: O Fogo da Esperança', '{"pch": "Ficaram todos cheios do Espírito Santo.", "interpretation": "O Espírito é o motor da esperança. Ele transforma o medo em coragem e a tristeza em missão alegre.", "practical_direction": "Fale do amor de Deus para alguém com entusiasmo hoje.", "guided_exercise": "Imagine línguas de fogo repousando sobre sua cabeça, renovando seu fervor.", "final_question": "O fogo da esperança está aceso em seu peito?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0005-4000-8000-000000000001', 11, 'A Glória de Maria Assunta ao Céu', '{"pch": "Apareceu no céu um grande sinal.", "interpretation": "Maria na glória é a garantia de que a esperança não decepciona. Onde Ela está, nós também um dia estaremos.", "practical_direction": "Reze uma Salve Rainha pedindo a graça de um olhar esperançoso.", "guided_exercise": "Contemple a beleza da Virgem coroada no Reino de seu Filho.", "final_question": "Maria é para você a Estrela que aponta o porto seguro?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0002-4000-8000-000000000001', 12, 'A Vida Eterna: Nossa Verdadeira Pátria', '{"pch": "Nossa pátria está nos céus.", "interpretation": "A esperança final é o encontro face a face. Tudo o que vivemos aqui é apenas o prefácio de uma história eterna.", "practical_direction": "Faça um ato de desapego de algo material, lembrando-se da eternidade.", "guided_exercise": "Visualize a paz e a luz indescritíveis da união com Deus.", "final_question": "Você tem saudades do Céu?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0005-4000-8000-000000000001', 13, 'O Triunfo Final de Cristo', '{"pch": "Vem, Senhor Jesus!", "interpretation": "A história caminha para um fim glorioso. Todo mal será vencido e Deus será tudo em todos. Essa é a âncora da nossa alma.", "practical_direction": "Descanse na promessa de que Deus tem o controle final da história.", "guided_exercise": "Sinta o alívio de saber que a Luz já venceu as trevas.", "final_question": "Você vive na expectativa alegre do Senhor que vem?"}'::jsonb),
(gen_random_uuid(), 'd1d1d1d1-0005-4000-8000-000000000001', 14, 'Permanecer na Esperança em meio à Noite', '{"pch": "A esperança não decepciona.", "interpretation": "O fim da jornada é a perseverança. Esperar contra toda esperança é o maior ato de confiança em Deus.", "practical_direction": "Ofereça hoje um sorriso e um gesto de esperança a alguém que está sofrendo.", "guided_exercise": "Ancore seu coração firmemente na Rocha que é Cristo.", "final_question": "Sua esperança é baseada em sentimentos ou na Palavra de Deus?"}'::jsonb);

-- Update estimated_days for these 5 journeys
UPDATE public.journeys SET estimated_days = 14 WHERE id IN (
  'd1d1d1d1-0001-4000-8000-000000000001',
  'd1d1d1d1-0002-4000-8000-000000000001',
  'd1d1d1d1-0003-4000-8000-000000000001',
  'd1d1d1d1-0004-4000-8000-000000000001',
  'd1d1d1d1-0005-4000-8000-000000000001'
);