-- Expand Caminhar na Fé (a0a0a0a0-0002-4000-8000-000000000001) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('a0a0a0a0-0002-4000-8000-000000000001', 'A Fé em Tempos de Crise', 8, '{"pch": "Tende fé em Deus.", "interpretation": "A fé não é apenas para os dias ensolarados, mas a bússola que nos guia nas tempestades e noites escuras da alma.", "practical_direction": "Identifique uma situação de crise e faça um ato de confiança hoje.", "guided_exercise": "Imagine Jesus no barco durante a tempestade, dormindo em paz.", "final_question": "Sua fé resiste à prova?"}'::jsonb),
('a0a0a0a0-0002-4000-8000-000000000001', 'Fé e Razão: Um Diálogo', 9, '{"pch": "Creio para entender, entendo para crer.", "interpretation": "Fé e razão são como as duas asas com as quais o espírito humano se eleva para a contemplação da verdade.", "practical_direction": "Leia um breve texto apologético ou teológico hoje.", "guided_exercise": "Peça a luz do Espírito para sua inteligência.", "final_question": "Sua fé é inteligente ou cega?"}'::jsonb),
('a0a0a0a0-0002-4000-8000-000000000001', 'A Fé no Invisível', 10, '{"pch": "Bem-aventurados os que não viram e creram.", "interpretation": "Fé é a certeza do que se espera e a prova das realidades que não se veem. É enxergar com os olhos do coração.", "practical_direction": "Feche os olhos por alguns minutos e tente sentir a presença de Deus.", "guided_exercise": "Agradeça por realidades que você não vê, mas sabe que existem.", "final_question": "Você precisa ver para crer?"}'::jsonb),
('a0a0a0a0-0002-4000-8000-000000000001', 'O Escudo da Fé', 11, '{"pch": "Embraçai o escudo da fé.", "interpretation": "A fé nos protege contra os dardos inflamados do inimigo: a dúvida, o desespero e a tentação do desânimo.", "practical_direction": "Use uma jaculatória curta de fé sempre que for tentado hoje.", "guided_exercise": "Imagine-se protegido por uma luz que é a sua fé.", "final_question": "Sua fé te protege ou você se sente vulnerável?"}'::jsonb),
('a0a0a0a0-0002-4000-8000-000000000001', 'Fé que Transforma a História', 12, '{"pch": "Pela fé, os antigos alcançaram bom testemunho.", "interpretation": "A fé não é um assunto privado; ela molda nossas ações públicas e tem o poder de mudar o mundo ao nosso redor.", "practical_direction": "Realize uma ação baseada na sua fé que beneficie sua comunidade hoje.", "guided_exercise": "Pense nos santos que mudaram a história pela fé.", "final_question": "Sua fé faz diferença no mundo?"}'::jsonb),
('a0a0a0a0-0002-4000-8000-000000000001', 'A Fé do Pobre de Espírito', 13, '{"pch": "Pai, eu Te agradeço porque revelaste estas coisas aos pequenos.", "interpretation": "A verdadeira fé exige a humildade de uma criança que confia plenamente no seu pai, sem querer entender tudo.", "practical_direction": "Tente não questionar um ''não'' de Deus hoje.", "guided_exercise": "Imagine-se como uma criança no colo do Pai.", "final_question": "Você tem a simplicidade da fé?"}'::jsonb),
('a0a0a0a0-0002-4000-8000-000000000001', 'Viver pela Fé: O Amém Final', 14, '{"pch": "O justo viverá pela fé.", "interpretation": "A meta é que a fé não seja um ato isolado, mas o ambiente em que respiramos e o fundamento de toda a nossa vida.", "practical_direction": "Consagre todos os seus planos futuros a Deus hoje.", "guided_exercise": "Diga um ''Amém'' profundo a tudo o que Deus preparou para você.", "final_question": "Você está pronto para caminhar pela fé até o fim?"}'::jsonb);

-- Expand O Caminho do Perdão (a0a0a0a0-0003-4000-8000-000000000001) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('a0a0a0a0-0003-4000-8000-000000000001', 'O Perdão nas Pequenas Coisas', 8, '{"pch": "Suportai-vos uns aos outros.", "interpretation": "O perdão não é apenas para grandes ofensas, mas para os pequenos atritos diários que corroem a paz.", "practical_direction": "Não guarde mágoa de uma pequena grosseria que receber hoje.", "guided_exercise": "Peça a graça da paciência com as limitações alheias.", "final_question": "Você é melindroso ou resiliente no amor?"}'::jsonb),
('a0a0a0a0-0003-4000-8000-000000000001', 'A Dureza de Coração', 9, '{"pch": "Não endureçais os vossos corações.", "interpretation": "A falta de perdão petrifica a alma. Somente a água viva do Espírito pode amolecer o coração ferido.", "practical_direction": "Identifique uma área de rigidez no seu coração e peça suavidade.", "guided_exercise": "Imagine o gelo da mágoa derretendo sob o Sol da Misericórdia.", "final_question": "O que você ganha mantendo seu coração duro?"}'::jsonb),
('a0a0a0a0-0003-4000-8000-000000000001', 'Misericórdia e Justiça', 10, '{"pch": "A misericórdia triunfa sobre o julgamento.", "interpretation": "Perdoar não é negar a justiça, mas entregar o julgamento a Deus e escolher o caminho da paz.", "practical_direction": "Abandone o desejo de ver alguém ''pagar'' pelo que fez a você.", "guided_exercise": "Peça justiça para si mesmo e misericórdia para os outros.", "final_question": "Você prefere ter razão ou ter paz?"}'::jsonb),
('a0a0a0a0-0003-4000-8000-000000000001', 'O Perdão como Decisão', 11, '{"pch": "Setenta vezes sete.", "interpretation": "O perdão é um ato da vontade, não um sentimento. É decidir não usar a dívida do outro contra ele.", "practical_direction": "Diga conscientemente: ''Eu perdoo fulano'', mesmo que não sinta nada.", "guided_exercise": "Rasgue simbolicamente uma nota de cobrança mental que você tem contra alguém.", "final_question": "Você está esperando sentir vontade para perdoar?"}'::jsonb),
('a0a0a0a0-0003-4000-8000-000000000001', 'Cicatrizes que se Tornam Glória', 12, '{"pch": "Pelas suas chagas fomos curados.", "interpretation": "Uma ferida perdoada torna-se uma cicatriz de glória. Ela não dói mais, mas serve de testemunho da vitória do amor.", "practical_direction": "Agradeça a Deus por uma dor passada que hoje é fonte de sabedoria.", "guided_exercise": "Beije simbolicamente as suas próprias cicatrizes interiores.", "final_question": "Sua dor te amargurou ou te ensinou a amar?"}'::jsonb),
('a0a0a0a0-0003-4000-8000-000000000001', 'O Abraço do Pai Misericordioso', 13, '{"pch": "O Pai o viu e correu ao seu encontro.", "interpretation": "O ápice do perdão é a reconciliação e o retorno à comunhão plena com Deus e com os irmãos.", "practical_direction": "Procure alguém para um gesto concreto de reconciliação hoje.", "guided_exercise": "Sinta-se envolvido pelo abraço de Deus, que não te faz perguntas, apenas te acolhe.", "final_question": "Você se sente perdoado por Deus?"}'::jsonb),
('a0a0a0a0-0003-4000-8000-000000000001', 'Embaixadores da Reconciliação', 14, '{"pch": "Sede embaixadores de Cristo.", "interpretation": "Fomos perdoados para sermos canais de perdão no mundo. Nossa missão é espalhar a paz que recebemos.", "practical_direction": "Ajude duas pessoas em conflito a se entenderem, se possível.", "guided_exercise": "Peça a graça de ser um instrumento de paz onde houver ódio.", "final_question": "Você tem sido sinal de união ou de divisão?"}'::jsonb);

-- Expand Metanoia — A Volta pra Casa (a0a0a0a0-0004-4000-8000-000000000001) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('a0a0a0a0-0004-4000-8000-000000000001', 'A Vigilância do Coração', 8, '{"pch": "Vigiai e orai para não entrardes em tentação.", "interpretation": "A metanoia exige uma atenção constante aos movimentos da alma para não cairmos novamente nos velhos trilhos.", "practical_direction": "Faça pequenas pausas durante o dia para checar sua intenção.", "guided_exercise": "Imagine-se como um guarda no portão do seu coração.", "final_question": "Sua alma está dormindo ou atenta?"}'::jsonb),
('a0a0a0a0-0004-4000-8000-000000000001', 'O Combate Espiritual', 9, '{"pch": "O Reino dos céus é dos violentos.", "interpretation": "A conversão é uma luta contra as nossas inclinações desordenadas. Exige esforço, disciplina e a força da graça.", "practical_direction": "Enfrente hoje aquela tentação que você sempre deixa vencer.", "guided_exercise": "Peça a ajuda do seu Anjo da Guarda para o combate.", "final_question": "Você está lutando ou se entregando sem resistência?"}'::jsonb),
('a0a0a0a0-0004-4000-8000-000000000001', 'Fugir das Ocasiões de Pecado', 10, '{"pch": "Quem ama o perigo, nele perecerá.", "interpretation": "Parte da prudência na conversão é evitar os lugares, pessoas ou situações que sabemos que nos fazem cair.", "practical_direction": "Identifique uma ''ocasião próxima'' de pecado e afaste-se dela hoje.", "guided_exercise": "Peça sabedoria para reconhecer as armadilhas do caminho.", "final_question": "Você está brincando com o fogo e esperando não se queimar?"}'::jsonb),
('a0a0a0a0-0004-4000-8000-000000000001', 'A Alegria de Recomeçar', 11, '{"pch": "Haverá mais alegria no céu por um só pecador que se arrepende.", "interpretation": "O arrependimento não deve ser triste, mas cheio da esperança de quem descobriu que é possível ter uma vida nova.", "practical_direction": "Celebre um pequeno progresso que você fez hoje.", "guided_exercise": "Sinta a alegria dos anjos pela sua decisão de voltar.", "final_question": "Sua conversão tem cheiro de vida ou de mofo?"}'::jsonb),
('a0a0a0a0-0004-4000-8000-000000000001', 'Transformação da Mente', 12, '{"pch": "Transformai-vos pela renovação da vossa mente.", "interpretation": "Metanoia significa literalmente mudar de mente. É aprender a pensar como Deus pensa, e não como o mundo.", "practical_direction": "Substitua um pensamento mundano por uma verdade bíblica hoje.", "guided_exercise": "Peça a graça de ter os mesmos sentimentos de Cristo Jesus.", "final_question": "O que governa seus pensamentos: as notícias ou o Evangelho?"}'::jsonb),
('a0a0a0a0-0004-4000-8000-000000000001', 'Seguindo os Passos do Mestre', 13, '{"pch": "Se alguém quer vir após Mim, negue-se a si mesmo.", "interpretation": "A conversão só é plena quando se torna seguimento. Não basta deixar o mal, é preciso seguir o Bem.", "practical_direction": "Escolha um traço da personalidade de Jesus e tente imitá-lo hoje.", "guided_exercise": "Imagine-se caminhando ao lado de Jesus, ouvindo Suas palavras.", "final_question": "Aonde você está indo com a sua nova vida?"}'::jsonb),
('a0a0a0a0-0004-4000-8000-000000000001', 'A Festa do Reencontro', 14, '{"pch": "Era preciso festejar porque este meu filho estava morto e reviveu.", "interpretation": "O fim da metanoia é a integração plena na família de Deus. É o banquete da graça preparado para os que voltam.", "practical_direction": "Faça um ato de gratidão profunda por ter sido buscado por Deus.", "guided_exercise": "Imagine-se sentado à mesa com o Senhor, sendo servido por Ele.", "final_question": "Você já se sente em casa?"}'::jsonb);

-- Expand A Aliança com Deus (a0a0a0a0-0005-4000-8000-000000000001) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('a0a0a0a0-0005-4000-8000-000000000001', 'Profetas: A Aliança Renovada', 8, '{"pch": "Porei minha lei no seu interior.", "interpretation": "Mesmo quando o povo foi infiel, Deus enviou profetas para prometer uma Aliança nova e eterna, gravada não em pedras, mas nos corações.", "practical_direction": "Leia uma passagem de um profeta hoje.", "guided_exercise": "Peça a Deus que escreva Sua vontade no seu coração.", "final_question": "Você ouve os apelos de Deus para renovar sua aliança?"}'::jsonb),
('a0a0a0a0-0005-4000-8000-000000000001', 'A Aliança no Casamento', 9, '{"pch": "O que Deus uniu, o homem não separe.", "interpretation": "O matrimônio é um sinal visível da Aliança de Deus com a humanidade. É uma entrega mútua e indissolúvel baseada no amor.", "practical_direction": "Reze hoje por todos os casais e pelas famílias.", "guided_exercise": "Medite no amor fiel e sacrificial como fundamento da união.", "final_question": "Suas relações refletem a fidelidade de Deus?"}'::jsonb),
('a0a0a0a0-0005-4000-8000-000000000001', 'O Sacerdócio da Aliança', 10, '{"pch": "Vós sois um sacerdócio real.", "interpretation": "Pela Aliança, somos chamados a oferecer nossa vida como sacrifício espiritual, unindo o céu e a terra em adoração.", "practical_direction": "Ofereça seu trabalho ou cansaço de hoje como uma oração.", "guided_exercise": "Imagine-se como uma ponte entre as pessoas e Deus.", "final_question": "Você vive sua vida como uma oferta a Deus?"}'::jsonb),
('a0a0a0a0-0005-4000-8000-000000000001', 'Eucaristia: Memorial da Aliança', 11, '{"pch": "Este é o Cálice da Nova Aliança no Meu Sangue.", "interpretation": "Cada missa é a renovação da Aliança selada na Cruz. É o alimento que nos sustenta na fidelidade.", "practical_direction": "Se possível, visite o Santíssimo Sacramento hoje.", "guided_exercise": "Imagine-se aos pés da Cruz, recebendo a vida de Jesus.", "final_question": "A Eucaristia é o centro da sua vida de aliança?"}'::jsonb),
('a0a0a0a0-0005-4000-8000-000000000001', 'A Quebra da Aliança e o Arrependimento', 12, '{"pch": "Voltai para Mim e Eu voltarei para vós.", "interpretation": "A infidelidade humana não anula a fidelidade divina. Deus sempre oferece um caminho de volta através da confissão.", "practical_direction": "Faça um exame de consciência sobre suas falhas na aliança com Deus.", "guided_exercise": "Sinta a dor de Deus pela nossa falta de amor.", "final_question": "O que te afasta da sua promessa a Deus?"}'::jsonb),
('a0a0a0a0-0005-4000-8000-000000000001', 'A Aliança Eterna no Céu', 13, '{"pch": "Eles serão o Seu povo e o próprio Deus estará com eles.", "interpretation": "A história da Aliança terminará no céu, onde não haverá mais véu entre Deus e o homem. É o casamento eterno do Cordeiro.", "practical_direction": "Pense no céu hoje como o destino final de todas as suas lutas.", "guided_exercise": "Imagine a paz de ser plenamente um com Deus.", "final_question": "Sua vida é uma preparação para esse encontro?"}'::jsonb),
('a0a0a0a0-0005-4000-8000-000000000001', 'Sendo Sinal da Aliança', 14, '{"pch": "Sereis para Mim um reino de sacerdotes e uma nação santa.", "interpretation": "Viver a Aliança é ser um sinal da presença de Deus no mundo. Nossa fidelidade atrai outros para a mesma amizade divina.", "practical_direction": "Seja uma pessoa de palavra e integridade hoje.", "guided_exercise": "Peça a graça de ser um reflexo da fidelidade de Deus.", "final_question": "Quem vê você, vê a Deus?"}'::jsonb);

-- Expand Jornada do Batismo (b1b1b1b1-0001-4000-8000-000000000001) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('b1b1b1b1-0001-4000-8000-000000000001', 'Dia 8 – O Chamado ao Apostolado', 8, '{"pch": "Ide por todo o mundo.", "interpretation": "Pelo batismo, não somos apenas discípulos, mas também apóstolos. Recebemos a missão de anunciar o que vivemos.", "practical_direction": "Fale de uma verdade de fé para alguém hoje, com amor.", "guided_exercise": "Peça coragem para ser uma testemunha autêntica.", "final_question": "Você guarda sua fé só para si?"}'::jsonb),
('b1b1b1b1-0001-4000-8000-000000000001', 'Dia 9 – Testemunhas da Luz', 9, '{"pch": "Recebestes a luz de Cristo.", "interpretation": "A vela acesa no batismo significa que devemos brilhar no mundo, iluminando as trevas com nossas boas obras.", "practical_direction": "Seja luz em um ambiente de negatividade hoje.", "guided_exercise": "Imagine a chama da fé crescendo no seu interior.", "final_question": "Sua vida ilumina ou obscurece o Evangelho?"}'::jsonb),
('b1b1b1b1-0001-4000-8000-000000000001', 'Dia 10 – A Herança do Reino', 10, '{"pch": "Somos herdeiros de Deus e co-herdeiros com Cristo.", "interpretation": "O batismo nos dá o direito de cidadania no céu. Somos da família real de Deus.", "practical_direction": "Comporte-se hoje com a dignidade de um filho de Rei.", "guided_exercise": "Agradeça pela herança eterna que está guardada para você.", "final_question": "Você vive como um mendigo ou como um herdeiro?"}'::jsonb),
('b1b1b1b1-0001-4000-8000-000000000001', 'Dia 11 – Viver como Revestidos de Cristo', 11, '{"pch": "Vós sois revestidos de Cristo.", "interpretation": "A veste branca do batismo deve ser mantida pura pela prática das virtudes e pela fuga do pecado.", "practical_direction": "Faça um ato de virtude que contrarie sua maior inclinação hoje.", "guided_exercise": "Imagine-se vestindo uma túnica de luz imaculada.", "final_question": "Sua veste espiritual está limpa?"}'::jsonb),
('b1b1b1b1-0001-4000-8000-000000000001', 'Dia 12 – A Luta contra o Mal', 12, '{"pch": "Renunciais ao demônio e a todas as suas obras?", "interpretation": "O batizado é um guerreiro. Nossa vida é um combate constante contra o que nos afasta de Deus.", "practical_direction": "Diga um ''não'' firme a uma tentação recorrente hoje.", "guided_exercise": "Peça força a São Miguel Arcanjo para o combate.", "final_question": "Você está de que lado na batalha?"}'::jsonb),
('b1b1b1b1-0001-4000-8000-000000000001', 'Dia 13 – O Batismo como Início, não Fim', 13, '{"pch": "Aquele que começou em vós a boa obra a completará.", "interpretation": "O batismo é a semente de vida eterna que precisa ser regada e cuidada todos os dias para dar frutos.", "practical_direction": "Renove hoje suas promessas batismais.", "guided_exercise": "Peça perseverança final na graça de Deus.", "final_question": "Sua semente está crescendo ou secando?"}'::jsonb),
('b1b1b1b1-0001-4000-8000-000000000001', 'Dia 14 – Ser Sal e Luz no Mundo', 14, '{"pch": "Vós sois o sal da terra.", "interpretation": "O fim da jornada do batismo é a missão total. Dar sabor ao mundo e afastar a corrupção do mal.", "practical_direction": "Faça algo concreto que melhore o ambiente onde você vive.", "guided_exercise": "Consagre sua vida inteira para o serviço do Reino.", "final_question": "O mundo é melhor porque você é batizado?"}'::jsonb);

-- Expand Jornada da Igreja (b1b1b1b1-0002-4000-8000-000000000001) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('b1b1b1b1-0002-4000-8000-000000000001', 'Dia 8 – A Igreja e a Palavra', 8, '{"pch": "Toda a Escritura é inspirada por Deus.", "interpretation": "A Igreja é a guardiã da Palavra de Deus. Ela nos ensina a ler as Escrituras com os olhos da fé.", "practical_direction": "Leia o Evangelho do dia meditando no que a Igreja ensina.", "guided_exercise": "Peça a sabedoria para entender a vontade de Deus nas Escrituras.", "final_question": "Você lê a Bíblia com a Igreja ou sozinho?"}'::jsonb),
('b1b1b1b1-0002-4000-8000-000000000001', 'Dia 9 – Os Sacramentos como Canais de Graça', 9, '{"pch": "Os sacramentos são sinais eficazes da graça.", "interpretation": "Cristo age através dos sacramentos da Igreja para nos curar, fortalecer e santificar em cada etapa da vida.", "practical_direction": "Pense em qual sacramento você mais precisa agora e reze por isso.", "guided_exercise": "Agradeça pelos sete tesouros da Igreja.", "final_question": "Você busca a graça nos sacramentos?"}'::jsonb),
('b1b1b1b1-0002-4000-8000-000000000001', 'Dia 10 – A Hierarquia e o Serviço', 10, '{"pch": "Quem quiser ser o primeiro, seja o servo de todos.", "interpretation": "A autoridade na Igreja é, em sua essência, serviço. O Papa, os bispos e padres existem para nos guiar a Cristo.", "practical_direction": "Reze hoje pelo Papa e pelo seu bispo diocesano.", "guided_exercise": "Imagine a Igreja como um corpo onde cada membro tem sua função.", "final_question": "Você respeita e ajuda aqueles que Deus colocou para te guiar?"}'::jsonb),
('b1b1b1b1-0002-4000-8000-000000000001', 'Dia 11 – A Missão Ad Gentes', 11, '{"pch": "Ide e fazei discípulos de todas as nações.", "interpretation": "A Igreja é missionária por natureza. Se ela para de evangelizar, ela perde sua razão de ser.", "practical_direction": "Contribua de alguma forma com as missões hoje.", "guided_exercise": "Imagine o Evangelho chegando aos confins da terra.", "final_question": "Seu coração é missionário?"}'::jsonb),
('b1b1b1b1-0002-4000-8000-000000000001', 'Dia 12 – A Igreja Padecente e Triunfante', 12, '{"pch": "Cremos na comunhão dos santos.", "interpretation": "A Igreja não é apenas a que vemos aqui. Somos unidos aos que se purificam no Purgatório e aos que já reinam no Céu.", "practical_direction": "Reze uma oração pelas almas do Purgatório hoje.", "guided_exercise": "Sinta a companhia invisível de toda a Igreja de todos os tempos.", "final_question": "Você se lembra de rezar pelos falecidos?"}'::jsonb),
('b1b1b1b1-0002-4000-8000-000000000001', 'Dia 13 – Ecumenismo e Diálogo', 13, '{"pch": "Que todos sejam um.", "interpretation": "O desejo de Cristo é a unidade de Seus seguidores. A Igreja trabalha para que a divisão entre os cristãos seja superada.", "practical_direction": "Reze hoje pela unidade de todos os cristãos.", "guided_exercise": "Peça a graça de ver o que nos une antes do que nos separa.", "final_question": "Você promove a união ou a discórdia entre os cristãos?"}'::jsonb),
('b1b1b1b1-0002-4000-8000-000000000001', 'Dia 14 – Sentir com a Igreja', 14, '{"pch": "Sentire cum Ecclesia.", "interpretation": "Sentir com a Igreja é ter um coração sintonizado com o magistério, a liturgia e a vida da comunidade cristã universal.", "practical_direction": "Faça um ato de obediência amorosa a um ensinamento da Igreja.", "guided_exercise": "Consagre sua pertença à Igreja ao Imaculado Coração de Maria.", "final_question": "Você ama a Igreja como sua mãe?"}'::jsonb);

-- Update estimated_days for these journeys
UPDATE public.journeys SET estimated_days = 14 WHERE id IN (
  'a0a0a0a0-0002-4000-8000-000000000001',
  'a0a0a0a0-0003-4000-8000-000000000001',
  'a0a0a0a0-0004-4000-8000-000000000001',
  'a0a0a0a0-0005-4000-8000-000000000001',
  'b1b1b1b1-0001-4000-8000-000000000001',
  'b1b1b1b1-0002-4000-8000-000000000001'
);