INSERT INTO public.journey_steps (id, journey_id, step_order, title, subtitle, content) VALUES 
('fd0ff1dd-4856-4f51-b2a8-d914ed6a4d19', '051b209e-9985-44da-a832-ca884783cb98', 1, 'A Vontade Adormecida', NULL, '{"intro": "Psicologicamente, a vontade fraca é fruto de decisões adiadas.", "prayer": "Identifique uma área de preguiça e a enfrente.", "practice": "Tome uma pequena decisão hoje e cumpra-a imediatamente.", "reflection": "O maior inimigo da virtude não é o erro, é a inércia.", "journal_prompt": "O que você está evitando decidir?"}'),
('d6c3dab7-7d22-4195-92f3-472f6de6bc16', '051b209e-9985-44da-a832-ca884783cb98', 2, 'O Ordenamento dos Afetos', NULL, '{"intro": "Desordem emocional gera ansiedade constante.", "prayer": "Ore pedindo a graça de amar o que é eterno.", "practice": "Escolha um objeto em sua casa e o organize conscientemente.", "reflection": "Amar é colocar as coisas no seu devido lugar.", "journal_prompt": "Seus amores estão em ordem?"}'),
('f9ed5e91-2888-4f7e-8499-85f71ffe2101', '051b209e-9985-44da-a832-ca884783cb98', 3, 'A Força do Hábito', NULL, '{"intro": "Hábitos são os trilhos sobre os quais nossa vida corre.", "prayer": "Peça constância para as pequenas coisas.", "practice": "Inicie hoje um novo micro-hábito positivo.", "reflection": "Somos o que fazemos repetidamente.", "journal_prompt": "Quais trilhos você está construindo hoje?"}'),
('8c2ff870-c484-4716-b31b-cf4d3ed019e5', '051b209e-9985-44da-a832-ca884783cb98', 4, 'O Silêncio Educativo', NULL, '{"intro": "Falar demais é uma fuga do encontro consigo mesmo.", "prayer": "No silêncio, escute os batimentos do seu coração.", "practice": "Fique 30 minutos sem falar nada, apenas observando.", "reflection": "Quem não domina a própria língua não domina a si mesmo.", "journal_prompt": "O que o seu barulho tenta esconder?"}'),
('5faa51eb-e635-4b43-bd47-627c5fa2efcf', '051b209e-9985-44da-a832-ca884783cb98', 5, 'A Obediência à Verdade', NULL, '{"intro": "Negar a realidade é a raiz de todo sofrimento psíquico.", "prayer": "Abrace a sua fragilidade diante do Infinito.", "practice": "Aceite uma verdade difícil sobre você hoje.", "reflection": "A liberdade real nasce de submeter-se ao que é verdadeiro.", "journal_prompt": "Você prefere a mentira que conforta ou a verdade que cura?"}'),
('93c7e138-b527-4d3d-962e-df7b7447184a', '051b209e-9985-44da-a832-ca884783cb98', 6, 'A Coragem do Não', NULL, '{"intro": "A incapacidade de dizer não é falta de identidade.", "prayer": "Peça força para sustentar suas escolhas.", "practice": "Diga não a algo que rouba o seu tempo hoje.", "reflection": "Dizer sim a tudo é dizer não a si mesmo.", "journal_prompt": "A quem você está tentando agradar?"}'),
('7c57cc31-4852-4427-b2d7-02a25e3de1a5', '051b209e-9985-44da-a832-ca884783cb98', 7, 'O Caráter que se Ergue', NULL, '{"intro": "O homem formado é aquele que se torna porto seguro para os outros.", "prayer": "Agradeça pela jornada de fortalecimento.", "practice": "Faça algo por alguém sem esperar nada em troca.", "reflection": "A formação termina quando a sua vida se torna um dom.", "journal_prompt": "Quem pode contar com você hoje?"}'),
('182be334-906b-447c-8bb7-7be26c2ed328', '0b8ddab7-b106-4873-bc4d-3987421d265d', 1, 'O Despertar Sagrado', NULL, '{"intro": "O primeiro pensamento do dia é a semente de todas as suas ações.", "prayer": "Ofereça o seu dia antes de sair da cama.", "practice": "Não pegue no celular nos primeiros 15 minutos do dia.", "reflection": "A forma como você começa o dia determina a sua alma.", "journal_prompt": "Qual é a primeira coisa que você entrega ao mundo ao acordar?"}'),
('57763fc6-f48e-436d-a54f-f3431216a562', '0b8ddab7-b106-4873-bc4d-3987421d265d', 2, 'O Dever do Momento', NULL, '{"intro": "A ansiedade nasce de querer estar no futuro e negligenciar o presente.", "prayer": "Peça a graça da presença de espírito.", "practice": "Faça a sua tarefa mais chata com total atenção e amor.", "reflection": "A santidade está em fazer bem o que se deve fazer agora.", "journal_prompt": "Você está presente no que está fazendo?"}'),
('99ec6d50-4d70-4e62-9da8-e7ddcc40d68d', '0b8ddab7-b106-4873-bc4d-3987421d265d', 3, 'As Pequenas Mortes', NULL, '{"intro": "Pequenos sacrifícios fortalecem a alma contra grandes quedas.", "prayer": "Ofereça essa pequena morte pela conversão de alguém.", "practice": "Renuncie a uma pequena satisfação hoje (un café, un doce, um comentário).", "reflection": "Cada renúncia é um espaço que se abre para a vida.", "journal_prompt": "O que você pode soltar para ser mais livre?"}'),
('690f82c8-60c1-4876-81ea-db828cbb8172', '0b8ddab7-b106-4873-bc4d-3987421d265d', 4, 'A Alimentação da Alma', NULL, '{"intro": "O que você lê, assiste e ouve molda a sua percepção da realidade.", "prayer": "Peça discernimento para o que você deixa entrar pelos olhos.", "practice": "Leia 5 páginas de um livro espiritual em vez de rolar as redes sociais.", "reflection": "Você se torna o que você consome.", "journal_prompt": "Como está a saúde da sua alma hoje?"}'),
('995d2b5f-1b4c-4a45-a32b-4454c650afc2', '0b8ddab7-b106-4873-bc4d-3987421d265d', 5, 'O Encontro no Meio do Dia', NULL, '{"intro": "A rotina nos engole se não criarmos ilhas de silêncio.", "prayer": "Recite o Angelus ou uma oração curta de entrega.", "practice": "Pare tudo por 2 minutos ao meio-dia para uma oração rápida.", "reflection": "Uma pausa para respirar é uma pausa para lembrar de Deus.", "journal_prompt": "Você se lembrou dEle hoje?"}'),
('49208096-da61-4368-9311-7f68034f6a7e', '0b8ddab7-b106-4873-bc4d-3987421d265d', 6, 'A Caridade Ordinária', NULL, '{"intro": "O amor se prova na paciência com quem está ao nosso lado.", "prayer": "Peça para ver Cristo no próximo.", "practice": "Faça um elogio sincero a alguém que convive com você.", "reflection": "Não espere grandes ocasiões para amar.", "journal_prompt": "Quem você amou hoje de forma concreta?"}'),
('d71cbf89-8f87-414f-8eeb-675a3959172a', '0b8ddab7-b106-4873-bc4d-3987421d265d', 7, 'O Exame da Noite', NULL, '{"intro": "O fim do dia é o tempo da colheita e do perdão.", "prayer": "Peça perdão pelas falhas e agradeça pelas vitórias.", "practice": "Reveja o seu dia antes de dormir: onde houve amor? Onde faltou?", "reflection": "Ninguém melhora o que não avalia.", "journal_prompt": "Se hoje fosse o seu último dia, você estaria em paz?"}')
ON CONFLICT (id) DO UPDATE SET 
    journey_id = EXCLUDED.journey_id,
    step_order = EXCLUDED.step_order,
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    content = EXCLUDED.content;