
-- Batismo journey
INSERT INTO public.journeys (id, title, subtitle, description, icon, category, difficulty, estimated_days, is_premium, is_active, sort_order)
VALUES ('b1b1b1b1-0001-4000-8000-000000000001', 'Jornada do Batismo', 'Sacramento do novo nascimento', 'Uma jornada de 7 dias para aprofundar o significado do Batismo e viver como filho de Deus.', 'droplets', 'formacao', 'iniciante', 7, false, true, 20);

INSERT INTO public.journey_steps (journey_id, step_order, title, subtitle, step_type, duration_minutes, is_free, content) VALUES
('b1b1b1b1-0001-4000-8000-000000000001', 1, 'Dia 1 – Nascidos da Água', 'O significado do Batismo', 'reading', 10, true,
 '{"pch":"O Batismo não é apenas um rito: é o momento em que Deus nos gera como filhos. Pela água e pelo Espírito, morremos para o pecado e ressuscitamos em Cristo.","interpretation":"A imersão na água simboliza a morte com Cristo; a emersão, a ressurreição para uma vida nova. Somos revestidos de Cristo (Gl 3,27).","practical_direction":"Relembre a data do seu batismo. Se possível, visite a igreja onde foi batizado.","guided_exercise":"Reze: Senhor, obrigado por me chamar a ser teu filho. Renovo hoje as promessas do meu batismo.","final_question":"O que significa para você ser filho de Deus pelo Batismo?"}'::jsonb),
('b1b1b1b1-0001-4000-8000-000000000001', 2, 'Dia 2 – Libertos do Pecado', 'A graça batismal', 'reading', 10, true,
 '{"pch":"Pelo Batismo, o pecado original é apagado e recebemos a graça santificante que nos torna templos do Espírito Santo.","interpretation":"São Paulo ensina: fomos sepultados com Cristo pelo batismo na morte, para que vivamos em novidade de vida (Rm 6,4).","practical_direction":"Faça um exame de consciência: há algo na sua vida que contradiz a graça do seu batismo?","guided_exercise":"Reze o Credo lentamente, renovando sua adesão a cada artigo da fé.","final_question":"Como você pode viver hoje a liberdade que o Batismo lhe deu?"}'::jsonb),
('b1b1b1b1-0001-4000-8000-000000000001', 3, 'Dia 3 – Incorporados à Igreja', 'Membros do Corpo de Cristo', 'reading', 10, true,
 '{"pch":"O Batismo nos incorpora à Igreja, Corpo de Cristo. Não somos cristãos isolados, mas membros vivos de uma comunidade de fé.","interpretation":"Como membros do Corpo, cada um tem uma função (1Cor 12,12-27). O isolamento espiritual contradiz a natureza do batismo.","practical_direction":"Participe ativamente da sua comunidade paroquial esta semana.","guided_exercise":"Reze pelos membros da sua paróquia, especialmente os que estão afastados.","final_question":"Como você pode ser mais presente na sua comunidade de fé?"}'::jsonb),
('b1b1b1b1-0001-4000-8000-000000000001', 4, 'Dia 4 – Sacerdotes, Profetas e Reis', 'A tríplice missão', 'reading', 10, false,
 '{"pch":"Pelo Batismo, participamos da missão de Cristo como sacerdotes (oferecer a vida), profetas (anunciar a verdade) e reis (servir com autoridade moral).","interpretation":"O sacerdócio comum dos fiéis não substitui o sacerdócio ministerial, mas o complementa. Todo batizado é chamado a santificar o mundo.","practical_direction":"Escolha uma das três dimensões e viva-a concretamente hoje: ofereça um sacrifício, diga uma verdade com caridade, ou sirva alguém.","guided_exercise":"Senhor, faze de mim instrumento da tua paz. Onde houver ódio, que eu leve o amor.","final_question":"Qual das três dimensões (sacerdote, profeta, rei) é mais difícil para você?"}'::jsonb),
('b1b1b1b1-0001-4000-8000-000000000001', 5, 'Dia 5 – O Selo Indelével', 'Marcados para sempre', 'reading', 10, false,
 '{"pch":"O Batismo imprime na alma um selo espiritual indelével (caráter) que nenhum pecado pode apagar. Somos de Cristo para sempre.","interpretation":"Mesmo que alguém se afaste da fé, o caráter batismal permanece como um chamado constante ao retorno. É a marca do Bom Pastor.","practical_direction":"Se conhece alguém que se afastou da Igreja, reze por essa pessoa e procure ser ponte de retorno.","guided_exercise":"Contemple: Deus me marcou como seu. Nada pode separar-me do seu amor (Rm 8,38-39).","final_question":"O que o selo batismal significa na sua vida prática?"}'::jsonb),
('b1b1b1b1-0001-4000-8000-000000000001', 6, 'Dia 6 – Padrinhos e Comunidade', 'A responsabilidade coletiva', 'reading', 10, false,
 '{"pch":"O Batismo não é assunto privado. Padrinhos e comunidade assumem a responsabilidade de acompanhar o batizado na fé.","interpretation":"Os padrinhos representam a Igreja que acolhe. Sua missão é transmitir a fé pelo exemplo e pela oração.","practical_direction":"Se você é padrinho/madrinha, entre em contato com seu afilhado hoje. Se não é, reze por quem o acompanhou na fé.","guided_exercise":"Agradeça a Deus pelas pessoas que transmitiram a fé a você. Reze por elas nominalmente.","final_question":"Quem transmitiu a fé a você e como pode retribuir?"}'::jsonb),
('b1b1b1b1-0001-4000-8000-000000000001', 7, 'Dia 7 – Viver o Batismo Hoje', 'Compromisso renovado', 'reading', 10, false,
 '{"pch":"Viver o batismo não é apenas lembrar de um evento passado, mas renovar diariamente a escolha de seguir Cristo em todas as dimensões da vida.","interpretation":"As promessas batismais – renunciar ao pecado, crer em Deus – são um programa de vida que exige conversão contínua.","practical_direction":"Escreva suas promessas batismais renovadas. Coloque-as em lugar visível como lembrete diário.","guided_exercise":"Renove as promessas batismais: Renuncio ao pecado. Creio em Deus Pai, Filho e Espírito Santo. Quero viver como filho da luz.","final_question":"Que compromisso concreto você assume hoje para viver seu batismo?"}'::jsonb);

-- Igreja journey
INSERT INTO public.journeys (id, title, subtitle, description, icon, category, difficulty, estimated_days, is_premium, is_active, sort_order)
VALUES ('b1b1b1b1-0002-4000-8000-000000000001', 'Jornada da Igreja', 'Corpo Místico de Cristo', 'Uma jornada de 7 dias para compreender e amar a Igreja como Povo de Deus.', 'church', 'formacao', 'iniciante', 7, false, true, 21);

INSERT INTO public.journey_steps (journey_id, step_order, title, subtitle, step_type, duration_minutes, is_free, content) VALUES
('b1b1b1b1-0002-4000-8000-000000000001', 1, 'Dia 1 – O Plano de Deus', 'A Igreja no desígnio divino', 'reading', 10, true,
 '{"pch":"A Igreja não foi uma invenção humana, mas faz parte do plano eterno de Deus para reunir todos os homens numa só família.","interpretation":"Desde a criação, Deus desejou formar um povo. A Igreja é a realização desse desejo, prefigurada em Israel e fundada por Cristo.","practical_direction":"Reflita: a Igreja não é apenas instituição, é família. Como você se relaciona com essa família?","guided_exercise":"Reze: Senhor, ajuda-me a ver a Igreja com os teus olhos, não com os olhos do mundo.","final_question":"O que a Igreja significa para você além de uma instituição?"}'::jsonb),
('b1b1b1b1-0002-4000-8000-000000000001', 2, 'Dia 2 – Fundada por Cristo', 'Tu és Pedro', 'reading', 10, true,
 '{"pch":"Jesus fundou a Igreja sobre Pedro e os Apóstolos, dando-lhes a missão de ensinar, santificar e governar em seu nome.","interpretation":"As chaves do Reino (Mt 16,18-19) simbolizam autoridade. A Igreja é apostólica: mantém a fé transmitida pelos Apóstolos.","practical_direction":"Reze pelo Papa e pelos bispos. Eles carregam uma responsabilidade imensa.","guided_exercise":"Leia Mt 16,13-20 lentamente. O que Jesus está pedindo de Pedro? E de você?","final_question":"Como a apostolicidade da Igreja fortalece a sua fé?"}'::jsonb),
('b1b1b1b1-0002-4000-8000-000000000001', 3, 'Dia 3 – Corpo de Cristo', 'Muitos membros, um só corpo', 'reading', 10, true,
 '{"pch":"A Igreja é o Corpo Místico de Cristo. Cristo é a Cabeça e nós somos os membros. Quando um membro sofre, todo o corpo sofre.","interpretation":"São Paulo usa a imagem do corpo (1Cor 12) para mostrar que cada cristão tem um dom e uma função insubstituível na Igreja.","practical_direction":"Descubra seu dom: qual é a sua contribuição única para o Corpo de Cristo?","guided_exercise":"Reze: Espírito Santo, revela-me o dom que me deste para servir a Igreja.","final_question":"Qual é o seu dom e como você o coloca a serviço dos outros?"}'::jsonb),
('b1b1b1b1-0002-4000-8000-000000000001', 4, 'Dia 4 – Una, Santa, Católica e Apostólica', 'As quatro notas', 'reading', 10, false,
 '{"pch":"As quatro notas da Igreja – una, santa, católica e apostólica – não são ideais distantes, mas realidades que vivemos imperfeita mas verdadeiramente.","interpretation":"Una pela fé e sacramentos; santa porque Cristo a santifica; católica porque é universal; apostólica porque guarda a fé dos Apóstolos.","practical_direction":"Escolha uma das quatro notas e reflita: como ela se manifesta na sua paróquia?","guided_exercise":"Reze o Credo focando nas palavras sobre a Igreja. Cada palavra é uma profissão de fé.","final_question":"Qual das quatro notas da Igreja mais o desafia?"}'::jsonb),
('b1b1b1b1-0002-4000-8000-000000000001', 5, 'Dia 5 – Povo Peregrino', 'A Igreja em caminho', 'reading', 10, false,
 '{"pch":"A Igreja é um povo peregrino: ainda não chegou à perfeição, mas caminha na esperança rumo à plenitude do Reino.","interpretation":"A Igreja é santa e pecadora ao mesmo tempo: santa pela graça de Cristo, pecadora pelos pecados dos seus membros. Isso não é contradição, é mistério.","practical_direction":"Não se escandalize com os pecados na Igreja. Reze e trabalhe pela sua santificação.","guided_exercise":"Reze: Senhor, santifica a tua Igreja. Começa por mim.","final_question":"Como você pode contribuir para a santidade da Igreja?"}'::jsonb),
('b1b1b1b1-0002-4000-8000-000000000001', 6, 'Dia 6 – Mãe e Mestra', 'A Igreja que ensina e acolhe', 'reading', 10, false,
 '{"pch":"A Igreja é Mãe porque nos gera pela fé e pelos sacramentos; é Mestra porque guarda e transmite fielmente a verdade revelada.","interpretation":"O Magistério da Igreja não inventa doutrinas: guarda o depósito da fé recebido dos Apóstolos e o interpreta à luz do Espírito Santo.","practical_direction":"Leia um documento do Magistério esta semana. Comece pelo Catecismo, seção que mais lhe interesse.","guided_exercise":"Agradeça a Deus pela Igreja que lhe transmitiu a fé, os sacramentos e a Palavra.","final_question":"Em que momento a Igreja foi verdadeiramente Mãe para você?"}'::jsonb),
('b1b1b1b1-0002-4000-8000-000000000001', 7, 'Dia 7 – Amar a Igreja', 'Compromisso eclesial', 'reading', 10, false,
 '{"pch":"Amar a Igreja é amá-la como Cristo a ama: com suas feridas, suas lutas e sua beleza escondida. É comprometer-se com ela, não apenas criticá-la de fora.","interpretation":"Santa Teresa dizia: Na Igreja, eu serei o amor. Cada santo encontrou seu lugar na Igreja não fugindo dela, mas mergulhando nela.","practical_direction":"Assuma um compromisso concreto com sua paróquia: catequese, liturgia, caridade ou acolhimento.","guided_exercise":"Reze: Senhor, eu amo a tua Igreja. Faze-me construtor de comunhão, não de divisão.","final_question":"Que compromisso concreto você assume com a Igreja a partir de hoje?"}'::jsonb);

-- Maria journey
INSERT INTO public.journeys (id, title, subtitle, description, icon, category, difficulty, estimated_days, is_premium, is_active, sort_order)
VALUES ('b1b1b1b1-0003-4000-8000-000000000001', 'Jornada de Maria', 'Mãe de Deus e nossa', 'Uma jornada de 7 dias para conhecer e amar Maria como caminho para Jesus.', 'heart', 'formacao', 'iniciante', 7, false, true, 22);

INSERT INTO public.journey_steps (journey_id, step_order, title, subtitle, step_type, duration_minutes, is_free, content) VALUES
('b1b1b1b1-0003-4000-8000-000000000001', 1, 'Dia 1 – Ave Maria', 'A saudação do anjo', 'reading', 10, true,
 '{"pch":"Tudo começa com um sim. Maria, ao dizer \"eis aqui a serva do Senhor\", abriu a porta para a Encarnação do Verbo.","interpretation":"A Anunciação (Lc 1,26-38) não foi imposição: foi convite. Deus respeita a liberdade humana. Maria disse sim livremente.","practical_direction":"Reze a Ave Maria lentamente, saboreando cada palavra. Cada frase é um resumo do Evangelho.","guided_exercise":"Senhor, dá-me a coragem de Maria para dizer sim ao teu plano, mesmo quando não entendo.","final_question":"Existe algum sim que Deus está pedindo de você e que ainda não deu?"}'::jsonb),
('b1b1b1b1-0003-4000-8000-000000000001', 2, 'Dia 2 – Theotokos', 'Mãe de Deus', 'reading', 10, true,
 '{"pch":"Maria é Mãe de Deus (Theotokos), não porque seja superior a Deus, mas porque deu à luz Jesus, que é verdadeiro Deus e verdadeiro homem.","interpretation":"O Concílio de Éfeso (431) proclamou este dogma para proteger a verdade sobre Cristo: se Maria não é Mãe de Deus, então Jesus não é Deus.","practical_direction":"Quando rezar a Ave Maria, detenha-se em \"Santa Maria, Mãe de Deus\". Isso é um ato de fé em Cristo.","guided_exercise":"Reze: Maria, Mãe de Deus, roga por nós pecadores. Leva-me ao teu Filho.","final_question":"Como o título Mãe de Deus muda sua compreensão de Maria?"}'::jsonb),
('b1b1b1b1-0003-4000-8000-000000000001', 3, 'Dia 3 – Imaculada Conceição', 'Preservada do pecado', 'reading', 10, true,
 '{"pch":"Maria foi preservada do pecado original desde o primeiro instante de sua concepção, em vista dos méritos de Cristo.","interpretation":"A Imaculada Conceição não afasta Maria de nós: mostra o que a graça de Deus pode fazer numa criatura que coopera plenamente.","practical_direction":"Peça a Maria a graça de vencer o pecado que mais o atrapalha. Ela conhece o caminho da pureza.","guided_exercise":"Reze: Ó Maria, concebida sem pecado, rogai por nós que recorremos a vós.","final_question":"O que a pureza de Maria inspira na sua luta contra o pecado?"}'::jsonb),
('b1b1b1b1-0003-4000-8000-000000000001', 4, 'Dia 4 – Aos Pés da Cruz', 'Dor e redenção', 'reading', 10, false,
 '{"pch":"Aos pés da cruz, Maria não fugiu. Permaneceu de pé (stabat), unindo sua dor ao sacrifício do Filho pela salvação do mundo.","interpretation":"\"Mulher, eis o teu filho\" (Jo 19,26): Jesus entrega Maria como mãe de todos os discípulos. Ela é nossa mãe no momento supremo da redenção.","practical_direction":"Nos momentos de sofrimento, una sua dor à de Maria e de Cristo. O sofrimento oferecido tem valor redentor.","guided_exercise":"Reze a Stabat Mater ou medite sobre as Sete Dores de Maria.","final_question":"Como Maria aos pés da cruz inspira você nos momentos de dor?"}'::jsonb),
('b1b1b1b1-0003-4000-8000-000000000001', 5, 'Dia 5 – Maria e o Rosário', 'Escola de oração', 'reading', 10, false,
 '{"pch":"O Rosário não é repetição vazia: é contemplação dos mistérios de Cristo através dos olhos de Maria.","interpretation":"São João Paulo II chamou o Rosário de \"compêndio do Evangelho\". Cada mistério é uma janela para a vida de Cristo.","practical_direction":"Reze pelo menos uma dezena do Rosário hoje, contemplando um mistério com atenção.","guided_exercise":"Escolha um mistério do Rosário. Feche os olhos e imagine-se na cena. O que Maria está sentindo?","final_question":"Qual mistério do Rosário mais toca o seu coração e por quê?"}'::jsonb),
('b1b1b1b1-0003-4000-8000-000000000001', 6, 'Dia 6 – Assunção e Glória', 'Elevada ao céu', 'reading', 10, false,
 '{"pch":"Maria foi elevada ao céu em corpo e alma. Sua Assunção é a antecipação do que Deus promete a todos os seus filhos.","interpretation":"A Assunção mostra que o destino do corpo humano não é a corrupção, mas a glorificação. Maria é as primícias da ressurreição.","practical_direction":"Cuide do seu corpo como templo do Espírito Santo. Ele é destinado à glória.","guided_exercise":"Reze: Maria, gloriosa no céu, intercede por mim para que eu alcance a mesma glória.","final_question":"Como a Assunção de Maria transforma sua visão sobre a morte e a ressurreição?"}'::jsonb),
('b1b1b1b1-0003-4000-8000-000000000001', 7, 'Dia 7 – Consagração a Maria', 'Totus Tuus', 'reading', 10, false,
 '{"pch":"Consagrar-se a Maria é entregar-se totalmente a Jesus pelas mãos de Maria. É o caminho mais rápido, mais fácil e mais seguro para chegar a Cristo.","interpretation":"São Luís de Montfort ensina: \"Quanto mais uma alma for consagrada a Maria, mais será consagrada a Jesus Cristo.\" Maria não retém nada: tudo leva a Cristo.","practical_direction":"Faça um ato de consagração a Maria hoje. Entregue-lhe suas preocupações, planos e medos.","guided_exercise":"Reze: Minha Mãe, minha Confiança. Totus Tuus. Todo teu, Maria, para ser todo de Jesus.","final_question":"O que significa para você entregar sua vida a Jesus pelas mãos de Maria?"}'::jsonb);

-- Jesus journey
INSERT INTO public.journeys (id, title, subtitle, description, icon, category, difficulty, estimated_days, is_premium, is_active, sort_order)
VALUES ('b1b1b1b1-0004-4000-8000-000000000001', 'Jornada de Jesus', 'Seguir o Mestre', 'Uma jornada de 7 dias para conhecer, amar e seguir Jesus Cristo mais de perto.', 'cross', 'formacao', 'iniciante', 7, false, true, 23);

INSERT INTO public.journey_steps (journey_id, step_order, title, subtitle, step_type, duration_minutes, is_free, content) VALUES
('b1b1b1b1-0004-4000-8000-000000000001', 1, 'Dia 1 – O Verbo se Fez Carne', 'Quem é Jesus?', 'reading', 10, true,
 '{"pch":"Jesus não é apenas um grande mestre moral. Ele é o Verbo eterno de Deus que se fez homem para nos salvar.","interpretation":"\"No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus\" (Jo 1,1). Jesus é verdadeiro Deus e verdadeiro homem.","practical_direction":"Releia Jo 1,1-14 lentamente. Cada versículo é uma revelação sobre quem é Jesus.","guided_exercise":"Reze: Jesus, Verbo encarnado, revela-te a mim. Quero conhecer-te como tu és.","final_question":"Quem é Jesus para você, pessoalmente?"}'::jsonb),
('b1b1b1b1-0004-4000-8000-000000000001', 2, 'Dia 2 – O Rosto da Misericórdia', 'Jesus e os pecadores', 'reading', 10, true,
 '{"pch":"Jesus não veio para os justos, mas para os pecadores. Ele é o rosto visível da misericórdia do Pai.","interpretation":"As parábolas da misericórdia (Lc 15) revelam o coração de Deus: Ele sai à procura da ovelha perdida, espera o filho pródigo, celebra o reencontro.","practical_direction":"Vá ao Sacramento da Confissão esta semana. Deixe Jesus curar suas feridas.","guided_exercise":"Leia Lc 15,11-32. Identifique-se com o filho pródigo. O Pai corre ao seu encontro.","final_question":"Em que área da sua vida você precisa da misericórdia de Jesus?"}'::jsonb),
('b1b1b1b1-0004-4000-8000-000000000001', 3, 'Dia 3 – Mestre e Senhor', 'Os ensinamentos de Jesus', 'reading', 10, true,
 '{"pch":"Jesus ensina com autoridade (Mt 7,29). Suas palavras não são opiniões humanas, mas Palavra de Deus viva e eficaz.","interpretation":"O Sermão da Montanha (Mt 5-7) é a carta magna do Reino. As Bem-aventuranças invertem a lógica do mundo.","practical_direction":"Escolha uma Bem-aventurança e tente vivê-la concretamente hoje.","guided_exercise":"Leia Mt 5,3-12. Qual Bem-aventurança mais desafia você? Peça a graça de vivê-la.","final_question":"Qual ensinamento de Jesus mais transforma sua vida?"}'::jsonb),
('b1b1b1b1-0004-4000-8000-000000000001', 4, 'Dia 4 – Milagres e Sinais', 'O poder de Jesus', 'reading', 10, false,
 '{"pch":"Os milagres de Jesus não são espetáculo: são sinais do Reino que irrompe na história. Cada cura é uma antecipação da ressurreição.","interpretation":"Jesus cura cegos, paralíticos, leprosos: cada milagre é uma metáfora espiritual. O cego que vê é aquele que abre os olhos da fé.","practical_direction":"Peça a Jesus um milagre interior: a cura de uma cegueira espiritual, uma paralisia da alma.","guided_exercise":"Reze: Jesus, Filho de Davi, tem piedade de mim. Abre meus olhos para ver o que preciso mudar.","final_question":"Qual é a cura interior que você mais precisa de Jesus?"}'::jsonb),
('b1b1b1b1-0004-4000-8000-000000000001', 5, 'Dia 5 – A Cruz', 'O amor até o fim', 'reading', 10, false,
 '{"pch":"A Cruz não é derrota, mas o trono da vitória de Cristo. \"Tendo amado os seus, amou-os até o fim\" (Jo 13,1).","interpretation":"Na Cruz, Jesus carrega todos os pecados da humanidade. Seu amor transforma o instrumento de tortura em sinal de salvação.","practical_direction":"Carregue suas cruzes de hoje com Jesus. Ofereça seu sofrimento por alguém que precisa.","guided_exercise":"Faça uma Via Sacra (mesmo breve). Em cada estação, converse com Jesus sobre suas próprias cruzes.","final_question":"Como a Cruz de Cristo dá sentido ao seu sofrimento?"}'::jsonb),
('b1b1b1b1-0004-4000-8000-000000000001', 6, 'Dia 6 – Ressuscitou!', 'A vitória sobre a morte', 'reading', 10, false,
 '{"pch":"Se Cristo não ressuscitou, vã é a nossa fé (1Cor 15,14). A Ressurreição é o fundamento de tudo o que cremos.","interpretation":"A Ressurreição não é uma metáfora: é um evento histórico e transhistórico. O túmulo vazio e as aparições são provas de uma realidade nova.","practical_direction":"Viva hoje como alguém que acredita na Ressurreição. Não tenha medo.","guided_exercise":"Reze: Jesus Ressuscitado, aumenta a minha fé. Eu creio que tu venceste a morte.","final_question":"Como a fé na Ressurreição muda a maneira como você enfrenta a vida?"}'::jsonb),
('b1b1b1b1-0004-4000-8000-000000000001', 7, 'Dia 7 – Seguir Jesus Hoje', 'Discípulo missionário', 'reading', 10, false,
 '{"pch":"Seguir Jesus não é contemplação passiva: é missão. \"Ide e fazei discípulos\" (Mt 28,19). Todo cristão é chamado a ser missionário.","interpretation":"O discipulado não é perfeição, mas caminho. Pedro negou, Tomé duvidou, Paulo perseguiu – e todos se tornaram apóstolos.","practical_direction":"Compartilhe sua fé com alguém hoje: uma palavra de esperança, um convite à Missa, um gesto de amor.","guided_exercise":"Reze: Jesus, faze de mim teu discípulo. Envia-me onde quiseres, para quem quiseres.","final_question":"Como você pode ser discípulo missionário de Jesus no seu ambiente?"}'::jsonb);
