-- Expand Primeiros Passos na Fé (a1b2c3d4-0001-4000-8000-000000000001) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('a1b2c3d4-0001-4000-8000-000000000001', 'O Amor ao Próximo', 8, '{"pch": "Amai-vos uns aos outros como Eu vos amei.", "interpretation": "A fé que não se traduz em obras de amor é morta. Amar ao próximo é a prova concreta do nosso amor a Deus.", "practical_direction": "Identifique alguém hoje que precise de ajuda e faça um pequeno gesto de caridade.", "guided_exercise": "Peça a Deus um coração sensível às necessidades alheias.", "final_question": "Como o seu amor tem se manifestado na prática?"}'::jsonb),
('a1b2c3d4-0001-4000-8000-000000000001', 'O Perdão como Libertação', 9, '{"pch": "Perdoai-nos as nossas dívidas, assim como nós perdoamos aos nossos devedores.", "interpretation": "O perdão não é um sentimento, é uma decisão. Perdoar liberta a alma de um peso que impede a caminhada espiritual.", "practical_direction": "Tome a decisão de perdoar alguém que te magoou, mesmo que ainda sinta a dor.", "guided_exercise": "Entregue a Deus a mágoa que você carrega e peça paz.", "final_question": "Há alguém que você precise libertar pelo perdão hoje?"}'::jsonb),
('a1b2c3d4-0001-4000-8000-000000000001', 'A Igreja: Nossa Família', 10, '{"pch": "Vós sois o corpo de Cristo.", "interpretation": "Não caminhamos sozinhos. A Igreja é a família de Deus que nos acolhe, ensina e sustenta pelos sacramentos.", "practical_direction": "Tente participar de uma comunidade ou grupo de oração.", "guided_exercise": "Agradeça a Deus pelos pastores e irmãos que Ele colocou em sua vida.", "final_question": "Você se sente parte de uma família na fé?"}'::jsonb),
('a1b2c3d4-0001-4000-8000-000000000001', 'Os Mandamentos: Caminho de Vida', 11, '{"pch": "Se me amais, guardareis os meus mandamentos.", "interpretation": "Os mandamentos não são proibições, mas placas de sinalização que nos levam à verdadeira felicidade e liberdade.", "practical_direction": "Escolha um dos 10 mandamentos para meditar e viver com mais zelo hoje.", "guided_exercise": "Peça a graça de amar a lei de Deus como um guia seguro.", "final_question": "Você vê os mandamentos como um peso ou como um caminho de amor?"}'::jsonb),
('a1b2c3d4-0001-4000-8000-000000000001', 'O Espírito Santo: Nosso Amigo', 12, '{"pch": "O Consolador vos ensinará todas as coisas.", "interpretation": "O Espírito Santo é a força de Deus em nós. Ele nos guia, ilumina e dá coragem para viver o Evangelho.", "practical_direction": "Invoque o Espírito Santo várias vezes ao longo do dia: Vinde, Espírito Santo!", "guided_exercise": "Abra-se aos dons do Espírito e peça que Ele transforme seu coração.", "final_question": "Você tem dado espaço para o Espírito Santo agir na sua vida?"}'::jsonb),
('a1b2c3d4-0001-4000-8000-000000000001', 'A Vida Eterna e a Esperança', 13, '{"pch": "Nossa pátria está nos céus.", "interpretation": "Esta vida é um caminho para a eternidade. A esperança cristã nos dá forças para enfrentar os desafios do presente.", "practical_direction": "Lembre-se hoje de que você foi feito para o infinito, para a eternidade com Deus.", "guided_exercise": "Peça a graça da perseverança final para alcançar a morada eterna.", "final_question": "Onde está depositada a sua maior esperança?"}'::jsonb),
('a1b2c3d4-0001-4000-8000-000000000001', 'Ser um Discípulo Missionário', 14, '{"pch": "Ide e fazei discípulos em todas as nações.", "interpretation": "A caminhada não termina em nós mesmos. Somos chamados a transbordar o que recebemos e anunciar a alegria do Evangelho.", "practical_direction": "Compartilhe hoje algo da sua fé com alguém, por meio de palavras ou de um exemplo de vida.", "guided_exercise": "Consagre-se como um missionário do amor de Deus no mundo.", "final_question": "Como você pode ajudar outros a conhecerem o amor de Deus?"}'::jsonb);

-- Expand Aprofundamento Místico (a1b2c3d4-0003-4000-8000-000000000003) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('a1b2c3d4-0003-4000-8000-000000000003', 'O Castelo Interior de Santa Teresa', 8, '{"pch": "Não é outra coisa a oração mental senão tratar de amizade.", "interpretation": "A alma é como um castelo de diamante com muitas moradas. A oração é a porta para entrar nesse castelo e encontrar o Rei.", "practical_direction": "Imagine sua alma como um lugar sagrado onde Deus habita.", "guided_exercise": "Visualize-se entrando no centro da sua alma para estar com o Senhor.", "final_question": "Você tem dedicado tempo para visitar o Rei no seu castelo interior?"}'::jsonb),
('a1b2c3d4-0003-4000-8000-000000000003', 'A Subida do Monte Carmelo de São João da Cruz', 9, '{"pch": "Para vir a saber tudo, não queiras saber algo em nada.", "interpretation": "A mística exige o desapego de tudo o que não é Deus. É preciso atravessar o nada para chegar ao Tudo.", "practical_direction": "Identifique um apego desnecessário hoje e ofereça a Deus.", "guided_exercise": "Peça a graça do despojamento interior para voar mais alto até Deus.", "final_question": "O que ainda te prende e te impede de subir o monte da perfeição?"}'::jsonb),
('a1b2c3d4-0003-4000-8000-000000000003', 'O Pequeno Caminho de Santa Teresinha', 10, '{"pch": "No coração da Igreja, eu serei o amor.", "interpretation": "A santidade não está em grandes obras, mas em fazer as pequenas coisas com um amor imenso.", "practical_direction": "Realize uma tarefa simples hoje com a intenção de agradar a Deus perfeitamente.", "guided_exercise": "Ofereça pequenas flores (atos de amor) a Jesus durante o dia.", "final_question": "Você crê que pode ser santo nas pequenas coisas?"}'::jsonb),
('a1b2c3d4-0003-4000-8000-000000000003', 'A Mística do Sofrimento e da Redenção', 11, '{"pch": "Completo em minha carne o que falta às tribulações de Cristo.", "interpretation": "O sofrimento unido ao de Cristo torna-se redentor. A mística não foge da cruz, mas encontra nela o Ressuscitado.", "practical_direction": "Não reclame hoje de um pequeno incômodo; ofereça-o pela salvação das almas.", "guided_exercise": "Olhe para o Crucificado e una sua dor à Dele.", "final_question": "Você tem transformado sua dor em oferta de amor?"}'::jsonb),
('a1b2c3d4-0003-4000-8000-000000000003', 'O Casamento Espiritual', 12, '{"pch": "Meu Amado é meu e eu sou Dele.", "interpretation": "A união mística atinge seu ápice quando a vontade da alma se funde inteiramente com a vontade de Deus.", "practical_direction": "Renove hoje seu compromisso de fidelidade exclusiva a Deus.", "guided_exercise": "Repouse no abraço de Deus, sentindo-se um com Ele.", "final_question": "Sua alma suspira pela união total com o Divino Esposo?"}'::jsonb),
('a1b2c3d4-0003-4000-8000-000000000003', 'A Presença de Deus no Ordinário', 13, '{"pch": "Deus anda entre as panelas.", "interpretation": "A mística não se limita ao momento da oração formal; ela transborda para o trabalho e o cotidiano.", "practical_direction": "Tente manter a consciência da presença de Deus enquanto realiza suas tarefas.", "guided_exercise": "Peça a graça de ver a Deus em todas as pessoas e situações.", "final_question": "Você consegue encontrar Deus na agitação do seu dia?"}'::jsonb),
('a1b2c3d4-0003-4000-8000-000000000003', 'A Divinização da Alma', 14, '{"pch": "Já não sou eu que vivo, é Cristo que vive em mim.", "interpretation": "O fim último da mística é que nos tornemos por participação o que Deus é por natureza: Amor.", "practical_direction": "Faça um ato de fé na sua filiação divina e no destino eterno.", "guided_exercise": "Agradeça por ser templo vivo do Espírito Santo.", "final_question": "Você percebe que a sua vida é uma jornada de divinização?"}'::jsonb);

-- Update estimated_days for these journeys
UPDATE public.journeys SET estimated_days = 14 WHERE id IN ('a1b2c3d4-0001-4000-8000-000000000001', 'a1b2c3d4-0003-4000-8000-000000000003');