-- Expand Prisão Interior (a1b2c3d4-0004-4000-8000-000000000004) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('a1b2c3d4-0004-4000-8000-000000000004', 'Identificando os Ídolos do Coração', 8, '{"pch": "Não terás outros deuses diante de Mim.", "interpretation": "Ídolos não são apenas estátuas, mas qualquer coisa (dinheiro, fama, prazer) que ocupa o lugar de Deus no centro da nossa alma.", "practical_direction": "Identifique o que mais toma o seu tempo e preocupação fora de Deus.", "guided_exercise": "Peça a Deus que derrube os altares falsos do seu coração.", "final_question": "Quem ou o que realmente governa a sua vida?"}'::jsonb),
('a1b2c3d4-0004-4000-8000-000000000004', 'A Prisão do Orgulho', 9, '{"pch": "Deus resiste aos soberbos, mas dá graça aos humildes.", "interpretation": "O orgulho é a raiz de todos os pecados. Ele nos fecha em nós mesmos e nos impede de receber a ajuda de Deus.", "practical_direction": "Faça um ato de humildade hoje: peça desculpas ou reconheça um erro.", "guided_exercise": "Medite sobre a humildade de Jesus ao lavar os pés dos discípulos.", "final_question": "Você consegue admitir suas fraquezas diante de Deus?"}'::jsonb),
('a1b2c3d4-0004-4000-8000-000000000004', 'O Vício da Acídia (Preguiça Espiritual)', 10, '{"pch": "O Reino dos Céus é dos violentos.", "interpretation": "A acídia é um desânimo que nos afasta das coisas espirituais, tornando a oração e o bem pesados e sem sentido.", "practical_direction": "Cumpra hoje uma tarefa espiritual que você está adiando.", "guided_exercise": "Peça ao Espírito Santo o dom da fortaleza contra o desânimo.", "final_question": "Sua alma está dormindo ou vigiando?"}'::jsonb),
('a1b2c3d4-0004-4000-8000-000000000004', 'A Gula e o Desequilíbrio dos Sentidos', 11, '{"pch": "Nem só de pão vive o homem.", "interpretation": "A gula não é só comida, mas a busca desenfreada por satisfação sensorial que escraviza a vontade.", "practical_direction": "Faça uma pequena renúncia em uma refeição ou prazer sensorial hoje.", "guided_exercise": "Agradeça a Deus pelo sustento e peça temperança.", "final_question": "Quem manda em você: seu corpo ou sua alma?"}'::jsonb),
('a1b2c3d4-0004-4000-8000-000000000004', 'A Luxúria e a Cegueira da Alma', 12, '{"pch": "A lâmpada do corpo é o olhar.", "interpretation": "A luxúria usa o outro como objeto e obscurece a visão de Deus. A pureza liberta o coração para o verdadeiro amor.", "practical_direction": "Faça uma custódia dos olhos hoje: evite olhar para o que desperta desejos desordenados.", "guided_exercise": "Peça a Maria a graça de um coração puro e casto.", "final_question": "Seu olhar transmite a luz de Cristo?"}'::jsonb),
('a1b2c3d4-0004-4000-8000-000000000004', 'A Ira e o Descontrole das Emoções', 13, '{"pch": "Aprendei de Mim que sou manso e humilde de coração.", "interpretation": "A ira desgovernada destrói relacionamentos e a paz interior. A mansidão é a força de quem se domina por amor.", "practical_direction": "Responda com calma a uma situação irritante hoje.", "guided_exercise": "Peça a Jesus que acalme as tempestades do seu interior.", "final_question": "Sua paz depende das circunstâncias ou de Deus?"}'::jsonb),
('a1b2c3d4-0004-4000-8000-000000000004', 'A Liberdade dos Filhos de Deus', 14, '{"pch": "Onde está o Espírito do Senhor, aí há liberdade.", "interpretation": "A verdadeira liberdade não é fazer o que se quer, mas ter o poder de fazer o Bem. Fomos libertos para amar.", "practical_direction": "Celebre sua liberdade em Cristo realizando um ato de amor gratuito.", "guided_exercise": "Agradeça a Deus por ter te tirado de todas as prisões interiores.", "final_question": "Você se sente verdadeiramente livre para amar a Deus?"}'::jsonb);

-- Expand Cura (f0f35259-85b3-44fa-99c1-4f9ec87c9f4d) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('f0f35259-85b3-44fa-99c1-4f9ec87c9f4d', 'Cura das Feridas da Infância', 8, '{"pch": "Deixai vir a mim as criancinhas.", "interpretation": "Muitas das nossas dores atuais têm raiz em carências ou traumas da infância que precisam ser apresentados a Jesus.", "practical_direction": "Imagine Jesus abraçando você quando era criança e dizendo que você é amado.", "guided_exercise": "Peça ao Senhor que cure as memórias dolorosas dos seus primeiros anos.", "final_question": "Qual ferida da sua infância você ainda carrega hoje?"}'::jsonb),
('f0f35259-85b3-44fa-99c1-4f9ec87c9f4d', 'Cura dos Relacionamentos Rompidos', 9, '{"pch": "Tende paz uns com os outros.", "interpretation": "Rupturas e mágoas em amizades ou família podem paralisar nossa vida espiritual. A cura passa pela reconciliação interior.", "practical_direction": "Reze hoje por uma pessoa com quem você tem um relacionamento difícil.", "guided_exercise": "Peça a graça de ver essa pessoa com os olhos de misericórdia de Deus.", "final_question": "Você está disposto a deixar o passado no passado?"}'::jsonb),
('f0f35259-85b3-44fa-99c1-4f9ec87c9f4d', 'O Perdão a Si Mesmo', 10, '{"pch": "Eu também não te condeno; vai e não peques mais.", "interpretation": "Muitas vezes perdoamos os outros, mas guardamos uma culpa implacável contra nós mesmos. Se Deus perdoou, quem somos nós para nos condenar?", "practical_direction": "Olhe no espelho e diga: Deus me perdoa, eu também me perdoo.", "guided_exercise": "Entregue suas falhas passadas à infinita misericórdia divina.", "final_question": "Você ainda se pune por erros que Deus já esqueceu?"}'::jsonb),
('f0f35259-85b3-44fa-99c1-4f9ec87c9f4d', 'Cura do Sentimento de Rejeição', 11, '{"pch": "Tu és precioso aos meus olhos.", "interpretation": "A rejeição humana fere nossa identidade. A cura vem de mergulhar na aceitação incondicional do Pai.", "practical_direction": "Repita hoje: Eu sou filho(a) amado(a) de Deus, e isso me basta.", "guided_exercise": "Peça ao Espírito Santo que sele sua alma com a certeza do seu valor.", "final_question": "Você busca aprovação nas pessoas ou no amor de Deus?"}'::jsonb),
('f0f35259-85b3-44fa-99c1-4f9ec87c9f4d', 'Cura da Imagem de Deus (Pai Amoroso)', 12, '{"pch": "Abba! Pai!", "interpretation": "Muitas vezes projetamos em Deus as falhas de nossos pais terrenos. Precisamos descobrir o Deus que é Pai cheio de ternura.", "practical_direction": "Reze o Pai-Nosso lentamente, saboreando cada palavra de confiança.", "guided_exercise": "Sinta o olhar de amor que o Pai dirige a você neste exato momento.", "final_question": "Você tem medo de Deus ou confia Nele como um filho pequeno?"}'::jsonb),
('f0f35259-85b3-44fa-99c1-4f9ec87c9f4d', 'A Alegria como Sinal de Cura', 13, '{"pch": "A alegria do Senhor é a nossa força.", "interpretation": "Uma alma curada transborda alegria, não uma alegria passageira, mas uma paz profunda que o mundo não pode tirar.", "practical_direction": "Sorria para alguém hoje e compartilhe uma palavra de esperança.", "guided_exercise": "Peça a graça de ser um portador da alegria de Cristo no mundo.", "final_question": "Sua vida tem sido um testemunho da cura que Deus operou?"}'::jsonb),
('f0f35259-85b3-44fa-99c1-4f9ec87c9f4d', 'Caminhando na Plenitude', 14, '{"pch": "Eu vim para que tenham vida, e a tenham em abundância.", "interpretation": "A cura não é apenas a ausência de dor, mas a plenitude de vida em Deus. É o início de uma nova jornada.", "practical_direction": "Faça um ato de gratidão por tudo o que foi curado nestes 14 dias.", "guided_exercise": "Consagre sua saúde física, mental e espiritual ao Senhor.", "final_question": "Você está pronto para viver a vida abundante que Deus planejou?"}'::jsonb);

-- Update estimated_days for these journeys
UPDATE public.journeys SET estimated_days = 14 WHERE id IN ('a1b2c3d4-0004-4000-8000-000000000004', 'f0f35259-85b3-44fa-99c1-4f9ec87c9f4d');