-- Expand Formação (051b209e-9985-44da-a832-ca884783cb98) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('051b209e-9985-44da-a832-ca884783cb98', 'A Escuta Atenta', 8, '{"pch": "Quem tem ouvidos para ouvir, ouça.", "interpretation": "A escuta é o primeiro ato de caridade. Sem ouvir o outro e a Deus, nossas ações são apenas ecos do nosso ego.", "practical_direction": "Dedique 10 minutos para ouvir alguém hoje sem interromper.", "guided_exercise": "Peça a graça de ouvir a voz de Deus nos eventos do dia.", "final_question": "Sua mente está cheia de ruído ou aberta para a Verdade?"}'::jsonb),
('051b209e-9985-44da-a832-ca884783cb98', 'A Pobreza de Espírito', 9, '{"pch": "Bem-aventurados os pobres de espírito.", "interpretation": "Ser pobre de espírito é reconhecer que nada somos sem a graça de Deus. É o esvaziamento para ser preenchido pelo Infinito.", "practical_direction": "Identifique uma área onde você se sente autossuficiente e entregue-a a Deus.", "guided_exercise": "Imagine-se de mãos vazias diante do Criador, aceitando Sua vontade.", "final_question": "Você confia em suas próprias forças ou na providência divina?"}'::jsonb),
('051b209e-9985-44da-a832-ca884783cb98', 'A Castidade do Olhar', 10, '{"pch": "A lâmpada do corpo é o olhar.", "interpretation": "O que permitimos que entre pelos nossos olhos molda nossa alma. A pureza começa na guarda dos sentidos.", "practical_direction": "Evite conteúdos que despertem desejos desordenados hoje.", "guided_exercise": "Peça a Maria a pureza de coração para ver a Deus em tudo.", "final_question": "Seu olhar transmite a paz de Cristo ou a agitação do mundo?"}'::jsonb),
('051b209e-9985-44da-a832-ca884783cb98', 'A Justiça Ordinária', 11, '{"pch": "Dai a cada um o que lhe é devido.", "interpretation": "Justiça não é apenas um conceito legal, mas dar a Deus a adoração e ao próximo o amor e o respeito necessários.", "practical_direction": "Cumpra suas obrigações hoje com integridade e pontualidade.", "guided_exercise": "Examine se você tem sido justo com o tempo que dedica a Deus.", "final_question": "Você tem sido justo com aqueles que dependem de você?"}'::jsonb),
('051b209e-9985-44da-a832-ca884783cb98', 'A Prudência nas Decisões', 12, '{"pch": "Sede prudentes como as serpentes.", "interpretation": "A prudência é a reta razão no agir. Ela nos ajuda a escolher os meios certos para alcançar o Bem supremo.", "practical_direction": "Pense bem antes de falar ou agir em uma situação difícil hoje.", "guided_exercise": "Invoque o Espírito Santo antes de tomar qualquer decisão importante.", "final_question": "Suas escolhas são guiadas pelo impulso ou pela sabedoria?"}'::jsonb),
('051b209e-9985-44da-a832-ca884783cb98', 'A Fortaleza no Sofrimento', 13, '{"pch": "No mundo tereis aflições, mas tende bom ânimo.", "interpretation": "A fortaleza nos permite resistir às dificuldades e perseverar no bem, mesmo sob pressão ou dor.", "practical_direction": "Não reclame de um contratempo ou desconforto físico hoje.", "guided_exercise": "Una seu sofrimento à cruz de Cristo por uma intenção especial.", "final_question": "Onde você busca forças quando as suas acabam?"}'::jsonb),
('051b209e-9985-44da-a832-ca884783cb98', 'A Temperança nos Prazeres', 14, '{"pch": "Tudo me é permitido, mas nem tudo me convém.", "interpretation": "A temperança modera a atração pelos prazeres e assegura o domínio da vontade sobre os instintos.", "practical_direction": "Faça uma pequena renúncia em algo que você gosta muito hoje.", "guided_exercise": "Agradeça pelos dons de Deus e peça equilíbrio no uso deles.", "final_question": "Você é senhor ou escravo dos seus desejos?"}'::jsonb);

-- Expand Rotina de Transformação (0b8ddab7-b106-4873-bc4d-3987421d265d) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('0b8ddab7-b106-4873-bc4d-3987421d265d', 'O Jejum que Liberta', 8, '{"pch": "Nem só de pão vive o homem.", "interpretation": "O jejum não é autopunição, mas um exercício de liberdade. Ao dizer não ao corpo, fortalecemos o sim do espírito.", "practical_direction": "Faça um jejum parcial hoje (ex: pão e água em uma refeição).", "guided_exercise": "Ofereça sua fome pela libertação de um vício específico.", "final_question": "Quem governa sua vida: sua vontade ou seus apetites?"}'::jsonb),
('0b8ddab7-b106-4873-bc4d-3987421d265d', 'O Estudo que Ilumina', 9, '{"pch": "Conhecereis a verdade e a verdade vos libertará.", "interpretation": "O estudo sério da fé e das virtudes é uma forma de amar a Deus com toda a inteligência.", "practical_direction": "Dedique 20 minutos para ler um autor espiritual clássico hoje.", "guided_exercise": "Peça ao Espírito Santo o dom do entendimento.", "final_question": "Sua fé é baseada em sentimentos ou em convicções sólidas?"}'::jsonb),
('0b8ddab7-b106-4873-bc4d-3987421d265d', 'A Intercessão pelos Outros', 10, '{"pch": "Orai uns pelos outros.", "interpretation": "Sair de si mesmo para rezar pelas necessidades alheias é um ato de caridade mística e comunhão.", "practical_direction": "Faça uma lista de 5 pessoas que precisam de oração e reze por elas hoje.", "guided_exercise": "Imagine-se apresentando essas pessoas a Jesus.", "final_question": "Seu coração é largo o suficiente para acolher a dor do próximo?"}'::jsonb),
('0b8ddab7-b106-4873-bc4d-3987421d265d', 'A Paciência com a Própria Queda', 11, '{"pch": "O justo cai sete vezes e se levanta.", "interpretation": "O desânimo após o erro é orgulho ferido. A humildade nos faz levantar e recomeçar com confiança.", "practical_direction": "Se falhar hoje, não se culpe excessivamente. Peça perdão e continue.", "guided_exercise": "Sinta o abraço misericordioso do Pai após a sua queda.", "final_question": "Você tem paciência com suas limitações?"}'::jsonb),
('0b8ddab7-b106-4873-bc4d-3987421d265d', 'A Gratidão Radical', 12, '{"pch": "Em tudo dai graças.", "interpretation": "A gratidão muda nossa percepção da realidade. Ela nos faz ver a abundância onde antes víamos falta.", "practical_direction": "Escreva 10 coisas pelas quais você é grato hoje, mesmo as pequenas.", "guided_exercise": "Agradeça por um desafio que te fez crescer.", "final_question": "Você reclama mais do que agradece?"}'::jsonb),
('0b8ddab7-b106-4873-bc4d-3987421d265d', 'O Abandono na Providência', 13, '{"pch": "Não vos inquieteis com o dia de amanhã.", "interpretation": "O abandono é a entrega total do futuro a Deus. É descansar no colo de quem nos ama infinitamente.", "practical_direction": "Sempre que a ansiedade surgir hoje, diga: Jesus, eu confio em Vós.", "guided_exercise": "Imagine-se soltando as rédeas da sua vida nas mãos de Deus.", "final_question": "Você realmente acredita que Deus cuida de tudo?"}'::jsonb),
('0b8ddab7-b106-4873-bc4d-3987421d265d', 'A Vigília da Esperança', 14, '{"pch": "Vigiai e orai.", "interpretation": "Viver em vigília é estar atento à passagem de Deus no cotidiano, esperando com alegria o encontro final.", "practical_direction": "Termine o dia com um ato de esperança no céu.", "guided_exercise": "Peça a graça de desejar a eternidade acima de tudo.", "final_question": "Sua alma está desperta para o que é eterno?"}'::jsonb);

-- Expand Coração (150f78d3-019b-40c0-962e-a83576309ea5) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('150f78d3-019b-40c0-962e-a83576309ea5', 'O Coração de Carne', 8, '{"pch": "Tirarei o coração de pedra e darei um coração de carne.", "interpretation": "O pecado endurece o coração, tornando-o insensível. A graça o suaviza para que possa sentir novamente o amor.", "practical_direction": "Faça um ato de ternura para com alguém hoje.", "guided_exercise": "Peça ao Senhor que cure a dureza do seu interior.", "final_question": "Seu coração está aberto ou blindado contra a dor alheia?"}'::jsonb),
('150f78d3-019b-40c0-962e-a83576309ea5', 'O Desapego das Consolações', 9, '{"pch": "O Senhor deu, o Senhor tirou.", "interpretation": "Devemos amar o Deus das consolações, não as consolações de Deus. O verdadeiro amor se prova na aridez.", "practical_direction": "Continue sua oração hoje mesmo que não sinta nada.", "guided_exercise": "Reze: Senhor, eu Te amo por quem Tu és, não pelo que me dás.", "final_question": "Sua fé depende de como você se sente?"}'::jsonb),
('150f78d3-019b-40c0-962e-a83576309ea5', 'A Compassão que Cura', 10, '{"pch": "Sede misericordiosos como vosso Pai.", "interpretation": "A compassão é sofrer com o outro. Ela quebra o isolamento do ego e nos une à humanidade sofredora.", "practical_direction": "Ouça alguém que está sofrendo hoje com total empatia.", "guided_exercise": "Imagine Jesus chorando com você nas suas dores.", "final_question": "Você consegue ver a dor por trás do erro alheio?"}'::jsonb),
('150f78d3-019b-40c0-962e-a83576309ea5', 'O Fogo da Caridade', 11, '{"pch": "O amor é forte como a morte.", "interpretation": "A caridade é o amor de Deus em nós. Ela é o fogo que purifica nossas intenções e nos impulsiona ao dom de si.", "practical_direction": "Faça um sacrifício escondido por alguém hoje.", "guided_exercise": "Peça ao Espírito Santo que incendeie seu coração com amor divino.", "final_question": "Suas ações são movidas pelo amor ou pelo interesse?"}'::jsonb),
('150f78d3-019b-40c0-962e-a83576309ea5', 'A Unidade do Ser', 12, '{"pch": "Um só coração e uma só alma.", "interpretation": "A fragmentação interior cessa quando todas as nossas potências (mente, vontade, afeto) convergem para Deus.", "practical_direction": "Tente manter a presença de Deus em meio às atividades agitadas.", "guided_exercise": "Respire profundamente e sinta a unidade da sua vida em Deus.", "final_question": "Sua vida pública condiz com sua vida interior?"}'::jsonb),
('150f78d3-019b-40c0-962e-a83576309ea5', 'A Espera Ativa', 13, '{"pch": "Minha alma espera pelo Senhor.", "interpretation": "Esperar não é passividade, mas uma prontidão amorosa para a chegada do Amado em cada momento.", "practical_direction": "Pratique a paciência em uma fila ou espera hoje.", "guided_exercise": "Aguarde o silêncio de Deus com confiança.", "final_question": "Você sabe esperar o tempo de Deus?"}'::jsonb),
('150f78d3-019b-40c0-962e-a83576309ea5', 'O Repouso em Deus', 14, '{"pch": "Inquieto está o nosso coração até que descanse em Ti.", "interpretation": "O fim da jornada do coração é o repouso na Verdade e no Amor. É a paz que excede todo entendimento.", "practical_direction": "Tire um tempo para o descanso contemplativo hoje.", "guided_exercise": "Descanse na certeza de que você é amado incondicionalmente.", "final_question": "Onde seu coração realmente encontra descanso?"}'::jsonb);

-- Expand Fundamentos (9f444a3e-9838-48b8-ae77-0b5a6829d4fa) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('9f444a3e-9838-48b8-ae77-0b5a6829d4fa', 'A Verdade que Liberta', 8, '{"pch": "A verdade vos libertará.", "interpretation": "A liberdade cristã não é autonomia absoluta, mas a capacidade de aderir à Verdade que nos salva.", "practical_direction": "Seja totalmente honesto em uma conversa hoje.", "guided_exercise": "Peça ao Senhor que remova as máscaras da sua alma.", "final_question": "Você prefere a verdade que dói ou a ilusão que conforta?"}'::jsonb),
('9f444a3e-9838-48b8-ae77-0b5a6829d4fa', 'O Dom da Fé', 9, '{"pch": "A fé é o fundamento das coisas que se esperam.", "interpretation": "A fé não é um sentimento, mas uma adesão da inteligência e da vontade à revelação de Deus.", "practical_direction": "Faça um ato de fé diante de uma situação que você não entende.", "guided_exercise": "Recite o Credo lentamente, meditando em cada verdade.", "final_question": "Sua fé é uma luz para seus passos ou apenas uma tradição?"}'::jsonb),
('9f444a3e-9838-48b8-ae77-0b5a6829d4fa', 'A Graça da Perseverança', 10, '{"pch": "Aquele que perseverar até o fim será salvo.", "interpretation": "A vida espiritual é uma maratona, não uma corrida de cem metros. A constância é fruto da graça.", "practical_direction": "Não desista de um propósito espiritual hoje, mesmo que esteja difícil.", "guided_exercise": "Peça força para continuar a jornada nos dias cinzentos.", "final_question": "O que te faz querer desistir do caminho?"}'::jsonb),
('9f444a3e-9838-48b8-ae77-0b5a6829d4fa', 'A Sabedoria da Humildade', 11, '{"pch": "Quem se humilha será exaltado.", "interpretation": "A humildade é andar na verdade. É reconhecer nosso lugar como criaturas amadas, mas limitadas.", "practical_direction": "Aceite uma correção ou crítica sem se defender hoje.", "guided_exercise": "Medite na pequenez da semente de mostarda que cresce para Deus.", "final_question": "Sua autoestima está baseada no ego ou no amor de Deus?"}'::jsonb),
('9f444a3e-9838-48b8-ae77-0b5a6829d4fa', 'O Mistério da Santidade', 12, '{"pch": "Sede santos porque Eu sou santo.", "interpretation": "Santidade é a plenitude da caridade. É permitir que Cristo viva em nós e através de nós.", "practical_direction": "Faça o que você está fazendo agora com o máximo de amor possível.", "guided_exercise": "Peça a graça de ser transformado à imagem de Cristo.", "final_question": "Você realmente deseja ser santo ou apenas ser bom?"}'::jsonb),
('9f444a3e-9838-48b8-ae77-0b5a6829d4fa', 'O Testemunho da Vida', 13, '{"pch": "Sereis minhas testemunhas.", "interpretation": "Nossa vida é o único evangelho que muitos lerão. O testemunho fala mais alto que as palavras.", "practical_direction": "Deixe que sua alegria e paz hoje atraiam alguém para Deus.", "guided_exercise": "Peça coragem para viver coerentemente sua fé em público.", "final_question": "Sua conduta reflete o que você acredita?"}'::jsonb),
('9f444a3e-9838-48b8-ae77-0b5a6829d4fa', 'O Encontro Definitivo', 14, '{"pch": "Veremos Deus face a face.", "interpretation": "Toda a nossa vida é uma preparação para o encontro eterno. O fim é a união plena com a Beleza Infinita.", "practical_direction": "Viva o dia de hoje como se fosse o último, em paz com Deus e os homens.", "guided_exercise": "Imagine a alegria do acolhimento do Pai na eternidade.", "final_question": "Sua alma tem sede de Deus?"}'::jsonb);

-- Expand Mística (b25b02f4-0533-483f-9a7b-c2e866e6f25d) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('b25b02f4-0533-483f-9a7b-c2e866e6f25d', 'A Noite Escura dos Sentidos', 8, '{"pch": "Noite feliz, noite escura.", "interpretation": "A noite escura é um tempo de purificação onde Deus retira as consolações sensíveis para que o amemos por Ele mesmo.", "practical_direction": "Permaneça fiel à oração mesmo no deserto espiritual hoje.", "guided_exercise": "Confie no amor de Deus que age no silêncio e na ausência de sentimentos.", "final_question": "Você ama a Deus ou aos sentimentos que Ele te proporciona?"}'::jsonb),
('b25b02f4-0533-483f-9a7b-c2e866e6f25d', 'A Oração de Quietude', 9, '{"pch": "Aquietai-vos e sabei que Eu sou Deus.", "interpretation": "A quietude é um estado onde a vontade descansa em Deus, mesmo que a mente ainda divague. É o início da contemplação.", "practical_direction": "Fique 10 minutos em silêncio absoluto apenas focando na presença divina.", "guided_exercise": "Imagine-se como um lago calmo refletindo o céu.", "final_question": "Você consegue silenciar o barulho interno para ouvir a Deus?"}'::jsonb),
('b25b02f4-0533-483f-9a7b-c2e866e6f25d', 'O Despojamento de Si', 10, '{"pch": "Quem perder a sua vida por minha causa, a encontrará.", "interpretation": "A mística exige um despojamento radical do ego e de seus planos para que a vontade divina opere plenamente em nós.", "practical_direction": "Renuncie a um desejo pessoal legítimo hoje em favor da vontade de Deus.", "guided_exercise": "Imagine-se entregando as chaves da sua vida a Cristo.", "final_question": "Quem é o verdadeiro protagonista da sua história?"}'::jsonb),
('b25b02f4-0533-483f-9a7b-c2e866e6f25d', 'A Ferida de Amor', 11, '{"pch": "Feriste-me o coração com uma seta de amor.", "interpretation": "A ferida de amor é um desejo insaciável por Deus que, ao mesmo tempo que dói, traz uma doçura inefável.", "practical_direction": "Reze com um desejo ardente pela vinda do Reino de Deus.", "guided_exercise": "Sinta a sede de Deus pela sua alma e sua sede por Ele.", "final_question": "Sua alma suspira por Deus como a corça pelas águas?"}'::jsonb),
('b25b02f4-0533-483f-9a7b-c2e866e6f25d', 'O Olhar Contemplativo', 12, '{"pch": "Eu O olho e Ele me olha.", "interpretation": "Contemplação é um olhar amoroso e simples sobre Deus e Sua criação. É ver a digital do Criador em tudo.", "practical_direction": "Observe a natureza ou uma obra de arte e veja a beleza de Deus nela.", "guided_exercise": "Deixe-se ser olhado por Deus com ternura.", "final_question": "Você consegue ver Deus no ordinário da vida?"}'::jsonb),
('b25b02f4-0533-483f-9a7b-c2e866e6f25d', 'A União Transformativa', 13, '{"pch": "Já não sou eu que vivo, é Cristo que vive em mim.", "interpretation": "É o ápice da vida mística, onde a alma se torna um com Deus, mantendo sua identidade mas agindo sob a moção divina.", "practical_direction": "Tente fazer cada ação de hoje como se Cristo estivesse agindo através de você.", "guided_exercise": "Medite na união da gota de água com o vinho no cálice.", "final_question": "Cristo é o centro de todos os seus atos?"}'::jsonb),
('b25b02f4-0533-483f-9a7b-c2e866e6f25d', 'O Êxtase do Serviço', 14, '{"pch": "O amor não é amado.", "interpretation": "O verdadeiro encontro místico não fecha a pessoa em si, mas a impulsiona a um serviço heróico e humilde aos irmãos.", "practical_direction": "Sirva a alguém hoje com um amor que ultrapassa suas forças naturais.", "guided_exercise": "Peça a graça de ser um canal do amor de Deus para o mundo.", "final_question": "Sua vida espiritual transborda em caridade concreta?"}'::jsonb);

-- Expand O Caminho do Amor (a0a0a0a0-0001-4000-8000-000000000001) to 14 steps
INSERT INTO public.journey_steps (journey_id, title, step_order, content) VALUES
('a0a0a0a0-0001-4000-8000-000000000001', 'O Amor que Tudo Sofre', 8, '{"pch": "O amor é paciente.", "interpretation": "Sofrer com amor não é masoquismo, mas a capacidade de suportar as imperfeições alheias e as provações com paz.", "practical_direction": "Suporte com paciência uma pessoa difícil hoje.", "guided_exercise": "Imagine Jesus carregando a cruz por amor a você.", "final_question": "Você tem paciência com as fraquezas dos outros?"}'::jsonb),
('a0a0a0a0-0001-4000-8000-000000000001', 'O Amor que Tudo Crê', 9, '{"pch": "O amor crê em tudo.", "interpretation": "Crer no amor é acreditar na bondade fundamental do outro e na vitória final do Bem, mesmo diante do mal.", "practical_direction": "Dê um voto de confiança a alguém que falhou com você.", "guided_exercise": "Peça a graça de ver o potencial de santidade em cada pessoa.", "final_question": "Você foca mais no erro ou na possibilidade de mudança?"}'::jsonb),
('a0a0a0a0-0001-4000-8000-000000000001', 'O Amor que Tudo Espera', 10, '{"pch": "O amor espera tudo.", "interpretation": "A esperança no amor é a certeza de que Deus tira o bem do mal e que a última palavra é da Vida.", "practical_direction": "Não desanime diante de uma situação que parece sem saída hoje.", "guided_exercise": "Confie seus medos ao Deus que faz novas todas as coisas.", "final_question": "Onde está ancorada a sua esperança?"}'::jsonb),
('a0a0a0a0-0001-4000-8000-000000000001', 'O Amor que Tudo Suporta', 11, '{"pch": "O amor nunca acaba.", "interpretation": "Suportar é ser coluna. O amor maduro permanece fiel quando a empolgação passa e o cansaço chega.", "practical_direction": "Permaneça fiel a um compromisso hoje, mesmo sem vontade.", "guided_exercise": "Peça constância no amor ordinário.", "final_question": "Seu amor é fogo de palha ou uma chama constante?"}'::jsonb),
('a0a0a0a0-0001-4000-8000-000000000001', 'A Gratuidade do Amor', 12, '{"pch": "De graça recebestes, de graça dai.", "interpretation": "O amor verdadeiro não busca retorno. É um dom gratuito que imita a generosidade do Pai.", "practical_direction": "Faça algo por alguém que nunca poderá te retribuir hoje.", "guided_exercise": "Agradeça pelo amor gratuito que Deus tem por você.", "final_question": "Você ama esperando algo em troca?"}'::jsonb),
('a0a0a0a0-0001-4000-8000-000000000001', 'O Amor como Vínculo da Perfeição', 13, '{"pch": "Revesti-vos da caridade.", "interpretation": "A caridade é o que une todas as virtudes. Sem amor, a sabedoria é vã e o sacrifício é estéril.", "practical_direction": "Coloque um pouco de amor em cada conversa de hoje.", "guided_exercise": "Imagine-se revestido por uma luz que é o amor de Deus.", "final_question": "O amor é a prioridade da sua vida?"}'::jsonb),
('a0a0a0a0-0001-4000-8000-000000000001', 'Permanecer no Amor', 14, '{"pch": "Aquele que permanece no amor, permanece em Deus.", "interpretation": "A meta final é habitar no amor. Não apenas praticar atos de amor, mas tornar-se amor em Cristo.", "practical_direction": "Termine o dia com um profundo ato de adoração ao Deus-Amor.", "guided_exercise": "Descanse na presença do Amado que habita em você.", "final_question": "Você se sente em casa no Amor de Deus?"}'::jsonb);

-- Update estimated_days for these journeys
UPDATE public.journeys SET estimated_days = 14 WHERE id IN (
  '051b209e-9985-44da-a832-ca884783cb98',
  '0b8ddab7-b106-4873-bc4d-3987421d265d',
  '150f78d3-019b-40c0-962e-a83576309ea5',
  '9f444a3e-9838-48b8-ae77-0b5a6829d4fa',
  'b25b02f4-0533-483f-9a7b-c2e866e6f25d',
  'a0a0a0a0-0001-4000-8000-000000000001'
);